export const springBoot = {
  id: "spring-boot", icon: "🍃", title: "Spring Boot", color: "#22c55e", accent: "#4ade80",
  topics: [
    {
      title: "What is Spring Boot & Why Use It?", level: "Beginner",
      blocks: [
        {t:"text", v:"Spring Boot is the most popular Java framework for building web apps and microservices. It removes the painful XML configuration of older Spring, gives you a production-ready app in minutes, and embeds a web server so you just run a jar file."},
        {t:"heading", v:"Spring vs Spring Boot"},
        {t:"code", lang:"text", v:[
          "Spring Framework (2003):",
          "  Powerful but requires LOTS of manual XML configuration.",
          "  Set up DataSource, TransactionManager, ViewResolver, DispatcherServlet...",
          "  200+ lines of config for a basic web app.",
          "",
          "Spring Boot (2014) — Convention over Configuration:",
          "  Auto-detects your dependencies and configures automatically.",
          "  Embedded Tomcat — no separate server install needed.",
          "  Just run: java -jar myapp.jar",
          "  Production features built-in: health checks, metrics, config management.",
        ]},
        {t:"heading", v:"Your First REST Controller"},
        {t:"code", lang:"java", v:[
          "@SpringBootApplication  // @Configuration + @EnableAutoConfiguration + @ComponentScan",
          "public class OrderServiceApplication {",
          "    public static void main(String[] args) {",
          "        SpringApplication.run(OrderServiceApplication.class, args);",
          "        // Starts embedded Tomcat on :8080",
          "        // Scans all @Component/@Service/@Repository/@Controller beans",
          "        // Auto-configures JPA, Security, etc. based on classpath",
          "    }",
          "}",
          "",
          "@RestController",
          "@RequestMapping(\"/api/v1/orders\")",
          "public class OrderController {",
          "    private final OrderService orderService;",
          "",
          "    public OrderController(OrderService orderService) {",
          "        this.orderService = orderService; // Constructor injection",
          "    }",
          "",
          "    @GetMapping(\"/{id}\")",
          "    public ResponseEntity<Order> getOrder(@PathVariable Long id) {",
          "        return ResponseEntity.ok(orderService.findById(id));",
          "    }",
          "",
          "    @PostMapping",
          "    public ResponseEntity<Order> create(@Valid @RequestBody CreateOrderRequest req) {",
          "        Order created = orderService.create(req);",
          "        URI location = URI.create(\"/api/v1/orders/\" + created.getId());",
          "        return ResponseEntity.created(location).body(created);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"application.yml — All Configuration in One Place"},
        {t:"code", lang:"yaml", v:[
          "server:",
          "  port: 8080",
          "",
          "spring:",
          "  application:",
          "    name: order-service",
          "  datasource:",
          "    url: jdbc:postgresql://localhost:5432/orders_db",
          "    username: ${DB_USERNAME}   # From environment variable — never hardcode!",
          "    password: ${DB_PASSWORD}",
          "    hikari:",
          "      maximum-pool-size: 20",
          "      minimum-idle: 5",
          "  jpa:",
          "    hibernate:",
          "      ddl-auto: validate       # 'create-drop' in dev only, NEVER in prod",
          "    show-sql: false",
          "",
          "logging:",
          "  level:",
          "    root: INFO",
          "    com.mycompany: DEBUG",
        ]},
        {t:"heading", v:"Profiles — Different Config per Environment"},
        {t:"code", lang:"yaml", v:[
          "# application-dev.yml  (active when --spring.profiles.active=dev)",
          "spring:",
          "  datasource:",
          "    url: jdbc:h2:mem:testdb   # In-memory H2 for local dev",
          "  jpa:",
          "    hibernate:",
          "      ddl-auto: create-drop   # Recreate DB schema on every startup",
          "    show-sql: true",
          "",
          "# application-prod.yml  (active when --spring.profiles.active=prod)",
          "spring:",
          "  datasource:",
          "    url: jdbc:postgresql://prod-db:5432/orders",
          "  jpa:",
          "    hibernate:",
          "      ddl-auto: validate     # Only validate, NEVER recreate prod data!",
          "    show-sql: false",
          "",
          "# Start with profile:",
          "# java -jar app.jar --spring.profiles.active=prod",
          "# Or: SPRING_PROFILES_ACTIVE=prod java -jar app.jar",
        ]},
      ]
    },
    {
      title: "Spring IoC, DI & Bean Lifecycle", level: "Beginner",
      blocks: [
        {t:"text", v:"Inversion of Control (IoC) means: instead of your code creating objects, Spring creates and manages them. Dependency Injection (DI) is how Spring provides your classes with the objects they need. This makes your code loosely coupled and easy to test."},
        {t:"heading", v:"The Problem DI Solves"},
        {t:"code", lang:"java", v:[
          "// WITHOUT Spring — tightly coupled, untestable:",
          "public class OrderService {",
          "    // Hard-coded implementation — can't swap, can't test without a real DB",
          "    private OrderRepository repo = new MySQLOrderRepository(\"jdbc:mysql://...\");",
          "    private EmailService email   = new GmailEmailService(\"api-key-hardcoded\");",
          "}",
          "",
          "// WITH Spring — loosely coupled, fully testable:",
          "public class OrderService {",
          "    private final OrderRepository repo;   // Just declare what you need",
          "    private final EmailService email;",
          "",
          "    public OrderService(OrderRepository repo, EmailService email) {",
          "        this.repo  = repo;   // Spring provides these at startup",
          "        this.email = email;",
          "    }",
          "    // Production: Spring injects real JPA + Gmail",
          "    // Tests:      inject Mockito mocks — zero external dependencies",
          "}",
        ]},
        {t:"heading", v:"Spring Stereotype Annotations"},
        {t:"code", lang:"java", v:[
          "// These all register the class as a Spring Bean:",
          "@Component    // Generic spring-managed component",
          "@Service      // Business logic layer (semantic meaning)",
          "@Repository   // Data access layer (also translates DB exceptions)",
          "@Controller   // MVC web controller",
          "@RestController // REST API controller (@Controller + @ResponseBody)",
          "",
          "// Example:",
          "@Service",
          "public class UserService {",
          "    private final UserRepository repo;",
          "    public UserService(UserRepository repo) { this.repo = repo; }",
          "    public User findById(Long id) {",
          "        return repo.findById(id).orElseThrow(() -> new UserNotFoundException(id));",
          "    }",
          "}",
          "",
          "@Repository",
          "public interface UserRepository extends JpaRepository<User, Long> {",
          "    Optional<User> findByEmail(String email);",
          "    // Spring Data generates the implementation — you write ZERO SQL",
          "}",
        ]},
        {t:"heading", v:"Bean Scopes"},
        {t:"code", lang:"java", v:[
          "// SINGLETON (default): One instance shared across entire app",
          "@Service // implicitly singleton",
          "public class OrderService {",
          "    // Safe IF you don't store mutable state in fields",
          "    // thousands of requests share this ONE instance",
          "}",
          "",
          "// PROTOTYPE: New instance every time it's injected/requested",
          "@Component @Scope(\"prototype\")",
          "public class ReportBuilder {",
          "    private List<String> rows = new ArrayList<>(); // Safe: each caller gets own instance",
          "}",
          "",
          "// TRAP: Injecting prototype into singleton — only ONE prototype created!",
          "@Service",
          "public class ReportService {",
          "    @Autowired private ReportBuilder builder; // Only ONE builder created!",
          "}",
          "",
          "// FIX: Use ObjectProvider to get a fresh prototype each time",
          "@Service",
          "public class ReportService {",
          "    private final ObjectProvider<ReportBuilder> builderProvider;",
          "    public ReportService(ObjectProvider<ReportBuilder> p) { this.builderProvider = p; }",
          "    public Report generate() {",
          "        return builderProvider.getObject().build(); // Fresh each time",
          "    }",
          "}",
        ]},
        {t:"heading", v:"@Configuration and Bean Lifecycle"},
        {t:"code", lang:"java", v:[
          "@Configuration",
          "public class AppConfig {",
          "",
          "    // Manual bean registration (for third-party classes you can't annotate)",
          "    @Bean",
          "    public ObjectMapper objectMapper() {",
          "        return new ObjectMapper()",
          "            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)",
          "            .registerModule(new JavaTimeModule());",
          "    }",
          "",
          "    @Bean @Primary",
          "    public DataSource primaryDataSource() {",
          "        HikariConfig config = new HikariConfig();",
          "        config.setJdbcUrl(\"jdbc:postgresql://db:5432/orders\");",
          "        config.setMaximumPoolSize(20);",
          "        config.setMinimumIdle(5);",
          "        config.setConnectionTimeout(30_000);",
          "        return new HikariDataSource(config);",
          "    }",
          "}",
          "",
          "// Bean lifecycle hooks:",
          "@Service",
          "public class CacheService {",
          "    @PostConstruct  // Runs AFTER all dependencies injected",
          "    public void initCache() { loadDataIntoCache(); }",
          "",
          "    @PreDestroy    // Runs BEFORE Spring shuts down",
          "    public void clearCache() { cache.clear(); }",
          "}",
        ]},
      ]
    },
    {
      title: "Spring Data JPA — Database Made Easy", level: "Intermediate",
      blocks: [
        {t:"text", v:"Spring Data JPA eliminates most database boilerplate. You define your model as Java classes (Entities) annotated with JPA annotations, and Spring generates the SQL, manages connections, and handles transactions automatically."},
        {t:"heading", v:"Entity Mapping — Java Class to DB Table"},
        {t:"code", lang:"java", v:[
          "@Entity",
          "@Table(name = \"orders\",",
          "       indexes = {",
          "           @Index(name = \"idx_customer\", columnList = \"customer_id\"),",
          "           @Index(name = \"idx_status_date\", columnList = \"status,created_at\")",
          "       })",
          "@EntityListeners(AuditingEntityListener.class)",
          "public class Order {",
          "",
          "    @Id",
          "    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = \"order_seq\")",
          "    @SequenceGenerator(name=\"order_seq\", sequenceName=\"order_id_seq\", allocationSize=50)",
          "    private Long id;",
          "",
          "    @Enumerated(EnumType.STRING)  // Stores 'PENDING' not 0,1,2 — readable!",
          "    @Column(nullable = false, length = 20)",
          "    private OrderStatus status;",
          "",
          "    @ManyToOne(fetch = FetchType.LAZY)  // ALWAYS LAZY — don't load unless needed",
          "    @JoinColumn(name = \"customer_id\", nullable = false)",
          "    private Customer customer;",
          "",
          "    @OneToMany(mappedBy = \"order\", cascade = CascadeType.ALL, orphanRemoval = true)",
          "    private List<OrderItem> items = new ArrayList<>();",
          "",
          "    @Column(precision = 10, scale = 2)",
          "    private BigDecimal totalAmount;",
          "",
          "    @CreatedDate @Column(updatable = false) private Instant createdAt;",
          "    @LastModifiedDate private Instant updatedAt;",
          "",
          "    @Version  // Optimistic locking: prevents two users overwriting each other's changes",
          "    private Long version;",
          "}",
        ]},
        {t:"heading", v:"Repository — Zero Boilerplate Queries"},
        {t:"code", lang:"java", v:[
          "public interface OrderRepository extends JpaRepository<Order, Long> {",
          "",
          "    // Spring Data derives SQL from method names — NO SQL needed!",
          "    List<Order> findByCustomerId(Long customerId);",
          "    List<Order> findByStatus(OrderStatus status);",
          "    Optional<Order> findByIdAndCustomerId(Long id, Long customerId);",
          "    long countByStatus(OrderStatus status);",
          "    boolean existsByCustomerIdAndStatus(Long customerId, OrderStatus status);",
          "",
          "    // Custom JPQL (when method names get too long):",
          "    @Query(\"SELECT o FROM Order o JOIN FETCH o.customer \" +",
          "           \"WHERE o.status = :status AND o.createdAt > :since\")",
          "    List<Order> findRecentByStatus(@Param(\"status\") OrderStatus status,",
          "                                   @Param(\"since\") Instant since);",
          "",
          "    // Pagination support:",
          "    Page<Order> findByStatus(OrderStatus status, Pageable pageable);",
          "",
          "    // Projection: only fetch needed columns (faster)",
          "    @Query(\"SELECT o.id as id, o.status as status, c.name as customerName \" +",
          "           \"FROM Order o JOIN o.customer c WHERE o.status = :s\")",
          "    List<OrderSummaryProjection> findSummaryByStatus(@Param(\"s\") OrderStatus s);",
          "}",
          "",
          "// Usage:",
          "Pageable pageable = PageRequest.of(0, 20, Sort.by(\"createdAt\").descending());",
          "Page<Order> page = repo.findByStatus(PENDING, pageable);",
          "page.getContent();      // The 20 orders",
          "page.getTotalElements(); // Total count",
        ]},
        {t:"heading", v:"N+1 Query Problem — The #1 Performance Bug"},
        {t:"text", v:"N+1 means: 1 query to load a list, then N more queries to load related data. For 100 orders each needing a customer, that's 101 queries. At scale this destroys performance."},
        {t:"code", lang:"java", v:[
          "// BAD: N+1 queries — 1 query for orders + N for customers",
          "@Transactional",
          "public void printSummaries() {",
          "    List<Order> orders = orderRepo.findAll(); // SELECT * FROM orders",
          "    for (Order o : orders) {",
          "        o.getCustomer().getName(); // SELECT * FROM customers WHERE id=? (×N!)",
          "    }",
          "}",
          "",
          "// FIX 1: JOIN FETCH — everything in ONE query",
          "@Query(\"SELECT o FROM Order o JOIN FETCH o.customer\")",
          "List<Order> findAllWithCustomer();",
          "",
          "// FIX 2: @EntityGraph — declarative, no JPQL needed",
          "@EntityGraph(attributePaths = {\"customer\", \"items\"})",
          "List<Order> findByStatus(OrderStatus status);",
          "",
          "// FIX 3: Projection — only fetch columns you need (most efficient)",
          "public interface OrderSummaryProjection {",
          "    Long getId();",
          "    String getStatus();",
          "    @Value(\"#{target.customer.name}\") String getCustomerName();",
          "}",
          "List<OrderSummaryProjection> findProjectedByStatus(OrderStatus status);",
          "// Generates: SELECT o.id, o.status, c.name FROM orders o JOIN customers c...",
        ]},
        {t:"heading", v:"@Transactional — Atomic Operations"},
        {t:"code", lang:"java", v:[
          "@Service",
          "public class OrderService {",
          "",
          "    // @Transactional: if ANY step throws exception → ALL DB changes rolled back",
          "    @Transactional",
          "    public Order placeOrder(CreateOrderRequest req) {",
          "        // Step 1: Reduce stock",
          "        inventoryRepo.decrementStock(req.getProductId(), req.getQuantity());",
          "",
          "        // Step 2: Create order",
          "        Order order = orderRepo.save(Order.from(req));",
          "",
          "        // Step 3: Record payment",
          "        paymentRepo.save(Payment.from(order));",
          "",
          "        // If step 3 throws an exception:",
          "        // → Steps 1 and 2 are ROLLED BACK automatically",
          "        // → No orphan orders, no negative inventory",
          "        return order;",
          "    }",
          "",
          "    // Read-only hint: allows DB optimizations (no dirty checking etc.)",
          "    @Transactional(readOnly = true)",
          "    public List<Order> getCustomerOrders(Long customerId) {",
          "        return orderRepo.findByCustomerId(customerId);",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Building REST APIs — Best Practices", level: "Intermediate",
      blocks: [
        {t:"text", v:"Building a REST API is more than just @GetMapping. Production APIs need proper HTTP status codes, request validation, pagination, and consistent error responses. Here's the complete picture."},
        {t:"heading", v:"Full CRUD Controller"},
        {t:"code", lang:"java", v:[
          "@RestController",
          "@RequestMapping(\"/api/v1/products\")",
          "@RequiredArgsConstructor",
          "public class ProductController {",
          "    private final ProductService service;",
          "",
          "    @GetMapping",
          "    public Page<ProductDto> list(",
          "            @RequestParam(defaultValue=\"0\")    int page,",
          "            @RequestParam(defaultValue=\"20\")   int size,",
          "            @RequestParam(defaultValue=\"name\") String sortBy) {",
          "        return service.findAll(PageRequest.of(page, size, Sort.by(sortBy)));",
          "    }",
          "",
          "    @GetMapping(\"/{id}\")",
          "    public ProductDto getById(@PathVariable Long id) {",
          "        return service.findById(id);  // throws 404 if not found",
          "    }",
          "",
          "    @PostMapping",
          "    @ResponseStatus(HttpStatus.CREATED)",
          "    public ProductDto create(@Valid @RequestBody CreateProductRequest req) {",
          "        return service.create(req);",
          "    }",
          "",
          "    @PutMapping(\"/{id}\")",
          "    public ProductDto update(@PathVariable Long id,",
          "                             @Valid @RequestBody UpdateProductRequest req) {",
          "        return service.update(id, req);",
          "    }",
          "",
          "    @DeleteMapping(\"/{id}\")",
          "    @ResponseStatus(HttpStatus.NO_CONTENT)",
          "    public void delete(@PathVariable Long id) {",
          "        service.delete(id);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Request Validation with @Valid"},
        {t:"code", lang:"java", v:[
          "public record CreateProductRequest(",
          "    @NotBlank(message = \"Name is required\")",
          "    @Size(min = 2, max = 100)",
          "    String name,",
          "",
          "    @NotNull(message = \"Price required\")",
          "    @DecimalMin(value = \"0.01\", message = \"Price must be positive\")",
          "    BigDecimal price,",
          "",
          "    @Min(value = 0, message = \"Stock cannot be negative\")",
          "    Integer stock,",
          "",
          "    @Email String supplierEmail,",
          "",
          "    @Pattern(regexp = \"[A-Z]{2}-[0-9]{6}\",",
          "             message = \"SKU must match XX-000000\")",
          "    String sku",
          ") {}",
          "",
          "// @Valid on controller method triggers validation before method runs.",
          "// If validation fails: 400 Bad Request returned automatically",
          "// with field-level error messages from GlobalExceptionHandler.",
        ]},
        {t:"heading", v:"HTTP Status Codes — Use Them Correctly"},
        {t:"table", v:[
          ["Status","Meaning","When to Use"],
          ["200 OK","Success","GET, PUT — returned resource"],
          ["201 Created","Resource created","POST — new resource made"],
          ["204 No Content","Success, no body","DELETE, PATCH with no response"],
          ["400 Bad Request","Client error","Validation failed, bad input"],
          ["401 Unauthorized","Not authenticated","Missing or invalid JWT token"],
          ["403 Forbidden","Not authorized","Valid token but no permission"],
          ["404 Not Found","Resource missing","ID doesn't exist"],
          ["409 Conflict","State conflict","Duplicate email, version mismatch"],
          ["422 Unprocessable","Business rule fail","Insufficient stock"],
          ["500 Internal Error","Server bug","Unexpected exception"],
        ]},
      ]
    },
    {
      title: "Spring Security — JWT Auth", level: "Advanced",
      blocks: [
        {t:"text", v:"Security is not optional. Every API needs to know WHO is calling (authentication) and WHETHER they're allowed (authorization). Spring Security + JWT is the standard for stateless microservices."},
        {t:"heading", v:"JWT Flow Explained"},
        {t:"code", lang:"text", v:[
          "1. Client: POST /api/v1/auth/login { email, password }",
          "2. Server: Verifies credentials against database",
          "3. Server: Creates JWT = Header.Payload.Signature",
          "         Payload: { userId, roles, issuedAt, expiresAt }",
          "         Signed with a secret key — tamper-proof",
          "4. Server: Returns JWT to client",
          "",
          "5. Client: Stores JWT, sends on every request:",
          "         Authorization: Bearer eyJhbGciOiJIUzI1NiJ9...",
          "6. Server: Validates JWT signature + checks not expired",
          "7. Server: Extracts userId + roles from payload",
          "8. Server: Checks if role has access to this endpoint",
          "9. Server: Executes the business logic",
          "",
          "Benefits: Stateless (no session DB), scalable (any server can verify),",
          "          self-contained (userId/roles in token itself)",
        ]},
        {t:"heading", v:"Security Configuration"},
        {t:"code", lang:"java", v:[
          "@Configuration @EnableWebSecurity @EnableMethodSecurity",
          "public class SecurityConfig {",
          "",
          "    @Bean",
          "    public SecurityFilterChain filterChain(HttpSecurity http,",
          "                                            JwtAuthFilter jwtFilter) throws Exception {",
          "        return http",
          "            .csrf(csrf -> csrf.disable())       // Stateless = no CSRF needed",
          "            .sessionManagement(s ->",
          "                s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))",
          "            .authorizeHttpRequests(auth -> auth",
          "                .requestMatchers(\"/api/v1/auth/**\").permitAll()    // Public",
          "                .requestMatchers(\"/actuator/health\").permitAll()   // Public",
          "                .requestMatchers(GET, \"/api/v1/products/**\").permitAll()",
          "                .requestMatchers(\"/api/v1/admin/**\").hasRole(\"ADMIN\")",
          "                .anyRequest().authenticated())",
          "            .addFilterBefore(jwtFilter, UsernamePasswordAuthenticationFilter.class)",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    public PasswordEncoder passwordEncoder() {",
          "        return new BCryptPasswordEncoder(12);",
          "        // NEVER store plain text. BCrypt: slow by design — resists brute force",
          "    }",
          "}",
        ]},
        {t:"heading", v:"JWT Filter"},
        {t:"code", lang:"java", v:[
          "@Component @RequiredArgsConstructor",
          "public class JwtAuthFilter extends OncePerRequestFilter {",
          "    private final JwtService jwtService;",
          "",
          "    @Override",
          "    protected void doFilterInternal(HttpServletRequest req,",
          "            HttpServletResponse res, FilterChain chain)",
          "            throws ServletException, IOException {",
          "        String header = req.getHeader(\"Authorization\");",
          "        if (header == null || !header.startsWith(\"Bearer \")) {",
          "            chain.doFilter(req, res); return;  // No token — pass through",
          "        }",
          "        try {",
          "            String token = header.substring(7);",
          "            String userId = jwtService.extractUserId(token);",
          "            List<String> roles = jwtService.extractRoles(token);",
          "",
          "            var authorities = roles.stream()",
          "                .map(r -> new SimpleGrantedAuthority(\"ROLE_\" + r))",
          "                .collect(Collectors.toList());",
          "",
          "            var auth = new UsernamePasswordAuthenticationToken(",
          "                userId, null, authorities);",
          "            SecurityContextHolder.getContext().setAuthentication(auth);",
          "",
          "        } catch (ExpiredJwtException e) {",
          "            res.sendError(401, \"Token expired\"); return;",
          "        } catch (JwtException e) {",
          "            res.sendError(401, \"Invalid token\"); return;",
          "        }",
          "        chain.doFilter(req, res);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Method Security"},
        {t:"code", lang:"java", v:[
          "@Service",
          "public class OrderService {",
          "",
          "    // Only the owner OR an admin can see their orders",
          "    @PreAuthorize(\"#customerId == authentication.name or hasRole('ADMIN')\")",
          "    public List<Order> getCustomerOrders(String customerId) {",
          "        return orderRepo.findByCustomerId(customerId);",
          "    }",
          "",
          "    // Check RETURNED object belongs to caller (post-execution)",
          "    @PostAuthorize(\"returnObject.customerId == authentication.name\")",
          "    public Order getOrder(Long orderId) {",
          "        return orderRepo.findById(orderId)",
          "            .orElseThrow(() -> new OrderNotFoundException(orderId));",
          "    }",
          "",
          "    // Get current user anywhere in your service layer:",
          "    private String getCurrentUserId() {",
          "        return (String) SecurityContextHolder.getContext()",
          "            .getAuthentication().getPrincipal();",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Actuator, Metrics & Observability", level: "Advanced",
      blocks: [
        {t:"text", v:"A deployed app needs more than just working endpoints. You need to know: Is it healthy? Is it slow? Are there errors? Spring Boot Actuator + Micrometer give you this visibility with almost no code."},
        {t:"heading", v:"Actuator Setup"},
        {t:"code", lang:"yaml", v:[
          "management:",
          "  endpoints:",
          "    web:",
          "      exposure:",
          "        include: health,info,metrics,prometheus,loggers,threaddump",
          "  endpoint:",
          "    health:",
          "      show-details: when_authorized",
          "      probes:",
          "        enabled: true  # /actuator/health/liveness & /readiness for Kubernetes",
          "  metrics:",
          "    export:",
          "      prometheus:",
          "        enabled: true",
        ]},
        {t:"heading", v:"Key Endpoints"},
        {t:"table", v:[
          ["Endpoint","Purpose","Used For"],
          ["/actuator/health","App health status","Kubernetes probes"],
          ["/actuator/health/liveness","JVM alive?","K8s: restart if down"],
          ["/actuator/health/readiness","Ready for traffic?","K8s: remove from LB if not ready"],
          ["/actuator/prometheus","Metrics in Prometheus format","Scraped every 15s by Prometheus"],
          ["/actuator/loggers","View/change log levels","Debug prod without restart"],
          ["/actuator/threaddump","All thread states","Diagnose deadlocks"],
          ["/actuator/metrics","List all metric names","Find metric names to query"],
        ]},
        {t:"heading", v:"Custom Health Indicator"},
        {t:"code", lang:"java", v:[
          "@Component",
          "public class ExternalApiHealth implements HealthIndicator {",
          "    private final WebClient paymentApiClient;",
          "",
          "    @Override",
          "    public Health health() {",
          "        try {",
          "            paymentApiClient.get().uri(\"/ping\").retrieve().toBodilessEntity().block();",
          "            return Health.up()",
          "                .withDetail(\"service\", \"Stripe API\")",
          "                .withDetail(\"status\", \"Reachable\")",
          "                .build();",
          "        } catch (Exception e) {",
          "            return Health.down()",
          "                .withDetail(\"service\", \"Stripe API\")",
          "                .withDetail(\"error\", e.getMessage())",
          "                .withDetail(\"impact\", \"Payment processing unavailable\")",
          "                .build();",
          "        }",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Custom Business Metrics with Micrometer"},
        {t:"code", lang:"java", v:[
          "@Service",
          "public class OrderService {",
          "    private final Counter ordersCreated;",
          "    private final Counter ordersFailed;",
          "    private final Timer   processingTime;",
          "",
          "    public OrderService(MeterRegistry registry, OrderRepository repo) {",
          "        ordersCreated = Counter.builder(\"orders.created.total\")",
          "            .description(\"Total orders created\").register(registry);",
          "",
          "        ordersFailed = Counter.builder(\"orders.failed.total\")",
          "            .description(\"Total orders failed\").register(registry);",
          "",
          "        processingTime = Timer.builder(\"orders.processing.seconds\")",
          "            .publishPercentiles(0.50, 0.95, 0.99)  // p50, p95, p99",
          "            .register(registry);",
          "",
          "        // Gauge: live count of pending orders",
          "        Gauge.builder(\"orders.pending.count\", repo,",
          "                      r -> r.countByStatus(PENDING))",
          "             .register(registry);",
          "    }",
          "",
          "    @Transactional",
          "    public Order create(CreateOrderRequest req) {",
          "        return processingTime.recordCallable(() -> {",
          "            try {",
          "                Order o = doCreate(req);",
          "                ordersCreated.increment();",
          "                return o;",
          "            } catch (Exception e) {",
          "                ordersFailed.increment(Tags.of(\"reason\", e.getClass().getSimpleName()));",
          "                throw e;",
          "            }",
          "        });",
          "    }",
          "}",
          "// Grafana alert: orders.failed.total rate > 1% → page on-call engineer",
        ]},
      ]
    },
  ]
};

springBoot.topics.push(
  {
    title: "Spring AOP — Cross-Cutting Concerns", level: "Advanced",
    blocks: [
      {t:"text", v:"Aspect-Oriented Programming (AOP) lets you add behaviour to existing code without modifying it. Logging, security, transactions, and performance monitoring are all cross-cutting concerns — AOP handles them in one place instead of scattered across every method."},
      {t:"heading", v:"AOP Concepts"},
      {t:"code", lang:"text", v:[
        "ASPECT:     The cross-cutting concern itself (e.g., logging, timing)",
        "JOIN POINT: A point in execution (method call, exception throw)",
        "POINTCUT:   Expression selecting which join points to intercept",
        "ADVICE:     Code to run at the selected join points",
        "",
        "Advice types:",
        "  @Before        — runs before the method",
        "  @After         — runs after (always, even on exception)",
        "  @AfterReturning— runs after successful return",
        "  @AfterThrowing — runs after exception",
        "  @Around        — wraps the method (most powerful)",
        "",
        "Spring AOP uses PROXY pattern internally:",
        "  Your bean → Spring creates a proxy → proxy intercepts calls",
        "  This is why @Transactional on private methods doesn't work!",
        "  (private methods can't be proxied)",
      ]},
      {t:"heading", v:"Real-World AOP Examples"},
      {t:"code", lang:"java", v:[
        "@Aspect @Component",
        "public class PerformanceMonitoringAspect {",
        "",
        "    // Pointcut: all methods in service classes",
        "    @Pointcut(\"execution(* com.myapp.service.*Service.*(..))\") ",
        "    public void serviceLayer() {}",
        "",
        "    // Around advice: measure execution time",
        "    @Around(\"serviceLayer()\")",
        "    public Object measureTime(ProceedingJoinPoint joinPoint) throws Throwable {",
        "        long start = System.currentTimeMillis();",
        "        String method = joinPoint.getSignature().getName();",
        "",
        "        try {",
        "            Object result = joinPoint.proceed(); // Execute actual method",
        "            long elapsed = System.currentTimeMillis() - start;",
        "            if (elapsed > 500) {",
        "                log.warn(\"SLOW: {} took {}ms\", method, elapsed);",
        "            }",
        "            return result;",
        "        } catch (Exception e) {",
        "            log.error(\"FAILED: {} threw {}\", method, e.getMessage());",
        "            throw e;",
        "        }",
        "    }",
        "}",
        "",
        "@Aspect @Component",
        "public class AuditLogAspect {",
        "",
        "    // Intercept methods annotated with custom @Audited annotation",
        "    @AfterReturning(",
        "        pointcut = \"@annotation(audited)\",",
        "        returning = \"result\"",
        "    )",
        "    public void auditMethodCall(JoinPoint jp, Audited audited, Object result) {",
        "        String user   = SecurityContextHolder.getContext()",
        "                            .getAuthentication().getName();",
        "        String method = jp.getSignature().getName();",
        "        auditRepo.save(new AuditLog(user, method, audited.action(), Instant.now()));",
        "    }",
        "}",
        "",
        "// Custom annotation:",
        "@Target(ElementType.METHOD)",
        "@Retention(RetentionPolicy.RUNTIME)",
        "public @interface Audited {",
        "    String action() default \"\";",
        "}",
        "",
        "// Usage — just annotate the method:",
        "@Audited(action = \"DELETE_ORDER\")",
        "public void deleteOrder(Long orderId) { ... }",
        "// Automatically logged to audit trail without touching the method body!",
      ]},
    ]
  },
  {
    title: "Spring Scheduling & Async Tasks", level: "Intermediate",
    blocks: [
      {t:"text", v:"Production applications need background tasks: send daily reports, clean up expired data, retry failed jobs, sync with external systems. Spring makes this simple with @Scheduled and @Async."},
      {t:"heading", v:"@Scheduled — Background Jobs"},
      {t:"code", lang:"java", v:[
        "@Configuration",
        "@EnableScheduling",
        "public class SchedulerConfig { }",
        "",
        "@Component",
        "public class ScheduledJobs {",
        "",
        "    // Run every 5 minutes",
        "    @Scheduled(fixedDelay = 5 * 60 * 1000)",
        "    public void processOutboxEvents() {",
        "        outboxService.publishPendingEvents();",
        "    }",
        "",
        "    // Cron: every day at 2am",
        "    @Scheduled(cron = \"0 0 2 * * *\")",
        "    public void generateDailyReport() {",
        "        reportService.generateAndEmail();",
        "    }",
        "",
        "    // Cron: every weekday at 9am",
        "    @Scheduled(cron = \"0 0 9 * * MON-FRI\")",
        "    public void sendMorningDigest() {",
        "        emailService.sendDigest();",
        "    }",
        "",
        "    // Run once 30 seconds after startup",
        "    @Scheduled(initialDelay = 30000, fixedDelay = Long.MAX_VALUE)",
        "    public void warmUpCaches() {",
        "        cacheWarmupService.warmUp();",
        "    }",
        "}",
        "",
        "// Cron format: second minute hour day-of-month month day-of-week",
        "// 0 0/15 9-17 * * MON-FRI = Every 15 min, 9am-5pm, weekdays",
      ]},
      {t:"heading", v:"@Async — Non-Blocking Method Calls"},
      {t:"code", lang:"java", v:[
        "@Configuration @EnableAsync",
        "public class AsyncConfig {",
        "    @Bean(name = \"taskExecutor\")",
        "    public Executor taskExecutor() {",
        "        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();",
        "        executor.setCorePoolSize(5);",
        "        executor.setMaxPoolSize(20);",
        "        executor.setQueueCapacity(500);",
        "        executor.setThreadNamePrefix(\"async-\");",
        "        executor.initialize();",
        "        return executor;",
        "    }",
        "}",
        "",
        "@Service",
        "public class NotificationService {",
        "",
        "    // Returns immediately — runs in background thread pool",
        "    @Async(\"taskExecutor\")",
        "    public CompletableFuture<Void> sendEmail(String to, String subject) {",
        "        emailClient.send(to, subject);  // Slow external call",
        "        return CompletableFuture.completedFuture(null);",
        "    }",
        "",
        "    @Async",
        "    public void sendPushNotification(String deviceToken, String message) {",
        "        pushClient.send(deviceToken, message);  // Fire and forget",
        "    }",
        "}",
        "",
        "// In caller: placeOrder returns before email is sent",
        "@Transactional",
        "public Order placeOrder(CreateOrderRequest req) {",
        "    Order order = orderRepo.save(Order.from(req));",
        "    notificationService.sendEmail(order.getEmail(), \"Order Confirmed!\");",
        "    // ^ Returns immediately! Email sent in background.",
        "    return order;  // Fast response to user",
        "}",
      ]},
    ]
  }
);
