export const webServicesData = {
  id: "webservices", icon: "🌐", title: "Web Services & APIs", color: "#8b5cf6", accent: "#a78bfa",
  topics: [
    {
      title: "RESTful API Design — Best Practices", level: "Intermediate",
      blocks: [
        {t:"text", v:"REST (Representational State Transfer) is the dominant architectural style for building web APIs. A well-designed REST API is intuitive, consistent, and a joy to use. Poor API design creates bugs, confusion, and technical debt that haunts teams for years."},
        {t:"heading", v:"REST Constraints & Resource Design"},
        {t:"code", lang:"text", v:[
          "REST CONSTRAINTS:",
          "  1. Stateless       — Each request contains all info needed (no server sessions)",
          "  2. Client-Server   — Separation of concerns",
          "  3. Cacheable       — Responses define their cacheability",
          "  4. Uniform Interface — Consistent resource naming + HTTP verbs",
          "  5. Layered System  — Client doesn't know if talking to server or proxy",
          "",
          "RESOURCE NAMING RULES (nouns, not verbs):",
          "  GOOD:  /api/v1/orders          (collection)",
          "  GOOD:  /api/v1/orders/42       (single resource)",
          "  GOOD:  /api/v1/orders/42/items (sub-resource)",
          "  BAD:   /api/v1/getOrders       (verb in URL)",
          "  BAD:   /api/v1/order           (not plural)",
          "  BAD:   /api/v1/Orders          (inconsistent case)",
          "",
          "HTTP VERBS → CRUD mapping:",
          "  GET    /orders        → List orders (Read)",
          "  GET    /orders/42     → Get order 42 (Read)",
          "  POST   /orders        → Create new order (Create)",
          "  PUT    /orders/42     → Replace order 42 entirely (Update)",
          "  PATCH  /orders/42     → Partially update order 42 (Update)",
          "  DELETE /orders/42     → Delete order 42 (Delete)",
          "",
          "IDEMPOTENCY (calling N times = calling once):",
          "  Idempotent:     GET, PUT, DELETE, HEAD, OPTIONS",
          "  NOT idempotent: POST (creates new resource each call)",
          "  Safe (no side effects): GET, HEAD, OPTIONS",
        ]},
        {t:"heading", v:"API Versioning Strategies"},
        {t:"code", lang:"java", v:[
          "// Strategy 1: URL versioning (most common, most visible)",
          "@RequestMapping(\"/api/v1/orders\")  // v1",
          "@RequestMapping(\"/api/v2/orders\")  // v2 — breaking changes",
          "",
          "// Strategy 2: Header versioning (clean URLs)",
          "@GetMapping(\"/orders\")",
          "public ResponseEntity<?> getOrders(",
          "    @RequestHeader(value=\"API-Version\", defaultValue=\"v1\") String version) {",
          "    if (\"v2\".equals(version)) return ResponseEntity.ok(orderServiceV2.findAll());",
          "    return ResponseEntity.ok(orderService.findAll());",
          "}",
          "",
          "// Strategy 3: Accept header versioning",
          "@GetMapping(value=\"/orders\",",
          "            produces=\"application/vnd.myapi.v1+json\")",
          "public List<OrderV1Dto> getOrdersV1() { ... }",
          "",
          "@GetMapping(value=\"/orders\",",
          "            produces=\"application/vnd.myapi.v2+json\")",
          "public List<OrderV2Dto> getOrdersV2() { ... }",
          "",
          "// Best practice versioning rules:",
          "// 1. Never change behaviour of existing version",
          "// 2. Deprecate old versions with Deprecation header",
          "// 3. Sunset old version with 12 months notice",
          "// 4. Breaking changes: new version",
          "// 5. Additive changes (new fields): same version OK",
        ]},
        {t:"heading", v:"HATEOAS — Self-Describing APIs"},
        {t:"code", lang:"java", v:[
          "// HATEOAS: Hypermedia As The Engine Of Application State",
          "// Responses include links to related actions — like web pages with links",
          "",
          "// Response for GET /orders/42:",
          "{",
          "  'id': 42,",
          "  'status': 'PENDING',",
          "  'total': 299.99,",
          "  '_links': {",
          "    'self':   { 'href': '/api/v1/orders/42' },",
          "    'cancel': { 'href': '/api/v1/orders/42/cancel', 'method': 'POST' },",
          "    'items':  { 'href': '/api/v1/orders/42/items' },",
          "    'customer':{ 'href': '/api/v1/customers/cust-123' }",
          "  }",
          "}",
          "// Client doesn't need to construct URLs — follows links like web browsing",
          "",
          "// Spring HATEOAS implementation:",
          "@RestController",
          "@RequestMapping(\"/api/v1/orders\")",
          "public class OrderController {",
          "    @GetMapping(\"/{id}\")",
          "    public EntityModel<OrderDto> getOrder(@PathVariable Long id) {",
          "        OrderDto order = orderService.findById(id);",
          "        return EntityModel.of(order,",
          "            linkTo(methodOn(OrderController.class).getOrder(id)).withSelfRel(),",
          "            linkTo(methodOn(OrderController.class).getItems(id)).withRel(\"items\"),",
          "            linkTo(methodOn(CustomerController.class).getCustomer(order.getCustomerId())).withRel(\"customer\")",
          "        );",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Pagination, Filtering & Sorting Standards"},
        {t:"code", lang:"java", v:[
          "// Standard pagination response envelope:",
          "@GetMapping",
          "public ResponseEntity<PageResponse<OrderDto>> getOrders(",
          "    @RequestParam(defaultValue = \"0\")    int page,",
          "    @RequestParam(defaultValue = \"20\")   int size,",
          "    @RequestParam(defaultValue = \"createdAt\") String sortBy,",
          "    @RequestParam(defaultValue = \"desc\") String sortDir,",
          "    @RequestParam(required = false)       String status,",
          "    @RequestParam(required = false)       String customerId) {",
          "",
          "    Sort sort = sortDir.equalsIgnoreCase(\"asc\")",
          "        ? Sort.by(sortBy).ascending()",
          "        : Sort.by(sortBy).descending();",
          "    Pageable pageable = PageRequest.of(page, Math.min(size, 100), sort);",
          "",
          "    Page<Order> result = orderService.findAll(customerId, status, pageable);",
          "",
          "    PageResponse<OrderDto> response = PageResponse.<OrderDto>builder()",
          "        .content(result.map(orderMapper::toDto).getContent())",
          "        .page(page)",
          "        .size(size)",
          "        .totalElements(result.getTotalElements())",
          "        .totalPages(result.getTotalPages())",
          "        .first(result.isFirst())",
          "        .last(result.isLast())",
          "        .build();",
          "",
          "    return ResponseEntity.ok()",
          "        .header(\"X-Total-Count\", String.valueOf(result.getTotalElements()))",
          "        .body(response);",
          "}",
          "",
          "// URL: GET /api/v1/orders?page=0&size=20&sortBy=total&sortDir=desc&status=PENDING",
        ]},
        {t:"heading", v:"Error Response Standards"},
        {t:"code", lang:"java", v:[
          "// Consistent error response — RFC 7807 Problem Details standard",
          "@Data @Builder",
          "public class ProblemDetail {",
          "    private String type;      // URI identifying error type",
          "    private String title;     // Short human-readable summary",
          "    private int    status;    // HTTP status code",
          "    private String detail;    // Human-readable explanation",
          "    private String instance; // URI of specific occurrence",
          "    private Instant timestamp;",
          "    private String traceId;   // Distributed trace ID",
          "    private Map<String, Object> errors; // Field validation errors",
          "}",
          "",
          "// Example error responses:",
          "// 400 Bad Request:",
          "// { type: '/errors/validation-failed',",
          "//   title: 'Validation Failed',",
          "//   status: 400,",
          "//   detail: 'Request body has 2 validation errors',",
          "//   errors: { 'customerId': 'must not be blank', 'total': 'must be positive' }}",
          "",
          "// 404 Not Found:",
          "// { type: '/errors/order-not-found',",
          "//   title: 'Order Not Found',",
          "//   status: 404,",
          "//   detail: 'No order found with id: 99999',",
          "//   instance: '/api/v1/orders/99999' }",
        ]},
      ]
    },
    {
      title: "SOAP & JAX-WS — Legacy Web Services", level: "Intermediate",
      blocks: [
        {t:"text", v:"SOAP (Simple Object Access Protocol) is the older XML-based web services standard, still widely used in enterprise systems — banks, insurance, government, SAP integrations. As a J2EE developer you will encounter SOAP in legacy integration work."},
        {t:"heading", v:"SOAP vs REST Comparison"},
        {t:"table", v:[
          ["Aspect","SOAP","REST"],
          ["Protocol","Strict protocol with WSDL contract","Architectural style, flexible"],
          ["Data format","XML only","JSON, XML, any format"],
          ["Transport","HTTP, SMTP, TCP, JMS","HTTP only"],
          ["Contract","WSDL (strict, machine-readable)","OpenAPI/Swagger (optional)"],
          ["Security","WS-Security (header-based)","HTTPS + JWT/OAuth2"],
          ["Transactions","WS-AtomicTransaction support","No built-in transaction support"],
          ["Error handling","SOAP Fault (standard structure)","HTTP status + body"],
          ["Tooling","Auto-generate client from WSDL","Manual or OpenAPI generation"],
          ["Performance","Verbose XML, slower","Lightweight, faster"],
          ["Use case","Enterprise B2B, banking, legacy","Modern APIs, mobile, microservices"],
        ]},
        {t:"heading", v:"Creating a SOAP Web Service with JAX-WS"},
        {t:"code", lang:"java", v:[
          "// Server-side: @WebService creates WSDL automatically",
          "@WebService",
          "@SOAPBinding(style = SOAPBinding.Style.DOCUMENT)",
          "public interface OrderWebService {",
          "",
          "    @WebMethod",
          "    @WebResult(name = \"order\")",
          "    OrderResponse createOrder(",
          "        @WebParam(name = \"request\") CreateOrderRequest request",
          "    );",
          "",
          "    @WebMethod",
          "    @WebResult(name = \"order\")",
          "    OrderResponse getOrder(",
          "        @WebParam(name = \"orderId\") Long orderId",
          "    );",
          "}",
          "",
          "@WebService(endpointInterface = \"com.myapp.OrderWebService\")",
          "@Service",
          "public class OrderWebServiceImpl implements OrderWebService {",
          "",
          "    @Override",
          "    public OrderResponse createOrder(CreateOrderRequest request) {",
          "        Order order = orderService.create(request);",
          "        return OrderResponse.fromOrder(order);",
          "    }",
          "",
          "    @Override",
          "    public OrderResponse getOrder(Long orderId) {",
          "        return OrderResponse.fromOrder(orderService.findById(orderId));",
          "    }",
          "}",
          "",
          "// Register endpoint in Spring Boot:",
          "@Bean",
          "public Endpoint orderEndpoint(Bus bus) {",
          "    EndpointImpl endpoint = new EndpointImpl(bus, new OrderWebServiceImpl());",
          "    endpoint.publish(\"/orders\");",
          "    return endpoint;",
          "}",
          "// WSDL available at: http://localhost:8080/services/orders?wsdl",
        ]},
        {t:"heading", v:"Consuming SOAP Services — Generate Client from WSDL"},
        {t:"code", lang:"bash", v:[
          "# Generate Java client classes from WSDL using wsimport (JDK tool):",
          "wsimport -keep -p com.myapp.client.payment \\",
          "    http://payment-gateway.bank.com/PaymentService?wsdl",
          "",
          "# Or with Maven CXF plugin (pom.xml):",
          "# <plugin>",
          "#   <groupId>org.apache.cxf</groupId>",
          "#   <artifactId>cxf-codegen-plugin</artifactId>",
          "#   <executions>",
          "#     <execution>",
          "#       <goals><goal>wsdl2java</goal></goals>",
          "#       <configuration>",
          "#         <wsdlOptions>",
          "#           <wsdlOption>",
          "#             <wsdl>src/main/resources/payment-service.wsdl</wsdl>",
          "#             <packagename>com.myapp.client.payment</packagename>",
          "#           </wsdlOption>",
          "#         </wsdlOptions>",
          "#       </configuration>",
          "#     </execution>",
          "#   </executions>",
          "# </plugin>",
        ]},
        {t:"code", lang:"java", v:[
          "// Use generated client:",
          "@Service",
          "public class PaymentGatewayClient {",
          "    private final PaymentService paymentService;",
          "",
          "    public PaymentGatewayClient(@Value(\"${payment.gateway.url}\") String wsdlUrl) {",
          "        PaymentServiceService service = new PaymentServiceService(",
          "            new URL(wsdlUrl));",
          "        this.paymentService = service.getPaymentServicePort();",
          "",
          "        // Add WS-Security header for authentication:",
          "        Client client = ClientProxy.getClient(paymentService);",
          "        client.getRequestContext().put(",
          "            \"ws-security.username\", \"myuser\");",
          "        client.getRequestContext().put(",
          "            \"ws-security.password\", \"mypass\");",
          "    }",
          "",
          "    public PaymentResult chargeCard(PaymentRequest request) {",
          "        try {",
          "            ChargeCardRequest soapRequest = new ChargeCardRequest();",
          "            soapRequest.setAmount(request.getAmount());",
          "            soapRequest.setCardToken(request.getCardToken());",
          "            ChargeCardResponse response = paymentService.chargeCard(soapRequest);",
          "            return PaymentResult.from(response);",
          "        } catch (SOAPFaultException e) {",
          "            log.error(\"SOAP fault: {}\", e.getFault().getFaultString());",
          "            throw new PaymentGatewayException(e.getFault().getFaultString());",
          "        }",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "OpenAPI & Swagger — API Documentation", level: "Intermediate",
      blocks: [
        {t:"text", v:"OpenAPI (formerly Swagger) is the standard for documenting REST APIs. Good API documentation is as important as the API itself — it enables faster onboarding, auto-generated clients, and contract-first development."},
        {t:"heading", v:"SpringDoc OpenAPI Setup"},
        {t:"code", lang:"xml", v:[
          "<!-- pom.xml -->",
          "<dependency>",
          "    <groupId>org.springdoc</groupId>",
          "    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>",
          "    <version>2.3.0</version>",
          "</dependency>",
          "<!-- Swagger UI: http://localhost:8080/swagger-ui.html -->",
          "<!-- OpenAPI JSON: http://localhost:8080/v3/api-docs -->",
        ]},
        {t:"code", lang:"java", v:[
          "// Global API info configuration:",
          "@Configuration",
          "public class OpenApiConfig {",
          "    @Bean",
          "    public OpenAPI orderServiceOpenAPI() {",
          "        return new OpenAPI()",
          "            .info(new Info()",
          "                .title(\"Order Service API\")",
          "                .description(\"Manages the full order lifecycle\")",
          "                .version(\"v1.5.0\")",
          "                .contact(new Contact()",
          "                    .name(\"Platform Team\")",
          "                    .email(\"platform@mycompany.com\")))",
          "            .addSecurityItem(new SecurityRequirement().addList(\"bearerAuth\"))",
          "            .components(new Components()",
          "                .addSecuritySchemes(\"bearerAuth\",",
          "                    new SecurityScheme()",
          "                        .type(SecurityScheme.Type.HTTP)",
          "                        .scheme(\"bearer\")",
          "                        .bearerFormat(\"JWT\")));",
          "    }",
          "}",
          "",
          "// Annotate controllers for rich documentation:",
          "@RestController",
          "@RequestMapping(\"/api/v1/orders\")",
          "@Tag(name = \"Orders\", description = \"Order management endpoints\")",
          "public class OrderController {",
          "",
          "    @GetMapping(\"/{id}\")",
          "    @Operation(",
          "        summary = \"Get order by ID\",",
          "        description = \"Returns a single order. Returns 404 if not found.\")",
          "    @ApiResponses({",
          "        @ApiResponse(responseCode = \"200\", description = \"Order found\",",
          "            content = @Content(schema = @Schema(implementation = OrderDto.class))),",
          "        @ApiResponse(responseCode = \"404\", description = \"Order not found\"),",
          "        @ApiResponse(responseCode = \"401\", description = \"Unauthorized\")",
          "    })",
          "    public ResponseEntity<OrderDto> getOrder(",
          "        @Parameter(description = \"Order ID\", example = \"12345\")",
          "        @PathVariable Long id) {",
          "        return ResponseEntity.ok(orderService.findById(id));",
          "    }",
          "}",
          "",
          "// Annotate DTOs for schema documentation:",
          "@Schema(description = \"Order data transfer object\")",
          "public record OrderDto(",
          "    @Schema(description = \"Unique order identifier\", example = \"12345\")",
          "    Long id,",
          "",
          "    @Schema(description = \"Order status\", example = \"PENDING\",",
          "            allowableValues = {\"PENDING\",\"CONFIRMED\",\"SHIPPED\",\"DELIVERED\"})",
          "    String status,",
          "",
          "    @Schema(description = \"Order total in INR\", example = \"1299.99\")",
          "    BigDecimal total",
          ") {}",
        ]},
        {t:"heading", v:"Contract-First API Development"},
        {t:"code", lang:"yaml", v:[
          "# Define API contract FIRST in openapi.yaml, THEN generate server stubs",
          "# This ensures frontend and backend teams agree before writing code",
          "",
          "openapi: 3.0.3",
          "info:",
          "  title: Order Service API",
          "  version: 1.0.0",
          "",
          "paths:",
          "  /api/v1/orders:",
          "    post:",
          "      summary: Create new order",
          "      requestBody:",
          "        required: true",
          "        content:",
          "          application/json:",
          "            schema:",
          "              $ref: '#/components/schemas/CreateOrderRequest'",
          "      responses:",
          "        '201':",
          "          description: Order created",
          "          content:",
          "            application/json:",
          "              schema:",
          "                $ref: '#/components/schemas/OrderDto'",
          "",
          "components:",
          "  schemas:",
          "    CreateOrderRequest:",
          "      type: object",
          "      required: [customerId, items]",
          "      properties:",
          "        customerId:",
          "          type: string",
          "          example: cust-123",
          "        items:",
          "          type: array",
          "          items:",
          "            $ref: '#/components/schemas/OrderItem'",
          "",
          "# Generate Spring Boot server stub from spec:",
          "# mvn openapi-generator:generate -Dgenerator=spring",
        ]},
      ]
    },
    {
      title: "GraphQL — Flexible Query API", level: "Advanced",
      blocks: [
        {t:"text", v:"GraphQL is a query language for APIs where clients specify exactly what data they need. It solves over-fetching (getting too much data) and under-fetching (needing multiple requests) problems that plague REST APIs in complex frontend applications."},
        {t:"heading", v:"GraphQL vs REST"},
        {t:"code", lang:"text", v:[
          "REST PROBLEM — Mobile app showing order list needs:",
          "  GET /orders → returns 30 fields per order (over-fetch)",
          "  For each order: GET /customers/{id} → separate request (under-fetch)",
          "  Result: 1 + N requests, too much data",
          "",
          "GRAPHQL SOLUTION — One request, exactly what you need:",
          "  query {",
          "    orders(status: PENDING, first: 10) {",
          "      id",
          "      status",
          "      total",
          "      customer {    ← nested in same request",
          "        name",
          "        email",
          "      }",
          "    }",
          "  }",
          "  Result: 1 request, only 5 fields per order",
          "",
          "When to use GraphQL:",
          "  ✓ Mobile apps (minimize data over slow connections)",
          "  ✓ BFF (Backend for Frontend) aggregation layer",
          "  ✓ Complex domains with many relationships",
          "  ✓ Rapidly evolving frontend requirements",
          "",
          "When to stick with REST:",
          "  ✓ Simple CRUD APIs",
          "  ✓ Public APIs (REST is more familiar)",
          "  ✓ File upload/download",
          "  ✓ When caching is critical (REST URL-based caching is easy)",
        ]},
        {t:"heading", v:"Spring for GraphQL"},
        {t:"code", lang:"java", v:[
          "// Schema-first: define schema in src/main/resources/graphql/schema.graphqls",
          "// type Query {",
          "//   orders(status: String, first: Int): [Order!]!",
          "//   order(id: ID!): Order",
          "// }",
          "// type Mutation {",
          "//   createOrder(input: CreateOrderInput!): Order!",
          "//   cancelOrder(id: ID!): Order!",
          "// }",
          "// type Order {",
          "//   id: ID!, status: String!, total: Float!",
          "//   customer: Customer!",
          "//   items: [OrderItem!]!",
          "// }",
          "",
          "@Controller",
          "public class OrderGraphQLController {",
          "",
          "    @QueryMapping",
          "    public List<Order> orders(@Argument String status,",
          "                              @Argument Integer first) {",
          "        return orderService.findAll(status, first);",
          "    }",
          "",
          "    @QueryMapping",
          "    public Optional<Order> order(@Argument Long id) {",
          "        return orderService.findById(id);",
          "    }",
          "",
          "    @MutationMapping",
          "    public Order createOrder(@Argument CreateOrderInput input) {",
          "        return orderService.create(input);",
          "    }",
          "",
          "    // BatchMapping: solve N+1 for nested customer data",
          "    @BatchMapping",
          "    public Map<Order, Customer> customer(List<Order> orders) {",
          "        Set<Long> customerIds = orders.stream()",
          "            .map(Order::getCustomerId).collect(Collectors.toSet());",
          "        Map<Long, Customer> customerMap = customerService.findAllById(customerIds)",
          "            .stream().collect(Collectors.toMap(Customer::getId, c -> c));",
          "        return orders.stream()",
          "            .collect(Collectors.toMap(o -> o, o -> customerMap.get(o.getCustomerId())));",
          "        // ONE query for all customers — no N+1!",
          "    }",
          "",
          "    @SubscriptionMapping",
          "    public Flux<Order> orderStatusUpdated(@Argument Long orderId) {",
          "        return orderStatusPublisher.getUpdatesFor(orderId);",
          "        // Real-time WebSocket subscription",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "OAuth2 & JWT — Security Standards", level: "Advanced",
      blocks: [
        {t:"text", v:"OAuth2 is the industry standard for authorization. JWT (JSON Web Token) is the token format used to transmit claims between parties. Understanding these is essential for building secure APIs that integrate with identity providers like Google, Azure AD, and Keycloak."},
        {t:"heading", v:"OAuth2 Grant Types"},
        {t:"code", lang:"text", v:[
          "OAUTH2 ROLES:",
          "  Resource Owner:   The user who owns the data",
          "  Client:           Your application requesting access",
          "  Authorization Server: Issues tokens (Keycloak, Okta, Azure AD)",
          "  Resource Server:  Your API that validates tokens",
          "",
          "AUTHORIZATION CODE (most secure, for web/mobile apps):",
          "  1. User clicks 'Login with Google'",
          "  2. Redirect to Google: /authorize?client_id=...&redirect_uri=...&scope=email",
          "  3. User logs in at Google, grants permission",
          "  4. Google redirects back: /callback?code=AUTH_CODE",
          "  5. Your backend exchanges code for tokens (server-to-server, secure)",
          "  6. Google returns: access_token + refresh_token + id_token",
          "  Use for: Any application where a user logs in",
          "",
          "CLIENT CREDENTIALS (machine-to-machine):",
          "  1. Service A sends: POST /token { client_id, client_secret, grant_type }",
          "  2. Auth server returns: access_token (no user involved)",
          "  Use for: Microservice-to-microservice calls",
          "",
          "PKCE (Proof Key for Code Exchange):",
          "  Authorization Code enhanced for SPAs and mobile apps",
          "  Prevents authorization code interception attacks",
          "  Required when client_secret cannot be kept secret",
        ]},
        {t:"heading", v:"JWT Structure & Validation"},
        {t:"code", lang:"java", v:[
          "// JWT = Header.Payload.Signature (Base64 encoded, dot-separated)",
          "",
          "// Header:",
          "// { 'alg': 'RS256', 'typ': 'JWT', 'kid': 'key-id-123' }",
          "",
          "// Payload (claims):",
          "// {",
          "//   'sub': 'user-uuid-123',          ← Subject (user ID)",
          "//   'email': 'alice@example.com',",
          "//   'roles': ['USER', 'ORDER_ADMIN'],",
          "//   'iss': 'https://auth.mycompany.com', ← Issuer",
          "//   'aud': 'order-service',              ← Audience",
          "//   'iat': 1700000000,                   ← Issued at",
          "//   'exp': 1700003600                    ← Expires (1 hour)",
          "// }",
          "",
          "// Signature = RS256(Base64(header) + '.' + Base64(payload), privateKey)",
          "// Verification = RS256(token, publicKey) — anyone with public key can verify!",
          "",
          "// Spring Boot Resource Server — validate JWTs from Keycloak:",
          "@Configuration",
          "public class SecurityConfig {",
          "    @Bean",
          "    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {",
          "        return http",
          "            .oauth2ResourceServer(oauth2 -> oauth2",
          "                .jwt(jwt -> jwt",
          "                    .jwkSetUri(\"https://auth.mycompany.com/realms/myrealm/protocol/openid-connect/certs\")",
          "                    // Fetches public keys from Keycloak, validates signature",
          "                    .jwtAuthenticationConverter(keycloakRoleConverter())",
          "                ))",
          "            .build();",
          "    }",
          "",
          "    // Map Keycloak roles to Spring Security GrantedAuthority",
          "    private JwtAuthenticationConverter keycloakRoleConverter() {",
          "        JwtGrantedAuthoritiesConverter conv = new JwtGrantedAuthoritiesConverter();",
          "        conv.setAuthoritiesClaimName(\"realm_access.roles\");",
          "        conv.setAuthorityPrefix(\"ROLE_\");",
          "        JwtAuthenticationConverter jwtConverter = new JwtAuthenticationConverter();",
          "        jwtConverter.setJwtGrantedAuthoritiesConverter(conv);",
          "        return jwtConverter;",
          "    }",
          "}",
        ]},
        {t:"heading", v:"API Rate Limiting & Throttling"},
        {t:"code", lang:"java", v:[
          "// Bucket4j — token bucket rate limiting",
          "@Component",
          "public class RateLimitFilter extends OncePerRequestFilter {",
          "",
          "    // 100 requests per minute per user",
          "    private final Map<String, Bucket> buckets = new ConcurrentHashMap<>();",
          "",
          "    private Bucket createBucket() {",
          "        return Bucket.builder()",
          "            .addLimit(Bandwidth.classic(100,",
          "                Refill.greedy(100, Duration.ofMinutes(1))))",
          "            .build();",
          "    }",
          "",
          "    @Override",
          "    protected void doFilterInternal(HttpServletRequest req,",
          "            HttpServletResponse res, FilterChain chain)",
          "            throws ServletException, IOException {",
          "        String userId = getUserId(req);",
          "        Bucket bucket = buckets.computeIfAbsent(userId, k -> createBucket());",
          "",
          "        ConsumptionProbe probe = bucket.tryConsumeAndReturnRemaining(1);",
          "        if (probe.isConsumed()) {",
          "            res.addHeader(\"X-Rate-Limit-Remaining\",",
          "                String.valueOf(probe.getRemainingTokens()));",
          "            chain.doFilter(req, res);",
          "        } else {",
          "            long waitSeconds = probe.getNanosToWaitForRefill() / 1_000_000_000;",
          "            res.setStatus(429);  // Too Many Requests",
          "            res.addHeader(\"Retry-After\", String.valueOf(waitSeconds));",
          "            res.getWriter().write(\"{\\\"error\\\": \\\"Rate limit exceeded\\\"}\");",
          "        }",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "HTML5, CSS3 & JavaScript Essentials", level: "Beginner",
      blocks: [
        {t:"text", v:"Even as a Java backend developer, you need to understand the frontend stack. HTML5, CSS3, and modern JavaScript are the foundation that React and Angular are built on. This knowledge helps you collaborate effectively with frontend teams and understand full-stack architecture."},
        {t:"heading", v:"HTML5 Semantic Structure"},
        {t:"code", lang:"html", v:[
          "<!DOCTYPE html>",
          "<html lang='en'>",
          "<head>",
          "    <meta charset='UTF-8'>",
          "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>",
          "    <title>Order Management</title>",
          "    <link rel='stylesheet' href='styles.css'>",
          "</head>",
          "<body>",
          "    <!-- Semantic HTML5 tags improve SEO and accessibility -->",
          "    <header>",
          "        <nav>",
          "            <a href='/dashboard'>Dashboard</a>",
          "            <a href='/orders'>Orders</a>",
          "        </nav>",
          "    </header>",
          "",
          "    <main>",
          "        <section class='order-list'>",
          "            <h1>Orders</h1>",
          "            <article class='order-card' data-order-id='42'>",
          "                <h2>Order #42</h2>",
          "                <p>Status: <span class='status pending'>Pending</span></p>",
          "                <p>Total: <strong>₹1,299</strong></p>",
          "                <!-- data-* attributes: attach data to elements for JS -->",
          "            </article>",
          "        </section>",
          "",
          "        <aside class='filters'>",
          "            <form id='filter-form'>",
          "                <label for='status'>Status:</label>",
          "                <select id='status' name='status'>",
          "                    <option value=''>All</option>",
          "                    <option value='PENDING'>Pending</option>",
          "                    <option value='SHIPPED'>Shipped</option>",
          "                </select>",
          "                <button type='submit'>Filter</button>",
          "            </form>",
          "        </aside>",
          "    </main>",
          "",
          "    <footer>",
          "        <p>&copy; 2024 MyCompany. All rights reserved.</p>",
          "    </footer>",
          "",
          "    <script src='app.js' defer></script>",
          "</body>",
          "</html>",
        ]},
        {t:"heading", v:"CSS3 — Flexbox & Grid"},
        {t:"code", lang:"css", v:[
          "/* CSS Variables (custom properties) */",
          ":root {",
          "    --primary:    #2563eb;",
          "    --success:    #16a34a;",
          "    --danger:     #dc2626;",
          "    --text:       #1e293b;",
          "    --bg:         #f8fafc;",
          "    --radius:     8px;",
          "    --shadow:     0 1px 3px rgba(0,0,0,0.1);",
          "}",
          "",
          "/* FLEXBOX — one-dimensional layout */",
          ".navbar {",
          "    display: flex;",
          "    justify-content: space-between;  /* space between items */",
          "    align-items: center;             /* vertically center */",
          "    gap: 16px;",
          "    padding: 12px 24px;",
          "}",
          "",
          "/* CSS GRID — two-dimensional layout */",
          ".dashboard {",
          "    display: grid;",
          "    grid-template-columns: 240px 1fr;   /* sidebar + main content */",
          "    grid-template-rows: 60px 1fr 40px;  /* header + content + footer */",
          "    min-height: 100vh;",
          "}",
          "",
          "/* Responsive: stack on mobile */",
          "@media (max-width: 768px) {",
          "    .dashboard {",
          "        grid-template-columns: 1fr;     /* single column */",
          "    }",
          "}",
          "",
          "/* Modern CSS utilities */",
          ".card {",
          "    background: white;",
          "    border-radius: var(--radius);",
          "    box-shadow: var(--shadow);",
          "    padding: 20px;",
          "    transition: transform 0.2s ease, box-shadow 0.2s ease;",
          "}",
          ".card:hover {",
          "    transform: translateY(-2px);",
          "    box-shadow: 0 4px 12px rgba(0,0,0,0.15);",
          "}",
        ]},
        {t:"heading", v:"Modern JavaScript — ES6+ Essentials"},
        {t:"code", lang:"javascript", v:[
          "// Fetch API — call your Spring Boot REST API",
          "async function loadOrders(status = '') {",
          "    try {",
          "        const token = localStorage.getItem('jwt_token');",
          "        const url = `/api/v1/orders${status ? '?status=' + status : ''}`;",
          "",
          "        const response = await fetch(url, {",
          "            headers: {",
          "                'Authorization': `Bearer ${token}`,",
          "                'Content-Type': 'application/json'",
          "            }",
          "        });",
          "",
          "        if (!response.ok) {",
          "            if (response.status === 401) { redirectToLogin(); return; }",
          "            throw new Error(`HTTP error! status: ${response.status}`);",
          "        }",
          "",
          "        const data = await response.json();",
          "        return data.content;  // Your PageResponse content",
          "",
          "    } catch (error) {",
          "        console.error('Failed to load orders:', error);",
          "        showErrorMessage('Failed to load orders. Please try again.');",
          "        return [];",
          "    }",
          "}",
          "",
          "// Destructuring, spread, template literals:",
          "const { id, status, total, customer: { name } } = order;",
          "const updatedOrder = { ...order, status: 'SHIPPED' };",
          "const message = `Order #${id} for ${name}: ₹${total.toFixed(2)}`;",
          "",
          "// Modules (ES6 — used in Angular/React):",
          "// utils.js",
          "export const formatCurrency = (amount) =>",
          "    new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' })",
          "        .format(amount);",
          "",
          "// main.js",
          "import { formatCurrency } from './utils.js';",
        ]},
      ]
    },
  ]
};
