export const microservices = {
  id: "microservices", icon: "🔬", title: "Microservices", color: "#6366f1", accent: "#818cf8",
  topics: [
    {
      title: "What are Microservices & When to Use Them", level: "Beginner",
      blocks: [
        {t:"text", v:"Microservices is an architectural style where you build an application as a collection of small, independent services — each with its own database, deployable separately. Understanding the trade-offs is more important than knowing how to implement them."},
        {t:"heading", v:"Monolith vs Microservices"},
        {t:"code", lang:"text", v:[
          "MONOLITH: One deployable unit, shared database",
          "  PROS:",
          "    + Simple to develop at the start",
          "    + Easy end-to-end testing",
          "    + No network latency between components",
          "    + Simple deployment (one thing to deploy)",
          "  CONS:",
          "    - Teams step on each other as codebase grows",
          "    - Slow builds and deploys for large apps",
          "    - Must scale everything together (can't just scale payments)",
          "    - One bug can crash the whole application",
          "",
          "MICROSERVICES: Many small services, each with own DB",
          "  PROS:",
          "    + Teams deploy independently — no coordination needed",
          "    + Scale individual services as needed",
          "    + Fault isolation — payment down ≠ catalog down",
          "    + Technology freedom per service",
          "  CONS:",
          "    - Complex infrastructure (service discovery, tracing, etc.)",
          "    - Network calls add latency and failure modes",
          "    - Distributed data consistency is hard",
          "    - More DevOps overhead",
          "",
          "RECOMMENDATION: Start with a well-structured MONOLITH.",
          "  Migrate to microservices when teams >10 developers,",
          "  or parts need to scale independently,",
          "  or different services need different tech stacks.",
        ]},
        {t:"heading", v:"Domain-Driven Design — How to Split Services"},
        {t:"code", lang:"text", v:[
          "Use 'Bounded Contexts' — areas of the business with their own",
          "language and rules. Each Bounded Context = one microservice.",
          "",
          "E-Commerce Bounded Contexts:",
          "",
          "         ┌──────────────────────────────────┐",
          "         │           API Gateway            │  Single entry point",
          "         └──┬───┬────┬────┬────┬────────────┘",
          "            │   │    │    │    │",
          "         [User][Cat][Cart][Order][Payment][Ship]",
          "           |    |    |     |      |        |",
          "         UserDB CatDB CartDB OrdDB PayDB ShipDB",
          "",
          "Golden Rule: Each service OWNS its data.",
          "NEVER share a database table between two services.",
          "If Service A needs Service B's data: ask B via API or events.",
        ]},
        {t:"heading", v:"Sync vs Async Communication"},
        {t:"code", lang:"java", v:[
          "// SYNCHRONOUS REST (use when you need an immediate response):",
          "// Order Service calls Payment Service, waits for result",
          "@Service",
          "public class CheckoutService {",
          "    private final WebClient paymentClient;",
          "",
          "    public PaymentResult pay(Order order) {",
          "        return paymentClient.post()",
          "            .uri(\"/api/v1/payments\")",
          "            .bodyValue(PaymentRequest.from(order))",
          "            .retrieve()",
          "            .bodyToMono(PaymentResult.class)",
          "            .timeout(Duration.ofSeconds(5))",
          "            .block();  // Blocking — waits for response",
          "    }",
          "}",
          "",
          "// ASYNCHRONOUS Events (use when you don't need immediate response):",
          "// Order Service publishes event, moves on — others react later",
          "@Service",
          "public class OrderService {",
          "    public Order placeOrder(CreateOrderRequest req) {",
          "        Order order = orderRepo.save(Order.from(req));",
          "        kafkaTemplate.send(\"order.placed\", OrderPlacedEvent.from(order));",
          "        return order; // Return immediately — don't wait for email/inventory",
          "    }",
          "}",
          "// Email Service, Inventory Service, Analytics react independently",
        ]},
      ]
    },
    {
      title: "API Gateway & Service Discovery", level: "Intermediate",
      blocks: [
        {t:"text", v:"With dozens of microservices, clients can't call each service directly. The API Gateway is a single front door that handles routing, authentication, rate limiting, and more. Service Discovery lets services find each other dynamically."},
        {t:"heading", v:"API Gateway — Spring Cloud Gateway"},
        {t:"code", lang:"yaml", v:[
          "spring:",
          "  cloud:",
          "    gateway:",
          "      routes:",
          "        - id: order-service",
          "          uri: lb://ORDER-SERVICE   # lb:// = load-balanced via Eureka",
          "          predicates:",
          "            - Path=/api/v1/orders/**",
          "          filters:",
          "            # Add correlation ID to every request for distributed tracing:",
          "            - AddRequestHeader=X-Correlation-Id, #{T(java.util.UUID).randomUUID()}",
          "",
          "            # Rate limit: 100 requests/second per user:",
          "            - name: RequestRateLimiter",
          "              args:",
          "                redis-rate-limiter.replenishRate: 100",
          "                redis-rate-limiter.burstCapacity: 200",
          "                key-resolver: '#{@userKeyResolver}'",
          "",
          "            # Circuit breaker with fallback:",
          "            - name: CircuitBreaker",
          "              args:",
          "                name: orderCB",
          "                fallbackUri: forward:/fallback/orders",
          "",
          "            # Retry GET requests (safe, idempotent):",
          "            - name: Retry",
          "              args:",
          "                retries: 3",
          "                methods: GET  # NEVER retry POST/DELETE — not idempotent!",
          "",
          "        - id: auth-service",
          "          uri: lb://AUTH-SERVICE",
          "          predicates:",
          "            - Path=/api/v1/auth/**",
          "          filters:",
          "            - RemoveRequestHeader=Cookie  # Strip cookies at gateway",
        ]},
        {t:"heading", v:"Service Discovery — Eureka"},
        {t:"code", lang:"java", v:[
          "// === EUREKA SERVER ===",
          "@SpringBootApplication @EnableEurekaServer",
          "public class RegistryApp {",
          "    public static void main(String[] args) {",
          "        SpringApplication.run(RegistryApp.class, args);",
          "    }",
          "}",
          "// application.yml:",
          "// server.port: 8761",
          "// eureka.client.register-with-eureka: false",
          "// eureka.client.fetch-registry: false",
          "",
          "// === EACH MICROSERVICE registers itself ===",
          "// application.yml for order-service:",
          "// spring.application.name: ORDER-SERVICE",
          "// eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/",
          "",
          "// === CALLING ANOTHER SERVICE BY NAME ===",
          "@Configuration",
          "public class WebClientConfig {",
          "    @Bean",
          "    @LoadBalanced  // Makes WebClient resolve service names via Eureka",
          "    public WebClient.Builder loadBalancedWebClientBuilder() {",
          "        return WebClient.builder();",
          "    }",
          "}",
          "",
          "@Service",
          "public class PaymentService {",
          "    private final WebClient webClient;",
          "",
          "    public PaymentResult charge(PaymentRequest req) {",
          "        // 'PAYMENT-SERVICE' is resolved to real IP:port by Eureka",
          "        // If 3 instances exist, load balancer picks one automatically",
          "        return webClient.post()",
          "            .uri(\"http://PAYMENT-SERVICE/api/v1/payments\")",
          "            .bodyValue(req)",
          "            .retrieve()",
          "            .bodyToMono(PaymentResult.class)",
          "            .block();",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Resilience — Circuit Breaker, Retry & Bulkhead", level: "Advanced",
      blocks: [
        {t:"text", v:"In a distributed system, anything can fail. Without resilience patterns, one slow downstream service will eventually exhaust your thread pool and cascade into a full outage. Resilience4j is the standard library for this in the Spring Boot ecosystem."},
        {t:"heading", v:"Circuit Breaker — Stop Hitting a Failing Service"},
        {t:"code", lang:"text", v:[
          "Problem: Payment service is returning errors.",
          "Each request waits 30s for a timeout, blocking a thread.",
          "1000 users × 30s = thread pool exhausted = your app is also dead.",
          "",
          "Circuit Breaker States:",
          "",
          "  CLOSED ─── (normal, all requests pass through)",
          "     │",
          "     │  failure rate > 50% in last 10 calls",
          "     ▼",
          "  OPEN ──── (fast-fail: return fallback in milliseconds, no real call)",
          "     │",
          "     │  after 30 seconds",
          "     ▼",
          "  HALF-OPEN ─ (let 3 test requests through)",
          "     │             │",
          "     │ success     │ failure",
          "     ▼             ▼",
          "  CLOSED        OPEN again",
          "",
          "Result: Failing downstream = fast error in <1ms, not 30s timeout.",
          "Your app stays responsive. Failing service gets time to recover.",
        ]},
        {t:"heading", v:"Resilience4j Configuration"},
        {t:"code", lang:"yaml", v:[
          "resilience4j:",
          "  circuitbreaker:",
          "    instances:",
          "      payment-service:",
          "        registerHealthIndicator: true  # Shows in /actuator/health",
          "        failureRateThreshold: 50        # Open if >50% of calls fail",
          "        slowCallRateThreshold: 80        # Open if >80% of calls are slow",
          "        slowCallDurationThreshold: 3s    # 'Slow' = >3 seconds",
          "        waitDurationInOpenState: 30s     # Stay OPEN for 30s",
          "        slidingWindowSize: 10            # Evaluate last 10 calls",
          "        permittedNumberOfCallsInHalfOpenState: 3",
          "",
          "  timelimiter:",
          "    instances:",
          "      payment-service:",
          "        timeoutDuration: 5s",
          "",
          "  retry:",
          "    instances:",
          "      inventory-service:",
          "        maxAttempts: 3",
          "        waitDuration: 500ms",
          "        exponentialBackoffMultiplier: 2.0  # 500ms, 1s, 2s",
          "        retryExceptions:",
          "          - java.net.ConnectException",
          "          - java.util.concurrent.TimeoutException",
          "        ignoreExceptions:",
          "          - com.myapp.ValidationException  # Don't retry bad input!",
          "",
          "  bulkhead:",
          "    instances:",
          "      payment-service:",
          "        maxConcurrentCalls: 20   # Max 20 simultaneous calls to payment",
          "        maxWaitDuration: 100ms   # Wait 100ms for a slot, then fail fast",
          "      inventory-service:",
          "        maxConcurrentCalls: 50",
        ]},
        {t:"heading", v:"Applying in Code"},
        {t:"code", lang:"java", v:[
          "@Service @RequiredArgsConstructor",
          "public class PaymentService {",
          "    private final WebClient paymentClient;",
          "",
          "    @CircuitBreaker(name = \"payment-service\", fallbackMethod = \"paymentFallback\")",
          "    @TimeLimiter(name = \"payment-service\")",
          "    @Bulkhead(name = \"payment-service\")",
          "    public CompletableFuture<PaymentResult> processPayment(PaymentRequest req) {",
          "        return paymentClient.post()",
          "            .uri(\"/payments\")",
          "            .bodyValue(req)",
          "            .retrieve()",
          "            .bodyToMono(PaymentResult.class)",
          "            .toFuture();",
          "    }",
          "",
          "    // Fallback: called when circuit is open or timeout exceeded",
          "    public CompletableFuture<PaymentResult> paymentFallback(",
          "            PaymentRequest req, Exception ex) {",
          "        log.warn(\"Payment service unavailable, queueing: {}\", ex.getMessage());",
          "        pendingPaymentsQueue.add(req);  // Process later",
          "        return CompletableFuture.completedFuture(",
          "            PaymentResult.queued(req.getOrderId()));",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Event-Driven Architecture with Kafka", level: "Advanced",
      blocks: [
        {t:"text", v:"Apache Kafka is a distributed event streaming platform. Services publish events (things that happened) and others react asynchronously. This completely decouples services — they don't need to know about each other at all."},
        {t:"heading", v:"Core Kafka Concepts"},
        {t:"code", lang:"text", v:[
          "TOPIC: Named stream of events (like a table, but append-only)",
          "  Examples: order.placed, payment.processed, user.registered",
          "",
          "PARTITION: Topics split into partitions for parallelism.",
          "  Messages in same partition are ordered.",
          "  More partitions = more consumers can work in parallel.",
          "",
          "CONSUMER GROUP: Multiple service instances sharing work.",
          "  3 partitions + 3 instances = each instance reads 1 partition",
          "",
          "  order.events (3 partitions)",
          "    Partition 0 ──> inventory-service instance 1",
          "    Partition 1 ──> inventory-service instance 2",
          "    Partition 2 ──> inventory-service instance 3",
          "",
          "OFFSET: Position within a partition.",
          "  Kafka remembers where each consumer group stopped.",
          "  On restart: continues from where it left off.",
          "  This is how Kafka guarantees at-least-once delivery.",
        ]},
        {t:"heading", v:"Publishing Events"},
        {t:"code", lang:"java", v:[
          "// Event: what happened — use a record for immutability",
          "public record OrderPlacedEvent(",
          "    String orderId,",
          "    String customerId,",
          "    List<OrderItem> items,",
          "    BigDecimal totalAmount,",
          "    Instant occurredAt",
          ") {}",
          "",
          "// Transactional Outbox Pattern: guarantees no events are lost on crash",
          "@Service @Transactional",
          "public class OrderService {",
          "    private final OrderRepository orderRepo;",
          "    private final OutboxRepository outboxRepo;",
          "",
          "    public Order placeOrder(CreateOrderRequest req) {",
          "        // Both writes in the SAME DB transaction:",
          "        Order order = orderRepo.save(Order.from(req));",
          "        outboxRepo.save(new OutboxEvent(",
          "            \"order.placed\",",
          "            JsonUtils.toJson(OrderPlacedEvent.from(order))",
          "        ));",
          "        // If app crashes before publishing to Kafka,",
          "        // a relay process picks up the outbox record on restart.",
          "        // No lost events!",
          "        return order;",
          "    }",
          "}",
          "",
          "// Simple direct publish (use when eventual consistency is acceptable):",
          "kafkaTemplate.send(",
          "    \"order.placed\",",
          "    order.getCustomerId(),  // Message key: same customer -> same partition -> ordered",
          "    OrderPlacedEvent.from(order)",
          ");",
        ]},
        {t:"heading", v:"Consuming Events with Retry & Dead Letter"},
        {t:"code", lang:"java", v:[
          "@Component @Slf4j",
          "public class InventoryEventConsumer {",
          "",
          "    // @RetryableTopic: auto-retry with backoff, then send to dead-letter topic",
          "    @KafkaListener(topics = \"order.placed\", groupId = \"inventory-service\")",
          "    @RetryableTopic(",
          "        attempts = \"4\",",
          "        backoff = @Backoff(delay = 1000, multiplier = 2.0),  // 1s, 2s, 4s",
          "        dltTopicSuffix = \".DLT\"  // Failed events go to order.placed.DLT",
          "    )",
          "    public void handleOrderPlaced(",
          "            @Payload OrderPlacedEvent event,",
          "            @Header(KafkaHeaders.RECEIVED_PARTITION) int partition,",
          "            @Header(KafkaHeaders.OFFSET) long offset) {",
          "",
          "        log.info(\"Processing {} from partition {} offset {}\",",
          "                 event.orderId(), partition, offset);",
          "",
          "        // IDEMPOTENCY: what if this event arrives twice?",
          "        // (Kafka guarantees at-least-once, not exactly-once)",
          "        if (processedRepo.existsById(event.orderId())) {",
          "            log.info(\"Already processed {}, skipping\", event.orderId());",
          "            return;",
          "        }",
          "",
          "        inventoryService.reserve(event.items());",
          "        processedRepo.markProcessed(event.orderId());",
          "    }",
          "",
          "    // Called after ALL 4 retry attempts fail:",
          "    @DltHandler",
          "    public void handleDeadLetter(OrderPlacedEvent event) {",
          "        log.error(\"DEAD LETTER: order {} failed all retries\", event.orderId());",
          "        alertService.page(\"Order processing failed: \" + event.orderId());",
          "        deadLetterRepo.save(DeadLetterRecord.from(event));",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Saga Pattern — Distributed Transactions", level: "Advanced",
      blocks: [
        {t:"text", v:"In microservices, you can't use ACID database transactions across multiple services. The Saga pattern manages distributed transactions by breaking them into a sequence of local transactions, with compensating actions to undo completed steps when something fails."},
        {t:"heading", v:"Why You Need Saga"},
        {t:"code", lang:"text", v:[
          "Placing an order involves 4 services:",
          "  1. OrderService:     Create order record",
          "  2. InventoryService: Reserve items from stock",
          "  3. PaymentService:   Charge customer's card",
          "  4. ShippingService:  Schedule delivery",
          "",
          "If PaymentService FAILS (step 3):",
          "  - Order is created (step 1 committed) ← must undo",
          "  - Inventory is reserved (step 2 committed) ← must undo",
          "  - Payment failed (step 3 rolled back) ← already clean",
          "",
          "Traditional transaction would ROLLBACK all steps automatically.",
          "But these are 4 DIFFERENT databases — no shared transaction!",
          "",
          "Saga Solution: Compensating transactions in reverse order.",
          "  PaymentFailed →",
          "    InventoryService.releaseReservation()  ← undo step 2",
          "    OrderService.cancelOrder()             ← undo step 1",
        ]},
        {t:"heading", v:"Orchestration Saga"},
        {t:"code", lang:"java", v:[
          "@Component @Slf4j @RequiredArgsConstructor",
          "public class PlaceOrderSaga {",
          "    private final OrderService     orderService;",
          "    private final InventoryClient  inventoryClient;",
          "    private final PaymentClient    paymentClient;",
          "    private final ShippingClient   shippingClient;",
          "    private final AlertService     alertService;",
          "",
          "    public OrderResult execute(CreateOrderRequest req) {",
          "        // Stack of undo operations (LIFO = reverse order on failure)",
          "        Deque<Callable<Void>> compensations = new ArrayDeque<>();",
          "",
          "        try {",
          "            // Step 1: Create order",
          "            Order order = orderService.createPending(req);",
          "            compensations.push(() -> {",
          "                orderService.cancel(order.getId(), \"Saga rollback\");",
          "                return null;",
          "            });",
          "",
          "            // Step 2: Reserve inventory",
          "            String reservationId = inventoryClient.reserve(order.getId(), req.getItems());",
          "            compensations.push(() -> {",
          "                inventoryClient.release(reservationId);",
          "                return null;",
          "            });",
          "",
          "            // Step 3: Process payment",
          "            String txnId = paymentClient.charge(req.getCustomerId(), order.getTotal());",
          "            compensations.push(() -> {",
          "                paymentClient.refund(txnId);",
          "                return null;",
          "            });",
          "",
          "            // Step 4: Schedule shipping",
          "            shippingClient.schedule(order);",
          "",
          "            orderService.markConfirmed(order.getId());",
          "            return OrderResult.success(order.getId());",
          "",
          "        } catch (Exception e) {",
          "            log.error(\"Saga failed: {}, compensating...\", e.getMessage());",
          "",
          "            // Execute compensations in reverse order:",
          "            while (!compensations.isEmpty()) {",
          "                try { compensations.pop().call(); }",
          "                catch (Exception ce) {",
          "                    // Compensation itself failed — needs manual review!",
          "                    log.error(\"COMPENSATION FAILED — INCONSISTENT STATE!\", ce);",
          "                    alertService.page(\"Manual intervention needed: saga compensation failed\");",
          "                }",
          "            }",
          "            return OrderResult.failed(e.getMessage());",
          "        }",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Docker & Kubernetes — Production Deployment", level: "Expert",
      blocks: [
        {t:"text", v:"Modern microservices run in Docker containers orchestrated by Kubernetes. Docker packages your app and all dependencies into a portable image. Kubernetes runs hundreds of containers, handles scaling, self-heals failed pods, and rolls out updates with zero downtime."},
        {t:"heading", v:"Optimized Multi-Stage Dockerfile"},
        {t:"code", lang:"dockerfile", v:[
          "# Stage 1: Build the JAR",
          "FROM eclipse-temurin:21-jdk-alpine AS builder",
          "WORKDIR /app",
          "# Copy pom.xml first — Maven dependencies are cached if pom.xml unchanged",
          "COPY pom.xml .",
          "RUN mvn dependency:go-offline -q",
          "COPY src ./src",
          "RUN mvn package -DskipTests -q",
          "",
          "# Stage 2: Extract Spring Boot layers for better Docker layer caching",
          "FROM eclipse-temurin:21-jre-alpine AS layers",
          "WORKDIR /app",
          "COPY --from=builder /app/target/*.jar app.jar",
          "RUN java -Djarmode=layertools -jar app.jar extract",
          "",
          "# Stage 3: Final minimal image (~200MB vs ~400MB for single stage)",
          "FROM eclipse-temurin:21-jre-alpine",
          "WORKDIR /app",
          "# Copy layers: least-changing first (best cache hit rate)",
          "COPY --from=layers /app/dependencies/ ./",
          "COPY --from=layers /app/spring-boot-loader/ ./",
          "COPY --from=layers /app/snapshot-dependencies/ ./",
          "COPY --from=layers /app/application/ ./   # Your code — changes most often",
          "",
          "# Never run as root in production:",
          "RUN addgroup -S app && adduser -S appuser -G app",
          "USER appuser",
          "",
          "EXPOSE 8080",
          "HEALTHCHECK --interval=30s --timeout=3s --start-period=60s \\",
          "  CMD wget -q -O- http://localhost:8080/actuator/health | grep -q UP",
          "",
          "ENTRYPOINT [\"java\",\"-XX:+UseContainerSupport\",",
          "  \"-XX:MaxRAMPercentage=75.0\",\"-XX:+UseG1GC\",",
          "  \"org.springframework.boot.loader.JarLauncher\"]",
        ]},
        {t:"heading", v:"Kubernetes Deployment"},
        {t:"code", lang:"yaml", v:[
          "apiVersion: apps/v1",
          "kind: Deployment",
          "metadata:",
          "  name: order-service",
          "  namespace: production",
          "spec:",
          "  replicas: 3",
          "  strategy:",
          "    type: RollingUpdate",
          "    rollingUpdate:",
          "      maxUnavailable: 1   # Always have 2 pods running during update",
          "      maxSurge: 1         # Spin up 1 extra during update",
          "  template:",
          "    spec:",
          "      containers:",
          "      - name: order-service",
          "        image: myregistry/order-service:1.5.2  # Never use 'latest'!",
          "        resources:",
          "          requests: { memory: 512Mi, cpu: 250m }  # Scheduler uses this",
          "          limits:   { memory: 1Gi,   cpu: 1000m } # Pod killed if exceeded",
          "        # Readiness: remove from load balancer if not ready",
          "        readinessProbe:",
          "          httpGet: { path: /actuator/health/readiness, port: 8080 }",
          "          initialDelaySeconds: 30",
          "          periodSeconds: 10",
          "        # Liveness: restart pod if unhealthy",
          "        livenessProbe:",
          "          httpGet: { path: /actuator/health/liveness, port: 8080 }",
          "          initialDelaySeconds: 60",
          "          failureThreshold: 3",
          "        env:",
          "        - name: SPRING_PROFILES_ACTIVE",
          "          value: prod",
          "        - name: DB_PASSWORD",
          "          valueFrom:",
          "            secretKeyRef:",
          "              name: order-db-secret",
          "              key: password  # From Kubernetes Secret — never hardcode!",
        ]},
        {t:"heading", v:"Horizontal Pod Autoscaler"},
        {t:"code", lang:"yaml", v:[
          "apiVersion: autoscaling/v2",
          "kind: HorizontalPodAutoscaler",
          "metadata:",
          "  name: order-service-hpa",
          "spec:",
          "  scaleTargetRef:",
          "    kind: Deployment",
          "    name: order-service",
          "  minReplicas: 2    # Always at least 2 for high availability",
          "  maxReplicas: 20   # Cap to control cloud costs",
          "  metrics:",
          "  # Scale when average CPU > 70%:",
          "  - type: Resource",
          "    resource:",
          "      name: cpu",
          "      target: { type: Utilization, averageUtilization: 70 }",
          "  # Scale based on Prometheus custom metric (business-level scaling!):",
          "  - type: Pods",
          "    pods:",
          "      metric:",
          "        name: orders_pending_count  # Exposed by Micrometer",
          "      target:",
          "        type: AverageValue",
          "        averageValue: '100'   # Add a pod when > 100 pending orders per pod",
          "  behavior:",
          "    scaleDown:",
          "      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down",
          "      # Prevents 'flapping': spinning up and down repeatedly",
        ]},
      ]
    },
  ]
};
