export const coreJava = {
  id: "core-java", icon: "☕", title: "Core Java", color: "#f59e0b", accent: "#fbbf24",
  topics: [
    {
      title: "JVM, JDK & JRE — How Java Really Works", level: "Beginner",
      blocks: [
        {t:"text", v:"Before writing a single line of Java, you must understand the platform it runs on. This separates developers who guess from developers who know."},
        {t:"heading", v:"The Big Picture — Write Once, Run Anywhere"},
        {t:"code", lang:"text", v:[
          "Your .java file",
          "     |",
          "     v  javac (Java compiler)",
          "  .class file  (bytecode — NOT machine code)",
          "     |",
          "     v  JVM reads bytecode",
          "  Machine Code  (specific to your OS/CPU)",
          "     |",
          "     v",
          "  Program runs!",
          "",
          "Same .class file runs on Windows, Mac, Linux",
          "because each OS has its own JVM implementation.",
        ]},
        {t:"heading", v:"JDK — Java Development Kit (What You Install to Code)"},
        {t:"text", v:"The JDK is what you install on your machine to write and compile Java programs. It contains everything: the compiler (javac), debugger, jar tool, and the JRE."},
        {t:"bullet", v:"**javac**: Compiles .java source files into .class bytecode"},
        {t:"bullet", v:"**java**: Launches the JVM to run your compiled program"},
        {t:"bullet", v:"**jar**: Packages compiled classes into a .jar file for deployment"},
        {t:"bullet", v:"**jdb**: Command-line debugger for troubleshooting"},
        {t:"note", v:"Install JDK 21 (LTS) for all new projects. LTS = Long Term Support = production-stable for years."},
        {t:"heading", v:"JVM Internal Architecture"},
        {t:"code", lang:"text", v:[
          "┌──────────────────────────────────────────┐",
          "│            Class Loader                  │  Loads .class files into memory",
          "├──────────────────────────────────────────┤",
          "│          Runtime Data Areas              │",
          "│  ┌───────────┐  ┌──────────────────────┐│",
          "│  │   Heap    │  │  Stack (per thread)  ││",
          "│  │ (objects) │  │ (method calls, vars) ││",
          "│  └───────────┘  └──────────────────────┘│",
          "│  ┌─────────────────────────────────────┐ │",
          "│  │     Method Area / Metaspace          │ │  Class definitions",
          "│  └─────────────────────────────────────┘ │",
          "├──────────────────────────────────────────┤",
          "│          Execution Engine                │",
          "│   Interpreter + JIT Compiler + GC        │  Actually runs the code",
          "└──────────────────────────────────────────┘",
        ]},
        {t:"subheading", v:"Heap vs Stack — Critical to Understand"},
        {t:"bullet", v:"**Heap**: Where all OBJECTS live. Shared by all threads. Managed by Garbage Collector. Larger but slightly slower."},
        {t:"bullet", v:"**Stack**: Where METHOD CALLS and LOCAL VARIABLES live. Each thread gets its own stack. Auto-cleaned when method returns."},
        {t:"code", lang:"java", v:[
          "public class MemoryExample {",
          "    public static void main(String[] args) {",
          "        int x = 10;              // x lives on the STACK",
          "        String name = \"Alice\";   // 'name' reference on STACK",
          "                                 // actual String object on HEAP",
          "",
          "        Person p = new Person(); // 'p' reference on STACK",
          "                                 // Person object on HEAP",
          "    }",
          "    // When main() returns: stack frame is popped (x, p cleaned up)",
          "    // Person object on Heap becomes eligible for Garbage Collection",
          "    // GC runs periodically and frees heap memory automatically",
          "}",
        ]},
        {t:"heading", v:"Production JVM Tuning"},
        {t:"code", lang:"bash", v:[
          "java \\",
          "  -Xms512m \\                    # Initial heap (JVM starts here)",
          "  -Xmx2g \\                      # Max heap (don't exceed 70% of RAM)",
          "  -XX:+UseG1GC \\               # G1 Garbage Collector (best for most apps)",
          "  -XX:MaxGCPauseMillis=200 \\   # Target max 200ms GC pause",
          "  -XX:+HeapDumpOnOutOfMemoryError \\  # Save heap when app crashes with OOM",
          "  -XX:HeapDumpPath=/var/log/app/ \\",
          "  -XX:+UseContainerSupport \\         # Respect Docker memory limits",
          "  -XX:MaxRAMPercentage=75.0 \\        # Use 75% of container RAM",
          "  -jar payment-service.jar",
        ]},
        {t:"note", v:"Set -Xms equal to -Xmx in production. This prevents the JVM from wasting time resizing the heap and reduces GC pauses significantly."},
      ]
    },
    {
      title: "Data Types, Variables & Operators", level: "Beginner",
      blocks: [
        {t:"text", v:"Java is a strongly-typed language — every variable must have a declared type. This catches bugs at compile time rather than at runtime in front of your users."},
        {t:"heading", v:"The 8 Primitive Types"},
        {t:"table", v:[
          ["Type","Size","Range / Use","Example"],
          ["byte","1 byte","-128 to 127, network data","byte flags = 0b1010;"],
          ["short","2 bytes","-32,768 to 32,767","short port = 8080;"],
          ["int","4 bytes","-2.1B to 2.1B, most integers","int count = 100;"],
          ["long","8 bytes","Very large numbers, IDs","long userId = 9876543210L;"],
          ["float","4 bytes","Decimal, 7 digits precision","float ratio = 3.14f;"],
          ["double","8 bytes","Decimal, 15 digits precision","double pi = 3.14159265;"],
          ["boolean","1 bit","true / false only","boolean active = true;"],
          ["char","2 bytes","Single Unicode character","char grade = 'A';"],
        ]},
        {t:"note", v:"Never use float or double for money — they lose precision! Use **BigDecimal** for all financial calculations."},
        {t:"code", lang:"java", v:[
          "// WHY BigDecimal for money:",
          "double bad = 0.1 + 0.2;         // 0.30000000000000004 ← WRONG!",
          "BigDecimal good = new BigDecimal(\"0.1\").add(new BigDecimal(\"0.2\")); // 0.3 ← CORRECT",
          "",
          "// Integer overflow — silent and dangerous:",
          "int max = Integer.MAX_VALUE;  // 2,147,483,647",
          "int overflow = max + 1;       // -2,147,483,648 — wraps silently!",
          "long safe = (long) max + 1;   // 2,147,483,648 — correct",
          "",
          "// Readable number literals (Java 7+):",
          "int million  = 1_000_000;",
          "long billion = 1_000_000_000L;",
          "int hex      = 0xFF_EC_D1_12;",
        ]},
        {t:"heading", v:"Reference Types vs Primitives"},
        {t:"text", v:"Primitives store the value directly. Reference types (String, arrays, all objects) store a memory address pointing to the object on the heap. This is why == works for primitives but NOT for objects."},
        {t:"code", lang:"java", v:[
          "// Primitives: == compares VALUES",
          "int a = 5, b = 5;",
          "a == b;  // true — same value",
          "",
          "// Objects: == compares MEMORY ADDRESSES (references)",
          "String s1 = new String(\"hello\");",
          "String s2 = new String(\"hello\");",
          "s1 == s2;       // FALSE — different objects in memory",
          "s1.equals(s2);  // TRUE  — same content",
          "",
          "// String Pool exception:",
          "String s3 = \"hello\";  // Goes into String Pool",
          "String s4 = \"hello\";  // Reuses SAME Pool object",
          "s3 == s4;             // TRUE — same object from pool",
          "",
          "// RULE: Always use .equals() to compare Strings and objects",
        ]},
        {t:"heading", v:"Type Casting"},
        {t:"code", lang:"java", v:[
          "// Widening — automatic, safe (smaller type into larger):",
          "int i = 100;",
          "long l = i;      // int -> long: automatic",
          "double d = i;    // int -> double: automatic",
          "",
          "// Narrowing — manual, risky (larger into smaller, may lose data):",
          "double pi = 3.14159;",
          "int truncated = (int) pi;   // 3 — decimal part LOST silently",
          "",
          "// var — local type inference (Java 10+)",
          "var orderMap = new HashMap<String, List<Order>>();  // type inferred",
          "var items = List.of(\"apple\", \"banana\");",
          "",
          "// var is still STRONGLY typed — just inferred at compile time",
          "var name = \"Alice\";",
          "// name = 42;  // COMPILE ERROR — can't assign int to inferred String",
        ]},
      ]
    },
    {
      title: "OOP — Classes, Objects & the 4 Pillars", level: "Beginner",
      blocks: [
        {t:"text", v:"Object-Oriented Programming models your program as a collection of objects — entities with data (fields) and behaviour (methods). Instead of a list of instructions, you think in terms of real-world entities that interact."},
        {t:"heading", v:"Classes and Objects"},
        {t:"code", lang:"java", v:[
          "// CLASS — the blueprint (defines structure and behaviour)",
          "public class BankAccount {",
          "    // Fields: the data/state of each object",
          "    private String accountNumber;",
          "    private String ownerName;",
          "    private double balance;",
          "",
          "    // Constructor: called when creating a new object",
          "    public BankAccount(String accountNumber, String ownerName) {",
          "        this.accountNumber = accountNumber;",
          "        this.ownerName     = ownerName;",
          "        this.balance       = 0.0;",
          "    }",
          "",
          "    // Methods: the behaviour",
          "    public void deposit(double amount) {",
          "        if (amount <= 0) throw new IllegalArgumentException(\"Must be positive\");",
          "        this.balance += amount;",
          "    }",
          "",
          "    public void withdraw(double amount) {",
          "        if (amount > balance) throw new IllegalStateException(\"Insufficient funds\");",
          "        this.balance -= amount;",
          "    }",
          "",
          "    public double getBalance() { return balance; }",
          "}",
          "",
          "// OBJECTS: instances of the blueprint (each has its own state)",
          "BankAccount alice = new BankAccount(\"ACC001\", \"Alice\");",
          "BankAccount bob   = new BankAccount(\"ACC002\", \"Bob\");",
          "",
          "alice.deposit(1000);  // alice.balance = 1000",
          "bob.deposit(500);     // bob.balance   = 500   (independent!)",
        ]},
        {t:"heading", v:"Pillar 1 — Encapsulation (Protect Your Data)"},
        {t:"text", v:"Encapsulation hides internal data and only exposes it through controlled methods. The 'balance' field is private — nobody can set alice.balance = 999999. They must use deposit() which validates input. This protects data integrity."},
        {t:"heading", v:"Pillar 2 — Inheritance (Reuse and Extend)"},
        {t:"code", lang:"java", v:[
          "public class Animal {",
          "    protected String name;",
          "    public Animal(String name) { this.name = name; }",
          "    public void eat() { System.out.println(name + \" is eating\"); }",
          "}",
          "",
          "// Dog IS-A Animal — inherits eat(), name field",
          "public class Dog extends Animal {",
          "    private String breed;",
          "    public Dog(String name, String breed) {",
          "        super(name);      // Call parent constructor first!",
          "        this.breed = breed;",
          "    }",
          "    public void fetch() { System.out.println(name + \" fetches!\"); }",
          "    @Override",
          "    public String toString() { return name + \" (\" + breed + \")\"; }",
          "}",
          "",
          "Dog rex = new Dog(\"Rex\", \"Labrador\");",
          "rex.eat();    // Inherited from Animal",
          "rex.fetch();  // Dog-only method",
        ]},
        {t:"note", v:"Prefer **composition over inheritance**. Only use extends for true IS-A relationships. Use interfaces for shared behaviour contracts."},
        {t:"heading", v:"Pillar 3 — Polymorphism (One Interface, Many Forms)"},
        {t:"code", lang:"java", v:[
          "abstract class Shape {",
          "    abstract double area();",
          "    void printArea() { System.out.println(\"Area: \" + area()); }",
          "}",
          "",
          "class Circle    extends Shape { double r; Circle(double r){this.r=r;} double area(){return Math.PI*r*r;} }",
          "class Rectangle extends Shape { double w,h; Rectangle(double w,double h){this.w=w;this.h=h;} double area(){return w*h;} }",
          "",
          "// Polymorphism: same method call, different behaviour at runtime",
          "List<Shape> shapes = List.of(new Circle(5), new Rectangle(4, 6));",
          "shapes.forEach(Shape::printArea);",
          "// Area: 78.53...",
          "// Area: 24.0",
        ]},
        {t:"heading", v:"Pillar 4 — Abstraction (Hide Complexity)"},
        {t:"code", lang:"java", v:[
          "// Interface defines WHAT, not HOW",
          "public interface PaymentGateway {",
          "    PaymentResult charge(PaymentRequest req);",
          "    boolean refund(String transactionId);",
          "}",
          "",
          "// Stripe and Razorpay both implement the interface differently",
          "public class StripeGateway implements PaymentGateway {",
          "    public PaymentResult charge(PaymentRequest req) { /* Stripe API */ }",
          "    public boolean refund(String txnId)              { /* Stripe refund */ }",
          "}",
          "",
          "// OrderService uses the abstraction — doesn't care which gateway",
          "public class OrderService {",
          "    private final PaymentGateway gateway;  // Could be Stripe, Razorpay, PayPal",
          "    public void checkout(Order order) {",
          "        gateway.charge(order.toPaymentRequest()); // Same code for all gateways",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "SOLID Principles — Professional Code Design", level: "Intermediate",
      blocks: [
        {t:"text", v:"SOLID is a set of 5 principles for writing maintainable, testable, extensible code. Senior developers think in SOLID — it's the difference between code that lasts years vs code that becomes a nightmare in 3 months."},
        {t:"heading", v:"S — Single Responsibility Principle"},
        {t:"text", v:"A class should have ONE reason to change. If UserService handles registration, email, PDF reports, and audit logs — a change to the email template modifies user logic. That's fragile."},
        {t:"code", lang:"java", v:[
          "// BAD: UserService does too many unrelated things",
          "class UserService {",
          "    void register(UserDto dto) { ... }",
          "    void sendWelcomeEmail(User u) { ... }   // email concern",
          "    byte[] generateReport(User u) { ... }   // PDF concern",
          "    void auditLog(User u) { ... }            // audit concern",
          "}",
          "",
          "// GOOD: Each class has ONE responsibility",
          "class UserService        { void register(UserDto dto) { ... } }",
          "class EmailService       { void sendWelcome(User u)   { ... } }",
          "class UserReportService  { byte[] generate(User u)    { ... } }",
          "class AuditService       { void log(String event, Long id) { ... } }",
        ]},
        {t:"heading", v:"O — Open/Closed Principle"},
        {t:"text", v:"Open for extension, closed for modification. Add new behaviour by ADDING new classes, not changing existing tested ones."},
        {t:"code", lang:"java", v:[
          "// BAD: Adding a new discount type requires modifying this class",
          "class DiscountCalculator {",
          "    double calculate(Order o, String type) {",
          "        if (type.equals(\"STUDENT\")) return o.getTotal() * 0.10;",
          "        if (type.equals(\"SENIOR\"))  return o.getTotal() * 0.15;",
          "        // Need VETERAN discount? You must EDIT this file — risky!",
          "        return 0;",
          "    }",
          "}",
          "",
          "// GOOD: Add discounts by adding new classes",
          "interface DiscountStrategy {",
          "    double calculate(Order order);",
          "    boolean appliesTo(User user);",
          "}",
          "class StudentDiscount implements DiscountStrategy {",
          "    public double calculate(Order o) { return o.getTotal() * 0.10; }",
          "    public boolean appliesTo(User u) { return u.isStudent(); }",
          "}",
          "class VeteranDiscount implements DiscountStrategy {",
          "    public double calculate(Order o) { return o.getTotal() * 0.20; }",
          "    public boolean appliesTo(User u) { return u.isVeteran(); }",
          "}",
          "// Adding PayPal? Zero changes to existing code.",
        ]},
        {t:"heading", v:"I — Interface Segregation Principle"},
        {t:"code", lang:"java", v:[
          "// BAD: Fat interface forces implementors to stub methods they don't need",
          "interface NotificationService {",
          "    void sendEmail(String to, String msg);",
          "    void sendSMS(String phone, String msg);",
          "    void sendPush(String deviceId, String msg);",
          "}",
          "// EmailOnlyService is forced to throw UnsupportedOperationException for SMS and Push",
          "",
          "// GOOD: Segregated — implement only what you support",
          "interface EmailNotifier { void sendEmail(String to, String msg); }",
          "interface SMSNotifier   { void sendSMS(String phone, String msg); }",
          "interface PushNotifier  { void sendPush(String deviceId, String msg); }",
          "",
          "class GmailService  implements EmailNotifier { ... }",
          "class TwilioService implements SMSNotifier, EmailNotifier { ... }",
        ]},
        {t:"heading", v:"D — Dependency Inversion Principle"},
        {t:"code", lang:"java", v:[
          "// BAD: OrderService hard-wired to MySQL — can't test without a real DB",
          "class OrderService {",
          "    private MySQLOrderRepository repo = new MySQLOrderRepository();",
          "}",
          "",
          "// GOOD: Depend on the abstraction (interface), not the implementation",
          "interface OrderRepository {",
          "    Order save(Order order);",
          "    Optional<Order> findById(Long id);",
          "}",
          "",
          "class OrderService {",
          "    private final OrderRepository repo;  // Interface!",
          "    public OrderService(OrderRepository repo) { this.repo = repo; }",
          "}",
          "",
          "// Production: Spring injects real JPA implementation",
          "// Tests: inject a Mockito mock — no database needed!",
          "OrderRepository mock = Mockito.mock(OrderRepository.class);",
          "OrderService service = new OrderService(mock);",
        ]},
      ]
    },
    {
      title: "Collections Framework Deep Dive", level: "Intermediate",
      blocks: [
        {t:"text", v:"The Collections Framework is one of the most-used parts of Java. Picking the wrong collection causes bugs (thread safety), wrong results (ordering issues), or major performance problems. Master this and you'll avoid a whole class of production incidents."},
        {t:"heading", v:"Collection Hierarchy Overview"},
        {t:"code", lang:"text", v:[
          "Iterable",
          "  └── Collection",
          "        ├── List        (ordered, allows duplicates)",
          "        │     ├── ArrayList      (array-backed, fast random access)",
          "        │     └── LinkedList     (doubly-linked, fast insert/remove)",
          "        ├── Set         (no duplicates)",
          "        │     ├── HashSet        (no order, O(1) operations)",
          "        │     ├── LinkedHashSet  (insertion order maintained)",
          "        │     └── TreeSet        (sorted, O(log n) operations)",
          "        └── Queue / Deque",
          "              ├── PriorityQueue  (heap-based, smallest first)",
          "              └── ArrayDeque     (fast stack/queue, no nulls)",
          "",
          "Map (key-value pairs, NOT a Collection):",
          "  ├── HashMap            (no order, fastest, O(1))",
          "  ├── LinkedHashMap      (insertion order)",
          "  ├── TreeMap            (sorted by key, O(log n))",
          "  └── ConcurrentHashMap  (thread-safe, lock-free reads)",
        ]},
        {t:"heading", v:"Performance Complexity"},
        {t:"table", v:[
          ["Collection","get/contains","add","remove","Thread Safe?"],
          ["ArrayList","O(1) by index","O(1) amortized","O(n) shift","No"],
          ["LinkedList","O(n) search","O(1) head/tail","O(1) with iter","No"],
          ["HashSet","O(1) avg","O(1) avg","O(1) avg","No"],
          ["TreeSet","O(log n)","O(log n)","O(log n)","No"],
          ["HashMap","O(1) avg","O(1) avg","O(1) avg","No"],
          ["ConcurrentHashMap","O(1)","O(1)","O(1)","YES"],
          ["PriorityQueue","O(n) search","O(log n)","O(log n)","No"],
        ]},
        {t:"heading", v:"Choosing the Right Collection"},
        {t:"code", lang:"java", v:[
          "// Simple ordered list — ArrayList (default choice)",
          "List<Product> products = new ArrayList<>();",
          "",
          "// Fast membership check — HashSet NOT List!",
          "// BAD: O(n) per check = O(n^2) for 1 million items",
          "List<String> processedIds = new ArrayList<>();",
          "if (!processedIds.contains(id)) { ... }  // Slow!",
          "",
          "// GOOD: O(1) per check",
          "Set<String> processedIds = new HashSet<>();",
          "if (processedIds.add(id)) { /* add() returns false if already present */ }",
          "",
          "// Maintain insertion order in a Map (e.g. user cart):",
          "Map<String, CartItem> cart = new LinkedHashMap<>();",
          "",
          "// Thread-safe map for shared state across threads:",
          "Map<String, UserSession> sessions = new ConcurrentHashMap<>();",
          "",
          "// Priority queue — process orders by urgency:",
          "PriorityQueue<Order> queue = new PriorityQueue<>(",
          "    Comparator.comparingInt(Order::getPriority).reversed());",
          "",
          "// Immutable collections (Java 9+) for config data:",
          "List<String>       allowed = List.of(\"GET\", \"POST\", \"PUT\");",
          "Set<String>        roles   = Set.of(\"ADMIN\", \"USER\", \"GUEST\");",
          "Map<String,String> config  = Map.of(\"env\", \"prod\", \"region\", \"us-east\");",
        ]},
        {t:"heading", v:"HashMap Internals — Why equals() and hashCode() Matter"},
        {t:"code", lang:"java", v:[
          "// HashMap uses hashCode() to find the bucket, equals() to find the key",
          "// If you override equals() you MUST override hashCode() — rule!",
          "",
          "// DANGEROUS: Mutable object as HashMap key",
          "class User { String name; }",
          "Map<User, String> roles = new HashMap<>();",
          "User u = new User(); u.name = \"Alice\";",
          "roles.put(u, \"admin\");",
          "u.name = \"Bob\";           // Mutate the key",
          "roles.get(u);             // null! hashCode changed, can't find it",
          "",
          "// SAFE: Always use immutable keys (String, Integer, Long, record)",
          "Map<Long, String> userRoles = new HashMap<>();",
          "userRoles.put(userId, \"admin\"); // Long is immutable — always safe",
        ]},
      ]
    },
    {
      title: "Exception Handling — Production Patterns", level: "Intermediate",
      blocks: [
        {t:"text", v:"Exceptions are how Java signals that something went wrong. Poor exception handling is one of the leading causes of silent data corruption and production incidents. Learn this right — it separates junior from senior developers."},
        {t:"heading", v:"The Exception Hierarchy"},
        {t:"code", lang:"text", v:[
          "Throwable",
          "  ├── Error  (JVM problems — NEVER catch these)",
          "  │     ├── OutOfMemoryError",
          "  │     └── StackOverflowError",
          "  └── Exception",
          "        ├── Checked Exceptions  (must handle or declare)",
          "        │     ├── IOException, SQLException, FileNotFoundException",
          "        │     └── These signal recoverable situations",
          "        └── RuntimeException    (unchecked — optional to handle)",
          "              ├── NullPointerException  — accessed null reference",
          "              ├── IllegalArgumentException — bad method argument",
          "              ├── IllegalStateException    — object in wrong state",
          "              └── IndexOutOfBoundsException — bad array index",
        ]},
        {t:"note", v:"In modern Java (Spring Boot etc.), use unchecked exceptions everywhere for cleaner code. Only checked exceptions where the caller genuinely needs to recover from them (like file I/O)."},
        {t:"heading", v:"try-with-resources — Always Use for I/O"},
        {t:"code", lang:"java", v:[
          "// OLD: error-prone, easy to forget close()",
          "Connection conn = null;",
          "try {",
          "    conn = dataSource.getConnection();",
          "    // ... work",
          "} finally {",
          "    if (conn != null) try { conn.close(); } catch (Exception e) {}",
          "}",
          "",
          "// MODERN: resources auto-closed even if exception thrown",
          "try (Connection conn   = dataSource.getConnection();",
          "     PreparedStatement ps = conn.prepareStatement(SQL)) {",
          "    ps.setLong(1, orderId);",
          "    ResultSet rs = ps.executeQuery();",
          "    // ... process results",
          "} // conn and ps automatically closed here",
          "// Works for any class that implements AutoCloseable",
        ]},
        {t:"heading", v:"Custom Domain Exception Hierarchy"},
        {t:"code", lang:"java", v:[
          "// Base exception — all your app's exceptions extend this",
          "public abstract class AppException extends RuntimeException {",
          "    private final String errorCode;",
          "    private final int httpStatus;",
          "",
          "    protected AppException(String message, String code, int status) {",
          "        super(message);",
          "        this.errorCode  = code;",
          "        this.httpStatus = status;",
          "    }",
          "    // Overload: wraps an underlying cause (exception chaining)",
          "    protected AppException(String message, String code, int status, Throwable cause) {",
          "        super(message, cause);",
          "        this.errorCode  = code;",
          "        this.httpStatus = status;",
          "    }",
          "    public String getErrorCode()  { return errorCode; }",
          "    public int    getHttpStatus() { return httpStatus; }",
          "}",
          "",
          "// Domain-specific exceptions:",
          "public class OrderNotFoundException extends AppException {",
          "    public OrderNotFoundException(Long id) {",
          "        super(\"Order not found: \" + id, \"ORDER_NOT_FOUND\", 404);",
          "    }",
          "}",
          "public class DuplicateEmailException extends AppException {",
          "    public DuplicateEmailException(String email) {",
          "        super(\"Email already registered: \" + email, \"DUPLICATE_EMAIL\", 409);",
          "    }",
          "}",
          "public class InsufficientStockException extends AppException {",
          "    public InsufficientStockException(String sku, int need, int have) {",
          "        super(String.format(\"SKU %s: need %d, have %d\", sku, need, have),",
          "              \"INSUFFICIENT_STOCK\", 422);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Global Exception Handler (Spring Boot)"},
        {t:"code", lang:"java", v:[
          "@RestControllerAdvice",
          "public class GlobalExceptionHandler {",
          "",
          "    @ExceptionHandler(AppException.class)",
          "    public ResponseEntity<ErrorResponse> handleApp(AppException ex) {",
          "        log.warn(\"App exception [{}]: {}\", ex.getErrorCode(), ex.getMessage());",
          "        return ResponseEntity.status(ex.getHttpStatus())",
          "            .body(new ErrorResponse(ex.getErrorCode(), ex.getMessage(), Instant.now()));",
          "    }",
          "",
          "    @ExceptionHandler(MethodArgumentNotValidException.class)",
          "    public ResponseEntity<ErrorResponse> handleValidation(MethodArgumentNotValidException ex) {",
          "        String errors = ex.getBindingResult().getFieldErrors().stream()",
          "            .map(e -> e.getField() + \": \" + e.getDefaultMessage())",
          "            .collect(Collectors.joining(\", \"));",
          "        return ResponseEntity.badRequest()",
          "            .body(new ErrorResponse(\"VALIDATION_FAILED\", errors, Instant.now()));",
          "    }",
          "",
          "    @ExceptionHandler(Exception.class)",
          "    public ResponseEntity<ErrorResponse> handleUnexpected(Exception ex) {",
          "        log.error(\"Unexpected error — this needs investigation!\", ex);",
          "        return ResponseEntity.status(500)",
          "            .body(new ErrorResponse(\"INTERNAL_ERROR\", \"Unexpected error\", Instant.now()));",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Multithreading & Concurrency", level: "Advanced",
      blocks: [
        {t:"text", v:"Concurrency is what lets your application handle many users simultaneously. It's also the source of the hardest-to-find bugs: race conditions that only appear under load, deadlocks that freeze your app. Master this and you're ahead of 90% of developers."},
        {t:"heading", v:"Thread Lifecycle"},
        {t:"code", lang:"text", v:[
          "new Thread() ──> start() ──> RUNNABLE ──> CPU picks it ──> RUNNING",
          "                                                              |",
          "                                          ┌──────────────────┼──────────────┐",
          "                                          v                  v              v",
          "                                       BLOCKED           WAITING      TIMED_WAITING",
          "                                    (waiting for       (wait(),       (sleep(ms),",
          "                                     a lock)           join())         wait(ms))",
          "                                          |                  |              |",
          "                                          └──────────────────┴──────────────┘",
          "                                                             |",
          "                                                        TERMINATED",
        ]},
        {t:"heading", v:"Race Conditions — The Silent Bug"},
        {t:"code", lang:"java", v:[
          "// DANGEROUS: race condition — two threads can both read balance=1000",
          "// and both withdraw 500, leaving balance at 500 instead of 0",
          "public class BankAccount {",
          "    private int balance = 1000;",
          "",
          "    public void withdraw(int amount) {",
          "        if (balance >= amount) {   // Thread A: 1000>=500 TRUE",
          "                                   // --- context switch here ---",
          "                                   // Thread B: 1000>=800 TRUE (reads same 1000!)",
          "            balance -= amount;     // Thread A: balance = 500",
          "                                   // Thread B: balance = -300 !!",
          "        }",
          "    }",
          "}",
          "",
          "// FIX 1: synchronized — only one thread enters at a time",
          "public synchronized void withdraw(int amount) {",
          "    if (balance >= amount) balance -= amount;",
          "}",
          "",
          "// FIX 2: AtomicInteger for simple counters (faster than synchronized)",
          "private final AtomicInteger balance = new AtomicInteger(1000);",
          "public boolean withdraw(int amount) {",
          "    int current, next;",
          "    do {",
          "        current = balance.get();",
          "        if (current < amount) return false;",
          "        next = current - amount;",
          "    } while (!balance.compareAndSet(current, next)); // Retry if changed",
          "    return true;",
          "}",
        ]},
        {t:"heading", v:"ExecutorService — Never Use Raw Threads in Production"},
        {t:"code", lang:"java", v:[
          "// NEVER in production:",
          "new Thread(() -> processOrder(order)).start();",
          "// Creates unbounded threads, no lifecycle management",
          "",
          "// PRODUCTION: bounded thread pool",
          "ThreadPoolExecutor executor = new ThreadPoolExecutor(",
          "    5,                              // corePoolSize: always-alive threads",
          "    20,                             // maximumPoolSize: max under load",
          "    60, TimeUnit.SECONDS,           // idle threads die after 60s",
          "    new LinkedBlockingQueue<>(500), // bounded queue — backpressure!",
          "    new ThreadPoolExecutor.CallerRunsPolicy() // queue full? caller runs it",
          ");",
          "",
          "Future<Order> future = executor.submit(() -> processOrder(request));",
          "Order result = future.get(10, TimeUnit.SECONDS); // timeout after 10s",
        ]},
        {t:"heading", v:"CompletableFuture — Parallel Calls (Java 8+)"},
        {t:"code", lang:"java", v:[
          "// Sequential: 3 API calls × 1s each = 3 seconds total",
          "// Parallel:   3 API calls simultaneously = 1 second total",
          "",
          "CompletableFuture<UserProfile> profileF =",
          "    CompletableFuture.supplyAsync(() -> profileService.get(userId), executor);",
          "CompletableFuture<List<Order>> ordersF =",
          "    CompletableFuture.supplyAsync(() -> orderService.getRecent(userId), executor);",
          "CompletableFuture<Wallet> walletF =",
          "    CompletableFuture.supplyAsync(() -> walletService.get(userId), executor);",
          "",
          "// Wait for all, combine results:",
          "CompletableFuture.allOf(profileF, ordersF, walletF)",
          "    .thenApply(v -> new Dashboard(profileF.join(), ordersF.join(), walletF.join()))",
          "    .exceptionally(ex -> {",
          "        log.error(\"Dashboard load failed\", ex);",
          "        return Dashboard.empty(); // Graceful degradation",
          "    });",
        ]},
        {t:"heading", v:"Virtual Threads — Java 21 (Project Loom)"},
        {t:"code", lang:"java", v:[
          "// Before Loom: thread-per-request model limited to ~1000s of threads",
          "// Platform threads are expensive (1MB stack each)",
          "",
          "// Java 21: Virtual threads are cheap (a few KB each)",
          "// JVM can run MILLIONS of virtual threads on a handful of platform threads",
          "",
          "// Old Spring Boot (blocking I/O):",
          "// 1000 concurrent requests = 1000 threads = needs 1GB just for stacks",
          "",
          "// Spring Boot 3.2+ with virtual threads:",
          "// application.yml:",
          "// spring.threads.virtual.enabled: true",
          "// That's it! Now uses virtual threads for all request handling.",
          "",
          "// Manual virtual thread creation:",
          "try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {",
          "    IntStream.range(0, 100_000).forEach(i ->",
          "        executor.submit(() -> callExternalAPI(i))",
          "    );",
          "} // 100,000 concurrent I/O operations — no thread exhaustion!",
        ]},
      ]
    },
    {
      title: "Java 8–21 Modern Features", level: "Advanced",
      blocks: [
        {t:"text", v:"Java has evolved dramatically. Modern Java (8 through 21) introduced features that fundamentally change how you write code — less boilerplate, more expressive, fewer bugs."},
        {t:"heading", v:"Lambdas & Functional Interfaces (Java 8)"},
        {t:"code", lang:"java", v:[
          "// Before lambdas: verbose anonymous inner classes",
          "Collections.sort(names, new Comparator<String>() {",
          "    @Override public int compare(String a, String b) { return a.compareTo(b); }",
          "});",
          "",
          "// With lambdas: concise",
          "names.sort((a, b) -> a.compareTo(b));",
          "names.sort(String::compareTo); // Method reference — even shorter",
          "",
          "// Built-in functional interfaces:",
          "Predicate<String>      isLong  = s -> s.length() > 10;",
          "Function<String, Integer> len  = String::length;",
          "Consumer<String>       printer = System.out::println;",
          "Supplier<String>       greeting = () -> \"Hello!\";",
          "BiFunction<Integer,Integer,Integer> add = Integer::sum;",
        ]},
        {t:"heading", v:"Stream API (Java 8)"},
        {t:"code", lang:"java", v:[
          "// Declarative data processing — replaces for loops",
          "List<OrderSummary> top5 = orders.stream()",
          "    .filter(o -> o.getStatus() == Status.COMPLETED)",
          "    .filter(o -> o.getDate().isAfter(LocalDate.now().minusDays(30)))",
          "    .sorted(Comparator.comparingDouble(Order::getTotal).reversed())",
          "    .limit(5)",
          "    .map(o -> new OrderSummary(o.getId(), o.getTotal()))",
          "    .collect(Collectors.toList());",
          "",
          "// Aggregations:",
          "double total = orders.stream().mapToDouble(Order::getTotal).sum();",
          "OptionalDouble avg = orders.stream().mapToDouble(Order::getTotal).average();",
          "",
          "// Grouping — very powerful for reporting:",
          "Map<Status, List<Order>> byStatus =",
          "    orders.stream().collect(Collectors.groupingBy(Order::getStatus));",
          "",
          "Map<Status, Long> countByStatus =",
          "    orders.stream().collect(Collectors.groupingBy(Order::getStatus, Collectors.counting()));",
        ]},
        {t:"heading", v:"Optional (Java 8) — No More NullPointerException"},
        {t:"code", lang:"java", v:[
          "// Old way: NPE waiting to happen",
          "User user = repo.findByEmail(email);",
          "String city = user.getAddress().getCity(); // NPE if user or address is null!",
          "",
          "// Optional forces you to handle the empty case:",
          "Optional<User> userOpt = repo.findByEmail(email);",
          "",
          "// Get with default:",
          "String name = userOpt.map(User::getName).orElse(\"Guest\");",
          "",
          "// Throw meaningful exception:",
          "User user = userOpt.orElseThrow(() -> new UserNotFoundException(email));",
          "",
          "// Safe chaining:",
          "String city = userOpt",
          "    .map(User::getAddress)",
          "    .map(Address::getCity)",
          "    .orElse(\"Unknown\");",
          "// No NPE even if user, address, or city is null!",
        ]},
        {t:"heading", v:"Records (Java 16+) — Immutable Data Classes"},
        {t:"code", lang:"java", v:[
          "// Records auto-generate: constructor, getters, equals, hashCode, toString",
          "public record CreateOrderRequest(",
          "    String customerId,",
          "    List<OrderItem> items,",
          "    String deliveryAddress",
          ") {",
          "    // Optional compact constructor for validation:",
          "    public CreateOrderRequest {",
          "        Objects.requireNonNull(customerId, \"customerId required\");",
          "        if (items == null || items.isEmpty())",
          "            throw new IllegalArgumentException(\"Need at least one item\");",
          "        items = List.copyOf(items); // Defensive copy — truly immutable",
          "    }",
          "}",
          "",
          "// Usage — accessor methods use field names (not getXxx):",
          "var req = new CreateOrderRequest(\"cust-1\", items, \"123 Main St\");",
          "req.customerId();       // not getCustomerId()",
          "req.deliveryAddress();  // not getDeliveryAddress()",
        ]},
        {t:"heading", v:"Sealed Classes + Pattern Matching (Java 17/21)"},
        {t:"code", lang:"java", v:[
          "// Sealed: restricts which classes can implement/extend",
          "public sealed interface PaymentResult",
          "    permits PaymentSuccess, PaymentFailure, PaymentPending {}",
          "",
          "record PaymentSuccess(String txnId, BigDecimal amount)  implements PaymentResult {}",
          "record PaymentFailure(String code, boolean retryable)    implements PaymentResult {}",
          "record PaymentPending(String refId, Instant eta)         implements PaymentResult {}",
          "",
          "// Switch expression with pattern matching (Java 21):",
          "// Compiler REQUIRES you to handle ALL cases — no missing branch!",
          "String userMsg = switch (result) {",
          "    case PaymentSuccess s -> \"Paid \" + s.amount() + \". Ref: \" + s.txnId();",
          "    case PaymentFailure f when f.retryable() -> \"Failed, please retry: \" + f.code();",
          "    case PaymentFailure f                    -> \"Failed (permanent): \" + f.code();",
          "    case PaymentPending p -> \"Processing, ETA: \" + p.eta();",
          "};",
          "// Add a new PaymentResult type? Every switch BREAKS until you handle it.",
          "// The compiler is your safety net.",
        ]},
      ]
    },
  ]
};

// Extra topics appended
coreJava.topics.push(
  {
    title: "Generics — Type-Safe Collections & Methods", level: "Intermediate",
    blocks: [
      {t:"text", v:"Generics let you write code that works with any type while maintaining compile-time type safety. Without generics, you'd need to cast everywhere and could get ClassCastException at runtime. With generics, type errors are caught at compile time."},
      {t:"heading", v:"Why Generics?"},
      {t:"code", lang:"java", v:[
        "// Without generics (pre-Java 5) — unsafe:",
        "List list = new ArrayList();",
        "list.add(\"hello\");",
        "list.add(42);       // No error — but mixing types!",
        "String s = (String) list.get(1); // ClassCastException at runtime!",
        "",
        "// With generics — type-safe:",
        "List<String> list = new ArrayList<>();",
        "list.add(\"hello\");",
        "// list.add(42);     // COMPILE ERROR — caught immediately",
        "String s = list.get(0); // No cast needed",
      ]},
      {t:"heading", v:"Generic Classes & Methods"},
      {t:"code", lang:"java", v:[
        "// Generic class: T is a type parameter (placeholder)",
        "public class Box<T> {",
        "    private T value;",
        "    public Box(T value) { this.value = value; }",
        "    public T getValue() { return value; }",
        "    public <R> Box<R> map(Function<T, R> mapper) {",
        "        return new Box<>(mapper.apply(value));",
        "    }",
        "}",
        "",
        "Box<String>  nameBox  = new Box<>(\"Alice\");",
        "Box<Integer> lengthBox = nameBox.map(String::length);",
        "",
        "// Generic method:",
        "public static <T extends Comparable<T>> T max(T a, T b) {",
        "    return a.compareTo(b) >= 0 ? a : b;",
        "}",
        "int maxInt    = max(3, 7);         // T inferred as Integer",
        "String maxStr = max(\"apple\", \"mango\"); // T inferred as String",
        "",
        "// Generic with multiple type parameters:",
        "public class Pair<K, V> {",
        "    private final K key;",
        "    private final V value;",
        "    public Pair(K key, V value) { this.key = key; this.value = value; }",
        "    public K getKey()   { return key; }",
        "    public V getValue() { return value; }",
        "}",
        "Pair<String, Integer> pair = new Pair<>(\"age\", 30);",
      ]},
      {t:"heading", v:"Bounded Type Parameters & Wildcards"},
      {t:"code", lang:"java", v:[
        "// Upper bounded: T must be Number or its subclass",
        "public static <T extends Number> double sum(List<T> list) {",
        "    return list.stream().mapToDouble(Number::doubleValue).sum();",
        "}",
        "sum(List.of(1, 2, 3));         // Integer extends Number: OK",
        "sum(List.of(1.5, 2.5));        // Double extends Number: OK",
        "",
        "// Wildcards:",
        "// ? extends T (upper bounded): can READ, cannot write (covariant)",
        "public void printList(List<? extends Number> list) {",
        "    list.forEach(System.out::println);  // Reading is fine",
        "    // list.add(42);  // COMPILE ERROR",
        "}",
        "",
        "// ? super T (lower bounded): can WRITE, cannot read specific type (contravariant)",
        "public void addNumbers(List<? super Integer> list) {",
        "    list.add(1); list.add(2);  // Writing is fine",
        "}",
        "",
        "// Producer Extends, Consumer Super (PECS rule):",
        "// If a collection PRODUCES T for you to read: use extends",
        "// If a collection CONSUMES T that you write:  use super",
      ]},
      {t:"note", v:"Generics are erased at runtime (type erasure) — `List<String>` and `List<Integer>` are both just `List` at runtime. This is why you can't do `new T()` or `instanceof List<String>`. Use `Class<T>` token pattern when you need runtime type info."},
    ]
  },
  {
    title: "Functional Programming — Streams, Lambdas in Depth", level: "Advanced",
    blocks: [
      {t:"text", v:"Java 8 introduced functional programming features that fundamentally changed how Java code is written. Mastering these makes your code more concise, readable, and parallelizable."},
      {t:"heading", v:"Functional Interfaces — The Foundation"},
      {t:"code", lang:"java", v:[
        "// A functional interface has exactly ONE abstract method",
        "// Can be implemented as a lambda",
        "",
        "// Built-in functional interfaces:",
        "Predicate<String>      isLong   = s -> s.length() > 5;",
        "Function<String, Integer> len   = String::length;",
        "BiFunction<Integer,Integer,Integer> add = Integer::sum;",
        "Consumer<String>       printer  = System.out::println;",
        "Supplier<String>       greeting = () -> \"Hello World\";",
        "UnaryOperator<String>  upper    = String::toUpperCase;",
        "BinaryOperator<Integer> multiply = (a, b) -> a * b;",
        "",
        "// Composing functions:",
        "Function<String, String> transform =",
        "    Function.<String>identity()",
        "        .andThen(String::trim)",
        "        .andThen(String::toLowerCase);",
        "",
        "Predicate<Integer> isPositive = n -> n > 0;",
        "Predicate<Integer> isEven     = n -> n % 2 == 0;",
        "Predicate<Integer> isPositiveEven = isPositive.and(isEven);",
        "Predicate<Integer> eitherOr       = isPositive.or(isEven);",
        "Predicate<Integer> isNegative     = isPositive.negate();",
      ]},
      {t:"heading", v:"Advanced Stream Operations"},
      {t:"code", lang:"java", v:[
        "// flatMap: flatten nested collections",
        "List<List<Integer>> nested = List.of(List.of(1,2), List.of(3,4), List.of(5));",
        "List<Integer> flat = nested.stream()",
        "    .flatMap(Collection::stream)",
        "    .collect(Collectors.toList()); // [1, 2, 3, 4, 5]",
        "",
        "// Collectors.toMap:",
        "Map<Long, Product> productMap = products.stream()",
        "    .collect(Collectors.toMap(",
        "        Product::getId,",
        "        product -> product,",
        "        (existing, duplicate) -> existing  // Handle duplicates",
        "    ));",
        "",
        "// Collectors.teeing (Java 12+): two collectors at once",
        "record Stats(long count, double sum) {}",
        "Stats stats = orders.stream()",
        "    .collect(Collectors.teeing(",
        "        Collectors.counting(),",
        "        Collectors.summingDouble(Order::getTotal),",
        "        Stats::new",
        "    ));",
        "",
        "// Custom collector:",
        "Collector<String, StringBuilder, String> joiner =",
        "    Collector.of(",
        "        StringBuilder::new,",
        "        (sb, s) -> sb.append(s).append(\", \"),",
        "        StringBuilder::append,",
        "        sb -> sb.length() > 0 ? sb.substring(0, sb.length()-2) : \"\"",
        "    );",
        "",
        "// Parallel streams — only for CPU-bound, large collections:",
        "long count = veryLargeList.parallelStream()",
        "    .filter(ExpensiveCheck::test)  // Runs on ForkJoinPool",
        "    .count();",
        "// WARNING: parallel != always faster. Benchmark first.",
        "// Bad for: I/O, stateful operations, small collections",
      ]},
      {t:"heading", v:"Method References — Four Types"},
      {t:"code", lang:"java", v:[
        "// 1. Static method reference: ClassName::staticMethod",
        "Function<String, Integer> parse = Integer::parseInt;",
        "parse.apply(\"42\"); // same as Integer.parseInt(\"42\")",
        "",
        "// 2. Instance method on specific object: object::instanceMethod",
        "String prefix = \"Hello, \";",
        "Function<String, String> greet = prefix::concat;",
        "greet.apply(\"Alice\"); // \"Hello, Alice\"",
        "",
        "// 3. Instance method on arbitrary object of type: ClassName::instanceMethod",
        "Function<String, String> upper = String::toUpperCase;",
        "upper.apply(\"hello\"); // \"HELLO\"",
        "",
        "// 4. Constructor reference: ClassName::new",
        "Supplier<ArrayList<String>> listFactory = ArrayList::new;",
        "Function<String, User> userFactory = User::new;",
        "",
        "// Practical use in streams:",
        "List<String> names = users.stream()",
        "    .map(User::getName)          // Method ref to getter",
        "    .filter(Objects::nonNull)    // Static method ref",
        "    .sorted(String::compareTo)   // Method ref to comparator",
        "    .collect(Collectors.toList());",
      ]},
    ]
  },
  {
    title: "Design Patterns — Gang of Four", level: "Advanced",
    blocks: [
      {t:"text", v:"Design patterns are proven solutions to common software design problems. The Gang of Four (GoF) patterns are the most widely used — you'll see them throughout the Spring framework and every large Java codebase."},
      {t:"heading", v:"Creational: Singleton, Builder, Factory"},
      {t:"code", lang:"java", v:[
        "// SINGLETON: One instance globally",
        "// Thread-safe with double-checked locking:",
        "public class DatabaseConfig {",
        "    private static volatile DatabaseConfig instance;",
        "    private DatabaseConfig() {}",
        "",
        "    public static DatabaseConfig getInstance() {",
        "        if (instance == null) {                    // First check (no lock)",
        "            synchronized (DatabaseConfig.class) {",
        "                if (instance == null)              // Second check (with lock)",
        "                    instance = new DatabaseConfig();",
        "            }",
        "        }",
        "        return instance;",
        "    }",
        "}",
        "// In Spring: @Component is singleton by default — no manual Singleton needed!",
        "",
        "// BUILDER: Construct complex objects step by step",
        "Order order = Order.builder()",
        "    .customerId(\"cust-123\")",
        "    .deliveryAddress(address)",
        "    .addItem(laptop, 1)",
        "    .addItem(mouse, 2)",
        "    .priority(OrderPriority.EXPRESS)",
        "    .build();",
        "",
        "// FACTORY METHOD: Let subclasses decide which class to instantiate",
        "public interface NotificationFactory {",
        "    Notification create(String recipient, String message);",
        "}",
        "public class EmailNotificationFactory implements NotificationFactory {",
        "    public Notification create(String to, String msg) {",
        "        return new EmailNotification(to, msg);",
        "    }",
        "}",
      ]},
      {t:"heading", v:"Structural: Decorator, Proxy, Adapter"},
      {t:"code", lang:"java", v:[
        "// DECORATOR: Add behaviour without changing the original class",
        "interface OrderRepository {",
        "    Optional<Order> findById(Long id);",
        "}",
        "",
        "// Original repository",
        "class JpaOrderRepository implements OrderRepository { ... }",
        "",
        "// Decorator adds caching around existing repository:",
        "class CachingOrderRepository implements OrderRepository {",
        "    private final OrderRepository delegate;  // Wraps original",
        "    private final Map<Long, Order> cache = new HashMap<>();",
        "",
        "    public Optional<Order> findById(Long id) {",
        "        if (cache.containsKey(id)) return Optional.of(cache.get(id));",
        "        Optional<Order> order = delegate.findById(id);",
        "        order.ifPresent(o -> cache.put(id, o));",
        "        return order;",
        "    }",
        "}",
        "// Spring AOP is basically Decorator pattern implemented with proxies!",
        "",
        "// STRATEGY: Encapsulate interchangeable algorithms",
        "interface SortStrategy<T> { List<T> sort(List<T> items); }",
        "",
        "class QuickSort<T extends Comparable<T>> implements SortStrategy<T> {",
        "    public List<T> sort(List<T> items) { /* quicksort */ return items; }",
        "}",
        "class MergeSort<T extends Comparable<T>> implements SortStrategy<T> {",
        "    public List<T> sort(List<T> items) { /* mergesort */ return items; }",
        "}",
        "",
        "class DataProcessor<T extends Comparable<T>> {",
        "    private SortStrategy<T> sortStrategy;",
        "    // Swap strategies at runtime without changing DataProcessor",
        "    public void setSortStrategy(SortStrategy<T> strategy) {",
        "        this.sortStrategy = strategy;",
        "    }",
        "}",
      ]},
      {t:"heading", v:"Behavioural: Observer, Chain of Responsibility"},
      {t:"code", lang:"java", v:[
        "// OBSERVER: Notify subscribers of state changes",
        "// Spring's ApplicationEvent is Observer pattern:",
        "",
        "// 1. Define event:",
        "public class OrderPlacedEvent extends ApplicationEvent {",
        "    private final Order order;",
        "    public OrderPlacedEvent(Object source, Order order) {",
        "        super(source); this.order = order;",
        "    }",
        "    public Order getOrder() { return order; }",
        "}",
        "",
        "// 2. Publish event:",
        "@Service",
        "public class OrderService {",
        "    private final ApplicationEventPublisher events;",
        "    public Order placeOrder(CreateOrderRequest req) {",
        "        Order order = orderRepo.save(Order.from(req));",
        "        events.publishEvent(new OrderPlacedEvent(this, order));",
        "        return order;",
        "    }",
        "}",
        "",
        "// 3. Multiple listeners (observers):",
        "@EventListener",
        "public void sendConfirmationEmail(OrderPlacedEvent e) { ... }",
        "",
        "@EventListener @Async",
        "public void updateInventory(OrderPlacedEvent e) { ... }",
        "",
        "@EventListener @Async",
        "public void notifyWarehouse(OrderPlacedEvent e) { ... }",
        "// OrderService doesn't know about email/inventory/warehouse",
        "// — fully decoupled via Observer pattern",
      ]},
    ]
  }
);

coreJava.topics.push(
  {
    title: "Core Java Interview Questions — Complete Bank", level: "Advanced",
    blocks: [
      {t:"text", v:"These are the most asked Core Java questions at top companies. Answers go deep — memorising the definition is not enough, you need to explain the 'why' and handle cross-questions confidently."},
      {t:"heading", v:"Q1: What is the difference between String, StringBuilder, and StringBuffer?"},
      {t:"code", lang:"java", v:[
        "// String: IMMUTABLE — every operation creates a new object",
        "String s = \"Hello\";",
        "s = s + \" World\";  // Creates NEW String object, old one eligible for GC",
        "s.concat(\" Java\"); // Returns new String — original s unchanged!",
        "",
        "// Why immutable?",
        "// 1. Thread-safe by design — can be shared across threads safely",
        "// 2. String Pool works because value never changes",
        "// 3. Safe as HashMap key — hashcode never changes",
        "// 4. Security — can't modify a String passed to a method",
        "",
        "// StringBuilder: MUTABLE, NOT thread-safe, fast",
        "StringBuilder sb = new StringBuilder();",
        "for (int i = 0; i < 10000; i++) {",
        "    sb.append(i).append(\",\"); // Same object, internal char array grows",
        "}",
        "String result = sb.toString();",
        "// Use StringBuilder for: string building in loops, single-threaded code",
        "",
        "// StringBuffer: MUTABLE, thread-safe (synchronized), slower",
        "StringBuffer buffer = new StringBuffer();",
        "buffer.append(\"thread-safe\"); // synchronized methods",
        "// Use StringBuffer: multi-threaded shared string building (rare in practice)",
        "",
        "// Performance comparison for 10,000 concatenations:",
        "// String:        VERY slow — 10,000 new String objects created",
        "// StringBuilder: FAST — one object, O(1) amortized append",
        "// StringBuffer:  Fast but slower than StringBuilder (sync overhead)",
        "",
        "// Java compiler optimizes simple concatenation:",
        "String a = \"Hello\" + \" \" + \"World\"; // Compile-time constant → one String",
        "String b = firstName + \" \" + lastName; // Compiler converts to StringBuilder",
      ]},
      {t:"note", v:"Cross Question: 'Why is String immutable in Java?' → Five reasons: 1) String Pool efficiency — multiple references can safely point to same object. 2) Thread safety — immutable objects are automatically thread-safe. 3) Security — passwords/file paths can't be modified after validation. 4) HashMap keys — hashCode consistent (cached after first call). 5) JVM optimization — class loading, reflection use String and need stability. Cross Question: 'What is String interning?' → String.intern() moves a heap String into the String Pool and returns the pool reference. Useful for memory optimization when many duplicate Strings exist (e.g., storing millions of same-value strings)."},
      {t:"heading", v:"Q2: What is the difference between abstract class and interface? When to use each?"},
      {t:"code", lang:"java", v:[
        "// ABSTRACT CLASS:",
        "// - Can have constructors",
        "// - Can have instance variables (state)",
        "// - Can have concrete methods (default implementation)",
        "// - Can have any access modifiers",
        "// - A class can extend ONLY ONE abstract class",
        "// Use when: sharing code between closely related classes (IS-A + shared behavior)",
        "",
        "public abstract class Animal {",
        "    protected String name;    // State — concrete field",
        "    protected int age;",
        "",
        "    public Animal(String name, int age) {  // Constructor",
        "        this.name = name; this.age = age;",
        "    }",
        "",
        "    public void eat() {                    // Concrete method — shared",
        "        System.out.println(name + \" is eating\");",
        "    }",
        "",
        "    public abstract void makeSound();      // Must implement in subclass",
        "}",
        "",
        "// INTERFACE (Java 8+):",
        "// - No constructors, no instance variables",
        "// - All fields are public static final (constants)",
        "// - Methods: abstract (must implement), default (optional override),",
        "//            static (utility), private (helper for default methods)",
        "// - A class can implement MULTIPLE interfaces",
        "// Use when: defining a contract/capability across unrelated classes",
        "",
        "public interface Payable {",
        "    PaymentResult processPayment(BigDecimal amount);  // Must implement",
        "",
        "    default void logPayment(BigDecimal amount) {      // Optional override",
        "        System.out.println(\"Payment processed: \" + amount);",
        "    }",
        "",
        "    static Payable create(String type) {              // Factory utility",
        "        return \"STRIPE\".equals(type) ? new StripeGateway() : new RazorpayGateway();",
        "    }",
        "}",
        "",
        "// Real-world example — combine both:",
        "abstract class Vehicle {         // Abstract: shared state + behavior",
        "    protected int speed;",
        "    public void start() { speed = 10; }",
        "    public abstract String getType();",
        "}",
        "",
        "interface Electric {            // Interface: capability",
        "    void charge();",
        "    default int getBatteryLevel() { return 80; }",
        "}",
        "",
        "interface Autonomous {          // Interface: another capability",
        "    void enableAutopilot();",
        "}",
        "",
        "class Tesla extends Vehicle implements Electric, Autonomous {",
        "    public String getType() { return \"Electric Car\"; }",
        "    public void charge() { /* ... */ }",
        "    public void enableAutopilot() { /* ... */ }",
        "}",
      ]},
      {t:"note", v:"Cross Question: 'What is a default method in interface and why was it added in Java 8?' → Default methods allow interfaces to have concrete implementations without breaking existing implementations. Added to enable evolution of existing interfaces — Java Collections Framework needed forEach(), stream() etc. without breaking the millions of existing Collection implementations. Cross Question: 'What is diamond problem in Java and how does it handle it?' → If two interfaces have same default method and a class implements both, compiler forces you to override and resolve the conflict. Example: MyClass must override the conflicting method and specify which interface's implementation to call using InterfaceA.super.method()."},
      {t:"heading", v:"Q3: Explain Java Memory Management and Garbage Collection"},
      {t:"code", lang:"java", v:[
        "// JVM Memory structure:",
        "// HEAP: new objects go here (shared across threads)",
        "//   Young Generation:",
        "//     Eden Space:     new objects created here",
        "//     Survivor S0/S1: objects that survived Minor GC",
        "//   Old Generation (Tenured): long-lived objects",
        "// METASPACE: class definitions, method metadata (JDK 8+, replaced PermGen)",
        "// STACK: each thread has its own (method frames, local vars)",
        "",
        "// GC Process:",
        "// Minor GC: Eden full → copy survivors to S0/S1",
        "//   Objects that survive enough minor GCs → promoted to Old Gen",
        "// Major/Full GC: Old Gen full → collect entire heap (STOP-THE-WORLD)",
        "",
        "// GC Algorithms:",
        "// G1GC (default since Java 9):",
        "//   Divides heap into equal-sized regions",
        "//   Predictable pause times (target with -XX:MaxGCPauseMillis)",
        "//   Best for: most production apps, 4GB+ heap",
        "",
        "// ZGC (Java 15+ production-ready):",
        "//   Pause times < 10ms regardless of heap size",
        "//   Concurrent — most work happens alongside application",
        "//   Best for: latency-sensitive apps (trading, real-time)",
        "",
        "// Common memory leak causes in Java:",
        "// 1. Static collections that grow forever:",
        "static Map<String, Object> cache = new HashMap<>(); // Never evicted!",
        "",
        "// 2. Event listeners not removed:",
        "button.addActionListener(this); // Object held as long as button exists",
        "// Fix: button.removeActionListener(this) when done",
        "",
        "// 3. ThreadLocal not cleaned:",
        "ThreadLocal<UserContext> ctx = new ThreadLocal<>();",
        "ctx.set(user); // Must call ctx.remove() in finally block!",
        "",
        "// 4. Unclosed streams/connections:",
        "FileInputStream fis = new FileInputStream(\"file.txt\");",
        "// fis.close() never called → file descriptor leak",
        "// Fix: always use try-with-resources",
        "",
        "// Memory tuning flags:",
        "// -Xms512m -Xmx2g         Initial/Max heap",
        "// -XX:+UseG1GC             GC algorithm",
        "// -XX:MaxGCPauseMillis=200 Target max pause",
        "// -XX:+HeapDumpOnOutOfMemoryError  Save heap on OOM",
      ]},
      {t:"note", v:"Cross Question: 'How do you diagnose an OutOfMemoryError in production?' → 1) Check which type: java.lang.OutOfMemoryError: Java heap space (heap full), GC overhead limit exceeded (GC taking >98% of time), Metaspace (too many classes loaded). 2) Analyze heap dump (jmap -dump or -XX:+HeapDumpOnOutOfMemoryError). 3) Use Eclipse MAT or IntelliJ to find largest object trees. 4) Look for collections that grew unexpectedly. Cross Question: 'What is the difference between WeakReference, SoftReference, and PhantomReference?' → WeakReference: collected at next GC (used in WeakHashMap for caches). SoftReference: collected only when JVM needs memory (better for caches). PhantomReference: collected after finalization, used for cleanup actions."},
      {t:"heading", v:"Q4: What is the Java Memory Model (JMM) and what is the 'happens-before' relationship?"},
      {t:"code", lang:"java", v:[
        "// Java Memory Model defines:",
        "// - How threads interact through memory",
        "// - When changes made by one thread are visible to others",
        "// - What orderings of memory operations are guaranteed",
        "",
        "// Without JMM guarantees — visibility problem:",
        "class SharedData {",
        "    boolean ready = false;",
        "    int value = 0;",
        "}",
        "",
        "// Thread 1:",
        "data.value = 42;",
        "data.ready = true;",
        "",
        "// Thread 2:",
        "while (!data.ready) {}   // May loop forever!",
        "System.out.println(data.value); // May print 0!",
        "// CPU caches and instruction reordering can break this",
        "",
        "// Happens-Before rules (guarantees visibility):",
        "// 1. Within a thread: each action happens-before subsequent actions",
        "// 2. Monitor unlock happens-before subsequent lock of same monitor",
        "// 3. volatile write happens-before subsequent read of same variable",
        "// 4. Thread.start() happens-before all actions in started thread",
        "// 5. All actions in thread happen-before Thread.join() returns",
        "// 6. Constructor completion happens-before finalizer start",
        "",
        "// Fix with volatile:",
        "class SafeSharedData {",
        "    volatile boolean ready = false;  // Volatile write/read = happens-before",
        "    int value = 0;                    // Safe because ready guards it",
        "}",
        "",
        "// Fix with synchronized:",
        "synchronized (lock) { data.value = 42; data.ready = true; }",
        "synchronized (lock) { if (data.ready) use(data.value); }",
        "",
        "// volatile vs synchronized:",
        "// volatile:    visibility only (no atomicity)",
        "//              int x++; is NOT atomic even with volatile!",
        "// synchronized: visibility + atomicity + mutual exclusion",
        "",
        "// AtomicInteger for atomic compound operations:",
        "AtomicInteger counter = new AtomicInteger(0);",
        "counter.incrementAndGet();  // Atomic: read + increment + write as one operation",
        "counter.compareAndSet(5, 10); // CAS: set to 10 only if currently 5",
      ]},
      {t:"heading", v:"Q5: What are the new features in Java 11, 17, and 21 and what do they mean for production code?"},
      {t:"table", v:[
        ["Version","Key Feature","Production Impact"],
        ["Java 11 (LTS)","var in lambda, HTTP Client, String methods","isBlank(), strip(), lines(), repeat()"],
        ["Java 14","Switch expressions (standard)","Return values from switch, no fall-through"],
        ["Java 15","Text blocks (standard)","Multi-line strings without \\n escaping"],
        ["Java 16","Records (standard), Pattern matching instanceof","Immutable DTOs in one line"],
        ["Java 17 (LTS)","Sealed classes, Random generators","Model domain hierarchies, secure random"],
        ["Java 19-20","Virtual threads (preview)","Millions of concurrent I/O tasks"],
        ["Java 21 (LTS)","Virtual threads (standard), Sequenced Collections, Pattern matching in switch","Game-changing for microservices scalability"],
      ]},
      {t:"code", lang:"java", v:[
        "// Java 21 highlights for production Java developers:",
        "",
        "// 1. Virtual Threads — change everything for I/O-bound microservices",
        "// Spring Boot 3.2+: spring.threads.virtual.enabled=true",
        "// Before: 1 platform thread per request → max ~1000 concurrent requests",
        "// After:  1 virtual thread per request  → millions of concurrent requests",
        "// Virtual threads are cheap (few KB vs 1MB for platform threads)",
        "",
        "// 2. Sequenced Collections — consistent first/last API",
        "SequencedCollection<String> list = new ArrayList<>(List.of(\"a\",\"b\",\"c\"));",
        "list.getFirst();  // \"a\" — works on List, Deque, LinkedHashSet",
        "list.getLast();   // \"c\"",
        "list.addFirst(\"z\"); // Add at front",
        "list.reversed();    // Reversed view",
        "",
        "// 3. Pattern Matching in Switch (standard)",
        "Object obj = getObject();",
        "String result = switch (obj) {",
        "    case Integer i when i > 0  -> \"Positive: \" + i;",
        "    case Integer i             -> \"Non-positive: \" + i;",
        "    case String s when s.isEmpty() -> \"Empty string\";",
        "    case String s              -> \"String: \" + s;",
        "    case null                  -> \"null\";",
        "    default                    -> \"Other: \" + obj;",
        "};",
        "",
        "// 4. Record Patterns",
        "record Point(int x, int y) {}",
        "Object o = new Point(1, 2);",
        "if (o instanceof Point(int x, int y)) {",
        "    System.out.println(\"x=\" + x + \", y=\" + y);",
        "}",
      ]},
    ]
  },
  {
    title: "Java Collections & Data Structures Interview Q&A", level: "Intermediate",
    blocks: [
      {t:"text", v:"Collections questions are asked in almost every Java interview. These go beyond 'what is HashMap' — interviewers want you to know internals, thread safety, and production trade-offs."},
      {t:"heading", v:"Q1: How does HashMap work internally? What changed in Java 8?"},
      {t:"code", lang:"java", v:[
        "// HashMap = array of linked lists (buckets)",
        "// Key → hashCode() → index in array → put in that bucket",
        "",
        "// Step-by-step for put(key, value):",
        "// 1. key.hashCode() → int (may be large)",
        "// 2. Apply secondary hash: hash = (h = key.hashCode()) ^ (h >>> 16)",
        "//    (This spreads bits to reduce collisions)",
        "// 3. index = hash & (capacity - 1)  (capacity is always power of 2)",
        "// 4. If bucket empty: add Entry directly",
        "// 5. If bucket has entries: traverse, check key.equals(existing)",
        "//    - equals() true: UPDATE existing value",
        "//    - equals() false: ADD to bucket (collision)",
        "",
        "// PRE-Java 8: Collisions = Linked List → O(n) worst case",
        "// JAVA 8+:    When bucket has >8 entries → convert to Red-Black Tree → O(log n)",
        "",
        "// HashMap pitfalls:",
        "",
        "// 1. Mutable key — hashCode changes after mutation!",
        "Map<List<String>, String> bad = new HashMap<>();",
        "List<String> key = new ArrayList<>(List.of(\"a\"));",
        "bad.put(key, \"value\");",
        "key.add(\"b\");  // Mutating the key!",
        "bad.get(key);  // null — hashCode changed, bucket changed!",
        "// RULE: Only use immutable objects as HashMap keys",
        "",
        "// 2. Missing equals/hashCode — objects not found in map",
        "class Order { Long id; }",
        "Map<Order, String> map = new HashMap<>();",
        "Order o1 = new Order(42L);",
        "map.put(o1, \"data\");",
        "Order o2 = new Order(42L);",
        "map.get(o2); // null! o1 and o2 are different objects, default hashCode differs",
        "// FIX: Override equals() and hashCode() (or use @EqualsAndHashCode from Lombok)",
        "",
        "// 3. ConcurrentModificationException:",
        "Map<String, Integer> map2 = new HashMap<>();",
        "for (Map.Entry<String, Integer> entry : map2.entrySet()) {",
        "    if (entry.getValue() == 0) map2.remove(entry.getKey()); // EXCEPTION!",
        "}",
        "// FIX: Use iterator.remove() or ConcurrentHashMap or collect-then-remove",
        "map2.entrySet().removeIf(e -> e.getValue() == 0); // Safe",
      ]},
      {t:"note", v:"Cross Question: 'What is the load factor in HashMap and what happens when it's exceeded?' → Default load factor is 0.75. When (size / capacity) > 0.75, HashMap RESIZES: creates new array of double the capacity and rehashes all entries. This is expensive (O(n)). Pre-size if you know the expected size: new HashMap<>(expectedSize * 2) to avoid resizing. Cross Question: 'What is the difference between HashMap and Hashtable?' → Hashtable: synchronized (thread-safe), doesn't allow null keys/values, legacy class (avoid it). HashMap: not synchronized, allows one null key, multiple null values, faster. Use ConcurrentHashMap for thread-safe maps."},
      {t:"heading", v:"Q2: When should you use LinkedList over ArrayList?"},
      {t:"code", lang:"java", v:[
        "// ArrayList: backed by array",
        "// get(index):    O(1) — direct array access",
        "// add(end):      O(1) amortized — array may need to grow",
        "// add(middle):   O(n) — shifts elements right",
        "// remove(middle):O(n) — shifts elements left",
        "// Memory: compact (just the array + object overhead)",
        "",
        "// LinkedList: doubly-linked list",
        "// get(index):    O(n) — must traverse from head or tail",
        "// add(head/tail):O(1) — just change pointers",
        "// add(middle):   O(n) to find position + O(1) to insert",
        "// remove(with iterator): O(1) — just change pointers",
        "// Memory: MORE overhead (each element = node + 2 pointers)",
        "",
        "// WHEN TO USE LinkedList:",
        "// 1. Queue/Deque operations (addFirst, addLast, removeFirst)",
        "Deque<Task> taskQueue = new LinkedList<>();",
        "taskQueue.addFirst(highPriorityTask);  // O(1)",
        "taskQueue.addLast(normalTask);          // O(1)",
        "Task next = taskQueue.pollFirst();       // O(1)",
        "",
        "// 2. Frequent insertions/deletions in the MIDDLE using iterator:",
        "ListIterator<String> iter = linkedList.listIterator();",
        "while (iter.hasNext()) {",
        "    if (shouldRemove(iter.next())) iter.remove(); // O(1)",
        "}",
        "",
        "// In PRACTICE: ArrayList wins almost always",
        "// - Better CPU cache locality (contiguous memory)",
        "// - Even O(n) shifts are fast due to System.arraycopy (native, vectorized)",
        "// - LinkedList pointer chasing kills CPU cache performance",
        "// Benchmark before assuming LinkedList is faster for your use case!",
      ]},
      {t:"heading", v:"Q3: What is the difference between Comparable and Comparator?"},
      {t:"code", lang:"java", v:[
        "// Comparable: natural ordering — class defines its own comparison",
        "// Implement in the CLASS itself",
        "public class Product implements Comparable<Product> {",
        "    private String name;",
        "    private BigDecimal price;",
        "",
        "    @Override",
        "    public int compareTo(Product other) {",
        "        return this.price.compareTo(other.price); // Sort by price ascending",
        "    }",
        "}",
        "",
        "List<Product> products = new ArrayList<>(getAllProducts());",
        "Collections.sort(products); // Uses compareTo — natural order (by price)",
        "",
        "// Comparator: external, custom ordering — defined separately",
        "// Multiple different orderings without changing the class",
        "",
        "// Sort by name:",
        "products.sort(Comparator.comparing(Product::getName));",
        "",
        "// Sort by price descending:",
        "products.sort(Comparator.comparing(Product::getPrice).reversed());",
        "",
        "// Multi-level sort: by category, then by price:",
        "products.sort(Comparator",
        "    .comparing(Product::getCategory)",
        "    .thenComparing(Product::getPrice)",
        "    .thenComparing(Product::getName));",
        "",
        "// Null-safe comparator:",
        "products.sort(Comparator",
        "    .comparing(Product::getCategory,",
        "               Comparator.nullsLast(Comparator.naturalOrder()))",
        "    .thenComparing(Product::getPrice));",
        "",
        "// TreeMap with custom ordering:",
        "Map<String, Integer> caseInsensitive =",
        "    new TreeMap<>(String.CASE_INSENSITIVE_ORDER);",
        "",
        "// Rule of thumb:",
        "// Comparable: when there's ONE natural order (dates, numbers, alphabetical)",
        "// Comparator: when you need MULTIPLE different orderings",
        "//             when you can't modify the class (third-party)",
      ]},
    ]
  }
);
