export const hibernateData = {
  id: "hibernate", icon: "🔄", title: "Hibernate & JPA", color: "#059669", accent: "#34d399",
  topics: [
    {
      title: "Hibernate Architecture & JPA Fundamentals", level: "Beginner",
      blocks: [
        {t:"text", v:"Hibernate is the most popular ORM (Object-Relational Mapping) framework for Java. JPA (Java Persistence API) is the standard specification, and Hibernate is the most widely used implementation. Together they let you work with database tables as Java objects — no SQL required for most operations."},
        {t:"heading", v:"ORM Concept — Why Hibernate?"},
        {t:"code", lang:"text", v:[
          "WITHOUT ORM (raw JDBC):",
          "  Connection conn = dataSource.getConnection();",
          "  PreparedStatement ps = conn.prepareStatement(",
          "      'INSERT INTO orders (customer_id, status, total) VALUES (?,?,?)');",
          "  ps.setLong(1, order.getCustomerId());",
          "  ps.setString(2, order.getStatus().name());",
          "  ps.setBigDecimal(3, order.getTotal());",
          "  ps.executeUpdate();",
          "  // Then get generated ID... handle exceptions... close resources...",
          "  // Multiply this by every table in your app: hundreds of lines",
          "",
          "WITH HIBERNATE/JPA:",
          "  entityManager.persist(order);  // That's it!",
          "  // Hibernate generates SQL, maps columns to fields, handles keys",
          "",
          "ORM does:",
          "  ✓ Maps Java classes to database tables",
          "  ✓ Maps Java fields to database columns",
          "  ✓ Generates CRUD SQL automatically",
          "  ✓ Manages database connections",
          "  ✓ Tracks which objects changed (dirty checking)",
          "  ✓ Caches data for performance",
          "  ✓ Handles relationships (OneToMany, ManyToOne)",
        ]},
        {t:"heading", v:"JPA Entity Mapping in Depth"},
        {t:"code", lang:"java", v:[
          "@Entity",
          "@Table(name = \"orders\",",
          "       schema = \"public\",",
          "       uniqueConstraints = @UniqueConstraint(columnNames = {\"reference_number\"}),",
          "       indexes = {",
          "           @Index(name = \"idx_customer\", columnList = \"customer_id\"),",
          "           @Index(name = \"idx_status_date\", columnList = \"status, created_at DESC\")",
          "       })",
          "@EntityListeners(AuditingEntityListener.class)",
          "public class Order {",
          "",
          "    // Primary key strategies:",
          "    @Id",
          "    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = \"order_seq\")",
          "    @SequenceGenerator(name=\"order_seq\", sequenceName=\"order_id_seq\",",
          "                       allocationSize=50) // Pre-allocate 50 IDs per batch",
          "    private Long id;",
          "",
          "    // Basic column mappings:",
          "    @Column(name = \"reference_number\", nullable = false, length = 20)",
          "    private String referenceNumber;",
          "",
          "    @Column(precision = 12, scale = 2)",
          "    private BigDecimal total;",
          "",
          "    // Enum stored as string (NEVER use ORDINAL):",
          "    @Enumerated(EnumType.STRING)",
          "    @Column(nullable = false, length = 20)",
          "    private OrderStatus status;",
          "",
          "    // Embedded value object:",
          "    @Embedded",
          "    private DeliveryAddress deliveryAddress;",
          "",
          "    // Audit fields:",
          "    @CreatedDate",
          "    @Column(updatable = false)",
          "    private Instant createdAt;",
          "",
          "    @LastModifiedDate",
          "    private Instant updatedAt;",
          "",
          "    @CreatedBy",
          "    @Column(updatable = false)",
          "    private String createdBy;",
          "",
          "    // Optimistic locking:",
          "    @Version",
          "    private Long version; // Hibernate auto-manages",
          "}",
          "",
          "@Embeddable",
          "public class DeliveryAddress {",
          "    private String street;",
          "    private String city;",
          "    private String state;",
          "    @Column(name = \"postal_code\") private String postalCode;",
          "    @Column(name = \"country_code\") private String countryCode;",
          "}",
        ]},
        {t:"heading", v:"Hibernate Session & EntityManager Lifecycle"},
        {t:"code", lang:"java", v:[
          "// Entity states in Hibernate:",
          "// TRANSIENT: new object, not associated with session, no DB row",
          "Order order = new Order(customerId, items);  // TRANSIENT",
          "",
          "// PERSISTENT: associated with session, changes auto-tracked (dirty checking)",
          "entityManager.persist(order);  // TRANSIENT → PERSISTENT",
          "// Now: INSERT SQL queued (may be delayed until flush)",
          "",
          "// Load = PERSISTENT immediately:",
          "Order loaded = entityManager.find(Order.class, 42L);  // PERSISTENT",
          "loaded.setStatus(OrderStatus.SHIPPED);",
          "// No update() call needed! Hibernate dirty-checks on flush",
          "",
          "// DETACHED: disconnected from session (after close/clear/evict)",
          "entityManager.detach(loaded);  // PERSISTENT → DETACHED",
          "// Changes no longer tracked",
          "",
          "// REMOVED: marked for deletion",
          "entityManager.remove(loaded);  // PERSISTENT → REMOVED",
          "// DELETE SQL queued",
          "",
          "// First-Level Cache (Session Cache):",
          "Order o1 = entityManager.find(Order.class, 42L);  // DB query",
          "Order o2 = entityManager.find(Order.class, 42L);  // CACHE HIT — no query!",
          "o1 == o2;  // true — same Java object!",
          "",
          "// Second-Level Cache (across sessions — optional, needs setup):",
          "@Entity @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)",
          "public class Product { ... }",
          "// Product loaded in any transaction hits L2 cache first",
        ]},
      ]
    },
    {
      title: "Hibernate Relationships & Fetch Strategies", level: "Intermediate",
      blocks: [
        {t:"text", v:"Relationships are the most complex and most bug-prone part of Hibernate. Getting fetch strategies wrong causes N+1 queries or OutOfMemoryErrors. This is one of the most important topics for any Java developer using databases."},
        {t:"heading", v:"All Relationship Types"},
        {t:"code", lang:"java", v:[
          "// @OneToMany — Customer has many Orders",
          "@Entity",
          "public class Customer {",
          "    @OneToMany(",
          "        mappedBy = \"customer\",       // 'customer' field on Order side",
          "        cascade = CascadeType.ALL,    // operations cascade to orders",
          "        orphanRemoval = true,          // delete order if removed from list",
          "        fetch = FetchType.LAZY         // ALWAYS lazy for collections",
          "    )",
          "    private List<Order> orders = new ArrayList<>();",
          "",
          "    // Helper methods (always add these for bidirectional):",
          "    public void addOrder(Order order) {",
          "        orders.add(order);",
          "        order.setCustomer(this);",
          "    }",
          "    public void removeOrder(Order order) {",
          "        orders.remove(order);",
          "        order.setCustomer(null);",
          "    }",
          "}",
          "",
          "// @ManyToOne — Order belongs to Customer",
          "@Entity",
          "public class Order {",
          "    @ManyToOne(fetch = FetchType.LAZY)  // ALWAYS lazy",
          "    @JoinColumn(name = \"customer_id\", nullable = false)",
          "    private Customer customer;",
          "}",
          "",
          "// @ManyToMany — Order has many Products, Product in many Orders",
          "@Entity",
          "public class Order {",
          "    @ManyToMany",
          "    @JoinTable(",
          "        name = \"order_products\",",
          "        joinColumns = @JoinColumn(name = \"order_id\"),",
          "        inverseJoinColumns = @JoinColumn(name = \"product_id\")",
          "    )",
          "    private Set<Product> products = new HashSet<>();",
          "    // Use Set not List for ManyToMany — avoids duplicate join results",
          "}",
          "",
          "// @OneToOne — Order has one Invoice",
          "@Entity",
          "public class Order {",
          "    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY,",
          "              optional = false)",
          "    @JoinColumn(name = \"invoice_id\", unique = true)",
          "    private Invoice invoice;",
          "}",
        ]},
        {t:"heading", v:"FetchType LAZY vs EAGER — Critical Understanding"},
        {t:"code", lang:"java", v:[
          "// EAGER: load related data immediately in same query",
          "// LAZY:  load related data only when accessed (proxy)",
          "",
          "// DEFAULT fetch types (remember these!):",
          "// @ManyToOne  → EAGER by default ← Change to LAZY always!",
          "// @OneToOne   → EAGER by default ← Change to LAZY always!",
          "// @OneToMany  → LAZY by default",
          "// @ManyToMany → LAZY by default",
          "",
          "// WHY always LAZY?",
          "// EAGER on @ManyToOne Customer in Order:",
          "// orderRepo.findAll()  →  SELECT * FROM orders",
          "//                     +   SELECT * FROM customers WHERE id=1  (N times!)",
          "// Loading 1000 orders = 1001 SQL queries",
          "",
          "// LAZY → load only when needed:",
          "@ManyToOne(fetch = FetchType.LAZY)  // Always override to LAZY",
          "private Customer customer;",
          "",
          "// When you DO need customer data, use JOIN FETCH:",
          "@Query(\"SELECT o FROM Order o JOIN FETCH o.customer WHERE o.id = :id\")",
          "Optional<Order> findByIdWithCustomer(@Param(\"id\") Long id);",
          "// Result: 1 SQL query with JOIN — efficient",
          "",
          "// LazyInitializationException — the most common Hibernate error:",
          "// Occurs when accessing lazy relation outside of transaction",
          "Order order = orderRepo.findById(42L).get(); // Transaction ends here",
          "order.getCustomer().getName(); // EXCEPTION! Session closed",
          "",
          "// Fix 1: Keep transaction open (@Transactional on service method)",
          "// Fix 2: Use JOIN FETCH",
          "// Fix 3: Initialize in query (JPQL fetch join)",
          "// Fix 4: DTO projection (best for read-only views)",
        ]},
        {t:"heading", v:"Cascade Types Explained"},
        {t:"code", lang:"java", v:[
          "// Cascade: propagate operations from parent to children",
          "",
          "// CascadeType.PERSIST — save parent also saves children",
          "Order order = new Order(customer);",
          "order.addItem(new OrderItem(product, 2));",
          "orderRepo.save(order);  // Also saves OrderItem automatically",
          "",
          "// CascadeType.MERGE — update parent also updates children",
          "",
          "// CascadeType.REMOVE — delete parent also deletes children",
          "orderRepo.delete(order);  // Also deletes all OrderItems",
          "",
          "// CascadeType.ALL = PERSIST + MERGE + REMOVE + REFRESH + DETACH",
          "// Safe for owned entities (Order owns OrderItems)",
          "// NEVER cascade to shared entities (Order shouldn't cascade to Product!)",
          "",
          "// orphanRemoval: delete child if removed from parent's collection",
          "@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)",
          "private List<OrderItem> items = new ArrayList<>();",
          "",
          "order.getItems().remove(item);  // Triggers DELETE for this item",
          "// Without orphanRemoval: item stays in DB but orphaned",
          "",
          "// RULE: CascadeType.ALL + orphanRemoval = true",
          "// for entities that are 'owned' by parent",
          "// (OrderItem owned by Order, Address owned by Customer)",
        ]},
      ]
    },
    {
      title: "Spring Batch — Bulk Data Processing", level: "Advanced",
      blocks: [
        {t:"text", v:"Spring Batch is the standard framework for batch processing in Java — processing large volumes of data in chunks. Use cases: nightly data migrations, monthly invoice generation, bulk imports/exports, ETL pipelines, payment reconciliation."},
        {t:"heading", v:"Spring Batch Architecture"},
        {t:"code", lang:"text", v:[
          "Job → one complete batch process",
          "  Step → one phase of the job (can have multiple steps)",
          "    ItemReader  → read data (DB, file, API)",
          "    ItemProcessor → transform/validate data",
          "    ItemWriter   → write results (DB, file, email)",
          "",
          "Chunk-Oriented Processing (the standard pattern):",
          "  1. Read N items one at a time",
          "  2. Accumulate into a chunk (e.g., chunk size = 100)",
          "  3. Process all items in the chunk",
          "  4. Write the entire chunk in one transaction",
          "  5. Repeat until all items processed",
          "",
          "Spring Batch tracks job state in its own DB tables:",
          "  BATCH_JOB_INSTANCE    — distinct job runs",
          "  BATCH_JOB_EXECUTION   — each execution attempt",
          "  BATCH_STEP_EXECUTION  — each step execution",
          "  On restart: resumes from last successful chunk!",
        ]},
        {t:"heading", v:"Complete Batch Job — Invoice Generation"},
        {t:"code", lang:"java", v:[
          "@Configuration",
          "@EnableBatchProcessing",
          "public class InvoiceGenerationJobConfig {",
          "",
          "    @Bean",
          "    public Job invoiceGenerationJob(JobRepository jobRepo, Step generateStep) {",
          "        return new JobBuilder(\"invoiceGenerationJob\", jobRepo)",
          "            .incrementer(new RunIdIncrementer())  // New run each time",
          "            .start(generateStep)",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    public Step generateInvoicesStep(JobRepository jobRepo,",
          "                                      PlatformTransactionManager txMgr) {",
          "        return new StepBuilder(\"generateInvoicesStep\", jobRepo)",
          "            .<Order, Invoice>chunk(100, txMgr)  // Process 100 at a time",
          "            .reader(completedOrdersReader())",
          "            .processor(invoiceProcessor())",
          "            .writer(invoiceWriter())",
          "            .faultTolerant()",
          "            .skipLimit(10)                      // Skip up to 10 bad records",
          "            .skip(DataIntegrityViolationException.class)",
          "            .retryLimit(3)                      // Retry transient errors",
          "            .retry(TransientDataAccessException.class)",
          "            .listener(new InvoiceStepListener())  // Log progress",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    @StepScope",
          "    public JpaPagingItemReader<Order> completedOrdersReader(",
          "            @Value(\"#{jobParameters['month']}\") String month) {",
          "        return new JpaPagingItemReaderBuilder<Order>()",
          "            .name(\"completedOrdersReader\")",
          "            .entityManagerFactory(emf)",
          "            .queryString(\"SELECT o FROM Order o WHERE o.status = 'COMPLETED'\" +",
          "                         \" AND FUNCTION('date_trunc','month',o.completedAt) =\" +",
          "                         \" FUNCTION('to_date',:month,'YYYY-MM')\")",
          "            .parameterValues(Map.of(\"month\", month))",
          "            .pageSize(100)",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    public ItemProcessor<Order, Invoice> invoiceProcessor() {",
          "        return order -> {",
          "            if (order.getTotal().compareTo(BigDecimal.ZERO) <= 0) {",
          "                return null;  // null = skip this item",
          "            }",
          "            return invoiceService.generateFor(order);",
          "        };",
          "    }",
          "",
          "    @Bean",
          "    public JpaItemWriter<Invoice> invoiceWriter() {",
          "        return new JpaItemWriterBuilder<Invoice>()",
          "            .entityManagerFactory(emf)",
          "            .build();",
          "        // Writes 100 invoices per DB transaction",
          "    }",
          "}",
          "",
          "// Launch job (from scheduler or REST endpoint):",
          "@Service",
          "public class BatchJobLauncher {",
          "    public void runMonthlyInvoices(String month) {",
          "        JobParameters params = new JobParametersBuilder()",
          "            .addString(\"month\", month)",
          "            .addLong(\"timestamp\", System.currentTimeMillis())",
          "            .toJobParameters();",
          "        jobLauncher.run(invoiceGenerationJob, params);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Parallel Processing & Partitioning"},
        {t:"code", lang:"java", v:[
          "// Process multiple customer segments in PARALLEL:",
          "@Bean",
          "public Step partitionedStep(JobRepository jobRepo) {",
          "    return new StepBuilder(\"partitionedStep\", jobRepo)",
          "        .partitioner(\"workerStep\", rangePartitioner())",
          "        .step(workerStep())                  // Each partition runs this step",
          "        .gridSize(8)                          // 8 parallel partitions",
          "        .taskExecutor(new SimpleAsyncTaskExecutor())",
          "        .build();",
          "}",
          "",
          "@Bean",
          "public Partitioner rangePartitioner() {",
          "    return gridSize -> {",
          "        Map<String, ExecutionContext> partitions = new HashMap<>();",
          "        long totalOrders = orderRepo.count();",
          "        long chunkSize   = totalOrders / gridSize;",
          "        for (int i = 0; i < gridSize; i++) {",
          "            ExecutionContext ctx = new ExecutionContext();",
          "            ctx.putLong(\"minId\", i * chunkSize);",
          "            ctx.putLong(\"maxId\", (i + 1) * chunkSize - 1);",
          "            partitions.put(\"partition\" + i, ctx);",
          "        }",
          "        return partitions;",
          "    };",
          "}",
          "// Result: 8 threads each process 1/8 of the data simultaneously",
          "// 10M records / 8 threads = 8x faster than sequential",
        ]},
      ]
    },
    {
      title: "Testing — JUnit5, Mockito & Spring Test", level: "Intermediate",
      blocks: [
        {t:"text", v:"Testing is not optional — it is what separates professional code from amateur code. A comprehensive test suite lets you refactor fearlessly, deploy confidently, and sleep at night. This covers the full testing pyramid for Spring Boot applications."},
        {t:"heading", v:"Testing Pyramid"},
        {t:"code", lang:"text", v:[
          "        ╔═══════════════╗",
          "        ║  E2E Tests    ║  Few, slow, test full system",
          "        ╠═══════════════╣  (Selenium, TestContainers full stack)",
          "        ║  Integration  ║  Some, test layers together",
          "        ║  Tests        ║  (@SpringBootTest, @DataJpaTest)",
          "        ╠═══════════════╣",
          "        ║  Unit Tests   ║  Many, fast, test one class",
          "        ║               ║  (JUnit5 + Mockito, no Spring context)",
          "        ╚═══════════════╝",
          "",
          "Rule of thumb: 70% unit, 20% integration, 10% E2E",
        ]},
        {t:"heading", v:"Unit Testing with JUnit5 & Mockito"},
        {t:"code", lang:"java", v:[
          "@ExtendWith(MockitoExtension.class)",
          "class OrderServiceTest {",
          "",
          "    @Mock private OrderRepository orderRepo;",
          "    @Mock private PaymentService   paymentService;",
          "    @Mock private EmailService     emailService;",
          "    @InjectMocks private OrderService orderService;",
          "",
          "    @Test",
          "    @DisplayName(\"Should create order and send confirmation when payment succeeds\")",
          "    void createOrder_whenPaymentSucceeds_shouldSaveOrderAndSendEmail() {",
          "        // ARRANGE (Given)",
          "        CreateOrderRequest req = new CreateOrderRequest(\"cust-1\",",
          "            List.of(new OrderItem(\"prod-1\", 2, BigDecimal.valueOf(99.99))));",
          "        Order savedOrder = new Order(1L, \"cust-1\", BigDecimal.valueOf(199.98));",
          "",
          "        when(orderRepo.save(any(Order.class))).thenReturn(savedOrder);",
          "        when(paymentService.charge(any())).thenReturn(PaymentResult.success(\"txn-1\"));",
          "",
          "        // ACT (When)",
          "        Order result = orderService.createOrder(req);",
          "",
          "        // ASSERT (Then)",
          "        assertThat(result.getId()).isEqualTo(1L);",
          "        assertThat(result.getTotal()).isEqualByComparingTo(\"199.98\");",
          "",
          "        verify(orderRepo, times(1)).save(any(Order.class));",
          "        verify(emailService, times(1)).sendOrderConfirmation(savedOrder);",
          "        verify(paymentService).charge(argThat(p ->",
          "            p.getAmount().compareTo(BigDecimal.valueOf(199.98)) == 0));",
          "    }",
          "",
          "    @Test",
          "    void createOrder_whenPaymentFails_shouldNotSaveOrder() {",
          "        when(paymentService.charge(any()))",
          "            .thenThrow(new PaymentFailedException(\"Card declined\"));",
          "",
          "        assertThatThrownBy(() -> orderService.createOrder(mockRequest()))",
          "            .isInstanceOf(PaymentFailedException.class)",
          "            .hasMessageContaining(\"Card declined\");",
          "",
          "        verify(orderRepo, never()).save(any());",
          "        verify(emailService, never()).sendOrderConfirmation(any());",
          "    }",
          "",
          "    @ParameterizedTest",
          "    @ValueSource(strings = { \"\", \"   \", \"invalid-email\" })",
          "    void createOrder_withInvalidCustomerId_shouldThrowValidationException(String id) {",
          "        assertThatThrownBy(() ->",
          "            orderService.createOrder(new CreateOrderRequest(id, List.of())))",
          "            .isInstanceOf(IllegalArgumentException.class);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Integration Testing with @SpringBootTest"},
        {t:"code", lang:"java", v:[
          "// Full Spring context — tests everything wired together",
          "@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)",
          "@AutoConfigureMockMvc",
          "@ActiveProfiles(\"test\")",
          "@Transactional  // Rollback after each test — keeps DB clean",
          "class OrderControllerIntegrationTest {",
          "",
          "    @Autowired private MockMvc mockMvc;",
          "    @Autowired private ObjectMapper objectMapper;",
          "    @Autowired private OrderRepository orderRepository;",
          "",
          "    @Test",
          "    void createOrder_withValidRequest_returns201WithOrderDetails() throws Exception {",
          "        CreateOrderRequest req = new CreateOrderRequest(",
          "            \"cust-123\",",
          "            List.of(new OrderItem(\"prod-1\", 2, BigDecimal.valueOf(50)))",
          "        );",
          "",
          "        mockMvc.perform(post(\"/api/v1/orders\")",
          "                .contentType(MediaType.APPLICATION_JSON)",
          "                .content(objectMapper.writeValueAsString(req))",
          "                .header(\"Authorization\", \"Bearer \" + getTestJwt()))",
          "            .andExpect(status().isCreated())",
          "            .andExpect(jsonPath(\"$.status\").value(\"PENDING\"))",
          "            .andExpect(jsonPath(\"$.total\").value(100.0))",
          "            .andExpect(jsonPath(\"$.customerId\").value(\"cust-123\"))",
          "            .andExpect(header().exists(\"Location\"));",
          "",
          "        assertThat(orderRepository.findAll()).hasSize(1);",
          "    }",
          "",
          "    @Test",
          "    void getOrder_withInvalidId_returns404() throws Exception {",
          "        mockMvc.perform(get(\"/api/v1/orders/99999\")",
          "                .header(\"Authorization\", \"Bearer \" + getTestJwt()))",
          "            .andExpect(status().isNotFound())",
          "            .andExpect(jsonPath(\"$.errorCode\").value(\"ORDER_NOT_FOUND\"));",
          "    }",
          "}",
          "",
          "// @DataJpaTest — test only JPA layer (faster)",
          "@DataJpaTest",
          "@AutoConfigureTestDatabase(replace = NONE)  // Use real DB",
          "class OrderRepositoryTest {",
          "    @Autowired private OrderRepository orderRepo;",
          "",
          "    @Test",
          "    void findByStatus_returnsPendingOrders() {",
          "        orderRepo.save(Order.pending(\"cust-1\"));",
          "        orderRepo.save(Order.pending(\"cust-2\"));",
          "        orderRepo.save(Order.shipped(\"cust-3\"));",
          "",
          "        List<Order> pending = orderRepo.findByStatus(OrderStatus.PENDING);",
          "        assertThat(pending).hasSize(2);",
          "    }",
          "}",
        ]},
      ]
    },
  ]
};
