export const reactData = {
  id: "react", icon: "⚛️", title: "React", color: "#38bdf8", accent: "#7dd3fc",
  topics: [
    {
      title: "React Fundamentals — JSX, Components & Props", level: "Beginner",
      blocks: [
        {t:"text", v:"React is a JavaScript library for building user interfaces. It lets you compose complex UIs from small, isolated pieces of code called 'components'. React only updates what needs to change — making it fast even for large apps."},
        {t:"heading", v:"Why React?"},
        {t:"code", lang:"text", v:[
          "Traditional DOM manipulation (jQuery era):",
          "  You tell the browser HOW to update the DOM step by step.",
          "  Hard to manage state, lots of bugs, spaghetti code.",
          "",
          "React approach (Declarative):",
          "  You describe WHAT the UI should look like for a given state.",
          "  React figures out HOW to update the DOM efficiently.",
          "  State changes → React re-renders only what changed.",
          "",
          "Virtual DOM:",
          "  React keeps a lightweight copy of the real DOM in memory.",
          "  On state change: computes diff between old and new virtual DOM.",
          "  Only applies the minimal real DOM changes (reconciliation).",
          "  Result: fast UI updates without touching the whole page.",
        ]},
        {t:"heading", v:"JSX — JavaScript + HTML"},
        {t:"text", v:"JSX lets you write HTML-like syntax inside JavaScript. It compiles to React.createElement() calls. Always return one root element — wrap siblings in a Fragment (<> </>) if needed."},
        {t:"code", lang:"jsx", v:[
          "// JSX compiles to:",
          "// React.createElement('div', { className: 'card' }, 'Hello')",
          "const element = <div className='card'>Hello</div>;",
          "",
          "// Rules:",
          "// 1. className instead of class (class is a JS reserved word)",
          "// 2. htmlFor instead of for (for is a JS reserved word)",
          "// 3. All tags must be closed: <img /> not <img>",
          "// 4. JavaScript expressions go in { }",
          "",
          "const name = 'Alice';",
          "const age  = 30;",
          "const el = (",
          "  <div>",
          "    <h1>Hello, {name}!</h1>",
          "    <p>Age: {age}</p>",
          "    <p>Adult: {age >= 18 ? 'Yes' : 'No'}</p>",
          "    {age > 18 && <span>Can vote</span>}",
          "  </div>",
          ");",
          "",
          "// Fragment: group elements without adding a div to the DOM",
          "const fragment = (",
          "  <>",
          "    <h1>Title</h1>",
          "    <p>Paragraph</p>",
          "  </>",
          ");",
        ]},
        {t:"heading", v:"Components — The Building Blocks"},
        {t:"code", lang:"jsx", v:[
          "// Functional Component (always use this — class components are legacy)",
          "function UserCard({ name, role, avatarUrl }) {",
          "  return (",
          "    <div className='user-card'>",
          "      <img src={avatarUrl} alt={name} />",
          "      <h2>{name}</h2>",
          "      <p>{role}</p>",
          "    </div>",
          "  );",
          "}",
          "",
          "// Props: data passed from parent to child (read-only!)",
          "// Parent passes props like HTML attributes:",
          "function App() {",
          "  return (",
          "    <div>",
          "      <UserCard",
          "        name='Alice'",
          "        role='Senior Engineer'",
          "        avatarUrl='https://example.com/alice.jpg'",
          "      />",
          "      <UserCard",
          "        name='Bob'",
          "        role='Product Manager'",
          "        avatarUrl='https://example.com/bob.jpg'",
          "      />",
          "    </div>",
          "  );",
          "}",
          "",
          "// Props with default values:",
          "function Button({ label, variant = 'primary', onClick, disabled = false }) {",
          "  return (",
          "    <button",
          "      className={`btn btn-${variant}`}",
          "      onClick={onClick}",
          "      disabled={disabled}",
          "    >",
          "      {label}",
          "    </button>",
          "  );",
          "}",
        ]},
        {t:"heading", v:"Rendering Lists"},
        {t:"code", lang:"jsx", v:[
          "const products = [",
          "  { id: 1, name: 'Laptop', price: 999 },",
          "  { id: 2, name: 'Phone',  price: 499 },",
          "  { id: 3, name: 'Tablet', price: 299 },",
          "];",
          "",
          "function ProductList() {",
          "  return (",
          "    <ul>",
          "      {products.map(product => (",
          "        // KEY is required! Helps React identify which items changed.",
          "        // Use stable unique IDs — NEVER use array index as key",
          "        // (index causes bugs when items are reordered/deleted)",
          "        <li key={product.id}>",
          "          {product.name} — ${product.price}",
          "        </li>",
          "      ))}",
          "    </ul>",
          "  );",
          "}",
          "",
          "// Conditional rendering:",
          "function OrderStatus({ status }) {",
          "  if (status === 'loading') return <Spinner />;",
          "  if (status === 'error')   return <ErrorMessage />;",
          "  return <OrderDetails />;",
          "}",
        ]},
      ]
    },
    {
      title: "useState & useEffect — Core Hooks", level: "Beginner",
      blocks: [
        {t:"text", v:"Hooks let functional components use state and lifecycle features. useState manages local component state. useEffect handles side effects — data fetching, subscriptions, DOM manipulation. These two hooks cover 80% of real-world React code."},
        {t:"heading", v:"useState — Local Component State"},
        {t:"code", lang:"jsx", v:[
          "import { useState } from 'react';",
          "",
          "function Counter() {",
          "  // useState returns: [currentValue, setterFunction]",
          "  // React re-renders component when state changes",
          "  const [count, setCount] = useState(0);  // 0 is the initial value",
          "",
          "  return (",
          "    <div>",
          "      <p>Count: {count}</p>",
          "      <button onClick={() => setCount(count + 1)}>+</button>",
          "      <button onClick={() => setCount(count - 1)}>-</button>",
          "      <button onClick={() => setCount(0)}>Reset</button>",
          "    </div>",
          "  );",
          "}",
          "",
          "// IMPORTANT: Never mutate state directly!",
          "// WRONG:",
          "// count = count + 1;       // React won't re-render",
          "// state.items.push(item);  // Won't trigger re-render",
          "",
          "// RIGHT: always use the setter",
          "setCount(count + 1);",
          "",
          "// For objects/arrays — create a new copy:",
          "const [user, setUser] = useState({ name: 'Alice', age: 30 });",
          "// WRONG: setUser(user.age = 31);",
          "// RIGHT: spread to create new object",
          "setUser(prev => ({ ...prev, age: 31 }));",
          "",
          "// Functional update (use when new state depends on old state):",
          "setCount(prev => prev + 1);  // Safer than setCount(count + 1)",
        ]},
        {t:"heading", v:"Managing Complex State"},
        {t:"code", lang:"jsx", v:[
          "function ShoppingCart() {",
          "  const [items, setItems] = useState([]);",
          "  const [discount, setDiscount] = useState(0);",
          "",
          "  const addItem = (product) => {",
          "    setItems(prev => {",
          "      const existing = prev.find(i => i.id === product.id);",
          "      if (existing) {",
          "        // Update quantity — create NEW array with updated item",
          "        return prev.map(i =>",
          "          i.id === product.id ? { ...i, qty: i.qty + 1 } : i",
          "        );",
          "      }",
          "      return [...prev, { ...product, qty: 1 }];  // Add new item",
          "    });",
          "  };",
          "",
          "  const removeItem = (productId) => {",
          "    setItems(prev => prev.filter(i => i.id !== productId));",
          "  };",
          "",
          "  const total = items.reduce((sum, i) => sum + i.price * i.qty, 0);",
          "  const discounted = total * (1 - discount / 100);",
          "",
          "  return ( /* render cart UI */ );",
          "}",
        ]},
        {t:"heading", v:"useEffect — Side Effects & Lifecycle"},
        {t:"code", lang:"jsx", v:[
          "import { useState, useEffect } from 'react';",
          "",
          "function UserProfile({ userId }) {",
          "  const [user, setUser]       = useState(null);",
          "  const [loading, setLoading] = useState(true);",
          "  const [error, setError]     = useState(null);",
          "",
          "  // useEffect(fn, [dependencies])",
          "  // Runs fn AFTER every render where deps changed",
          "  useEffect(() => {",
          "    let cancelled = false;  // Prevent state update on unmounted component",
          "",
          "    const fetchUser = async () => {",
          "      try {",
          "        setLoading(true);",
          "        const res = await fetch(`/api/users/${userId}`);",
          "        if (!res.ok) throw new Error('User not found');",
          "        const data = await res.json();",
          "        if (!cancelled) setUser(data);",
          "      } catch (e) {",
          "        if (!cancelled) setError(e.message);",
          "      } finally {",
          "        if (!cancelled) setLoading(false);",
          "      }",
          "    };",
          "",
          "    fetchUser();",
          "",
          "    // Cleanup: runs when component unmounts OR before next effect runs",
          "    return () => { cancelled = true; };",
          "",
          "  }, [userId]); // Re-run when userId changes",
          "",
          "  if (loading) return <Spinner />;",
          "  if (error)   return <p>Error: {error}</p>;",
          "  if (!user)   return null;",
          "  return <div>{user.name}</div>;",
          "}",
          "",
          "// Dependency array rules:",
          "// useEffect(fn)        // Runs after EVERY render (usually wrong)",
          "// useEffect(fn, [])    // Runs ONCE after first render (componentDidMount)",
          "// useEffect(fn, [id])  // Runs when 'id' changes",
        ]},
      ]
    },
    {
      title: "Advanced Hooks — useContext, useReducer, useMemo", level: "Intermediate",
      blocks: [
        {t:"text", v:"Beyond useState and useEffect, React's advanced hooks solve real architectural problems: sharing data deeply without prop drilling, managing complex state machines, and optimising expensive computations."},
        {t:"heading", v:"useContext — Global State Without Prop Drilling"},
        {t:"text", v:"Prop drilling means passing props through many layers of components that don't need them, just to get data to a deeply nested child. Context solves this by letting you broadcast data to any descendant."},
        {t:"code", lang:"jsx", v:[
          "import { createContext, useContext, useState } from 'react';",
          "",
          "// 1. Create the context",
          "const AuthContext = createContext(null);",
          "",
          "// 2. Create a Provider component",
          "export function AuthProvider({ children }) {",
          "  const [user, setUser] = useState(null);",
          "",
          "  const login = async (email, password) => {",
          "    const userData = await authService.login(email, password);",
          "    setUser(userData);",
          "  };",
          "",
          "  const logout = () => setUser(null);",
          "",
          "  return (",
          "    <AuthContext.Provider value={{ user, login, logout }}>",
          "      {children}",
          "    </AuthContext.Provider>",
          "  );",
          "}",
          "",
          "// 3. Custom hook for clean usage",
          "export function useAuth() {",
          "  const ctx = useContext(AuthContext);",
          "  if (!ctx) throw new Error('useAuth must be inside AuthProvider');",
          "  return ctx;",
          "}",
          "",
          "// 4. Use anywhere in the tree without prop drilling:",
          "function Navbar() {",
          "  const { user, logout } = useAuth();",
          "  return (",
          "    <nav>",
          "      {user ? (",
          "        <><span>Hello, {user.name}</span><button onClick={logout}>Logout</button></>",
          "      ) : (",
          "        <a href='/login'>Login</a>",
          "      )}",
          "    </nav>",
          "  );",
          "}",
        ]},
        {t:"heading", v:"useReducer — Complex State Machines"},
        {t:"code", lang:"jsx", v:[
          "import { useReducer } from 'react';",
          "",
          "// Define actions as constants:",
          "const ACTIONS = {",
          "  FETCH_START:   'FETCH_START',",
          "  FETCH_SUCCESS: 'FETCH_SUCCESS',",
          "  FETCH_ERROR:   'FETCH_ERROR',",
          "  RESET:         'RESET',",
          "};",
          "",
          "// Reducer: pure function (state, action) => newState",
          "function orderReducer(state, action) {",
          "  switch (action.type) {",
          "    case ACTIONS.FETCH_START:",
          "      return { ...state, loading: true, error: null };",
          "    case ACTIONS.FETCH_SUCCESS:",
          "      return { loading: false, error: null, orders: action.payload };",
          "    case ACTIONS.FETCH_ERROR:",
          "      return { ...state, loading: false, error: action.payload };",
          "    case ACTIONS.RESET:",
          "      return initialState;",
          "    default:",
          "      return state;",
          "  }",
          "}",
          "",
          "const initialState = { orders: [], loading: false, error: null };",
          "",
          "function OrderDashboard() {",
          "  const [state, dispatch] = useReducer(orderReducer, initialState);",
          "",
          "  const fetchOrders = async () => {",
          "    dispatch({ type: ACTIONS.FETCH_START });",
          "    try {",
          "      const orders = await orderService.getAll();",
          "      dispatch({ type: ACTIONS.FETCH_SUCCESS, payload: orders });",
          "    } catch (e) {",
          "      dispatch({ type: ACTIONS.FETCH_ERROR, payload: e.message });",
          "    }",
          "  };",
          "",
          "  // state.loading, state.orders, state.error",
          "}",
          "// useReducer shines when: multiple related state values,",
          "// next state depends on previous, state transitions are complex.",
        ]},
        {t:"heading", v:"useMemo & useCallback — Performance Optimisation"},
        {t:"code", lang:"jsx", v:[
          "import { useMemo, useCallback, useState } from 'react';",
          "",
          "function OrderAnalytics({ orders }) {",
          "  const [filter, setFilter] = useState('ALL');",
          "",
          "  // useMemo: memoize expensive computation",
          "  // Only re-computes when orders or filter changes",
          "  const filteredOrders = useMemo(() => {",
          "    console.log('Computing filtered orders...');  // Should not run on every render",
          "    return orders",
          "      .filter(o => filter === 'ALL' || o.status === filter)",
          "      .sort((a, b) => new Date(b.date) - new Date(a.date));",
          "  }, [orders, filter]);",
          "",
          "  const totalRevenue = useMemo(() => {",
          "    return filteredOrders.reduce((sum, o) => sum + o.total, 0);",
          "  }, [filteredOrders]);",
          "",
          "  // useCallback: memoize a function reference",
          "  // Without this, child components re-render every time parent renders",
          "  const handleDelete = useCallback((orderId) => {",
          "    orderService.delete(orderId);",
          "  }, []); // Empty deps = function never changes",
          "",
          "  return (",
          "    <div>",
          "      <p>Total: ${totalRevenue}</p>",
          "      <OrderList orders={filteredOrders} onDelete={handleDelete} />",
          "    </div>",
          "  );",
          "}",
          "",
          "// RULE: Don't over-optimise!",
          "// Only use useMemo/useCallback when:",
          "// 1. Computation is genuinely expensive (>1ms)",
          "// 2. Passing stable function refs to optimised child components",
        ]},
      ]
    },
    {
      title: "State Management — Redux Toolkit & React Query", level: "Intermediate",
      blocks: [
        {t:"text", v:"For large applications, component state isn't enough. Redux Toolkit manages global client state (auth, UI preferences). React Query manages server state (data from APIs) with automatic caching, refetching, and synchronisation."},
        {t:"heading", v:"Redux Toolkit — Global Client State"},
        {t:"code", lang:"jsx", v:[
          "// store/authSlice.js",
          "import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';",
          "",
          "// createAsyncThunk: handles the loading/success/error lifecycle automatically",
          "export const loginUser = createAsyncThunk(",
          "  'auth/login',",
          "  async ({ email, password }, { rejectWithValue }) => {",
          "    try {",
          "      const response = await authAPI.login(email, password);",
          "      localStorage.setItem('token', response.token);",
          "      return response.user;",
          "    } catch (error) {",
          "      return rejectWithValue(error.response.data.message);",
          "    }",
          "  }",
          ");",
          "",
          "const authSlice = createSlice({",
          "  name: 'auth',",
          "  initialState: { user: null, loading: false, error: null },",
          "  reducers: {",
          "    logout: (state) => {",
          "      state.user = null;",
          "      localStorage.removeItem('token');",
          "    },",
          "  },",
          "  extraReducers: (builder) => {",
          "    builder",
          "      .addCase(loginUser.pending,   (state) => { state.loading = true; state.error = null; })",
          "      .addCase(loginUser.fulfilled, (state, action) => {",
          "        state.loading = false;",
          "        state.user    = action.payload;",
          "      })",
          "      .addCase(loginUser.rejected,  (state, action) => {",
          "        state.loading = false;",
          "        state.error   = action.payload;",
          "      });",
          "  },",
          "});",
          "",
          "export const { logout } = authSlice.actions;",
          "export default authSlice.reducer;",
        ]},
        {t:"heading", v:"React Query — Server State Management"},
        {t:"text", v:"React Query treats server data differently from UI state. It caches responses, automatically refetches stale data, and handles loading/error states — eliminating 90% of data-fetching boilerplate."},
        {t:"code", lang:"jsx", v:[
          "import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';",
          "",
          "// Fetch orders — with caching, background refetch, loading/error states",
          "function OrderList() {",
          "  const { data: orders, isLoading, error, refetch } = useQuery({",
          "    queryKey: ['orders'],          // Cache key — unique identifier",
          "    queryFn: () => orderAPI.getAll(),",
          "    staleTime: 5 * 60 * 1000,     // Consider data fresh for 5 minutes",
          "    retry: 2,                      // Retry failed requests twice",
          "    refetchOnWindowFocus: true,    // Refetch when user tabs back",
          "  });",
          "",
          "  if (isLoading) return <Spinner />;",
          "  if (error)     return <p>Error: {error.message}</p>;",
          "",
          "  return <ul>{orders.map(o => <OrderItem key={o.id} order={o} />)}</ul>;",
          "}",
          "",
          "// Create order — with optimistic updates",
          "function CreateOrderForm() {",
          "  const queryClient = useQueryClient();",
          "",
          "  const mutation = useMutation({",
          "    mutationFn: (newOrder) => orderAPI.create(newOrder),",
          "    onSuccess: () => {",
          "      // Invalidate cache: next render will refetch fresh data",
          "      queryClient.invalidateQueries({ queryKey: ['orders'] });",
          "    },",
          "    onError: (error) => {",
          "      toast.error('Failed to create order: ' + error.message);",
          "    },",
          "  });",
          "",
          "  const handleSubmit = (formData) => {",
          "    mutation.mutate(formData);",
          "  };",
          "",
          "  return (",
          "    <form onSubmit={handleSubmit}>",
          "      {/* form fields */}",
          "      <button disabled={mutation.isPending}>",
          "        {mutation.isPending ? 'Creating...' : 'Create Order'}",
          "      </button>",
          "    </form>",
          "  );",
          "}",
        ]},
      ]
    },
    {
      title: "React Router & Code Splitting", level: "Intermediate",
      blocks: [
        {t:"text", v:"React Router v6 enables client-side navigation — switching pages without full page reloads. Code splitting lazily loads route components only when needed, reducing your initial bundle size dramatically."},
        {t:"heading", v:"React Router v6 Setup"},
        {t:"code", lang:"jsx", v:[
          "import { BrowserRouter, Routes, Route, Navigate,",
          "         useParams, useNavigate, Link, NavLink } from 'react-router-dom';",
          "",
          "// Lazy loading: component only downloaded when route is visited",
          "const Dashboard  = lazy(() => import('./pages/Dashboard'));",
          "const Orders     = lazy(() => import('./pages/Orders'));",
          "const OrderDetail = lazy(() => import('./pages/OrderDetail'));",
          "const Profile    = lazy(() => import('./pages/Profile'));",
          "",
          "function App() {",
          "  return (",
          "    <BrowserRouter>",
          "      <Suspense fallback={<PageSpinner />}>",
          "        <Routes>",
          "          <Route path='/' element={<Navigate to='/dashboard' replace />} />",
          "          <Route path='/login' element={<LoginPage />} />",
          "",
          "          {/* Protected routes: redirect to login if not authenticated */}",
          "          <Route element={<ProtectedLayout />}>",
          "            <Route path='/dashboard'      element={<Dashboard />} />",
          "            <Route path='/orders'         element={<Orders />} />",
          "            <Route path='/orders/:id'     element={<OrderDetail />} />",
          "            <Route path='/profile'        element={<Profile />} />",
          "          </Route>",
          "",
          "          <Route path='*' element={<NotFoundPage />} />",
          "        </Routes>",
          "      </Suspense>",
          "    </BrowserRouter>",
          "  );",
          "}",
          "",
          "// ProtectedLayout: wraps routes that require authentication",
          "function ProtectedLayout() {",
          "  const { user } = useAuth();",
          "  return user ? <Outlet /> : <Navigate to='/login' replace />;",
          "}",
        ]},
        {t:"heading", v:"Navigation & Route Params"},
        {t:"code", lang:"jsx", v:[
          "// Reading URL params: /orders/:id",
          "function OrderDetail() {",
          "  const { id } = useParams();  // { id: '42' }",
          "  const { data: order } = useQuery({",
          "    queryKey: ['orders', id],",
          "    queryFn: () => orderAPI.getById(id),",
          "  });",
          "  return <div>{order?.status}</div>;",
          "}",
          "",
          "// Programmatic navigation:",
          "function CreateOrder() {",
          "  const navigate = useNavigate();",
          "  const mutation = useMutation({",
          "    mutationFn: orderAPI.create,",
          "    onSuccess: (newOrder) => {",
          "      navigate(`/orders/${newOrder.id}`, { replace: true });",
          "    },",
          "  });",
          "}",
          "",
          "// NavLink: automatically adds 'active' class when route matches",
          "function Sidebar() {",
          "  return (",
          "    <nav>",
          "      <NavLink to='/dashboard'",
          "        className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}",
          "      >Dashboard</NavLink>",
          "      <NavLink to='/orders'",
          "        className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}",
          "      >Orders</NavLink>",
          "    </nav>",
          "  );",
          "}",
        ]},
      ]
    },
    {
      title: "React Performance & Production Patterns", level: "Advanced",
      blocks: [
        {t:"text", v:"Production React apps need careful performance tuning. Unnecessary re-renders are the #1 performance problem. Here are the patterns that senior React engineers use daily."},
        {t:"heading", v:"React.memo — Prevent Unnecessary Re-renders"},
        {t:"code", lang:"jsx", v:[
          "// Without memo: re-renders every time parent renders,",
          "// even if props haven't changed",
          "function OrderRow({ order, onDelete }) {",
          "  console.log('Rendering OrderRow:', order.id);",
          "  return (",
          "    <tr>",
          "      <td>{order.id}</td>",
          "      <td>{order.status}</td>",
          "      <td><button onClick={() => onDelete(order.id)}>Delete</button></td>",
          "    </tr>",
          "  );",
          "}",
          "",
          "// With memo: only re-renders when props actually change",
          "const OrderRow = memo(function OrderRow({ order, onDelete }) {",
          "  console.log('Rendering OrderRow:', order.id);",
          "  return (",
          "    <tr>",
          "      <td>{order.id}</td>",
          "      <td>{order.status}</td>",
          "      <td><button onClick={() => onDelete(order.id)}>Delete</button></td>",
          "    </tr>",
          "  );",
          "});",
          "",
          "// CRITICAL: memo only works if onDelete reference is stable!",
          "// Parent must use useCallback for the handler:",
          "const handleDelete = useCallback((id) => {",
          "  deleteOrder(id);",
          "}, []);  // Stable reference = memo works",
        ]},
        {t:"heading", v:"Custom Hooks — Reusable Logic"},
        {t:"code", lang:"jsx", v:[
          "// Extract repeated logic into custom hooks",
          "",
          "// useFetch: reusable data fetching with loading/error",
          "function useFetch(url) {",
          "  const [data, setData]       = useState(null);",
          "  const [loading, setLoading] = useState(true);",
          "  const [error, setError]     = useState(null);",
          "",
          "  useEffect(() => {",
          "    let cancelled = false;",
          "    setLoading(true);",
          "    fetch(url)",
          "      .then(r => r.json())",
          "      .then(d => { if (!cancelled) { setData(d); setLoading(false); } })",
          "      .catch(e => { if (!cancelled) { setError(e); setLoading(false); } });",
          "    return () => { cancelled = true; };",
          "  }, [url]);",
          "",
          "  return { data, loading, error };",
          "}",
          "",
          "// useDebounce: delay search input to reduce API calls",
          "function useDebounce(value, delay = 500) {",
          "  const [debounced, setDebounced] = useState(value);",
          "  useEffect(() => {",
          "    const timer = setTimeout(() => setDebounced(value), delay);",
          "    return () => clearTimeout(timer);",
          "  }, [value, delay]);",
          "  return debounced;",
          "}",
          "",
          "// useLocalStorage: persist state in localStorage",
          "function useLocalStorage(key, initialValue) {",
          "  const [value, setValue] = useState(() => {",
          "    try {",
          "      const item = localStorage.getItem(key);",
          "      return item ? JSON.parse(item) : initialValue;",
          "    } catch { return initialValue; }",
          "  });",
          "",
          "  const setStoredValue = (newValue) => {",
          "    setValue(newValue);",
          "    localStorage.setItem(key, JSON.stringify(newValue));",
          "  };",
          "",
          "  return [value, setStoredValue];",
          "}",
          "",
          "// Usage:",
          "const { data: orders } = useFetch('/api/orders');",
          "const debouncedSearch  = useDebounce(searchQuery, 300);",
          "const [theme, setTheme] = useLocalStorage('theme', 'dark');",
        ]},
        {t:"heading", v:"Error Boundaries — Catch Runtime Errors"},
        {t:"code", lang:"jsx", v:[
          "// Error boundaries must be class components (no hook equivalent yet)",
          "class ErrorBoundary extends React.Component {",
          "  state = { hasError: false, error: null };",
          "",
          "  static getDerivedStateFromError(error) {",
          "    return { hasError: true, error };",
          "  }",
          "",
          "  componentDidCatch(error, info) {",
          "    // Log to monitoring service:",
          "    errorTrackingService.log(error, info.componentStack);",
          "  }",
          "",
          "  render() {",
          "    if (this.state.hasError) {",
          "      return (",
          "        <div className='error-fallback'>",
          "          <h2>Something went wrong</h2>",
          "          <button onClick={() => this.setState({ hasError: false })}>",
          "            Try Again",
          "          </button>",
          "        </div>",
          "      );",
          "    }",
          "    return this.props.children;",
          "  }",
          "}",
          "",
          "// Wrap sections of your app:",
          "function App() {",
          "  return (",
          "    <ErrorBoundary>",
          "      <Dashboard />",
          "    </ErrorBoundary>",
          "  );",
          "}",
        ]},
      ]
    },
  ]
};
