export const databaseData = {
  id: "database", icon: "🗄️", title: "Databases", color: "#0ea5e9", accent: "#38bdf8",
  topics: [
    {
      title: "SQL Fundamentals — From Zero to Confident", level: "Beginner",
      blocks: [
        {t:"text", v:"A database stores your application's data persistently. Without a database, all data disappears when your app restarts. SQL (Structured Query Language) is the language used to create, read, update, and delete data in relational databases like PostgreSQL, MySQL, and Oracle."},
        {t:"heading", v:"What is a Relational Database?"},
        {t:"code", lang:"text", v:[
          "A relational database stores data in TABLES (like spreadsheets).",
          "Tables have ROWS (records) and COLUMNS (fields).",
          "Tables are RELATED to each other via keys.",
          "",
          "Example: E-commerce database",
          "",
          "customers table:          orders table:",
          "┌────┬───────┬──────────┐  ┌────┬─────────────┬────────┐",
          "│ id │ name  │ email    │  │ id │ customer_id │ total  │",
          "├────┼───────┼──────────┤  ├────┼─────────────┼────────┤",
          "│  1 │ Alice │ a@x.com  │  │  1 │           1 │ 299.99 │",
          "│  2 │ Bob   │ b@x.com  │  │  2 │           1 │  49.50 │",
          "│  3 │ Carol │ c@x.com  │  │  3 │           2 │ 199.00 │",
          "└────┴───────┴──────────┘  └────┴─────────────┴────────┘",
          "",
          "customer_id in orders is a FOREIGN KEY pointing to customers.id",
          "This is the 'relation' in relational database.",
        ]},
        {t:"heading", v:"Core SQL Commands — CRUD"},
        {t:"code", lang:"sql", v:[
          "-- CREATE TABLE",
          "CREATE TABLE customers (",
          "    id         SERIAL PRIMARY KEY,      -- Auto-increment ID",
          "    name       VARCHAR(100) NOT NULL,   -- Required text field",
          "    email      VARCHAR(255) UNIQUE NOT NULL, -- Must be unique",
          "    phone      VARCHAR(20),             -- Optional",
          "    created_at TIMESTAMPTZ DEFAULT NOW() -- Auto timestamp",
          ");",
          "",
          "-- INSERT (Create)",
          "INSERT INTO customers (name, email, phone)",
          "VALUES ('Alice Smith', 'alice@example.com', '+91-9876543210');",
          "",
          "-- SELECT (Read)",
          "SELECT * FROM customers;                          -- All rows, all columns",
          "SELECT name, email FROM customers;               -- Specific columns",
          "SELECT * FROM customers WHERE id = 1;            -- Filter by condition",
          "SELECT * FROM customers WHERE name LIKE 'A%';    -- Names starting with A",
          "SELECT * FROM customers ORDER BY name ASC;       -- Sort alphabetically",
          "SELECT * FROM customers LIMIT 10 OFFSET 20;      -- Pagination: page 3",
          "",
          "-- UPDATE",
          "UPDATE customers",
          "SET email = 'alice.new@example.com', phone = '+91-9999999999'",
          "WHERE id = 1;",
          "-- ALWAYS use WHERE on UPDATE or you update every row!",
          "",
          "-- DELETE",
          "DELETE FROM customers WHERE id = 1;",
          "-- ALWAYS use WHERE on DELETE or you delete everything!",
        ]},
        {t:"heading", v:"JOINs — Combining Tables"},
        {t:"code", lang:"sql", v:[
          "-- INNER JOIN: Only rows that match in BOTH tables",
          "SELECT c.name, o.id as order_id, o.total",
          "FROM customers c",
          "INNER JOIN orders o ON c.id = o.customer_id;",
          "-- Result: Only customers who HAVE orders",
          "",
          "-- LEFT JOIN: All rows from left table, matched rows from right",
          "SELECT c.name, COUNT(o.id) as order_count",
          "FROM customers c",
          "LEFT JOIN orders o ON c.id = o.customer_id",
          "GROUP BY c.id, c.name;",
          "-- Result: ALL customers, including those with 0 orders",
          "",
          "-- Practical example: Get order details with customer and product info",
          "SELECT",
          "    c.name   AS customer_name,",
          "    o.id     AS order_id,",
          "    o.total,",
          "    o.status,",
          "    o.created_at",
          "FROM orders o",
          "INNER JOIN customers c ON o.customer_id = c.id",
          "WHERE o.status = 'PENDING'",
          "ORDER BY o.created_at DESC",
          "LIMIT 50;",
        ]},
        {t:"heading", v:"Aggregations & Grouping"},
        {t:"code", lang:"sql", v:[
          "-- Count, Sum, Average, Min, Max",
          "SELECT",
          "    COUNT(*)              AS total_orders,",
          "    SUM(total)            AS revenue,",
          "    AVG(total)            AS avg_order_value,",
          "    MIN(total)            AS smallest_order,",
          "    MAX(total)            AS largest_order",
          "FROM orders",
          "WHERE status = 'COMPLETED';",
          "",
          "-- GROUP BY: aggregate per group",
          "SELECT",
          "    status,",
          "    COUNT(*)    AS count,",
          "    SUM(total)  AS total_revenue",
          "FROM orders",
          "GROUP BY status",
          "ORDER BY total_revenue DESC;",
          "",
          "-- HAVING: filter on aggregated results (WHERE is for rows, HAVING is for groups)",
          "SELECT",
          "    customer_id,",
          "    COUNT(*)   AS order_count,",
          "    SUM(total) AS lifetime_value",
          "FROM orders",
          "GROUP BY customer_id",
          "HAVING SUM(total) > 1000  -- Only customers who spent > 1000",
          "ORDER BY lifetime_value DESC;",
        ]},
        {t:"note", v:"Production rule: Always have a WHERE clause on UPDATE and DELETE statements. A missing WHERE is one of the most common and costly database mistakes — it updates or deletes every single row in the table."},
      ]
    },
    {
      title: "PostgreSQL Deep Dive — Production Database", level: "Intermediate",
      blocks: [
        {t:"text", v:"PostgreSQL is the most powerful open-source relational database and the preferred choice for most production Java applications. It supports advanced data types, JSON, full-text search, window functions, and much more."},
        {t:"heading", v:"Advanced Data Types"},
        {t:"code", lang:"sql", v:[
          "-- PostgreSQL supports many data types beyond basic SQL:",
          "",
          "CREATE TABLE products (",
          "    id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,  -- UUID instead of int",
          "    name        VARCHAR(200) NOT NULL,",
          "    price       NUMERIC(10, 2) NOT NULL,  -- Exact decimal for money",
          "    tags        TEXT[],                    -- Array of strings",
          "    metadata    JSONB,                     -- JSON with indexing support",
          "    status      product_status NOT NULL,   -- Custom enum type",
          "    location    POINT,                     -- Geographic point",
          "    search_vec  TSVECTOR,                  -- Full-text search vector",
          "    created_at  TIMESTAMPTZ DEFAULT NOW()",
          ");",
          "",
          "-- Create custom enum type:",
          "CREATE TYPE product_status AS ENUM ('DRAFT', 'ACTIVE', 'DISCONTINUED');",
          "",
          "-- Working with arrays:",
          "INSERT INTO products (name, price, tags)",
          "VALUES ('Laptop', 999.99, ARRAY['electronics', 'computers', 'portable']);",
          "",
          "SELECT * FROM products WHERE 'electronics' = ANY(tags);",
          "SELECT * FROM products WHERE tags @> ARRAY['electronics'];  -- Contains",
          "",
          "-- Working with JSONB:",
          "INSERT INTO products (name, price, metadata)",
          "VALUES ('Phone', 499.99, '{\"brand\": \"Samsung\", \"ram\": 8, \"colors\": [\"black\", \"white\"]}');",
          "",
          "SELECT metadata->>'brand' FROM products;           -- Extract text",
          "SELECT metadata->'ram'    FROM products;           -- Extract JSON",
          "SELECT * FROM products WHERE metadata->>'brand' = 'Samsung';",
          "SELECT * FROM products WHERE (metadata->>'ram')::int > 6;",
        ]},
        {t:"heading", v:"Window Functions — Analytics Power"},
        {t:"text", v:"Window functions perform calculations across related rows without collapsing them into groups. They're essential for rankings, running totals, and time-series analysis."},
        {t:"code", lang:"sql", v:[
          "-- ROW_NUMBER: rank orders per customer by date",
          "SELECT",
          "    customer_id,",
          "    id AS order_id,",
          "    total,",
          "    created_at,",
          "    ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC)",
          "        AS order_rank",
          "FROM orders;",
          "-- order_rank=1 means the most recent order for that customer",
          "",
          "-- Get each customer's most recent order:",
          "SELECT * FROM (",
          "    SELECT *,",
          "        ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY created_at DESC) AS rn",
          "    FROM orders",
          ") sub WHERE rn = 1;",
          "",
          "-- Running total (cumulative sum):",
          "SELECT",
          "    date_trunc('day', created_at) AS day,",
          "    SUM(total)                    AS daily_revenue,",
          "    SUM(SUM(total)) OVER (ORDER BY date_trunc('day', created_at))",
          "        AS running_total",
          "FROM orders",
          "WHERE status = 'COMPLETED'",
          "GROUP BY 1",
          "ORDER BY 1;",
          "",
          "-- LAG/LEAD: compare with previous/next row",
          "SELECT",
          "    date_trunc('month', created_at) AS month,",
          "    SUM(total) AS revenue,",
          "    LAG(SUM(total)) OVER (ORDER BY date_trunc('month', created_at))",
          "        AS prev_month_revenue,",
          "    SUM(total) - LAG(SUM(total)) OVER (ORDER BY date_trunc('month', created_at))",
          "        AS growth",
          "FROM orders GROUP BY 1 ORDER BY 1;",
        ]},
        {t:"heading", v:"Full-Text Search"},
        {t:"code", lang:"sql", v:[
          "-- Add full-text search to products table:",
          "ALTER TABLE products ADD COLUMN search_vec TSVECTOR",
          "    GENERATED ALWAYS AS (",
          "        to_tsvector('english', coalesce(name,'') || ' ' ||",
          "                              coalesce(description,''))",
          "    ) STORED;",
          "",
          "-- Create GIN index for fast full-text search:",
          "CREATE INDEX idx_products_search ON products USING GIN(search_vec);",
          "",
          "-- Search query:",
          "SELECT name, price,",
          "    ts_rank(search_vec, query) AS rank",
          "FROM products,",
          "    plainto_tsquery('english', 'gaming laptop') AS query",
          "WHERE search_vec @@ query",
          "ORDER BY rank DESC",
          "LIMIT 20;",
          "-- Full-text search understands stemming:",
          "-- 'running' matches 'run', 'runner', 'runs'",
          "-- Much smarter than LIKE '%running%'",
        ]},
        {t:"heading", v:"Performance Tuning with EXPLAIN"},
        {t:"code", lang:"sql", v:[
          "-- EXPLAIN shows how PostgreSQL executes a query",
          "-- EXPLAIN ANALYZE actually runs it and shows real times",
          "EXPLAIN ANALYZE",
          "SELECT * FROM orders WHERE customer_id = 12345 AND status = 'PENDING';",
          "",
          "-- Output to look for:",
          "-- Seq Scan = full table scan (BAD for large tables)",
          "-- Index Scan = using an index (GOOD)",
          "-- Hash Join, Merge Join = join strategies",
          "-- Rows = estimated vs actual row count",
          "-- Execution Time = actual time",
          "",
          "-- If you see Seq Scan on a large table: ADD AN INDEX!",
          "CREATE INDEX idx_orders_customer_status ON orders(customer_id, status);",
          "",
          "-- Now re-run EXPLAIN ANALYZE — should show Index Scan",
          "",
          "-- Partial index: index only rows meeting a condition (smaller, faster)",
          "CREATE INDEX idx_orders_pending",
          "    ON orders(customer_id, created_at)",
          "    WHERE status = 'PENDING';  -- Only index pending orders",
          "",
          "-- Covering index: include extra columns to avoid table lookup",
          "CREATE INDEX idx_orders_covering",
          "    ON orders(customer_id)",
          "    INCLUDE (status, total, created_at);",
        ]},
      ]
    },
    {
      title: "Database Design & Normalization", level: "Intermediate",
      blocks: [
        {t:"text", v:"Good database design prevents data anomalies (duplicate data that gets out of sync), makes queries efficient, and keeps your schema maintainable as requirements change. Normalization is the process of organizing data to reduce redundancy."},
        {t:"heading", v:"Primary Keys, Foreign Keys & Constraints"},
        {t:"code", lang:"sql", v:[
          "CREATE TABLE orders (",
          "    id          BIGSERIAL PRIMARY KEY,",
          "    customer_id BIGINT NOT NULL",
          "                REFERENCES customers(id) ON DELETE RESTRICT,",
          "                -- ON DELETE RESTRICT: can't delete customer with orders",
          "                -- ON DELETE CASCADE:  deleting customer deletes their orders",
          "                -- ON DELETE SET NULL: sets customer_id to NULL on delete",
          "    status      VARCHAR(20) NOT NULL",
          "                CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),",
          "    total       NUMERIC(10,2) NOT NULL CHECK (total >= 0),",
          "    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()",
          ");",
          "",
          "-- Composite primary key (junction table for many-to-many):",
          "CREATE TABLE order_items (",
          "    order_id   BIGINT REFERENCES orders(id) ON DELETE CASCADE,",
          "    product_id BIGINT REFERENCES products(id) ON DELETE RESTRICT,",
          "    quantity   INT NOT NULL CHECK (quantity > 0),",
          "    unit_price NUMERIC(10,2) NOT NULL,",
          "    PRIMARY KEY (order_id, product_id)  -- Composite PK",
          ");",
          "",
          "-- Unique constraint across multiple columns:",
          "ALTER TABLE order_items",
          "    ADD CONSTRAINT uq_order_product UNIQUE (order_id, product_id);",
        ]},
        {t:"heading", v:"Normalization — 1NF, 2NF, 3NF"},
        {t:"code", lang:"text", v:[
          "FIRST NORMAL FORM (1NF):",
          "  Each column holds ATOMIC (single) values.",
          "  No repeating groups.",
          "",
          "BAD (violates 1NF):",
          "  orders: id | customer | products",
          "          1  | Alice    | 'Laptop,Phone,Charger'  ← multiple values",
          "",
          "GOOD (1NF):",
          "  orders: id | customer    order_items: order_id | product",
          "          1  | Alice                   1        | Laptop",
          "                                       1        | Phone",
          "                                       1        | Charger",
          "",
          "SECOND NORMAL FORM (2NF):",
          "  Must be 1NF + every non-key column depends on the WHOLE primary key.",
          "",
          "BAD (violates 2NF with composite key order_id+product_id):",
          "  order_items: order_id | product_id | qty | product_name",
          "  product_name depends only on product_id, not the whole key!",
          "",
          "GOOD (2NF): Move product_name to a separate products table.",
          "",
          "THIRD NORMAL FORM (3NF):",
          "  Must be 2NF + no column depends on another non-key column.",
          "",
          "BAD (violates 3NF):",
          "  orders: id | customer_id | customer_city | customer_country",
          "  customer_city depends on customer_id, not order id!",
          "",
          "GOOD (3NF): Move customer info to customers table.",
        ]},
        {t:"heading", v:"Many-to-Many Relationships"},
        {t:"code", lang:"sql", v:[
          "-- Students can enroll in many courses.",
          "-- Courses can have many students.",
          "-- Solution: junction (bridge) table.",
          "",
          "CREATE TABLE students (",
          "    id   BIGSERIAL PRIMARY KEY,",
          "    name VARCHAR(100) NOT NULL",
          ");",
          "",
          "CREATE TABLE courses (",
          "    id    BIGSERIAL PRIMARY KEY,",
          "    title VARCHAR(200) NOT NULL,",
          "    code  VARCHAR(20) UNIQUE NOT NULL",
          ");",
          "",
          "-- Junction table: the 'many-to-many' relationship",
          "CREATE TABLE enrollments (",
          "    student_id  BIGINT REFERENCES students(id) ON DELETE CASCADE,",
          "    course_id   BIGINT REFERENCES courses(id)  ON DELETE CASCADE,",
          "    enrolled_at TIMESTAMPTZ DEFAULT NOW(),",
          "    grade       VARCHAR(2),",
          "    PRIMARY KEY (student_id, course_id)  -- Can only enroll once",
          ");",
          "",
          "-- Find all courses a student is enrolled in:",
          "SELECT c.title, c.code, e.grade",
          "FROM enrollments e",
          "JOIN courses c ON e.course_id = c.id",
          "WHERE e.student_id = 42;",
          "",
          "-- Find all students in a course:",
          "SELECT s.name, e.enrolled_at, e.grade",
          "FROM enrollments e",
          "JOIN students s ON e.student_id = s.id",
          "WHERE e.course_id = 10",
          "ORDER BY s.name;",
        ]},
        {t:"heading", v:"Database Migrations — Flyway"},
        {t:"code", lang:"sql", v:[
          "-- Flyway: version-controlled database migrations",
          "-- Files named: V1__init.sql, V2__add_index.sql, V3__add_column.sql",
          "",
          "-- V1__create_tables.sql",
          "CREATE TABLE customers (",
          "    id         BIGSERIAL PRIMARY KEY,",
          "    name       VARCHAR(100) NOT NULL,",
          "    email      VARCHAR(255) UNIQUE NOT NULL,",
          "    created_at TIMESTAMPTZ DEFAULT NOW()",
          ");",
          "",
          "-- V2__add_phone_to_customers.sql",
          "ALTER TABLE customers ADD COLUMN phone VARCHAR(20);",
          "",
          "-- V3__add_orders_table.sql",
          "CREATE TABLE orders (",
          "    id          BIGSERIAL PRIMARY KEY,",
          "    customer_id BIGINT NOT NULL REFERENCES customers(id),",
          "    total       NUMERIC(10,2) NOT NULL,",
          "    status      VARCHAR(20) NOT NULL DEFAULT 'PENDING',",
          "    created_at  TIMESTAMPTZ DEFAULT NOW()",
          ");",
          "CREATE INDEX idx_orders_customer ON orders(customer_id);",
          "",
          "-- application.yml (Spring Boot + Flyway auto-runs migrations):",
          "-- spring.flyway.enabled: true",
          "-- spring.flyway.locations: classpath:db/migration",
          "-- Flyway tracks which migrations ran in flyway_schema_history table",
        ]},
      ]
    },
    {
      title: "MongoDB — Document Database", level: "Intermediate",
      blocks: [
        {t:"text", v:"MongoDB is a NoSQL document database. Instead of rows in tables, it stores JSON-like documents in collections. It's schema-flexible, horizontally scalable, and excellent for hierarchical or variable-structure data."},
        {t:"heading", v:"Core Concepts — Documents & Collections"},
        {t:"code", lang:"text", v:[
          "RDBMS        MongoDB",
          "─────────    ───────────",
          "Database  →  Database",
          "Table     →  Collection",
          "Row       →  Document (JSON object)",
          "Column    →  Field",
          "JOIN      →  Embedding or $lookup",
          "INDEX     →  Index",
          "",
          "Document example (products collection):",
          "{",
          "  _id: ObjectId('65f3a2b1c4e5d6a7b8c9d0e1'),",
          "  name: 'Gaming Laptop',",
          "  price: 1299.99,",
          "  category: 'Electronics',",
          "  specs: {                    ← Nested document",
          "    ram: 16,",
          "    storage: '512GB SSD',",
          "    gpu: 'RTX 4060'",
          "  },",
          "  tags: ['gaming', 'laptop'], ← Array",
          "  reviews: [                  ← Array of nested docs",
          "    { user: 'Alice', rating: 5, text: 'Great laptop!' },",
          "    { user: 'Bob',   rating: 4, text: 'Good value' }",
          "  ],",
          "  createdAt: ISODate('2024-01-15T10:30:00Z')",
          "}",
        ]},
        {t:"heading", v:"CRUD Operations"},
        {t:"code", lang:"javascript", v:[
          "// INSERT",
          "db.products.insertOne({",
          "  name: 'Wireless Headphones',",
          "  price: 149.99,",
          "  category: 'Electronics',",
          "  tags: ['audio', 'wireless']",
          "});",
          "",
          "db.products.insertMany([",
          "  { name: 'Phone Case', price: 19.99 },",
          "  { name: 'Charger',    price: 29.99 }",
          "]);",
          "",
          "// FIND (READ)",
          "db.products.find();                                    // All docs",
          "db.products.find({ category: 'Electronics' });         // Filter",
          "db.products.find({ price: { $lt: 50 } });              // Price < 50",
          "db.products.find({ price: { $gte: 100, $lte: 500 } }); // Range",
          "db.products.find({ tags: 'wireless' });                // Array contains",
          "db.products.find({ 'specs.ram': { $gte: 16 } });       // Nested field",
          "",
          "// Projection: select specific fields (1=include, 0=exclude)",
          "db.products.find({}, { name: 1, price: 1, _id: 0 });",
          "",
          "// Sort, limit, skip",
          "db.products.find().sort({ price: -1 }).limit(10).skip(20);",
          "",
          "// UPDATE",
          "db.products.updateOne(",
          "  { _id: ObjectId('65f3a2...') },",
          "  { $set: { price: 1199.99 }, $addToSet: { tags: 'sale' } }",
          ");",
          "",
          "// DELETE",
          "db.products.deleteOne({ _id: ObjectId('65f3a2...') });",
          "db.products.deleteMany({ status: 'DISCONTINUED' });",
        ]},
        {t:"heading", v:"Aggregation Pipeline"},
        {t:"code", lang:"javascript", v:[
          "// MongoDB's powerful data transformation pipeline",
          "",
          "// Total revenue by category for completed orders",
          "db.orders.aggregate([",
          "  // Stage 1: Filter",
          "  { $match: { status: 'COMPLETED' } },",
          "",
          "  // Stage 2: Join with products collection",
          "  { $lookup: {",
          "      from: 'products',",
          "      localField: 'productId',",
          "      foreignField: '_id',",
          "      as: 'product'",
          "  }},",
          "",
          "  // Stage 3: Unwind array from lookup",
          "  { $unwind: '$product' },",
          "",
          "  // Stage 4: Group and aggregate",
          "  { $group: {",
          "      _id: '$product.category',",
          "      totalRevenue: { $sum: '$total' },",
          "      orderCount:   { $sum: 1 },",
          "      avgOrderValue:{ $avg: '$total' }",
          "  }},",
          "",
          "  // Stage 5: Sort by revenue",
          "  { $sort: { totalRevenue: -1 } },",
          "",
          "  // Stage 6: Rename _id field",
          "  { $project: {",
          "      category:      '$_id',",
          "      totalRevenue:  1,",
          "      orderCount:    1,",
          "      avgOrderValue: { $round: ['$avgOrderValue', 2] },",
          "      _id: 0",
          "  }}",
          "]);",
        ]},
        {t:"heading", v:"Spring Data MongoDB"},
        {t:"code", lang:"java", v:[
          "// Document entity",
          "@Document(collection = \"products\")",
          "public class Product {",
          "    @Id private String id;",
          "    private String name;",
          "    private BigDecimal price;",
          "    private String category;",
          "    private List<String> tags;",
          "",
          "    @DBRef  // Reference to another document",
          "    private Supplier supplier;",
          "}",
          "",
          "// Repository",
          "public interface ProductRepository extends MongoRepository<Product, String> {",
          "    List<Product> findByCategory(String category);",
          "    List<Product> findByPriceLessThan(BigDecimal maxPrice);",
          "    List<Product> findByTagsContaining(String tag);",
          "",
          "    @Query(\"{ 'price': { $gte: ?0, $lte: ?1 } }\")",
          "    List<Product> findByPriceRange(BigDecimal min, BigDecimal max);",
          "}",
          "",
          "// Custom queries with MongoTemplate:",
          "@Service",
          "public class ProductService {",
          "    private final MongoTemplate mongoTemplate;",
          "",
          "    public List<Product> searchProducts(String keyword, BigDecimal maxPrice) {",
          "        Query query = new Query();",
          "        query.addCriteria(Criteria.where(\"name\").regex(keyword, \"i\"));",
          "        if (maxPrice != null)",
          "            query.addCriteria(Criteria.where(\"price\").lte(maxPrice));",
          "        query.with(Sort.by(\"price\").ascending());",
          "        return mongoTemplate.find(query, Product.class);",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Redis — In-Memory Data Store", level: "Intermediate",
      blocks: [
        {t:"text", v:"Redis is an in-memory data structure store used as a cache, message broker, and session store. Because everything is in RAM, Redis operations are microseconds fast — 100-1000x faster than a database query. Every production system uses Redis."},
        {t:"heading", v:"Redis Data Structures"},
        {t:"code", lang:"bash", v:[
          "# STRING — most basic type",
          "SET user:1:name \"Alice\"",
          "GET user:1:name           # Returns: Alice",
          "SET counter 0",
          "INCR counter              # Atomic increment → 1",
          "INCRBY counter 5          # Add 5 → 6",
          "SETEX session:abc123 3600 '{\"userId\":1}' # Set with 1-hour TTL",
          "",
          "# HASH — object/dictionary",
          "HSET product:42 name \"Laptop\" price 999 stock 50",
          "HGET product:42 name        # Returns: Laptop",
          "HGETALL product:42          # Returns all fields",
          "HINCRBY product:42 stock -1 # Decrement stock atomically",
          "",
          "# LIST — ordered list (deque)",
          "RPUSH notifications:user1 \"Order shipped\" \"Payment received\"",
          "LPOP  notifications:user1   # Pop from front",
          "LRANGE notifications:user1 0 -1  # Get all",
          "",
          "# SET — unique unordered collection",
          "SADD online_users user:1 user:2 user:3",
          "SISMEMBER online_users user:2  # Is user:2 online? → 1 (yes)",
          "SCARD online_users             # Count: 3",
          "SINTER friends:alice friends:bob  # Common friends",
          "",
          "# SORTED SET — set with scores (leaderboards!)",
          "ZADD leaderboard 1500 \"Alice\"",
          "ZADD leaderboard 1200 \"Bob\"",
          "ZADD leaderboard 1800 \"Carol\"",
          "ZRANGE leaderboard 0 -1 WITHSCORES REV  # Top players",
          "ZRANK leaderboard \"Alice\"               # Alice's rank",
        ]},
        {t:"heading", v:"Spring Boot + Redis — Caching"},
        {t:"code", lang:"java", v:[
          "// application.yml",
          "// spring.cache.type: redis",
          "// spring.data.redis.host: localhost",
          "// spring.data.redis.port: 6379",
          "",
          "@Configuration",
          "@EnableCaching",
          "public class CacheConfig {",
          "    @Bean",
          "    public RedisCacheManager cacheManager(RedisConnectionFactory factory) {",
          "        RedisCacheConfiguration config = RedisCacheConfiguration.defaultCacheConfig()",
          "            .entryTtl(Duration.ofMinutes(30))      // Default TTL: 30 minutes",
          "            .disableCachingNullValues();",
          "",
          "        Map<String, RedisCacheConfiguration> cacheConfigs = Map.of(",
          "            \"products\",   config.entryTtl(Duration.ofHours(1)),",
          "            \"userSessions\",config.entryTtl(Duration.ofDays(1)),",
          "            \"homepageFeed\",config.entryTtl(Duration.ofMinutes(5))",
          "        );",
          "",
          "        return RedisCacheManager.builder(factory)",
          "            .cacheDefaults(config)",
          "            .withInitialCacheConfigurations(cacheConfigs)",
          "            .build();",
          "    }",
          "}",
          "",
          "@Service",
          "public class ProductService {",
          "    // Cache result for 1 hour. Key: 'products::42'",
          "    @Cacheable(value = \"products\", key = \"#id\")",
          "    public Product getProduct(Long id) {",
          "        return productRepo.findById(id)  // DB hit only on cache miss",
          "            .orElseThrow(() -> new ProductNotFoundException(id));",
          "    }",
          "",
          "    // Update cache when product changes",
          "    @CachePut(value = \"products\", key = \"#result.id\")",
          "    public Product updateProduct(Long id, UpdateRequest req) {",
          "        return productRepo.save(/* update */);",
          "    }",
          "",
          "    // Remove from cache when deleted",
          "    @CacheEvict(value = \"products\", key = \"#id\")",
          "    public void deleteProduct(Long id) { productRepo.deleteById(id); }",
          "",
          "    // Clear entire cache",
          "    @CacheEvict(value = \"products\", allEntries = true)",
          "    @Scheduled(fixedRate = 3600000)  // Every hour",
          "    public void clearProductCache() { }",
          "}",
        ]},
        {t:"heading", v:"Redis for Sessions, Rate Limiting & Pub/Sub"},
        {t:"code", lang:"java", v:[
          "// Session management — store user sessions in Redis",
          "// application.yml:",
          "// spring.session.store-type: redis",
          "// All HttpSession data automatically stored in Redis",
          "// Works across multiple app instances!",
          "",
          "// Rate limiting with Redis sliding window:",
          "@Service",
          "public class RateLimiter {",
          "    private final StringRedisTemplate redis;",
          "",
          "    public boolean isAllowed(String userId, int maxRequests, long windowSeconds) {",
          "        String key = \"rate:\" + userId;",
          "        long now = System.currentTimeMillis();",
          "        long windowStart = now - (windowSeconds * 1000);",
          "",
          "        // Remove old entries outside the window",
          "        redis.opsForZSet().removeRangeByScore(key, 0, windowStart);",
          "",
          "        // Count requests in current window",
          "        Long count = redis.opsForZSet().zCard(key);",
          "        if (count != null && count >= maxRequests) return false;",
          "",
          "        // Record this request",
          "        redis.opsForZSet().add(key, String.valueOf(now), now);",
          "        redis.expire(key, Duration.ofSeconds(windowSeconds + 1));",
          "        return true;",
          "    }",
          "}",
          "",
          "// Distributed lock — prevent duplicate processing",
          "@Service",
          "public class DistributedLockService {",
          "    private final StringRedisTemplate redis;",
          "",
          "    public boolean acquireLock(String lockKey, String lockValue, long ttlSeconds) {",
          "        Boolean result = redis.opsForValue()",
          "            .setIfAbsent(lockKey, lockValue, Duration.ofSeconds(ttlSeconds));",
          "        return Boolean.TRUE.equals(result);",
          "    }",
          "",
          "    public void releaseLock(String lockKey, String expectedValue) {",
          "        // Only release if we own the lock (Lua script for atomicity)",
          "        String current = redis.opsForValue().get(lockKey);",
          "        if (expectedValue.equals(current)) redis.delete(lockKey);",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Database Transactions & ACID", level: "Intermediate",
      blocks: [
        {t:"text", v:"Transactions are the most important concept in databases. They guarantee data integrity — even when things go wrong (crashes, concurrent access). ACID properties define what a transaction must guarantee."},
        {t:"heading", v:"ACID Properties Explained"},
        {t:"code", lang:"text", v:[
          "A — ATOMICITY",
          "  All operations in a transaction succeed OR all fail.",
          "  There is no partial success.",
          "",
          "  Transfer Rs 500 from Alice to Bob:",
          "  Step 1: Debit Alice  -500  ← Both steps in ONE transaction",
          "  Step 2: Credit Bob   +500  ← If Step 2 fails, Step 1 is rolled back",
          "  Either both happen, or neither happens. Money never disappears.",
          "",
          "C — CONSISTENCY",
          "  Transaction brings DB from one valid state to another valid state.",
          "  All constraints, rules, and cascades are enforced.",
          "  e.g. account balance cannot go negative (CHECK constraint)",
          "",
          "I — ISOLATION",
          "  Concurrent transactions behave as if executed serially.",
          "  Transaction A doesn't see Transaction B's uncommitted changes.",
          "  Different isolation levels trade performance for correctness.",
          "",
          "D — DURABILITY",
          "  Once committed, changes survive crashes/power failures.",
          "  Data is written to disk (WAL — Write-Ahead Log).",
          "  You can trust: if the DB said 'commit OK', data is safe.",
        ]},
        {t:"heading", v:"Isolation Levels — The Trade-off"},
        {t:"code", lang:"sql", v:[
          "-- 4 isolation levels (from weakest to strongest):",
          "",
          "-- READ UNCOMMITTED: can read other transactions' uncommitted changes",
          "-- (Dirty reads) — almost never use this",
          "",
          "-- READ COMMITTED (PostgreSQL default):",
          "-- Can only read committed data. No dirty reads.",
          "-- But: non-repeatable reads possible (re-reading same row may give different result)",
          "SET TRANSACTION ISOLATION LEVEL READ COMMITTED;",
          "",
          "-- REPEATABLE READ:",
          "-- Same row always returns same data within transaction.",
          "-- No dirty reads, no non-repeatable reads.",
          "-- But: phantom reads possible (new rows added by other transaction are visible)",
          "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;",
          "",
          "-- SERIALIZABLE (strongest):",
          "-- Transactions behave as if running one at a time.",
          "-- Prevents all anomalies. Slowest.",
          "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
          "",
          "-- Practical example: bank transfer",
          "BEGIN;",
          "UPDATE accounts SET balance = balance - 500 WHERE id = 1;  -- Debit Alice",
          "UPDATE accounts SET balance = balance + 500 WHERE id = 2;  -- Credit Bob",
          "COMMIT;",
          "-- If any error occurs before COMMIT, ROLLBACK is automatic",
        ]},
        {t:"heading", v:"Optimistic vs Pessimistic Locking"},
        {t:"code", lang:"java", v:[
          "// PESSIMISTIC LOCKING: lock the row immediately",
          "// Good when: high contention, can't afford conflicts",
          "@Transactional",
          "public void transferFunds(Long fromId, Long toId, BigDecimal amount) {",
          "    // SELECT ... FOR UPDATE — locks both rows until transaction ends",
          "    Account from = accountRepo.findByIdForUpdate(fromId);",
          "    Account to   = accountRepo.findByIdForUpdate(toId);",
          "",
          "    if (from.getBalance().compareTo(amount) < 0)",
          "        throw new InsufficientFundsException();",
          "",
          "    from.setBalance(from.getBalance().subtract(amount));",
          "    to.setBalance(to.getBalance().add(amount));",
          "",
          "    accountRepo.save(from);",
          "    accountRepo.save(to);",
          "}  // Lock released on commit",
          "",
          "// OPTIMISTIC LOCKING: check for conflicts at commit time",
          "// Good when: low contention, avoid lock overhead",
          "@Entity",
          "public class Product {",
          "    @Version  // Hibernate auto-manages this field",
          "    private Long version;  // Starts at 0, increments on each update",
          "    private int stock;",
          "}",
          "",
          "@Transactional",
          "public void decrementStock(Long productId, int qty) {",
          "    Product p = productRepo.findById(productId).orElseThrow();",
          "    if (p.getStock() < qty) throw new InsufficientStockException();",
          "    p.setStock(p.getStock() - qty);",
          "    productRepo.save(p);",
          "    // If another transaction updated this product since we read it,",
          "    // Hibernate throws OptimisticLockException → retry or show error",
          "}",
        ]},
        {t:"note", v:"Use pessimistic locking for financial transactions (always must succeed, no retries). Use optimistic locking for e-commerce inventory (occasional conflicts OK, just show 'sold out' and retry)."},
      ]
    },
    {
      title: "Database Scaling — Replication & Sharding", level: "Advanced",
      blocks: [
        {t:"text", v:"When your application grows beyond what a single database server can handle, you need scaling strategies. Understanding these is essential for senior engineer interviews and real production architecture."},
        {t:"heading", v:"Read Replicas — Scale Reads"},
        {t:"code", lang:"text", v:[
          "PRIMARY (Master) — handles all WRITES",
          "    │  Replication (async, < 100ms lag)",
          "    ├─ REPLICA 1 — handles READ queries",
          "    ├─ REPLICA 2 — handles READ queries",
          "    └─ REPLICA 3 — handles READ queries + analytics",
          "",
          "Most applications: 80-90% reads, 10-20% writes.",
          "Read replicas let you scale the 80-90% cheaply.",
          "",
          "Spring Boot read/write splitting:",
          "  @Transactional(readOnly = true)  → routes to replica",
          "  @Transactional                   → routes to primary",
          "",
          "Replication lag consideration:",
          "  After writing, reading immediately from replica may return",
          "  stale data (replica hasn't caught up yet).",
          "  Solution: Route post-write reads to primary for 1 second,",
          "  or use synchronous replication for critical paths.",
        ]},
        {t:"heading", v:"Connection Pooling — HikariCP"},
        {t:"code", lang:"yaml", v:[
          "# HikariCP — fastest Java connection pool",
          "spring:",
          "  datasource:",
          "    url: jdbc:postgresql://db:5432/myapp",
          "    hikari:",
          "      maximum-pool-size: 20      # Max DB connections",
          "      minimum-idle: 5            # Keep 5 idle connections ready",
          "      connection-timeout: 30000  # Wait max 30s for a connection",
          "      idle-timeout: 600000       # Close idle connections after 10 min",
          "      max-lifetime: 1800000      # Recreate connections every 30 min",
          "      keepalive-time: 60000      # Ping DB every 60s to keep alive",
          "",
          "# Sizing the pool:",
          "# Too small: requests queue up waiting for connections",
          "# Too large: DB gets overwhelmed with concurrent queries",
          "",
          "# Formula: pool_size = (core_count * 2) + effective_spindle_count",
          "# For 4-core server with SSD: (4 * 2) + 1 = 9",
          "# But with multiple app instances: divide by instance count",
          "# 3 app instances, 20 max connections each = 60 total DB connections",
          "# Make sure DB server can handle that (PostgreSQL default max_connections = 100)",
        ]},
        {t:"heading", v:"Query Optimization Checklist"},
        {t:"code", lang:"sql", v:[
          "-- 1. Check slow query log",
          "-- PostgreSQL: log queries taking > 1 second",
          "-- In postgresql.conf:",
          "-- log_min_duration_statement = 1000   (ms)",
          "",
          "-- 2. Use EXPLAIN ANALYZE on slow queries",
          "EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)",
          "SELECT * FROM orders WHERE customer_id = 123 AND status = 'PENDING';",
          "",
          "-- Look for:",
          "-- Seq Scan on large table → needs index",
          "-- High actual vs estimated rows → stale statistics → ANALYZE",
          "-- Hash Join with high memory → may need work_mem increase",
          "",
          "-- 3. Add missing indexes",
          "CREATE INDEX CONCURRENTLY idx_orders_cust_status",
          "    ON orders(customer_id, status);",
          "-- CONCURRENTLY: builds index without locking the table!",
          "",
          "-- 4. Update statistics after bulk loads",
          "ANALYZE orders;",
          "",
          "-- 5. Use connection pooling (PgBouncer between app and DB)",
          "",
          "-- 6. Partition large tables",
          "CREATE TABLE orders (",
          "    id         BIGSERIAL,",
          "    created_at TIMESTAMPTZ NOT NULL,",
          "    status     VARCHAR(20)",
          ") PARTITION BY RANGE (created_at);",
          "",
          "CREATE TABLE orders_2024 PARTITION OF orders",
          "    FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');",
          "CREATE TABLE orders_2025 PARTITION OF orders",
          "    FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');",
          "-- Queries with WHERE created_at = '2024-...' only scan one partition!",
        ]},
      ]
    },
    {
      title: "Database Interview Questions", level: "Advanced",
      blocks: [
        {t:"text", v:"Database questions appear in almost every backend interview. These are the questions that distinguish candidates with real production experience."},
        {t:"heading", v:"Q1: What is the difference between clustered and non-clustered indexes?"},
        {t:"code", lang:"text", v:[
          "CLUSTERED INDEX:",
          "  The table data IS physically sorted by this index.",
          "  Only ONE per table (the primary key in PostgreSQL/MySQL InnoDB).",
          "  Range queries very fast — related rows are physically adjacent.",
          "  INSERT can be slow — may need to rearrange physical rows.",
          "",
          "NON-CLUSTERED INDEX:",
          "  Separate structure that points to table rows.",
          "  Multiple allowed per table.",
          "  Contains index column(s) + pointer to actual row.",
          "  Slightly slower than clustered (extra pointer hop).",
          "",
          "Example:",
          "  Primary key (id): clustered — rows sorted by ID on disk",
          "  Index on (email): non-clustered — separate B-tree pointing to rows",
          "  Index on (status, created_at): non-clustered covering index",
        ]},
        {t:"note", v:"Cross Question: 'When would you choose UUID over auto-increment for primary key?' → UUID: distributed systems (no central counter needed), expose IDs externally (non-guessable), merge databases. Auto-increment: single server, better B-tree performance (sequential inserts avoid page splits), smaller storage."},
        {t:"heading", v:"Q2: Explain the N+1 Problem and all its solutions"},
        {t:"code", lang:"java", v:[
          "// N+1: 1 query for list + N queries for related data",
          "// Load 100 orders and print each customer's name:",
          "",
          "List<Order> orders = orderRepo.findAll();    // Query 1: SELECT * FROM orders",
          "orders.forEach(o -> {",
          "    System.out.println(o.getCustomer().getName()); // Queries 2-101: lazy load",
          "});",
          "// Result: 101 SQL queries. At 10ms each = 1 second for 100 orders.",
          "// At 1000 orders = 10 seconds. Users will abandon the page.",
          "",
          "// SOLUTION 1: JOIN FETCH",
          "@Query(\"SELECT o FROM Order o JOIN FETCH o.customer\")",
          "List<Order> findAllWithCustomer(); // 1 query with JOIN",
          "",
          "// SOLUTION 2: @EntityGraph",
          "@EntityGraph(attributePaths = {\"customer\", \"items\"})",
          "List<Order> findByStatus(OrderStatus status);",
          "",
          "// SOLUTION 3: Batch loading",
          "@BatchSize(size = 20)  // Load customers in batches of 20",
          "@ManyToOne private Customer customer;",
          "// Result: ceil(100/20) = 5 queries instead of 100",
          "",
          "// SOLUTION 4: DTO projection — best for read-only views",
          "@Query(\"SELECT new OrderSummaryDto(o.id, c.name, o.total)\" +",
          "       \" FROM Order o JOIN o.customer c\")",
          "List<OrderSummaryDto> findSummaries();  // 1 query, minimal data",
          "",
          "// HOW TO DETECT: Enable SQL logging in dev",
          "// spring.jpa.show-sql=true",
          "// Count the SELECT statements — if you see N+1, fix it!",
        ]},
        {t:"heading", v:"Q3: When would you use NoSQL over SQL?"},
        {t:"table", v:[
          ["Use Case","Recommended DB","Reason"],
          ["Financial transactions","PostgreSQL","ACID required, complex queries"],
          ["User profiles with flexible fields","MongoDB","Schema varies per user"],
          ["Session data, caching","Redis","Speed > persistence"],
          ["Product catalog","PostgreSQL or MongoDB","SQL if relational, Mongo if flexible"],
          ["IoT sensor data, logs","Cassandra or InfluxDB","Time series, write-heavy, huge scale"],
          ["Social graph (friends of friends)","Neo4j","Graph traversal is native"],
          ["Full-text search","Elasticsearch","Inverted index built for search"],
          ["Event store, audit log","Kafka + Cassandra","Append-only, high throughput"],
        ]},
        {t:"note", v:"Cross Question: 'Can you use both SQL and NoSQL in the same application?' → Yes — polyglot persistence. Example: PostgreSQL for orders and payments, Redis for sessions and caching, Elasticsearch for product search, MongoDB for user-generated content. Each database is chosen for what it does best."},
        {t:"heading", v:"Q4: What is Database Connection Pooling and why is it essential?"},
        {t:"code", lang:"text", v:[
          "WITHOUT connection pooling:",
          "  Each request: Open TCP connection to DB (takes ~50ms)",
          "               Authenticate",
          "               Execute query",
          "               Close connection",
          "  100 requests/second = 100 new connections/second",
          "  PostgreSQL default max_connections = 100",
          "  Under load: connection exhaustion, requests fail",
          "",
          "WITH connection pooling (HikariCP):",
          "  App starts: Create 10 connections, keep them open",
          "  Each request: Borrow a connection (takes ~microseconds)",
          "               Execute query",
          "               Return connection to pool",
          "  Same 10 connections serve thousands of requests/second",
          "",
          "Key metrics to monitor:",
          "  Pool utilization:  connections in use / pool size",
          "  Wait time:         how long requests wait for a connection",
          "  Connection timeout: requests that couldn't get a connection",
          "",
          "If pool utilization is consistently > 80%: increase pool size",
          "or optimize queries to hold connections for shorter time.",
        ]},
      ]
    },
  ]
};

databaseData.topics.push(
  {
    title: "Database Indexing — Deep Dive Interview Questions", level: "Advanced",
    blocks: [
      {t:"text", v:"Indexing questions separate developers who've actually optimized production queries from those who only know the theory. These questions probe real understanding of how databases find data."},
      {t:"heading", v:"Q1: How does a B-Tree index actually work internally?"},
      {t:"code", lang:"text", v:[
        "B-Tree (Balanced Tree) structure:",
        "",
        "                  [50]",
        "                 /    \\",
        "            [20,35]    [70,85]",
        "           /   |   \\   /   |   \\",
        "        [10] [25] [40][60] [80] [90]",
        "",
        "Properties:",
        "- All leaf nodes at SAME depth (balanced)",
        "- Each node has multiple keys (not just 1 like binary tree)",
        "- Designed to minimize DISK READS (each node = 1 disk page, ~8KB)",
        "- Search: O(log n) but with very high branching factor (100s of keys per node)",
        "- A B-Tree with branching factor 200 can index 1 billion rows in only 4 levels!",
        "",
        "Why not just use Binary Search Tree?",
        "- BST is O(log n) but minimizes COMPARISONS, not DISK READS",
        "- Each disk read takes ~10ms (vs 100ns for RAM)",
        "- B-Tree minimizes disk reads by packing many keys per node",
        "- 1 billion rows: BST needs ~30 disk reads, B-Tree needs ~4!",
        "",
        "Index lookup process:",
        "1. Read root page from disk (or cache)",
        "2. Binary search within page to find which child to follow",
        "3. Read child page from disk",
        "4. Repeat until leaf page reached",
        "5. Leaf page contains pointer to actual table row (or the row itself in clustered index)",
      ]},
      {t:"note", v:"Cross Question: 'Why can't you have too many indexes on a table?' → Every INSERT/UPDATE/DELETE must update ALL indexes, not just the table. 10 indexes = 10x the write overhead. Also: more indexes = more disk space, more memory needed to cache them, query planner has more options to evaluate (can slow down query planning slightly). Rule of thumb: index columns used in WHERE, JOIN, ORDER BY frequently; avoid indexing columns rarely queried or with low cardinality."},
      {t:"heading", v:"Q2: What is index selectivity and why does it matter?"},
      {t:"code", lang:"sql", v:[
        "-- Selectivity = unique values / total rows",
        "-- High selectivity (close to 1) = good index candidate",
        "-- Low selectivity (close to 0) = poor index candidate",
        "",
        "-- Example: orders table with 1,000,000 rows",
        "",
        "-- LOW selectivity — BAD index candidate:",
        "-- status column: only 5 distinct values (PENDING, SHIPPED, etc.)",
        "-- Selectivity = 5 / 1,000,000 = 0.000005",
        "CREATE INDEX idx_status ON orders(status);",
        "-- Query: WHERE status = 'PENDING' might match 200,000 rows (20%)",
        "-- Database often chooses SEQ SCAN over using this index!",
        "-- Why: reading 20% of table via random index lookups is SLOWER",
        "--      than reading the whole table sequentially",
        "",
        "-- HIGH selectivity — GOOD index candidate:",
        "-- order_id column: 1,000,000 distinct values",
        "-- Selectivity = 1,000,000 / 1,000,000 = 1.0 (perfect)",
        "CREATE INDEX idx_order_id ON orders(id);",
        "-- Query: WHERE id = 12345 matches exactly 1 row — index is PERFECT here",
        "",
        "-- Composite index improves selectivity:",
        "CREATE INDEX idx_status_customer ON orders(status, customer_id);",
        "-- WHERE status='PENDING' AND customer_id=123",
        "-- Combined selectivity much higher — index becomes useful",
        "",
        "-- Check actual selectivity in PostgreSQL:",
        "SELECT attname, n_distinct, most_common_vals",
        "FROM pg_stats WHERE tablename = 'orders';",
        "-- n_distinct: -1 means unique, 0.5 means 50% of rows are duplicates of half",
      ]},
      {t:"heading", v:"Q3: Explain the difference between covering index and regular index"},
      {t:"code", lang:"sql", v:[
        "-- REGULAR INDEX: index has the indexed columns + pointer to row",
        "CREATE INDEX idx_customer ON orders(customer_id);",
        "",
        "-- Query needs columns NOT in the index:",
        "SELECT customer_id, status, total FROM orders WHERE customer_id = 123;",
        "-- Process: 1) Use index to find matching rows (fast)",
        "--          2) For EACH match, go to TABLE to get status, total (slow!)",
        "--          This extra step is called 'table lookup' or 'heap fetch'",
        "",
        "-- COVERING INDEX: includes ALL columns the query needs",
        "CREATE INDEX idx_customer_covering",
        "    ON orders(customer_id)",
        "    INCLUDE (status, total);  -- PostgreSQL syntax",
        "",
        "-- Now the SAME query:",
        "SELECT customer_id, status, total FROM orders WHERE customer_id = 123;",
        "-- Process: Index alone has everything needed!",
        "--          NO table lookup required — 'Index Only Scan'",
        "--          Can be 2-5x faster for read-heavy workloads",
        "",
        "-- Trade-off: covering indexes are LARGER (more disk, more memory)",
        "-- Use when: specific query pattern is extremely frequent and performance-critical",
        "",
        "-- Verify with EXPLAIN:",
        "EXPLAIN ANALYZE",
        "SELECT customer_id, status, total FROM orders WHERE customer_id = 123;",
        "-- Look for: 'Index Only Scan' (covering, fast) vs",
        "--           'Index Scan' + 'Heap Fetches' (regular, slower)",
      ]},
      {t:"heading", v:"Q4: What is the difference between clustered and heap table organization?"},
      {t:"code", lang:"text", v:[
        "HEAP TABLE (PostgreSQL default, MySQL MyISAM):",
        "  Rows stored in INSERTION order (no particular physical order)",
        "  Primary key is just a regular index pointing to row location",
        "  INSERT is fast — just append to end",
        "  Range queries on PK need index lookups + random table access",
        "",
        "CLUSTERED TABLE (MySQL InnoDB default, SQL Server):",
        "  Rows PHYSICALLY SORTED by primary key on disk",
        "  Primary key access doesn't need separate lookup —",
        "    primary key search directly navigates to the row",
        "  Range queries on PK are VERY fast (sequential disk read)",
        "  INSERT in middle of sequence: may require page split (slower)",
        "  Only ONE clustered index per table (data can only be sorted one way)",
        "",
        "PostgreSQL CLUSTER command (manual, one-time clustering):",
        "CLUSTER orders USING idx_orders_created_at;",
        "-- Physically reorders table to match index order",
        "-- NOT maintained automatically — must re-run periodically",
        "-- Useful for: time-series tables queried mostly by date range",
      ]},
      {t:"heading", v:"Q5: Why might a database choose NOT to use an available index?"},
      {t:"code", lang:"sql", v:[
        "-- The query planner estimates COST for each possible execution plan",
        "-- and chooses the CHEAPEST one — not necessarily the one 'using the index'",
        "",
        "-- Reason 1: Low selectivity (returning too many rows)",
        "SELECT * FROM orders WHERE status = 'COMPLETED';",
        "-- If 80% of orders are COMPLETED: seq scan is cheaper than",
        "-- index scan (random I/O) + heap fetch for 80% of the table",
        "",
        "-- Reason 2: Small table",
        "SELECT * FROM categories WHERE id = 5; -- Only 50 rows total",
        "-- Seq scan of 50 rows is faster than the overhead of using an index",
        "",
        "-- Reason 3: Outdated statistics",
        "-- Planner uses table statistics to estimate row counts",
        "-- If stats are stale (lots of changes since last ANALYZE):",
        "ANALYZE orders; -- Refresh statistics",
        "-- Run this after bulk loads/deletes",
        "",
        "-- Reason 4: Function applied to indexed column",
        "SELECT * FROM orders WHERE UPPER(status) = 'PENDING';",
        "-- Regular index on status CANNOT be used here!",
        "-- Need a FUNCTIONAL INDEX:",
        "CREATE INDEX idx_status_upper ON orders(UPPER(status));",
        "",
        "-- Reason 5: Implicit type conversion",
        "SELECT * FROM orders WHERE customer_id = '123'; -- customer_id is INT, '123' is TEXT",
        "-- Type mismatch may prevent index use! Always match types exactly",
        "",
        "-- Force index usage to TEST (don't use in production logic):",
        "SET enable_seqscan = OFF; -- PostgreSQL — forces planner to avoid seq scan",
        "EXPLAIN ANALYZE SELECT * FROM orders WHERE status = 'PENDING';",
      ]},
    ]
  },
  {
    title: "Oracle Database — Enterprise SQL Features", level: "Intermediate",
    blocks: [
      {t:"text", v:"Oracle Database remains dominant in large enterprises — banking, insurance, telecom, government. As a J2EE developer you will work with Oracle's distinctive SQL dialect and features that differ from PostgreSQL/MySQL."},
      {t:"heading", v:"Oracle-Specific SQL Syntax"},
      {t:"code", lang:"sql", v:[
        "-- Oracle uses DUAL table for expressions without a real table:",
        "SELECT SYSDATE FROM DUAL;",
        "SELECT 1 + 1 FROM DUAL;",
        "",
        "-- Sequences (before IDENTITY columns existed):",
        "CREATE SEQUENCE order_seq START WITH 1 INCREMENT BY 1;",
        "INSERT INTO orders (id, customer_id, total)",
        "VALUES (order_seq.NEXTVAL, 123, 299.99);",
        "",
        "-- Oracle 12c+ supports IDENTITY columns too:",
        "CREATE TABLE orders (",
        "    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,",
        "    customer_id NUMBER,",
        "    total NUMBER(10,2)",
        ");",
        "",
        "-- ROWNUM for pagination (older Oracle versions):",
        "SELECT * FROM (",
        "    SELECT a.*, ROWNUM rnum FROM (",
        "        SELECT * FROM orders ORDER BY created_at DESC",
        "    ) a WHERE ROWNUM <= 20",
        ") WHERE rnum > 0;",
        "",
        "-- Modern Oracle 12c+ pagination (cleaner):",
        "SELECT * FROM orders",
        "ORDER BY created_at DESC",
        "OFFSET 0 ROWS FETCH NEXT 20 ROWS ONLY;",
        "",
        "-- NVL — handle nulls (like COALESCE but Oracle-specific):",
        "SELECT NVL(phone, 'No phone') FROM customers;",
        "SELECT NVL2(phone, 'Has phone', 'No phone') FROM customers; -- ternary-like",
        "",
        "-- DECODE — like a CASE expression (older Oracle style):",
        "SELECT DECODE(status, 'P', 'Pending', 'S', 'Shipped', 'Unknown') FROM orders;",
        "-- Modern equivalent:",
        "SELECT CASE status WHEN 'P' THEN 'Pending' WHEN 'S' THEN 'Shipped'",
        "       ELSE 'Unknown' END FROM orders;",
        "",
        "-- MERGE statement (UPSERT) — very commonly used in Oracle batch jobs:",
        "MERGE INTO inventory tgt",
        "USING (SELECT :productId AS product_id, :qty AS qty FROM DUAL) src",
        "ON (tgt.product_id = src.product_id)",
        "WHEN MATCHED THEN",
        "    UPDATE SET tgt.stock = tgt.stock + src.qty",
        "WHEN NOT MATCHED THEN",
        "    INSERT (product_id, stock) VALUES (src.product_id, src.qty);",
      ]},
      {t:"heading", v:"PL/SQL — Oracle's Procedural Extension"},
      {t:"code", lang:"sql", v:[
        "-- Stored Procedure example — calculate customer loyalty discount",
        "CREATE OR REPLACE PROCEDURE calc_loyalty_discount(",
        "    p_customer_id IN NUMBER,",
        "    p_discount OUT NUMBER",
        ") AS",
        "    v_total_spent NUMBER;",
        "    v_order_count NUMBER;",
        "BEGIN",
        "    SELECT SUM(total), COUNT(*)",
        "    INTO v_total_spent, v_order_count",
        "    FROM orders",
        "    WHERE customer_id = p_customer_id AND status = 'COMPLETED';",
        "",
        "    IF v_total_spent > 100000 THEN",
        "        p_discount := 0.15;",
        "    ELSIF v_total_spent > 50000 THEN",
        "        p_discount := 0.10;",
        "    ELSIF v_order_count > 10 THEN",
        "        p_discount := 0.05;",
        "    ELSE",
        "        p_discount := 0;",
        "    END IF;",
        "",
        "EXCEPTION",
        "    WHEN NO_DATA_FOUND THEN",
        "        p_discount := 0;",
        "    WHEN OTHERS THEN",
        "        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);",
        "        RAISE;",
        "END calc_loyalty_discount;",
        "/",
        "",
        "-- Calling from Java via JDBC:",
        "-- CallableStatement cs = conn.prepareCall(",
        "--     \"{call calc_loyalty_discount(?, ?)}\");",
        "-- cs.setLong(1, customerId);",
        "-- cs.registerOutParameter(2, Types.NUMERIC);",
        "-- cs.execute();",
        "-- BigDecimal discount = cs.getBigDecimal(2);",
        "",
        "-- Or with Spring Data JPA:",
        "@Procedure(procedureName = \"calc_loyalty_discount\")",
        "BigDecimal calcLoyaltyDiscount(@Param(\"p_customer_id\") Long customerId);",
      ]},
      {t:"heading", v:"Oracle Performance — Hints & Execution Plans"},
      {t:"code", lang:"sql", v:[
        "-- Explain plan in Oracle:",
        "EXPLAIN PLAN FOR",
        "SELECT * FROM orders WHERE customer_id = 123 AND status = 'PENDING';",
        "",
        "SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);",
        "",
        "-- Optimizer hints (use sparingly — only when you understand WHY):",
        "SELECT /*+ INDEX(orders idx_customer_status) */ *",
        "FROM orders",
        "WHERE customer_id = 123 AND status = 'PENDING';",
        "",
        "SELECT /*+ PARALLEL(orders, 4) */ COUNT(*)",
        "FROM orders;  -- Use 4 parallel processes for large table scan",
        "",
        "-- Gather statistics (Oracle equivalent of ANALYZE):",
        "EXEC DBMS_STATS.GATHER_TABLE_STATS('SCHEMA_NAME', 'ORDERS');",
        "",
        "-- AWR (Automatic Workload Repository) for production diagnostics:",
        "-- DBAs use AWR reports to find slowest queries over time periods",
        "-- SELECT * FROM dba_hist_sqlstat WHERE elapsed_time_delta > 1000000;",
      ]},
    ]
  },
  {
    title: "SQL Server — T-SQL Essentials", level: "Intermediate",
    blocks: [
      {t:"text", v:"Microsoft SQL Server is widely used in enterprise .NET and Java shops, especially in finance and corporate IT. T-SQL (Transact-SQL) has its own dialect distinct from PostgreSQL and Oracle."},
      {t:"heading", v:"T-SQL Syntax Essentials"},
      {t:"code", lang:"sql", v:[
        "-- IDENTITY column (auto-increment, like SERIAL in PostgreSQL):",
        "CREATE TABLE orders (",
        "    id INT IDENTITY(1,1) PRIMARY KEY,",
        "    customer_id INT NOT NULL,",
        "    total DECIMAL(10,2),",
        "    status VARCHAR(20),",
        "    created_at DATETIME2 DEFAULT GETDATE()",
        ");",
        "",
        "-- TOP for limiting rows (instead of LIMIT):",
        "SELECT TOP 10 * FROM orders ORDER BY created_at DESC;",
        "",
        "-- Pagination with OFFSET-FETCH (SQL Server 2012+):",
        "SELECT * FROM orders",
        "ORDER BY created_at DESC",
        "OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY;",
        "",
        "-- ISNULL (like COALESCE, but only 2 args, SQL Server specific):",
        "SELECT ISNULL(phone, 'No phone') FROM customers;",
        "",
        "-- IIF — inline if (SQL Server 2012+):",
        "SELECT IIF(total > 1000, 'High Value', 'Standard') AS category",
        "FROM orders;",
        "",
        "-- MERGE statement (UPSERT):",
        "MERGE INTO inventory AS target",
        "USING (SELECT @productId AS product_id, @qty AS qty) AS source",
        "ON target.product_id = source.product_id",
        "WHEN MATCHED THEN",
        "    UPDATE SET target.stock = target.stock + source.qty",
        "WHEN NOT MATCHED THEN",
        "    INSERT (product_id, stock) VALUES (source.product_id, source.qty);",
        "",
        "-- Common Table Expression (CTE) — readable recursive/complex queries:",
        "WITH RecentOrders AS (",
        "    SELECT customer_id, COUNT(*) AS order_count, SUM(total) AS total_spent",
        "    FROM orders",
        "    WHERE created_at > DATEADD(MONTH, -3, GETDATE())",
        "    GROUP BY customer_id",
        ")",
        "SELECT c.name, ro.order_count, ro.total_spent",
        "FROM RecentOrders ro",
        "JOIN customers c ON c.id = ro.customer_id",
        "WHERE ro.total_spent > 10000",
        "ORDER BY ro.total_spent DESC;",
      ]},
      {t:"heading", v:"Stored Procedures in T-SQL"},
      {t:"code", lang:"sql", v:[
        "CREATE PROCEDURE GetCustomerOrderSummary",
        "    @CustomerId INT,",
        "    @FromDate DATETIME2 = NULL",
        "AS",
        "BEGIN",
        "    SET NOCOUNT ON;  -- Suppress row count messages (performance)",
        "",
        "    IF @FromDate IS NULL",
        "        SET @FromDate = DATEADD(YEAR, -1, GETDATE());",
        "",
        "    SELECT",
        "        o.id,",
        "        o.status,",
        "        o.total,",
        "        o.created_at",
        "    FROM orders o",
        "    WHERE o.customer_id = @CustomerId",
        "      AND o.created_at >= @FromDate",
        "    ORDER BY o.created_at DESC;",
        "",
        "    -- Multiple result sets are supported:",
        "    SELECT COUNT(*) AS TotalOrders, SUM(total) AS TotalSpent",
        "    FROM orders",
        "    WHERE customer_id = @CustomerId AND created_at >= @FromDate;",
        "END;",
        "",
        "-- Calling from Java (JDBC):",
        "-- CallableStatement cs = conn.prepareCall(",
        "--     \"{call GetCustomerOrderSummary(?, ?)}\");",
        "-- cs.setInt(1, customerId);",
        "-- cs.setTimestamp(2, fromDate);",
        "-- ResultSet rs = cs.executeQuery();",
        "",
        "-- Spring Data JPA native call:",
        "@Query(value = \"EXEC GetCustomerOrderSummary :customerId, :fromDate\",",
        "       nativeQuery = true)",
        "List<Object[]> getOrderSummary(@Param(\"customerId\") Long customerId,",
        "                                @Param(\"fromDate\") LocalDateTime fromDate);",
      ]},
      {t:"heading", v:"SQL Server Performance — Execution Plans & Indexes"},
      {t:"code", lang:"sql", v:[
        "-- View execution plan:",
        "SET STATISTICS IO ON;",
        "SET STATISTICS TIME ON;",
        "SELECT * FROM orders WHERE customer_id = 123;",
        "-- Output shows: logical reads, physical reads, CPU time, elapsed time",
        "",
        "-- Or use graphical execution plan in SSMS:",
        "-- Ctrl+M then run query — shows visual query plan tree",
        "",
        "-- Covering index (INCLUDE columns):",
        "CREATE NONCLUSTERED INDEX idx_orders_customer",
        "    ON orders(customer_id)",
        "    INCLUDE (status, total, created_at);",
        "",
        "-- Filtered index — index only relevant rows:",
        "CREATE NONCLUSTERED INDEX idx_pending_orders",
        "    ON orders(customer_id, created_at)",
        "    WHERE status = 'PENDING';",
        "-- Much smaller index, faster for this specific common query",
        "",
        "-- Update statistics:",
        "UPDATE STATISTICS orders;",
        "",
        "-- Rebuild fragmented index:",
        "ALTER INDEX idx_orders_customer ON orders REBUILD;",
        "",
        "-- Find missing index suggestions (SQL Server tracks this!):",
        "SELECT * FROM sys.dm_db_missing_index_details",
        "ORDER BY migs.avg_total_user_cost * migs.avg_user_impact DESC;",
      ]},
    ]
  },
);
