export const interviewData = {
  id: "interview", icon: "🎯", title: "Interview Q&A", color: "#a855f7", accent: "#c084fc",
  topics: [
    {
      title: "Core Java — Top Interview Questions", level: "Intermediate",
      blocks: [
        {t:"text", v:"These are the most commonly asked Core Java interview questions at companies like Amazon, Google, Flipkart, and Infosys — with detailed answers and follow-up cross questions you must be ready for."},
        {t:"heading", v:"Q1: What is the difference between == and .equals() in Java?"},
        {t:"code", lang:"java", v:[
          "// ANSWER:",
          "// == compares REFERENCES (memory addresses) for objects",
          "// == compares VALUES for primitives",
          "// .equals() compares CONTENT (what the object represents)",
          "",
          "String s1 = new String(\"hello\");",
          "String s2 = new String(\"hello\");",
          "",
          "s1 == s2;       // false — different objects in heap",
          "s1.equals(s2);  // true  — same content",
          "",
          "// String Pool exception:",
          "String s3 = \"hello\";  // Goes into String Pool",
          "String s4 = \"hello\";  // Reuses same Pool object",
          "s3 == s4;             // true — same object!",
          "",
          "// Primitives:",
          "int a = 5, b = 5;",
          "a == b; // true — same value",
        ]},
        {t:"note", v:"Cross Question: 'If you override equals(), what else must you override and why?' → Must override hashCode(). Contract: if a.equals(b) then a.hashCode() == b.hashCode(). HashMap uses hashCode() to find the bucket — if you break this, objects can't be found in maps."},
        {t:"heading", v:"Q2: What is the difference between HashMap, LinkedHashMap, and TreeMap?"},
        {t:"table", v:[
          ["Feature","HashMap","LinkedHashMap","TreeMap"],
          ["Order","No order","Insertion order","Sorted by key"],
          ["Performance","O(1)","O(1)","O(log n)"],
          ["Null keys","1 null key allowed","1 null key allowed","No null keys"],
          ["Thread safe","No","No","No"],
          ["Use case","Default, fastest","Ordered iteration, LRU cache","Sorted data, range queries"],
        ]},
        {t:"note", v:"Cross Question: 'How would you implement an LRU cache using Java collections?' → Use LinkedHashMap with removeEldestEntry() overridden, or Collections.synchronizedMap() for thread safety."},
        {t:"heading", v:"Q3: Explain Java Memory Model — Stack vs Heap"},
        {t:"code", lang:"java", v:[
          "// STACK: method call frames + local variables + references",
          "// Each THREAD has its own stack",
          "// Auto-managed: frame pushed on method call, popped on return",
          "// Fast access, limited size (StackOverflowError if exceeded)",
          "",
          "// HEAP: all objects created with 'new'",
          "// SHARED across all threads (concurrency issues here!)",
          "// Managed by Garbage Collector",
          "// Larger but slower than stack",
          "",
          "public void example() {",
          "    int x = 10;          // x on STACK",
          "    String s = \"hello\";  // s (reference) on STACK, object on HEAP",
          "    User user = new User(); // user (reference) on STACK, User on HEAP",
          "}",
          "// When example() returns: x, s, user references removed from stack",
          "// User object on heap → eligible for GC (no more references)",
        ]},
        {t:"note", v:"Cross Question: 'What causes a memory leak in Java?' → Holding references to objects you no longer need: static collections that grow forever, unclosed streams/connections, event listeners not removed, ThreadLocal values not cleaned up."},
        {t:"heading", v:"Q4: What is the difference between Checked and Unchecked Exceptions?"},
        {t:"code", lang:"java", v:[
          "// CHECKED: Extend Exception (not RuntimeException)",
          "// Compiler FORCES you to handle or declare them",
          "// Signal recoverable external conditions: file not found, network error",
          "// Examples: IOException, SQLException, FileNotFoundException",
          "",
          "public void readFile(String path) throws IOException { // Must declare",
          "    FileReader reader = new FileReader(path); // Compile error if not handled",
          "}",
          "",
          "// UNCHECKED: Extend RuntimeException",
          "// Compiler does NOT force handling",
          "// Signal programming bugs: wrong arguments, null access",
          "// Examples: NullPointerException, IllegalArgumentException",
          "",
          "public int divide(int a, int b) {",
          "    if (b == 0) throw new IllegalArgumentException(\"b cannot be zero\");",
          "    return a / b; // ArithmeticException if b=0 — unchecked",
          "}",
          "",
          "// Modern Spring Boot practice: use only Unchecked exceptions",
          "// Wrap checked exceptions in unchecked for cleaner APIs",
        ]},
        {t:"note", v:"Cross Question: 'When would you choose checked over unchecked exceptions?' → Checked when the caller CAN and SHOULD recover (e.g. file not found — user can retry with different path). Unchecked when it's a programming error the caller shouldn't be forced to handle."},
        {t:"heading", v:"Q5: What is the Java String Pool and why does it exist?"},
        {t:"code", lang:"java", v:[
          "// String Pool (intern pool) is a special memory area in the Heap",
          "// (stored in Metaspace since Java 8)",
          "",
          "// When you write a String literal, JVM checks the pool first:",
          "String s1 = \"hello\";  // Creates 'hello' in pool",
          "String s2 = \"hello\";  // REUSES existing 'hello' — no new object",
          "s1 == s2;             // true (same pool object)",
          "",
          "// new String() bypasses the pool:",
          "String s3 = new String(\"hello\");  // New object in heap",
          "String s4 = new String(\"hello\");  // Another new object",
          "s3 == s4;                          // false (different objects)",
          "",
          "// intern() forces a string into the pool:",
          "String s5 = s3.intern();   // Returns the pooled version",
          "s5 == s1;                  // true",
          "",
          "// Why it exists: Memory optimization.",
          "// If the same string literal appears 1000 times in code,",
          "// only ONE object is created instead of 1000.",
        ]},
      ]
    },
    {
      title: "Spring Boot — Interview Questions", level: "Intermediate",
      blocks: [
        {t:"text", v:"Spring Boot is asked in almost every Java backend interview. These questions cover the concepts that differentiate candidates who just use Spring from those who understand it."},
        {t:"heading", v:"Q1: How does Spring Boot Auto-Configuration work?"},
        {t:"code", lang:"java", v:[
          "// ANSWER: Auto-configuration = 'smart defaults based on your classpath'",
          "",
          "// 1. @SpringBootApplication includes @EnableAutoConfiguration",
          "// 2. Spring Boot reads: META-INF/spring/AutoConfiguration.imports",
          "//    (previously: META-INF/spring.factories)",
          "// 3. ~150 AutoConfiguration classes are evaluated",
          "// 4. Each uses @ConditionalOn* to decide if it should activate:",
          "",
          "@Configuration",
          "@ConditionalOnClass(DataSource.class)        // Only if JDBC on classpath",
          "@ConditionalOnMissingBean(DataSource.class)  // Only if you haven't defined one",
          "@ConditionalOnProperty(\"spring.datasource.url\") // Only if URL is set",
          "public class DataSourceAutoConfiguration {",
          "    // Creates DataSource, HikariPool, JdbcTemplate automatically",
          "}",
          "",
          "// Debug with: java -jar app.jar --debug",
          "// Shows 'CONDITIONS EVALUATION REPORT'",
        ]},
        {t:"note", v:"Cross Question: 'How do you disable a specific auto-configuration?' → @SpringBootApplication(exclude = {DataSourceAutoConfiguration.class}) or spring.autoconfigure.exclude property. Also: 'How do you create your own auto-configuration?' → Create a @Configuration class with @ConditionalOn* and register in META-INF/spring/AutoConfiguration.imports."},
        {t:"heading", v:"Q2: What is the difference between @Component, @Service, @Repository, @Controller?"},
        {t:"code", lang:"java", v:[
          "// ALL four are specializations of @Component.",
          "// Functionally identical — they all register a bean with Spring.",
          "// The difference is SEMANTIC — they communicate intent.",
          "",
          "@Component    // Generic Spring-managed bean",
          "@Service      // Business logic layer — signals 'service layer'",
          "@Repository   // Data access layer — ALSO enables JPA exception translation:",
          "              // Raw DataAccessException → Spring DataAccessException",
          "@Controller   // MVC presentation layer",
          "@RestController // @Controller + @ResponseBody (for REST APIs)",
          "",
          "// Best practice: Use the most specific annotation:",
          "// - Business logic → @Service",
          "// - Database access → @Repository",
          "// - REST API → @RestController",
          "// - Utilities/helpers → @Component",
        ]},
        {t:"note", v:"Cross Question: 'Can a @Service call another @Service directly?' → Yes, Spring injects them via DI. But be careful about circular dependencies. 'What is @Primary and @Qualifier?' → When multiple beans of same type exist, @Primary marks the default. @Qualifier('beanName') picks a specific one."},
        {t:"heading", v:"Q3: Explain Spring Bean Lifecycle"},
        {t:"code", lang:"text", v:[
          "Spring Bean Lifecycle (in order):",
          "",
          "1. Spring reads class definitions and creates bean definitions",
          "2. BeanFactoryPostProcessors run (modify bean definitions)",
          "3. Bean INSTANTIATION: Spring calls constructor",
          "4. DEPENDENCY INJECTION: Spring sets @Autowired fields/setters",
          "5. BeanPostProcessor.postProcessBeforeInitialization() runs",
          "6. @PostConstruct method runs (your initialization code here)",
          "7. InitializingBean.afterPropertiesSet() runs (if implemented)",
          "8. Custom init-method runs (if configured)",
          "9. BeanPostProcessor.postProcessAfterInitialization() runs",
          "   ← AOP proxies created here (for @Transactional, etc.)",
          "10. BEAN IS READY — used by your application",
          "",
          "On shutdown:",
          "11. @PreDestroy method runs",
          "12. DisposableBean.destroy() runs",
          "13. Custom destroy-method runs",
        ]},
        {t:"note", v:"Cross Question: 'What is the difference between @PostConstruct and constructor?' → Constructor runs before DI (dependencies not yet set). @PostConstruct runs after DI — so you can use injected services. 'When would you use @PreDestroy?' → Close connections, flush caches, release resources."},
        {t:"heading", v:"Q4: What is @Transactional and how does it work internally?"},
        {t:"code", lang:"java", v:[
          "// ANSWER: @Transactional uses AOP (Aspect Oriented Programming)",
          "// Spring creates a PROXY around your class.",
          "// The proxy intercepts method calls and manages the transaction.",
          "",
          "// What Spring does internally:",
          "// 1. Begin transaction (or join existing)",
          "// 2. Call your actual method",
          "// 3a. If no exception: COMMIT",
          "// 3b. If RuntimeException: ROLLBACK",
          "// 3c. If checked exception: COMMIT (by default — often surprising!)",
          "",
          "// To rollback on checked exceptions:",
          "@Transactional(rollbackFor = Exception.class)",
          "",
          "// Self-invocation problem — the most common @Transactional bug:",
          "@Service",
          "public class OrderService {",
          "    @Transactional",
          "    public void createOrder() { ... }",
          "",
          "    public void processOrders() {",
          "        createOrder(); // WRONG! Calls 'this' directly, bypasses proxy",
          "        // @Transactional has NO effect here!",
          "    }",
          "}",
          "// Fix: Inject OrderService into itself, or use ApplicationContext.getBean()",
        ]},
        {t:"note", v:"Cross Question: 'What are transaction propagation levels?' → REQUIRED (default, join or create), REQUIRES_NEW (always new, suspends current), SUPPORTS (joins if exists), NEVER (throws if exists), MANDATORY (must have existing). Cross Question: 'What is optimistic vs pessimistic locking?' → Optimistic (@Version field): assumes no conflict, fails at commit if row changed. Pessimistic (SELECT FOR UPDATE): locks row immediately, blocks other transactions."},
        {t:"heading", v:"Q5: How does Spring handle the N+1 Query Problem?"},
        {t:"code", lang:"java", v:[
          "// N+1: Load 100 orders → 100 separate queries to load each customer",
          "// Root cause: LAZY fetching — customer loaded on access, not with order",
          "",
          "// Solutions:",
          "",
          "// 1. JOIN FETCH — One query with JOIN",
          "@Query(\"SELECT o FROM Order o JOIN FETCH o.customer WHERE o.status = :s\")",
          "List<Order> findWithCustomer(@Param(\"s\") OrderStatus s);",
          "",
          "// 2. @EntityGraph — declarative, no JPQL needed",
          "@EntityGraph(attributePaths = {\"customer\", \"items\"})",
          "List<Order> findByStatus(OrderStatus status);",
          "",
          "// 3. @BatchSize — load related entities in batches (not N queries, but N/batch)",
          "@BatchSize(size = 20)",
          "@OneToMany(mappedBy = \"order\")",
          "private List<OrderItem> items;",
          "",
          "// 4. Projection — only fetch columns you need",
          "// 'How do you detect N+1 in production?'",
          "// spring.jpa.show-sql=true  → count the SELECT statements",
          "// Or use Hibernate Statistics / p6spy / datasource-proxy",
        ]},
      ]
    },
    {
      title: "Microservices — Interview Questions", level: "Advanced",
      blocks: [
        {t:"text", v:"Microservices questions test whether you understand distributed systems trade-offs — not just the happy path. These are asked at senior developer and architect level interviews."},
        {t:"heading", v:"Q1: How do you handle distributed transactions in microservices?"},
        {t:"code", lang:"text", v:[
          "ANSWER: You cannot use ACID transactions across multiple services",
          "(different databases, no shared transaction).",
          "",
          "Options:",
          "",
          "1. SAGA PATTERN (most common):",
          "   - Break transaction into local transactions",
          "   - Each step has a compensating action (undo)",
          "   - If step N fails: execute compensations for steps N-1, N-2...",
          "   - Choreography: services react to events",
          "   - Orchestration: central coordinator drives the flow",
          "",
          "2. OUTBOX PATTERN (for guaranteed event publishing):",
          "   - Write event to outbox table in SAME DB transaction as data",
          "   - Relay process reads outbox and publishes to Kafka",
          "   - Ensures: DB change and event publishing are atomic",
          "",
          "3. TWO-PHASE COMMIT (2PC) — avoid if possible:",
          "   - Phase 1: Ask all services to prepare",
          "   - Phase 2: If all prepared, commit; else rollback",
          "   - Problem: blocks resources, single point of failure (coordinator)",
          "   - Only use within a single database/bounded context",
          "",
          "4. EVENTUAL CONSISTENCY:",
          "   - Accept that different services will be temporarily inconsistent",
          "   - Use events to converge to consistent state eventually",
          "   - Right choice for most microservice interactions",
        ]},
        {t:"note", v:"Cross Question: 'What happens if a Saga compensation itself fails?' → This is a critical scenario. Options: retry compensation with exponential backoff, alert a human operator, store in a dead-letter queue for manual review, implement the compensation as idempotent (safe to retry multiple times)."},
        {t:"heading", v:"Q2: How does a Circuit Breaker differ from a Retry?"},
        {t:"table", v:[
          ["Aspect","Retry","Circuit Breaker"],
          ["Purpose","Handle transient failures","Prevent cascading failures"],
          ["When to use","Temporary unavailability","Service consistently failing"],
          ["Behaviour","Retry N times with backoff","OPEN = fast-fail without calling"],
          ["Effect on downstream","Increases load with retries","Reduces load — stops calling"],
          ["Recovery","Automatic on success","HALF-OPEN probes then CLOSED"],
          ["Best for","Network blips, timeouts","Dead/overloaded services"],
        ]},
        {t:"note", v:"Cross Question: 'Can you use both together?' → Yes, and you should. Order matters: Circuit Breaker wraps Retry. If retry exhausted → circuit breaker records failure. If circuit open → don't even retry. Cross Question: 'What is a Bulkhead?' → Limits concurrent calls to a service. If payment-service is slow, bulkhead limits threads waiting for it — preventing them from starving other services."},
        {t:"heading", v:"Q3: How do you ensure exactly-once message processing in Kafka?"},
        {t:"code", lang:"java", v:[
          "// ANSWER: Kafka guarantees 'at-least-once' delivery by default.",
          "// Exactly-once requires IDEMPOTENT CONSUMERS.",
          "",
          "// Problem: Consumer processes message, crashes before committing offset",
          "// → Restarted consumer reprocesses the same message",
          "// → Double inventory deduction, double charge!",
          "",
          "// Solution: Idempotency check before processing",
          "@KafkaListener(topics = \"order.placed\", groupId = \"inventory-service\")",
          "public void handleOrderPlaced(OrderPlacedEvent event) {",
          "    // Check if already processed (using event ID as idempotency key):",
          "    if (processedEventsRepo.existsById(event.getEventId())) {",
          "        log.info(\"Event {} already processed, skipping\", event.getEventId());",
          "        return;",
          "    }",
          "",
          "    // Process in one transaction with idempotency record:",
          "    processedEventsRepo.save(new ProcessedEvent(event.getEventId()));",
          "    inventoryService.reserve(event.getItems());",
          "}",
          "",
          "// Producer-side idempotency (prevent duplicate sends):",
          "// enable.idempotence=true in producer config",
          "// Spring Kafka transactions: produces exactly-once to Kafka",
        ]},
        {t:"note", v:"Cross Question: 'What is the difference between at-most-once, at-least-once, and exactly-once?' → At-most-once: fire and forget, may lose messages. At-least-once: retry until ack, may duplicate. Exactly-once: guaranteed no loss and no duplicates — requires idempotent consumers or Kafka transactions."},
        {t:"heading", v:"Q4: How do you handle service discovery in Kubernetes vs Eureka?"},
        {t:"code", lang:"text", v:[
          "EUREKA (Spring Cloud):",
          "  Services register themselves: 'I am ORDER-SERVICE at 10.0.1.5:8080'",
          "  Clients query Eureka: 'Where is PAYMENT-SERVICE?'",
          "  Eureka returns: '10.0.1.8:8080 or 10.0.1.9:8080'",
          "  Load balancing: client-side (Ribbon/Spring LB)",
          "  Best for: non-containerized Spring Boot apps",
          "",
          "KUBERNETES DNS:",
          "  Each K8s Service gets a stable DNS name: payment-service.default.svc.cluster.local",
          "  No registration needed — K8s does it automatically",
          "  Load balancing: kube-proxy / iptables (server-side)",
          "  Just use: http://payment-service/api/v1/payments",
          "  Best for: containerized microservices on Kubernetes",
          "",
          "In Kubernetes: you DON'T need Eureka.",
          "K8s provides service discovery + load balancing natively.",
          "Eureka is redundant overhead in a K8s environment.",
        ]},
        {t:"heading", v:"Q5: What is the difference between Choreography and Orchestration Saga?"},
        {t:"table", v:[
          ["Aspect","Choreography","Orchestration"],
          ["Control","Distributed (each service decides)","Central orchestrator"],
          ["Coupling","Services only know about events","Services know the orchestrator"],
          ["Traceability","Hard to follow the flow","Easy to see in one place"],
          ["Failure handling","Each service handles its own","Orchestrator manages compensations"],
          ["Complexity","Simple services, complex system","Complex coordinator, simple services"],
          ["Best for","Simple linear flows","Complex branching flows"],
          ["Tools","Kafka events","Spring State Machine, Temporal, Camunda"],
        ]},
        {t:"note", v:"Cross Question: 'How do you monitor a distributed transaction across services?' → Distributed tracing with Micrometer Tracing (Zipkin/Jaeger). Every service propagates the same traceId in headers. You can see the full call chain with timing for each step in a single trace view."},
      ]
    },
    {
      title: "React & Frontend — Interview Questions", level: "Intermediate",
      blocks: [
        {t:"text", v:"Frontend interviews at product companies are increasingly deep. These questions go beyond 'what is useState' to test your understanding of React's rendering model and performance."},
        {t:"heading", v:"Q1: What is the Virtual DOM and how does React's reconciliation work?"},
        {t:"code", lang:"text", v:[
          "ANSWER:",
          "Virtual DOM: A lightweight JavaScript object tree that mirrors the real DOM.",
          "",
          "Process on state change:",
          "1. React creates a new Virtual DOM tree",
          "2. DIFFING: Compares new tree with previous tree (O(n) algorithm)",
          "3. RECONCILIATION: Computes minimal set of real DOM changes",
          "4. COMMIT: Applies only those changes to the real DOM",
          "",
          "Why keys matter in lists:",
          "- Without key: React diffs by position — reorders destroy/recreate elements",
          "- With stable key: React identifies element by ID — reorders via move operations",
          "- Never use array index as key — causes bugs when items are inserted/deleted",
          "",
          "React 18 Concurrent Features:",
          "- Rendering is now interruptible",
          "- React can pause rendering to handle urgent updates (e.g. user input)",
          "- Automatic batching: multiple setState calls batched into one render",
        ]},
        {t:"note", v:"Cross Question: 'What is React Fiber?' → The reconciliation algorithm rewritten in React 16. Fiber breaks rendering work into units that can be paused, aborted, or reused. Enables concurrent features, time-slicing, and Suspense. Cross Question: 'What is the difference between React 17 and React 18?' → React 18 adds: automatic batching, concurrent rendering, Suspense for data fetching, useTransition, useDeferredValue."},
        {t:"heading", v:"Q2: Explain the difference between useMemo and useCallback"},
        {t:"code", lang:"jsx", v:[
          "// useMemo: memoizes a COMPUTED VALUE",
          "// Returns the cached value if dependencies unchanged",
          "const sortedOrders = useMemo(() => {",
          "  return orders.sort((a, b) => b.total - a.total);  // Expensive sort",
          "}, [orders]);  // Re-compute only when orders changes",
          "",
          "// useCallback: memoizes a FUNCTION REFERENCE",
          "// Returns the same function instance if dependencies unchanged",
          "const handleDelete = useCallback((id) => {",
          "  deleteOrder(id);",
          "}, []);  // Same function reference on every render",
          "",
          "// WHY IT MATTERS:",
          "// Without useCallback: every parent render creates a NEW function",
          "// → Child with React.memo receives new prop reference",
          "// → Child re-renders unnecessarily",
          "",
          "// With useCallback: same reference",
          "// → React.memo sees no change",
          "// → Child skips re-render",
          "",
          "// RULE: useMemo for expensive computations",
          "//       useCallback for stable function references to memoized children",
          "//       Don't over-optimize — profile first with React DevTools",
        ]},
        {t:"note", v:"Cross Question: 'What is the difference between useEffect and useLayoutEffect?' → useEffect: runs after browser paint (non-blocking, default choice). useLayoutEffect: runs synchronously after DOM mutations but before paint (use for measuring DOM, preventing visual flicker). Cross Question: 'When would you NOT use useEffect?' → If the computation can happen during render (no side effects), use useMemo instead. useEffect is for side effects only."},
        {t:"heading", v:"Q3: How does React Context differ from Redux?"},
        {t:"table", v:[
          ["Aspect","React Context","Redux / Redux Toolkit"],
          ["Purpose","Avoid prop drilling","Predictable state container"],
          ["Re-renders","ALL consumers re-render on change","Only connected components"],
          ["DevTools","Limited","Excellent (time-travel debugging)"],
          ["Middleware","No","Yes (thunk, saga, logger)"],
          ["Async handling","Manual (useEffect)","createAsyncThunk built-in"],
          ["Boilerplate","Low","Medium (RTK reduces this)"],
          ["Best for","Theme, locale, auth user","Complex global state, large apps"],
        ]},
        {t:"note", v:"Cross Question: 'When would you choose React Query over Redux?' → React Query for SERVER state (data from APIs, caching, refetching). Redux for CLIENT state (UI, user preferences, cart). They complement each other — use both. Cross Question: 'What is Zustand and when would you use it?' → Lightweight state management, much less boilerplate than Redux. Good for medium-complexity apps that outgrow Context but don't need Redux's full power."},
      ]
    },
    {
      title: "System Design — Full Stack Questions", level: "Advanced",
      blocks: [
        {t:"text", v:"System design questions test your ability to think holistically — from frontend to backend to database to deployment. These are asked at senior and lead engineer interviews."},
        {t:"heading", v:"Q1: Design a real-time order tracking system"},
        {t:"code", lang:"text", v:[
          "REQUIREMENTS:",
          "  - Customer can see live order status updates",
          "  - Driver location updates every 5 seconds",
          "  - Support 100,000 concurrent active orders",
          "",
          "DESIGN:",
          "",
          "Frontend (React):",
          "  WebSocket connection to order-tracking-service",
          "  Display live map with driver location",
          "  Status timeline: Confirmed → Preparing → Picked Up → Delivered",
          "",
          "Backend Services:",
          "  order-service: Manages order lifecycle, stores in PostgreSQL",
          "  tracking-service: WebSocket server (Spring WebSocket / Socket.IO)",
          "  driver-service: Receives GPS updates from driver app",
          "",
          "Real-time flow:",
          "  1. Driver app → POST /api/location { driverId, lat, lng }",
          "  2. driver-service → publishes to Kafka topic 'driver.location'",
          "  3. tracking-service → consumes Kafka, pushes to WebSocket subscribers",
          "  4. React frontend → receives WebSocket message, updates map",
          "",
          "Scaling for 100k concurrent orders:",
          "  - tracking-service: horizontal scale behind load balancer",
          "  - Sticky sessions (same user → same server) for WebSocket",
          "  - Or: Redis Pub/Sub between tracking-service instances",
          "  - Kafka: 100 partitions for driver.location topic",
          "  - PostgreSQL: Read replicas for order status queries",
        ]},
        {t:"heading", v:"Q2: Design the authentication system for a microservices platform"},
        {t:"code", lang:"text", v:[
          "COMPONENTS:",
          "",
          "1. auth-service (dedicated authentication service):",
          "   - POST /auth/login  → validates credentials, issues JWT + refresh token",
          "   - POST /auth/refresh → validates refresh token, issues new JWT",
          "   - POST /auth/logout → invalidates refresh token",
          "   - POST /auth/register → creates user account",
          "",
          "2. API Gateway (first point of contact):",
          "   - Validates JWT signature on every request",
          "   - Rejects invalid/expired tokens (401)",
          "   - Passes userId + roles in forwarded request headers",
          "   - Rate limiting per userId",
          "",
          "3. Downstream microservices:",
          "   - Trust the userId header from gateway (don't re-validate JWT)",
          "   - Use @PreAuthorize for fine-grained authorization",
          "",
          "JWT Design:",
          "   Header: { alg: RS256 }  ← Use RS256 (asymmetric) not HS256",
          "   Payload: { sub: userId, roles: ['USER'], exp: ..., iat: ... }",
          "   Signed with: private key (auth-service only)",
          "   Verified with: public key (all services can verify)",
          "",
          "Token TTLs:",
          "   JWT access token:  15 minutes (short — minimize exposure)",
          "   Refresh token:     7 days (stored in DB, can be revoked)",
          "",
          "Cross Question: How do you handle token revocation?",
          "   JWT is stateless — you can't invalidate it before expiry.",
          "   Solutions:",
          "   1. Short expiry (15 min) — token expires quickly",
          "   2. Token blacklist in Redis — check on each request (defeats stateless benefit)",
          "   3. Refresh token rotation — revoke refresh token on logout",
        ]},
        {t:"heading", v:"Q3: How would you migrate a monolith to microservices?"},
        {t:"code", lang:"text", v:[
          "ANSWER: Strangler Fig Pattern — incremental migration, never big bang",
          "",
          "Phase 1: Identify boundaries",
          "  - Analyse monolith: find high-cohesion, low-coupling modules",
          "  - Prioritise: which part scales differently? Which team owns it?",
          "  - Start with LOWEST RISK, HIGH VALUE service (e.g. notifications)",
          "",
          "Phase 2: Add an API Gateway in front of the monolith",
          "  - All traffic still goes to monolith via gateway",
          "  - Gateway is now ready to route to new services",
          "",
          "Phase 3: Extract first service (e.g. notification-service)",
          "  - Build new notification-service independently",
          "  - Route /api/notifications to new service in gateway",
          "  - Monolith calls new service via API or events",
          "  - Delete notification code from monolith",
          "",
          "Phase 4: Extract services one by one",
          "  - Follow same pattern: build → route → delete from monolith",
          "  - Database: each service gets its own schema/DB over time",
          "  - Use events (Kafka) to sync data between services",
          "",
          "Phase 5: Decommission monolith (if needed)",
          "",
          "Cross Questions:",
          "  'How do you handle the shared database during migration?'",
          "  → Temporary: services share DB but different schemas",
          "  → Long-term: each service owns its tables, sync via events",
          "",
          "  'How do you test a partially migrated system?'",
          "  → Contract testing (Pact) between services",
          "  → Integration tests on the API Gateway routing",
          "  → Feature flags to gradually shift traffic",
        ]},
      ]
    },
    {
      title: "Angular — Interview Questions", level: "Intermediate",
      blocks: [
        {t:"text", v:"Angular interviews at enterprise companies (banks, insurance, large IT firms) go deep on RxJS, change detection, and performance. Here are the most asked questions with cross questions."},
        {t:"heading", v:"Q1: What is the difference between Template-driven and Reactive Forms?"},
        {t:"table", v:[
          ["Aspect","Template-driven","Reactive"],
          ["Defined in","HTML template","Component TypeScript"],
          ["Validation","HTML attributes","Validator functions"],
          ["Testing","Hard (need DOM)","Easy (pure JS/TS)"],
          ["Dynamic fields","Difficult","Easy (FormArray)"],
          ["Complex logic","Hard","Easy (programmatic)"],
          ["NgModule","FormsModule","ReactiveFormsModule"],
          ["Best for","Simple forms","Complex/dynamic forms"],
        ]},
        {t:"note", v:"Cross Question: 'How do you create a custom validator in Reactive Forms?' → A function that takes AbstractControl and returns ValidationErrors | null. Cross Question: 'How do you create a cross-field validator (e.g. password match)?' → Validate at FormGroup level — access both fields from the group."},
        {t:"heading", v:"Q2: Explain Change Detection — Default vs OnPush"},
        {t:"code", lang:"typescript", v:[
          "// DEFAULT change detection:",
          "// Angular checks EVERY component on EVERY event:",
          "// Click, setTimeout, HTTP response, Promise resolution",
          "// For a large component tree: very expensive!",
          "",
          "// ONPUSH change detection:",
          "// Component only checked when:",
          "// 1. @Input() reference changes (new object, not mutation)",
          "// 2. An event originates IN this component (click, etc.)",
          "// 3. An Observable emits via async pipe",
          "// 4. ChangeDetectorRef.markForCheck() called manually",
          "",
          "@Component({",
          "  changeDetection: ChangeDetectionStrategy.OnPush",
          "})",
          "export class OrderRowComponent {",
          "  @Input() order!: Order;",
          "",
          "  // GOTCHA with OnPush:",
          "  updateStatus() {",
          "    this.order.status = 'SHIPPED';  // Mutation — no re-render!",
          "  }",
          "",
          "  // CORRECT: new object reference",
          "  updateStatus() {",
          "    // Parent must do: this.order = { ...this.order, status: 'SHIPPED' }",
          "    // Or use ChangeDetectorRef:",
          "    this.order.status = 'SHIPPED';",
          "    this.cdr.markForCheck();  // Tell Angular to check this component",
          "  }",
          "}",
        ]},
        {t:"note", v:"Cross Question: 'What is Zone.js and how does it relate to change detection?' → Zone.js monkey-patches browser async APIs (setTimeout, Promise, fetch, event listeners). When they complete, Zone.js notifies Angular to run change detection. Cross Question: 'What is zone-less Angular?' → Angular 17+ supports running without Zone.js using Signals for fine-grained reactivity — more efficient than zone-based detection."},
        {t:"heading", v:"Q3: What are Angular Signals (Angular 16+)?"},
        {t:"code", lang:"typescript", v:[
          "// Signals: fine-grained reactive primitives",
          "// Angular tracks dependencies automatically — no Zone.js needed",
          "",
          "import { signal, computed, effect } from '@angular/core';",
          "",
          "@Component({",
          "  template: `",
          "    <p>Count: {{ count() }}</p>",
          "    <p>Double: {{ doubled() }}</p>",
          "    <button (click)='increment()'>+</button>",
          "  `",
          "})",
          "export class CounterComponent {",
          "  // signal: writable reactive value",
          "  count = signal(0);",
          "",
          "  // computed: derived value — recalculates only when count changes",
          "  doubled = computed(() => this.count() * 2);",
          "",
          "  // effect: side effect when signal changes",
          "  constructor() {",
          "    effect(() => {",
          "      console.log('Count changed to:', this.count());",
          "    });",
          "  }",
          "",
          "  increment() {",
          "    this.count.update(c => c + 1);  // or this.count.set(newValue)",
          "  }",
          "}",
          "",
          "// Advantages over Zone.js + ChangeDetection:",
          "// - Only components that USE the signal re-render",
          "// - No need for OnPush or async pipe",
          "// - More predictable, easier to debug",
        ]},
        {t:"note", v:"Cross Question: 'How are Angular Signals similar to React hooks?' → Both track reactive state. React's useState re-renders the whole component. Angular Signals re-render only the parts of the template that USE that signal (more granular). Cross Question: 'Will Signals replace RxJS?' → No, they complement each other. Signals for component state, RxJS for streams and async event flows. Angular provides toSignal() and toObservable() for interop."},
      ]
    },
  ]
};
