export const angularData = {
  id: "angular", icon: "🅰️", title: "Angular", color: "#ef4444", accent: "#f87171",
  topics: [
    {
      title: "Angular Fundamentals — Architecture & Setup", level: "Beginner",
      blocks: [
        {t:"text", v:"Angular is a full-featured TypeScript framework by Google. Unlike React (a library), Angular is an opinionated framework with built-in solutions for routing, HTTP, forms, and dependency injection. It enforces structure — great for large enterprise teams."},
        {t:"heading", v:"Angular vs React — Key Differences"},
        {t:"table", v:[
          ["Aspect","Angular","React"],
          ["Type","Full Framework","UI Library"],
          ["Language","TypeScript (required)","JavaScript/TypeScript"],
          ["Data binding","Two-way binding","One-way data flow"],
          ["DI System","Built-in, powerful","Context API / external libs"],
          ["Forms","Reactive + Template Forms","Controlled components"],
          ["Learning curve","Steeper (more concepts)","Gentler (just JS)"],
          ["Best for","Large enterprise apps","Flexible, varied app sizes"],
        ]},
        {t:"heading", v:"Angular Building Blocks"},
        {t:"code", lang:"text", v:[
          "Angular App Structure:",
          "",
          "  AppModule (root module)",
          "  ├── Components  — UI + logic (like React components)",
          "  ├── Services    — Business logic, HTTP calls (injectable)",
          "  ├── Directives  — Extend HTML elements (*ngIf, *ngFor, custom)",
          "  ├── Pipes       — Transform displayed data (date, currency, custom)",
          "  └── Modules     — Group related features (lazy-loaded)",
          "",
          "  Component = Template (HTML) + Class (TS) + Styles (CSS)",
          "",
          "  Dependency Injection: Angular creates services once (singleton)",
          "  and injects them wherever declared in constructor.",
        ]},
        {t:"heading", v:"Your First Component"},
        {t:"code", lang:"typescript", v:[
          "// order-card.component.ts",
          "import { Component, Input, Output, EventEmitter, OnInit } from '@angular/core';",
          "import { Order } from './order.model';",
          "",
          "@Component({",
          "  selector: 'app-order-card',     // Use as <app-order-card> in templates",
          "  templateUrl: './order-card.component.html',",
          "  styleUrls: ['./order-card.component.scss'],",
          "  // standalone: true   // Angular 17+ standalone (no NgModule needed)",
          "})",
          "export class OrderCardComponent implements OnInit {",
          "  // @Input: receive data from parent",
          "  @Input() order!: Order;",
          "  @Input() showDetails = false;",
          "",
          "  // @Output: emit events to parent",
          "  @Output() orderCancelled = new EventEmitter<string>();",
          "  @Output() orderSelected  = new EventEmitter<Order>();",
          "",
          "  isExpanded = false;",
          "  formattedTotal = '';",
          "",
          "  ngOnInit(): void {",
          "    // Lifecycle hook: runs once after component initializes",
          "    this.formattedTotal = this.formatCurrency(this.order.total);",
          "  }",
          "",
          "  cancelOrder(): void {",
          "    this.orderCancelled.emit(this.order.id);  // Emit event to parent",
          "  }",
          "",
          "  selectOrder(): void {",
          "    this.orderSelected.emit(this.order);",
          "  }",
          "",
          "  private formatCurrency(amount: number): string {",
          "    return new Intl.NumberFormat('en-IN', {",
          "      style: 'currency', currency: 'INR'",
          "    }).format(amount);",
          "  }",
          "}",
        ]},
        {t:"heading", v:"Component Template"},
        {t:"code", lang:"html", v:[
          "<!-- order-card.component.html -->",
          "<div class='order-card' [class.expanded]='isExpanded'>",
          "",
          "  <!-- Property binding: [property]='expression' -->",
          "  <h3>Order #{{ order.id }}</h3>",
          "",
          "  <!-- Structural directive: *ngIf -->",
          "  <span *ngIf='order.status === \"URGENT\"' class='badge urgent'>URGENT</span>",
          "",
          "  <!-- ngSwitch -->",
          "  <div [ngSwitch]='order.status'>",
          "    <span *ngSwitchCase='\"PENDING\"' class='status pending'>Pending</span>",
          "    <span *ngSwitchCase='\"SHIPPED\"' class='status shipped'>Shipped</span>",
          "    <span *ngSwitchDefault class='status'>{{ order.status }}</span>",
          "  </div>",
          "",
          "  <!-- *ngFor: render lists -->",
          "  <ul *ngIf='showDetails'>",
          "    <li *ngFor='let item of order.items; let i = index; trackBy: trackById'>",
          "      {{ i + 1 }}. {{ item.name }} x {{ item.qty }}",
          "    </li>",
          "  </ul>",
          "",
          "  <p class='total'>{{ formattedTotal }}</p>",
          "",
          "  <!-- Event binding: (event)='handler()' -->",
          "  <button (click)='cancelOrder()'>Cancel</button>",
          "  <button (click)='isExpanded = !isExpanded'>",
          "    {{ isExpanded ? 'Collapse' : 'Expand' }}",
          "  </button>",
          "</div>",
        ]},
      ]
    },
    {
      title: "Services & Dependency Injection", level: "Beginner",
      blocks: [
        {t:"text", v:"Services are where your business logic and HTTP calls live. Angular's DI system creates services as singletons and injects them into components and other services automatically — similar to Spring's @Service and constructor injection."},
        {t:"heading", v:"Creating a Service"},
        {t:"code", lang:"typescript", v:[
          "// order.service.ts",
          "import { Injectable } from '@angular/core';",
          "import { HttpClient, HttpParams } from '@angular/common/http';",
          "import { Observable, throwError } from 'rxjs';",
          "import { catchError, map, tap } from 'rxjs/operators';",
          "",
          "// providedIn: 'root' = singleton available everywhere in the app",
          "@Injectable({ providedIn: 'root' })",
          "export class OrderService {",
          "  private readonly API_URL = '/api/v1/orders';",
          "",
          "  constructor(private http: HttpClient) {}",
          "",
          "  // Returns Observable — Angular's async primitive (like a Promise but cancellable)",
          "  getOrders(status?: string, page = 0): Observable<PagedOrders> {",
          "    let params = new HttpParams()",
          "      .set('page', page.toString())",
          "      .set('size', '20');",
          "",
          "    if (status) params = params.set('status', status);",
          "",
          "    return this.http.get<PagedOrders>(this.API_URL, { params }).pipe(",
          "      tap(data => console.log('Fetched:', data.totalElements, 'orders')),",
          "      catchError(this.handleError)",
          "    );",
          "  }",
          "",
          "  getById(id: string): Observable<Order> {",
          "    return this.http.get<Order>(`${this.API_URL}/${id}`).pipe(",
          "      catchError(this.handleError)",
          "    );",
          "  }",
          "",
          "  createOrder(request: CreateOrderRequest): Observable<Order> {",
          "    return this.http.post<Order>(this.API_URL, request).pipe(",
          "      catchError(this.handleError)",
          "    );",
          "  }",
          "",
          "  cancelOrder(id: string): Observable<void> {",
          "    return this.http.patch<void>(`${this.API_URL}/${id}/cancel`, {}).pipe(",
          "      catchError(this.handleError)",
          "    );",
          "  }",
          "",
          "  private handleError(error: HttpErrorResponse): Observable<never> {",
          "    const message = error.error?.message || 'Unknown error occurred';",
          "    console.error('API Error:', error.status, message);",
          "    return throwError(() => new Error(message));",
          "  }",
          "}",
        ]},
        {t:"heading", v:"Using Services in Components"},
        {t:"code", lang:"typescript", v:[
          "// order-list.component.ts",
          "@Component({",
          "  selector: 'app-order-list',",
          "  templateUrl: './order-list.component.html',",
          "})",
          "export class OrderListComponent implements OnInit, OnDestroy {",
          "  orders: Order[]     = [];",
          "  loading             = true;",
          "  error: string | null = null;",
          "  private subscription?: Subscription;  // Track subscriptions to prevent memory leaks",
          "",
          "  // Angular injects OrderService automatically via constructor",
          "  constructor(",
          "    private orderService: OrderService,",
          "    private router: Router,",
          "    private snackBar: MatSnackBar",
          "  ) {}",
          "",
          "  ngOnInit(): void {",
          "    this.loadOrders();",
          "  }",
          "",
          "  loadOrders(): void {",
          "    this.loading = true;",
          "    this.subscription = this.orderService.getOrders().subscribe({",
          "      next: (data) => {",
          "        this.orders  = data.content;",
          "        this.loading = false;",
          "      },",
          "      error: (err) => {",
          "        this.error   = err.message;",
          "        this.loading = false;",
          "      }",
          "    });",
          "  }",
          "",
          "  cancelOrder(orderId: string): void {",
          "    this.orderService.cancelOrder(orderId).subscribe({",
          "      next: () => {",
          "        this.snackBar.open('Order cancelled', 'Close', { duration: 3000 });",
          "        this.loadOrders();  // Refresh list",
          "      },",
          "      error: (err) => this.snackBar.open(err.message, 'Close'),",
          "    });",
          "  }",
          "",
          "  // CRITICAL: Always unsubscribe to prevent memory leaks!",
          "  ngOnDestroy(): void {",
          "    this.subscription?.unsubscribe();",
          "  }",
          "}",
        ]},
      ]
    },
    {
      title: "Angular Forms — Template & Reactive", level: "Intermediate",
      blocks: [
        {t:"text", v:"Angular has two approaches to forms. Template-driven forms are simpler for basic forms (two-way binding with ngModel). Reactive forms are more powerful for complex forms with dynamic fields, custom validators, and programmatic control."},
        {t:"heading", v:"Reactive Forms — Production Standard"},
        {t:"code", lang:"typescript", v:[
          "import { FormBuilder, FormGroup, FormArray, Validators } from '@angular/forms';",
          "",
          "@Component({ selector: 'app-create-order' })",
          "export class CreateOrderComponent implements OnInit {",
          "  orderForm!: FormGroup;",
          "",
          "  constructor(",
          "    private fb: FormBuilder,",
          "    private orderService: OrderService,",
          "    private router: Router",
          "  ) {}",
          "",
          "  ngOnInit(): void {",
          "    this.orderForm = this.fb.group({",
          "      customerId: ['', [Validators.required, Validators.minLength(3)]],",
          "      deliveryAddress: this.fb.group({",
          "        street:  ['', Validators.required],",
          "        city:    ['', Validators.required],",
          "        pincode: ['', [Validators.required, Validators.pattern(/^[1-9][0-9]{5}$/)]],",
          "      }),",
          "      items: this.fb.array([this.createItemGroup()]),  // Dynamic list",
          "      notes: [''],",
          "    });",
          "  }",
          "",
          "  createItemGroup(): FormGroup {",
          "    return this.fb.group({",
          "      productId: ['', Validators.required],",
          "      quantity:  [1,  [Validators.required, Validators.min(1)]],",
          "      price:     [0,  [Validators.required, Validators.min(0.01)]],",
          "    });",
          "  }",
          "",
          "  // Getter for FormArray — easy access in template",
          "  get items(): FormArray {",
          "    return this.orderForm.get('items') as FormArray;",
          "  }",
          "",
          "  addItem(): void {",
          "    this.items.push(this.createItemGroup());",
          "  }",
          "",
          "  removeItem(index: number): void {",
          "    if (this.items.length > 1) this.items.removeAt(index);",
          "  }",
          "",
          "  // Helper for template error display",
          "  isInvalid(field: string): boolean {",
          "    const control = this.orderForm.get(field);",
          "    return !!(control?.invalid && control?.touched);",
          "  }",
          "",
          "  onSubmit(): void {",
          "    if (this.orderForm.invalid) {",
          "      this.orderForm.markAllAsTouched();  // Show all validation errors",
          "      return;",
          "    }",
          "    this.orderService.createOrder(this.orderForm.value).subscribe({",
          "      next: (order) => this.router.navigate(['/orders', order.id]),",
          "      error: (err)  => console.error('Failed:', err.message),",
          "    });",
          "  }",
          "}",
        ]},
        {t:"heading", v:"Reactive Form Template"},
        {t:"code", lang:"html", v:[
          "<form [formGroup]='orderForm' (ngSubmit)='onSubmit()'>",
          "",
          "  <div formGroupName='deliveryAddress'>",
          "    <input formControlName='street' placeholder='Street' />",
          "    <span *ngIf='isInvalid(\"deliveryAddress.street\")'>Street is required</span>",
          "",
          "    <input formControlName='city' placeholder='City' />",
          "    <input formControlName='pincode' placeholder='PIN Code' />",
          "    <span *ngIf='orderForm.get(\"deliveryAddress.pincode\")?.errors?.[\"pattern\"]'>",
          "      Invalid PIN code",
          "    </span>",
          "  </div>",
          "",
          "  <!-- Dynamic form array -->",
          "  <div formArrayName='items'>",
          "    <div *ngFor='let item of items.controls; let i = index'",
          "         [formGroupName]='i'>",
          "      <input formControlName='productId' placeholder='Product ID' />",
          "      <input formControlName='quantity'  type='number' />",
          "      <input formControlName='price'     type='number' />",
          "      <button type='button' (click)='removeItem(i)'>Remove</button>",
          "    </div>",
          "  </div>",
          "  <button type='button' (click)='addItem()'>+ Add Item</button>",
          "",
          "  <button type='submit' [disabled]='orderForm.invalid'>Create Order</button>",
          "</form>",
        ]},
      ]
    },
    {
      title: "RxJS & Observables — Reactive Programming", level: "Intermediate",
      blocks: [
        {t:"text", v:"RxJS is the backbone of Angular. Observables are streams of data over time — like a Promise but for multiple values, cancellable, and composable. Mastering RxJS makes Angular click."},
        {t:"heading", v:"Observable Basics"},
        {t:"code", lang:"typescript", v:[
          "import { Observable, of, from, interval, Subject, BehaviorSubject } from 'rxjs';",
          "import { map, filter, debounceTime, switchMap,",
          "         takeUntil, catchError, shareReplay } from 'rxjs/operators';",
          "",
          "// Creating Observables:",
          "const numbers$ = of(1, 2, 3, 4, 5);      // Emits values synchronously",
          "const promise$ = from(fetch('/api/data')); // Wraps a Promise",
          "const timer$   = interval(1000);           // Emits 0,1,2... every second",
          "",
          "// Subscribing:",
          "numbers$.subscribe({",
          "  next:     (value) => console.log('Value:', value),",
          "  error:    (err)   => console.error('Error:', err),",
          "  complete: ()      => console.log('Done!'),",
          "});",
          "",
          "// Operators — transform streams:",
          "numbers$.pipe(",
          "  filter(n => n % 2 === 0),    // Keep even numbers",
          "  map(n => n * 10),             // Multiply by 10",
          ").subscribe(console.log);       // 20, 40",
        ]},
        {t:"heading", v:"Real-World RxJS — Search with Debounce"},
        {t:"code", lang:"typescript", v:[
          "@Component({ selector: 'app-search' })",
          "export class SearchComponent implements OnInit, OnDestroy {",
          "  results: Product[] = [];",
          "  private destroy$ = new Subject<void>();  // Used to clean up subscriptions",
          "",
          "  // FormControl tracks the search input value",
          "  searchControl = new FormControl('');",
          "",
          "  constructor(private productService: ProductService) {}",
          "",
          "  ngOnInit(): void {",
          "    this.searchControl.valueChanges.pipe(",
          "      debounceTime(300),            // Wait 300ms after user stops typing",
          "      filter(term => term!.length > 2), // Only search if 3+ chars",
          "      distinctUntilChanged(),        // Don't search if value didn't change",
          "",
          "      // switchMap: cancel previous HTTP call if new search starts",
          "      // Prevents race conditions with multiple in-flight requests",
          "      switchMap(term =>",
          "        this.productService.search(term!).pipe(",
          "          catchError(() => of([]))    // On error: return empty results",
          "        )",
          "      ),",
          "",
          "      takeUntil(this.destroy$)       // Auto-unsubscribe on component destroy",
          "    ).subscribe(results => {",
          "      this.results = results;",
          "    });",
          "  }",
          "",
          "  ngOnDestroy(): void {",
          "    this.destroy$.next();   // Signal: unsubscribe all takeUntil streams",
          "    this.destroy$.complete();",
          "  }",
          "}",
          "",
          "// The 4 most important RxJS operators to know:",
          "// switchMap  — cancel previous, start new (search, navigation)",
          "// mergeMap   — run all concurrently (parallel API calls)",
          "// concatMap  — run sequentially, preserve order",
          "// exhaustMap — ignore new until current completes (submit button)",
        ]},
        {t:"heading", v:"BehaviorSubject — State Management"},
        {t:"code", lang:"typescript", v:[
          "// Simple state management with BehaviorSubject",
          "// (before reaching for NgRx)",
          "@Injectable({ providedIn: 'root' })",
          "export class CartService {",
          "  // BehaviorSubject: holds current value, emits to new subscribers immediately",
          "  private cartItems$ = new BehaviorSubject<CartItem[]>([]);",
          "",
          "  // Expose as read-only Observable",
          "  readonly items$ = this.cartItems$.asObservable();",
          "",
          "  // Derived observables:",
          "  readonly count$ = this.items$.pipe(",
          "    map(items => items.reduce((sum, i) => sum + i.qty, 0)),",
          "    shareReplay(1)  // Cache for multiple subscribers",
          "  );",
          "",
          "  readonly total$ = this.items$.pipe(",
          "    map(items => items.reduce((sum, i) => sum + i.price * i.qty, 0)),",
          "    shareReplay(1)",
          "  );",
          "",
          "  addItem(product: Product): void {",
          "    const current = this.cartItems$.value;",
          "    const existing = current.find(i => i.id === product.id);",
          "    if (existing) {",
          "      this.cartItems$.next(",
          "        current.map(i => i.id === product.id ? { ...i, qty: i.qty + 1 } : i)",
          "      );",
          "    } else {",
          "      this.cartItems$.next([...current, { ...product, qty: 1 }]);",
          "    }",
          "  }",
          "}",
          "",
          "// In template with async pipe (auto-subscribes AND auto-unsubscribes):",
          "// <span>Items: {{ cartService.count$ | async }}</span>",
          "// <span>Total: {{ cartService.total$ | async | currency }}</span>",
        ]},
      ]
    },
    {
      title: "Angular Routing & Guards", level: "Intermediate",
      blocks: [
        {t:"text", v:"Angular Router provides client-side navigation with lazy loading, route guards, and route resolvers. Guards protect routes based on auth state. Lazy loading splits your bundle so users only download what they visit."},
        {t:"heading", v:"Router Setup with Lazy Loading"},
        {t:"code", lang:"typescript", v:[
          "// app-routing.module.ts",
          "const routes: Routes = [",
          "  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },",
          "",
          "  // Lazy-loaded feature modules — only downloaded when visited:",
          "  {",
          "    path: 'dashboard',",
          "    loadChildren: () =>",
          "      import('./features/dashboard/dashboard.module')",
          "        .then(m => m.DashboardModule),",
          "    canActivate: [AuthGuard],   // Protect with guard",
          "  },",
          "  {",
          "    path: 'orders',",
          "    loadChildren: () =>",
          "      import('./features/orders/orders.module')",
          "        .then(m => m.OrdersModule),",
          "    canActivate: [AuthGuard],",
          "  },",
          "  {",
          "    path: 'admin',",
          "    loadChildren: () =>",
          "      import('./features/admin/admin.module')",
          "        .then(m => m.AdminModule),",
          "    canActivate: [AuthGuard, AdminGuard],  // Multiple guards",
          "  },",
          "  { path: 'login', component: LoginComponent },",
          "  { path: '**',    component: NotFoundComponent },",
          "];",
        ]},
        {t:"heading", v:"Route Guards"},
        {t:"code", lang:"typescript", v:[
          "// auth.guard.ts",
          "@Injectable({ providedIn: 'root' })",
          "export class AuthGuard implements CanActivate {",
          "  constructor(",
          "    private authService: AuthService,",
          "    private router: Router",
          "  ) {}",
          "",
          "  canActivate(",
          "    route: ActivatedRouteSnapshot,",
          "    state: RouterStateSnapshot",
          "  ): boolean | UrlTree {",
          "    if (this.authService.isLoggedIn()) {",
          "      return true;  // Allow navigation",
          "    }",
          "    // Redirect to login, preserve intended URL",
          "    return this.router.createUrlTree(['/login'], {",
          "      queryParams: { returnUrl: state.url }",
          "    });",
          "  }",
          "}",
          "",
          "// role.guard.ts — check specific roles",
          "@Injectable({ providedIn: 'root' })",
          "export class AdminGuard implements CanActivate {",
          "  constructor(private authService: AuthService, private router: Router) {}",
          "",
          "  canActivate(): boolean | UrlTree {",
          "    if (this.authService.hasRole('ADMIN')) return true;",
          "    return this.router.createUrlTree(['/unauthorized']);",
          "  }",
          "}",
          "",
          "// HTTP Interceptor — add JWT to every outgoing request",
          "@Injectable()",
          "export class AuthInterceptor implements HttpInterceptor {",
          "  constructor(private authService: AuthService) {}",
          "",
          "  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {",
          "    const token = this.authService.getToken();",
          "    if (token) {",
          "      const authReq = req.clone({",
          "        setHeaders: { Authorization: `Bearer ${token}` }",
          "      });",
          "      return next.handle(authReq);",
          "    }",
          "    return next.handle(req);",
          "  }",
          "}",
        ]},
      ]
    },
    {
      title: "Angular Performance & Best Practices", level: "Advanced",
      blocks: [
        {t:"text", v:"Production Angular apps need OnPush change detection, trackBy on ngFor, and lazy loading to stay fast at scale. These patterns are what separate junior from senior Angular developers."},
        {t:"heading", v:"OnPush Change Detection"},
        {t:"text", v:"By default, Angular checks every component on every event. OnPush changes it to: only check when @Input references change, an event originates in this component, or an Observable emits via async pipe. This can make large lists 10x faster."},
        {t:"code", lang:"typescript", v:[
          "@Component({",
          "  selector: 'app-order-row',",
          "  templateUrl: './order-row.component.html',",
          "  changeDetection: ChangeDetectionStrategy.OnPush, // Only check when inputs change",
          "})",
          "export class OrderRowComponent {",
          "  @Input() order!: Order;",
          "  @Input() selected = false;",
          "  @Output() selected$ = new EventEmitter<Order>();",
          "",
          "  // With OnPush: this component only re-renders when:",
          "  // 1. order reference changes (new object, not mutation)",
          "  // 2. selected changes",
          "  // 3. An event originates here (click, etc.)",
          "  // 4. async pipe receives new value",
          "",
          "  // GOTCHA: Mutating order object won't trigger re-render!",
          "  // Parent must pass a NEW object: { ...order, status: 'SHIPPED' }",
          "}",
          "",
          "// Combined with trackBy in ngFor:",
          "// Without trackBy: Angular destroys and recreates ALL DOM elements on data change",
          "// With trackBy: Angular only updates changed rows",
          "",
          "// In template:",
          "// <tr *ngFor='let order of orders; trackBy: trackByOrderId'>",
          "",
          "// In component:",
          "trackByOrderId(index: number, order: Order): string {",
          "  return order.id;  // Stable identity — Angular reuses DOM elements",
          "}",
        ]},
        {t:"heading", v:"HTTP Interceptors — Cross-Cutting Concerns"},
        {t:"code", lang:"typescript", v:[
          "// Loading interceptor: show/hide global spinner",
          "@Injectable()",
          "export class LoadingInterceptor implements HttpInterceptor {",
          "  private activeRequests = 0;",
          "",
          "  constructor(private loadingService: LoadingService) {}",
          "",
          "  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {",
          "    this.activeRequests++;",
          "    this.loadingService.show();",
          "",
          "    return next.handle(req).pipe(",
          "      finalize(() => {",
          "        this.activeRequests--;",
          "        if (this.activeRequests === 0) this.loadingService.hide();",
          "      })",
          "    );",
          "  }",
          "}",
          "",
          "// Error interceptor: global 401/403 handling",
          "@Injectable()",
          "export class ErrorInterceptor implements HttpInterceptor {",
          "  constructor(private authService: AuthService, private router: Router) {}",
          "",
          "  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {",
          "    return next.handle(req).pipe(",
          "      catchError((error: HttpErrorResponse) => {",
          "        if (error.status === 401) {",
          "          this.authService.logout();",
          "          this.router.navigate(['/login']);",
          "        }",
          "        if (error.status === 403) {",
          "          this.router.navigate(['/forbidden']);",
          "        }",
          "        return throwError(() => error);",
          "      })",
          "    );",
          "  }",
          "}",
        ]},
      ]
    },
  ]
};
