export const devopsData = {
  id: "devops", icon: "⚙️", title: "Cloud & DevOps", color: "#f97316", accent: "#fb923c",
  topics: [
    {
      title: "Git — Version Control Mastery", level: "Beginner",
      blocks: [
        {t:"text", v:"Git is the version control system used by virtually every software team. It tracks changes, enables collaboration, and lets you safely experiment without breaking production. Mastering Git is non-negotiable for any professional developer."},
        {t:"heading", v:"Core Git Concepts"},
        {t:"code", lang:"text", v:[
          "WORKING DIRECTORY: Your local files on disk",
          "STAGING AREA (Index): Files prepared for next commit",
          "LOCAL REPOSITORY: Your local Git history (.git folder)",
          "REMOTE REPOSITORY: GitHub/GitLab/Bitbucket shared repo",
          "",
          "Basic workflow:",
          "  Edit files → git add → git commit → git push",
          "",
          "Branch model:",
          "  main/master  — production-ready code",
          "  develop      — integration branch",
          "  feature/xyz  — new feature (from develop)",
          "  hotfix/abc   — urgent prod fix (from main)",
          "  release/1.2  — release candidate",
        ]},
        {t:"heading", v:"Essential Git Commands"},
        {t:"code", lang:"bash", v:[
          "# Setup",
          "git config --global user.name  \"Your Name\"",
          "git config --global user.email \"you@example.com\"",
          "git config --global core.editor \"code --wait\"  # VS Code as editor",
          "",
          "# Start / Clone",
          "git init                          # New repo in current folder",
          "git clone https://github.com/user/repo.git",
          "",
          "# Day-to-day workflow",
          "git status                        # What changed?",
          "git diff                          # Show exact changes",
          "git add src/OrderService.java     # Stage specific file",
          "git add .                         # Stage all changes",
          "git commit -m \"feat: add order cancellation endpoint\"",
          "git push origin feature/order-cancel",
          "",
          "# Branching",
          "git checkout -b feature/payment-gateway  # Create + switch",
          "git switch main                           # Switch branch (modern)",
          "git merge feature/payment-gateway         # Merge into current",
          "git branch -d feature/payment-gateway     # Delete merged branch",
          "",
          "# Undo mistakes",
          "git restore src/File.java         # Discard working dir changes",
          "git restore --staged src/File.java # Unstage a file",
          "git reset HEAD~1                   # Undo last commit (keep changes)",
          "git revert abc1234                 # Create undo-commit (safe for shared branches)",
          "",
          "# History",
          "git log --oneline --graph --all   # Visual branch history",
          "git log -p src/OrderService.java  # History of one file",
          "git blame src/OrderService.java   # Who changed each line?",
          "git stash                         # Temporarily save uncommitted changes",
          "git stash pop                     # Restore stashed changes",
        ]},
        {t:"heading", v:"GitFlow — Professional Branching Strategy"},
        {t:"code", lang:"bash", v:[
          "# Gitflow Workflow used by most Java teams:",
          "",
          "# 1. Start new feature (always from develop)",
          "git checkout develop",
          "git pull origin develop",
          "git checkout -b feature/order-tracking",
          "",
          "# 2. Work on feature, make commits",
          "git add . && git commit -m \"feat: add real-time order tracking\"",
          "git add . && git commit -m \"test: add unit tests for tracking service\"",
          "",
          "# 3. Push and create Pull Request",
          "git push origin feature/order-tracking",
          "# → Create PR on GitHub: feature/order-tracking → develop",
          "# → Team code review",
          "# → Squash and merge (keeps develop history clean)",
          "",
          "# 4. Release: merge develop → main + tag",
          "git checkout main",
          "git merge develop",
          "git tag -a v1.5.0 -m \"Release 1.5.0 — Order tracking feature\"",
          "git push origin main --tags",
          "",
          "# 5. Hotfix directly from main:",
          "git checkout -b hotfix/payment-null-pointer main",
          "# Fix the bug",
          "git commit -m \"fix: handle null payment method gracefully\"",
          "git checkout main && git merge hotfix/payment-null-pointer",
          "git checkout develop && git merge hotfix/payment-null-pointer",
          "git tag -a v1.5.1 -m \"Hotfix 1.5.1\"",
        ]},
        {t:"heading", v:"Rebase vs Merge — When to Use Which"},
        {t:"code", lang:"bash", v:[
          "# MERGE: Creates a merge commit, preserves exact history",
          "git checkout main",
          "git merge feature/new-api",
          "# History: A--B--C--M (M = merge commit)",
          "#                 /",
          "#          D--E--F",
          "# Use merge for: integrating long-lived branches, shared branches",
          "",
          "# REBASE: Replays commits on top of another branch",
          "git checkout feature/new-api",
          "git rebase main",
          "# History: A--B--C--D'--E'--F' (clean linear history)",
          "# Use rebase for: cleaning up local feature branches before PR",
          "",
          "# Interactive rebase — squash multiple commits into one:",
          "git rebase -i HEAD~3  # Rewrite last 3 commits",
          "# In editor: pick → squash to combine, reword to rename",
          "",
          "# GOLDEN RULE: Never rebase a branch that others are working on!",
          "# Rebase rewrites commit SHAs → breaks other developers' history",
        ]},
        {t:"note", v:"Commit message convention (Conventional Commits): `feat:` new feature, `fix:` bug fix, `docs:` documentation, `refactor:` code change without feature/fix, `test:` tests, `chore:` build/tooling. Example: `feat(orders): add bulk cancel endpoint`. This enables automatic changelog generation and semantic versioning."},
      ]
    },
    {
      title: "Maven & Build Tools", level: "Beginner",
      blocks: [
        {t:"text", v:"Maven is the build tool for Java projects. It manages dependencies (automatically downloads libraries), compiles code, runs tests, and packages your application into a deployable JAR or WAR. Understanding Maven is essential for every Java developer."},
        {t:"heading", v:"Maven pom.xml Structure"},
        {t:"code", lang:"xml", v:[
          "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
          "<project>",
          "    <modelVersion>4.0.0</modelVersion>",
          "",
          "    <!-- Project identity -->",
          "    <groupId>com.mycompany</groupId>",
          "    <artifactId>order-service</artifactId>",
          "    <version>1.5.0-SNAPSHOT</version>",
          "    <packaging>jar</packaging>",
          "",
          "    <!-- Inherit from Spring Boot parent (manages dependency versions) -->",
          "    <parent>",
          "        <groupId>org.springframework.boot</groupId>",
          "        <artifactId>spring-boot-starter-parent</artifactId>",
          "        <version>3.2.0</version>",
          "    </parent>",
          "",
          "    <properties>",
          "        <java.version>21</java.version>",
          "        <mapstruct.version>1.5.5.Final</mapstruct.version>",
          "    </properties>",
          "",
          "    <dependencies>",
          "        <!-- Spring Boot starters (starter = curated dependency bundle) -->",
          "        <dependency>",
          "            <groupId>org.springframework.boot</groupId>",
          "            <artifactId>spring-boot-starter-web</artifactId>",
          "            <!-- No version needed — parent manages it -->",
          "        </dependency>",
          "        <dependency>",
          "            <groupId>org.springframework.boot</groupId>",
          "            <artifactId>spring-boot-starter-data-jpa</artifactId>",
          "        </dependency>",
          "        <dependency>",
          "            <groupId>org.springframework.boot</groupId>",
          "            <artifactId>spring-boot-starter-security</artifactId>",
          "        </dependency>",
          "        <dependency>",
          "            <groupId>org.postgresql</groupId>",
          "            <artifactId>postgresql</artifactId>",
          "            <scope>runtime</scope>",
          "        </dependency>",
          "        <!-- Test scope: only in test classpath -->",
          "        <dependency>",
          "            <groupId>org.springframework.boot</groupId>",
          "            <artifactId>spring-boot-starter-test</artifactId>",
          "            <scope>test</scope>",
          "        </dependency>",
          "    </dependencies>",
          "",
          "    <build>",
          "        <plugins>",
          "            <plugin>",
          "                <groupId>org.springframework.boot</groupId>",
          "                <artifactId>spring-boot-maven-plugin</artifactId>",
          "                <!-- Creates executable fat JAR with all dependencies -->",
          "            </plugin>",
          "        </plugins>",
          "    </build>",
          "</project>",
        ]},
        {t:"heading", v:"Essential Maven Commands"},
        {t:"code", lang:"bash", v:[
          "# Build lifecycle (each phase runs all previous phases first)",
          "mvn validate      # Check POM is valid",
          "mvn compile       # Compile src/main/java",
          "mvn test          # Run tests in src/test/java",
          "mvn package       # Create JAR/WAR in target/",
          "mvn install       # Package + install to local ~/.m2 repository",
          "mvn deploy        # Install + upload to remote Nexus/Artifactory",
          "",
          "# Common options",
          "mvn package -DskipTests          # Skip tests (faster build)",
          "mvn package -T 4                 # Use 4 threads (parallel modules)",
          "mvn clean package                # Clean target/ before building",
          "mvn dependency:tree              # Show all transitive dependencies",
          "mvn dependency:tree | grep spring # Find spring-related deps",
          "mvn versions:display-dependency-updates  # Find outdated dependencies",
          "",
          "# Profiles — different config for different environments",
          "mvn package -Pprod               # Activate 'prod' profile",
          "",
          "# Wrapper (use this in CI/CD — no Maven install needed on server)",
          "./mvnw package                   # Uses project-bundled Maven version",
        ]},
        {t:"heading", v:"Dependency Scopes & Conflict Resolution"},
        {t:"code", lang:"xml", v:[
          "<!-- Dependency scopes: -->",
          "<!-- compile  (default): available everywhere, included in JAR -->",
          "<!-- runtime:  not needed for compile, included in JAR (e.g. JDBC driver) -->",
          "<!-- provided: available at compile, NOT in JAR (e.g. servlet-api, Lombok) -->",
          "<!-- test:     only for test compilation and execution -->",
          "<!-- optional: doesn't get transitively included in other projects -->",
          "",
          "<dependency>",
          "    <groupId>org.projectlombok</groupId>",
          "    <artifactId>lombok</artifactId>",
          "    <scope>provided</scope>  <!-- Annotation processor, not in runtime JAR -->",
          "</dependency>",
          "",
          "<!-- Exclude transitive dependencies that cause conflicts: -->",
          "<dependency>",
          "    <groupId>org.springframework.kafka</groupId>",
          "    <artifactId>spring-kafka</artifactId>",
          "    <exclusions>",
          "        <exclusion>",
          "            <groupId>org.slf4j</groupId>",
          "            <artifactId>slf4j-log4j12</artifactId>",
          "        </exclusion>",
          "    </exclusions>",
          "</dependency>",
          "",
          "<!-- Force a specific version (override transitive): -->",
          "<dependencyManagement>",
          "    <dependencies>",
          "        <dependency>",
          "            <groupId>com.fasterxml.jackson.core</groupId>",
          "            <artifactId>jackson-databind</artifactId>",
          "            <version>2.16.0</version>  <!-- Override all transitive versions -->",
          "        </dependency>",
          "    </dependencies>",
          "</dependencyManagement>",
        ]},
      ]
    },
    {
      title: "Jenkins & CI/CD Pipelines", level: "Intermediate",
      blocks: [
        {t:"text", v:"CI/CD (Continuous Integration / Continuous Delivery) automates the path from code commit to production deployment. Jenkins is the most widely used CI/CD server in Java enterprises. Understanding pipelines is mandatory for senior developers."},
        {t:"heading", v:"CI/CD Pipeline Concepts"},
        {t:"code", lang:"text", v:[
          "CONTINUOUS INTEGRATION (CI):",
          "  Every code commit triggers: compile → test → static analysis → package",
          "  Catches bugs immediately, before they reach teammates",
          "  Everyone integrates frequently (daily), not in big painful merges",
          "",
          "CONTINUOUS DELIVERY (CD):",
          "  Every passing CI build is deployable to production",
          "  Deployment to prod is a manual decision (business controls when)",
          "",
          "CONTINUOUS DEPLOYMENT:",
          "  Every passing CI build is AUTOMATICALLY deployed to production",
          "  Requires extremely high test coverage and confidence",
          "",
          "Typical Java pipeline stages:",
          "  1. Checkout code from Git",
          "  2. Compile (mvn compile)",
          "  3. Unit tests (mvn test)",
          "  4. Static analysis (SonarQube)",
          "  5. Integration tests (mvn verify)",
          "  6. Build Docker image",
          "  7. Push image to registry (ECR/ACR/DockerHub)",
          "  8. Deploy to staging environment",
          "  9. Run smoke/E2E tests",
          " 10. Deploy to production (manual approval gate)",
        ]},
        {t:"heading", v:"Jenkinsfile — Declarative Pipeline"},
        {t:"code", lang:"groovy", v:[
          "// Jenkinsfile — lives in your repo root",
          "pipeline {",
          "    agent { docker { image 'eclipse-temurin:21-jdk' } }",
          "",
          "    environment {",
          "        DOCKER_REGISTRY = 'myregistry.azurecr.io'",
          "        APP_NAME        = 'order-service'",
          "        SONAR_TOKEN     = credentials('sonar-token')  // From Jenkins secrets",
          "    }",
          "",
          "    stages {",
          "        stage('Checkout') {",
          "            steps { checkout scm }",
          "        }",
          "",
          "        stage('Build & Test') {",
          "            steps {",
          "                sh './mvnw clean verify -B'  // -B = batch mode, no color",
          "            }",
          "            post {",
          "                always {",
          "                    junit 'target/surefire-reports/**/*.xml'",
          "                    publishHTML target: [",
          "                        reportDir: 'target/site/jacoco',",
          "                        reportFiles: 'index.html',",
          "                        reportName: 'Coverage Report'",
          "                    ]",
          "                }",
          "            }",
          "        }",
          "",
          "        stage('SonarQube Analysis') {",
          "            steps {",
          "                sh \"\"\"",
          "                    ./mvnw sonar:sonar \\",
          "                    -Dsonar.host.url=https://sonar.mycompany.com \\",
          "                    -Dsonar.login=${SONAR_TOKEN}",
          "                \"\"\"",
          "            }",
          "        }",
          "",
          "        stage('Docker Build & Push') {",
          "            when { branch 'main' }  // Only on main branch",
          "            steps {",
          "                script {",
          "                    def image = docker.build(\"${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_NUMBER}\")",
          "                    docker.withRegistry('https://' + DOCKER_REGISTRY, 'acr-creds') {",
          "                        image.push()",
          "                        image.push('latest')",
          "                    }",
          "                }",
          "            }",
          "        }",
          "",
          "        stage('Deploy to Staging') {",
          "            when { branch 'main' }",
          "            steps {",
          "                sh \"kubectl set image deployment/${APP_NAME} ${APP_NAME}=${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_NUMBER} -n staging\"",
          "                sh \"kubectl rollout status deployment/${APP_NAME} -n staging\"",
          "            }",
          "        }",
          "",
          "        stage('Deploy to Production') {",
          "            when { branch 'main' }",
          "            input { message 'Deploy to production?' ok 'Yes, deploy!' }",
          "            steps {",
          "                sh \"kubectl set image deployment/${APP_NAME} ${APP_NAME}=${DOCKER_REGISTRY}/${APP_NAME}:${BUILD_NUMBER} -n production\"",
          "            }",
          "        }",
          "    }",
          "",
          "    post {",
          "        failure { emailext to: 'team@mycompany.com', subject: \"FAILED: ${JOB_NAME}\", body: \"${BUILD_URL}\" }",
          "        success { slackSend channel: '#deployments', message: \"✅ ${APP_NAME} v${BUILD_NUMBER} deployed!\" }",
          "    }",
          "}",
        ]},
        {t:"heading", v:"SonarQube — Code Quality Gate"},
        {t:"code", lang:"xml", v:[
          "<!-- pom.xml — SonarQube plugin -->",
          "<plugin>",
          "    <groupId>org.sonarsource.scanner.maven</groupId>",
          "    <artifactId>sonar-maven-plugin</artifactId>",
          "    <version>3.10.0.2594</version>",
          "</plugin>",
          "",
          "<!-- JaCoCo — code coverage (required by SonarQube) -->",
          "<plugin>",
          "    <groupId>org.jacoco</groupId>",
          "    <artifactId>jacoco-maven-plugin</artifactId>",
          "    <executions>",
          "        <execution>",
          "            <id>prepare-agent</id>",
          "            <goals><goal>prepare-agent</goal></goals>",
          "        </execution>",
          "        <execution>",
          "            <id>report</id>",
          "            <phase>verify</phase>",
          "            <goals><goal>report</goal></goals>",
          "        </execution>",
          "        <execution>",
          "            <id>check</id>",
          "            <goals><goal>check</goal></goals>",
          "            <configuration>",
          "                <rules>",
          "                    <rule>",
          "                        <limits>",
          "                            <!-- Build fails if coverage < 80% -->",
          "                            <limit>",
          "                                <counter>LINE</counter>",
          "                                <value>COVEREDRATIO</value>",
          "                                <minimum>0.80</minimum>",
          "                            </limit>",
          "                        </limits>",
          "                    </rule>",
          "                </rules>",
          "            </configuration>",
          "        </execution>",
          "    </executions>",
          "</plugin>",
        ]},
        {t:"note", v:"SonarQube Quality Gate checks: code coverage > 80%, no critical bugs, no security vulnerabilities, code duplication < 3%, technical debt ratio < 5%. Configure in SonarQube dashboard. Block PR merges if quality gate fails — enforced in Jenkins pipeline."},
      ]
    },
    {
      title: "AWS — Cloud Services for Java Apps", level: "Intermediate",
      blocks: [
        {t:"text", v:"AWS is the dominant cloud platform. Java microservices are deployed, scaled, and monitored using AWS services. Understanding the core services is essential for senior Java developers and architects."},
        {t:"heading", v:"Core AWS Services Every Java Dev Needs"},
        {t:"table", v:[
          ["Service","What it does","Java Use Case"],
          ["EC2","Virtual servers (VMs)","Run Spring Boot apps, Kafka, DBs"],
          ["ECS/EKS","Container orchestration","Deploy Docker containers at scale"],
          ["RDS","Managed relational DB","PostgreSQL/MySQL/Oracle without DBA overhead"],
          ["ElastiCache","Managed Redis/Memcached","Session store, caching layer"],
          ["S3","Object storage","Store files, images, backups, static assets"],
          ["SQS","Managed message queue","Async task processing, decouple services"],
          ["SNS","Push notifications/pub-sub","Fan-out events to multiple consumers"],
          ["API Gateway","Managed API Gateway","Expose Lambda/ECS as REST APIs"],
          ["Lambda","Serverless functions","Event handlers, lightweight APIs"],
          ["CloudWatch","Monitoring & logs","App logs, metrics, alerts, dashboards"],
          ["IAM","Identity & access management","Service permissions, user access control"],
          ["VPC","Virtual Private Cloud","Network isolation, security groups"],
          ["CodePipeline","CI/CD service","Alternative to Jenkins on AWS"],
          ["ECR","Docker image registry","Store and pull Docker images"],
        ]},
        {t:"heading", v:"Spring Boot on AWS ECS (Container Service)"},
        {t:"code", lang:"yaml", v:[
          "# ECS Task Definition (simplified)",
          "# Define how your container runs",
          "{",
          "  \"family\": \"order-service\",",
          "  \"networkMode\": \"awsvpc\",",
          "  \"requiresCompatibilities\": [\"FARGATE\"],",
          "  \"cpu\": \"512\",    # 0.5 vCPU",
          "  \"memory\": \"1024\", # 1 GB",
          "  \"containerDefinitions\": [{",
          "    \"name\": \"order-service\",",
          "    \"image\": \"123456789.dkr.ecr.us-east-1.amazonaws.com/order-service:1.5.0\",",
          "    \"portMappings\": [{\"containerPort\": 8080}],",
          "    \"environment\": [",
          "      {\"name\": \"SPRING_PROFILES_ACTIVE\", \"value\": \"prod\"}",
          "    ],",
          "    \"secrets\": [",
          "      {\"name\": \"DB_PASSWORD\", \"valueFrom\": \"arn:aws:secretsmanager:us-east-1:123:secret:db-password\"}",
          "    ],",
          "    \"logConfiguration\": {",
          "      \"logDriver\": \"awslogs\",",
          "      \"options\": {",
          "        \"awslogs-group\": \"/ecs/order-service\",",
          "        \"awslogs-region\": \"us-east-1\"",
          "      }",
          "    },",
          "    \"healthCheck\": {",
          "      \"command\": [\"CMD-SHELL\", \"curl -f http://localhost:8080/actuator/health || exit 1\"],",
          "      \"interval\": 30, \"timeout\": 5, \"retries\": 3",
          "    }",
          "  }]",
          "}",
        ]},
        {t:"heading", v:"Spring Boot AWS Integration — Spring Cloud AWS"},
        {t:"code", lang:"java", v:[
          "// S3 — Store and retrieve files",
          "@Service",
          "public class FileStorageService {",
          "    private final S3Client s3Client;",
          "    private final String bucketName = \"my-orders-bucket\";",
          "",
          "    public String uploadFile(String key, byte[] content, String contentType) {",
          "        s3Client.putObject(",
          "            PutObjectRequest.builder()",
          "                .bucket(bucketName)",
          "                .key(key)",
          "                .contentType(contentType)",
          "                .build(),",
          "            RequestBody.fromBytes(content)",
          "        );",
          "        return \"https://\" + bucketName + \".s3.amazonaws.com/\" + key;",
          "    }",
          "",
          "    public byte[] downloadFile(String key) {",
          "        return s3Client.getObjectAsBytes(",
          "            GetObjectRequest.builder().bucket(bucketName).key(key).build()",
          "        ).asByteArray();",
          "    }",
          "}",
          "",
          "// SQS — Send and receive messages",
          "@Service",
          "public class OrderQueueService {",
          "    private final SqsClient sqsClient;",
          "    private final String queueUrl = \"https://sqs.us-east-1.amazonaws.com/123/order-queue\";",
          "",
          "    public void sendOrder(Order order) {",
          "        sqsClient.sendMessage(SendMessageRequest.builder()",
          "            .queueUrl(queueUrl)",
          "            .messageBody(JsonUtils.toJson(order))",
          "            .messageGroupId(order.getCustomerId())  // FIFO queue ordering",
          "            .build());",
          "    }",
          "}",
          "",
          "// Secrets Manager — never hardcode credentials",
          "@Configuration",
          "public class SecretsConfig {",
          "    @Bean",
          "    public String dbPassword() {",
          "        SecretsManagerClient client = SecretsManagerClient.create();",
          "        GetSecretValueResponse response = client.getSecretValue(",
          "            GetSecretValueRequest.builder().secretId(\"prod/order-service/db\").build()",
          "        );",
          "        return response.secretString();  // JSON string, parse as needed",
          "    }",
          "}",
        ]},
        {t:"heading", v:"CloudWatch — Monitoring & Alerting"},
        {t:"code", lang:"yaml", v:[
          "# application.yml — Send Micrometer metrics to CloudWatch",
          "management:",
          "  metrics:",
          "    export:",
          "      cloudwatch:",
          "        enabled: true",
          "        namespace: OrderService/Production",
          "        step: 1m   # Push metrics every minute",
          "",
          "# CloudWatch Alarm (Infrastructure as Code with CloudFormation):",
          "# Alert when error rate > 5% for 5 minutes:",
          "OrderServiceErrorAlarm:",
          "  Type: AWS::CloudWatch::Alarm",
          "  Properties:",
          "    AlarmName: OrderService-HighErrorRate",
          "    AlarmDescription: Error rate > 5% for 5 minutes",
          "    Namespace: OrderService/Production",
          "    MetricName: orders.failed.total",
          "    Statistic: Sum",
          "    Period: 300",
          "    EvaluationPeriods: 1",
          "    Threshold: 50",
          "    ComparisonOperator: GreaterThanThreshold",
          "    AlarmActions:",
          "      - arn:aws:sns:us-east-1:123:engineering-alerts  # Page on-call",
        ]},
      ]
    },
    {
      title: "Azure — Microsoft Cloud for Java", level: "Intermediate",
      blocks: [
        {t:"text", v:"Azure is Microsoft's cloud platform, commonly used in enterprise Java shops (especially in banking, insurance, and large corporations). Spring Boot has excellent first-class support for Azure through Spring Cloud Azure."},
        {t:"heading", v:"Core Azure Services for Java"},
        {t:"table", v:[
          ["AWS Equivalent","Azure Service","Purpose"],
          ["EC2","Azure VM","Virtual machines"],
          ["ECS/EKS","AKS (Azure Kubernetes Service)","Managed Kubernetes"],
          ["RDS","Azure Database for PostgreSQL","Managed PostgreSQL/MySQL"],
          ["ElastiCache","Azure Cache for Redis","Managed Redis"],
          ["S3","Azure Blob Storage","Object/file storage"],
          ["SQS","Azure Service Bus","Message queues & topics"],
          ["SNS","Azure Event Grid","Event routing & pub/sub"],
          ["API Gateway","Azure API Management","API gateway, throttling, analytics"],
          ["Lambda","Azure Functions","Serverless compute"],
          ["CloudWatch","Azure Monitor + App Insights","Monitoring, logging, tracing"],
          ["IAM","Azure Active Directory","Identity, RBAC"],
          ["ECR","Azure Container Registry (ACR)","Docker image registry"],
          ["CodePipeline","Azure DevOps Pipelines","CI/CD"],
          ["Secrets Manager","Azure Key Vault","Secrets, keys, certificates"],
        ]},
        {t:"heading", v:"Spring Boot with Azure — application.yml"},
        {t:"code", lang:"yaml", v:[
          "# Spring Cloud Azure — pom.xml dependency:",
          "# <dependency>",
          "#   <groupId>com.azure.spring</groupId>",
          "#   <artifactId>spring-cloud-azure-starter</artifactId>",
          "# </dependency>",
          "",
          "# application.yml for Azure services:",
          "spring:",
          "  cloud:",
          "    azure:",
          "      credential:",
          "        managed-identity-enabled: true  # Use Azure Managed Identity (no passwords!)",
          "      profile:",
          "        subscription-id: ${AZURE_SUBSCRIPTION_ID}",
          "",
          "  # Azure Blob Storage (like S3):",
          "      storage:",
          "        blob:",
          "          account-name: myorderstorage",
          "          container-name: orders",
          "",
          "  # Azure Service Bus (like SQS):",
          "      servicebus:",
          "        connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}",
          "        entity-name: order-queue",
          "        entity-type: queue",
          "",
          "  # Azure Key Vault (for secrets — replaces env vars):",
          "      keyvault:",
          "        secret:",
          "          endpoint: https://my-keyvault.vault.azure.net/",
          "          # Automatically maps Key Vault secrets to Spring properties!",
          "          # db-password in Key Vault → spring.datasource.password",
        ]},
        {t:"heading", v:"Azure DevOps Pipeline (azure-pipelines.yml)"},
        {t:"code", lang:"yaml", v:[
          "trigger:",
          "  branches:",
          "    include: [main, develop]",
          "",
          "pool:",
          "  vmImage: ubuntu-latest",
          "",
          "variables:",
          "  REGISTRY: myregistry.azurecr.io",
          "  IMAGE_NAME: order-service",
          "  TAG: $(Build.BuildId)",
          "",
          "stages:",
          "- stage: BuildAndTest",
          "  jobs:",
          "  - job: Build",
          "    steps:",
          "    - task: JavaToolInstaller@0",
          "      inputs: { versionSpec: '21', jdkArchitectureOption: 'x64' }",
          "",
          "    - script: ./mvnw clean verify -B",
          "      displayName: 'Build and Test'",
          "",
          "    - task: PublishTestResults@2",
          "      inputs:",
          "        testResultsFiles: '**/surefire-reports/*.xml'",
          "",
          "    - task: SonarQubePrepare@5",
          "      inputs: { SonarQube: 'SonarQube', scannerMode: 'MSBuild' }",
          "",
          "    - task: Docker@2",
          "      displayName: 'Build Docker Image'",
          "      inputs:",
          "        command: buildAndPush",
          "        repository: $(REGISTRY)/$(IMAGE_NAME)",
          "        dockerfile: Dockerfile",
          "        tags: $(TAG)",
          "",
          "- stage: DeployStaging",
          "  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))",
          "  jobs:",
          "  - deployment: Deploy",
          "    environment: staging",
          "    strategy:",
          "      runOnce:",
          "        deploy:",
          "          steps:",
          "          - task: KubernetesManifest@0",
          "            inputs:",
          "              action: deploy",
          "              manifests: k8s/staging/*.yaml",
          "              containers: $(REGISTRY)/$(IMAGE_NAME):$(TAG)",
          "",
          "- stage: DeployProduction",
          "  condition: succeeded('DeployStaging')",
          "  jobs:",
          "  - deployment: Deploy",
          "    environment: production   # Requires manual approval in Azure DevOps",
          "    strategy:",
          "      runOnce:",
          "        deploy:",
          "          steps:",
          "          - task: KubernetesManifest@0",
          "            inputs:",
          "              action: deploy",
          "              manifests: k8s/production/*.yaml",
        ]},
      ]
    },
    {
      title: "Docker & Container Fundamentals", level: "Intermediate",
      blocks: [
        {t:"text", v:"Docker packages your application and all its dependencies into a portable container that runs identically everywhere — developer laptop, CI server, or production Kubernetes cluster. Every modern Java deployment uses containers."},
        {t:"heading", v:"Core Docker Concepts"},
        {t:"code", lang:"bash", v:[
          "# IMAGE: read-only template (like a class in Java)",
          "# CONTAINER: running instance of an image (like an object)",
          "# REGISTRY: stores images (Docker Hub, ECR, ACR)",
          "",
          "# Pull and run an image:",
          "docker pull eclipse-temurin:21-jre-alpine",
          "docker run -p 8080:8080 eclipse-temurin:21-jre-alpine",
          "",
          "# Run Spring Boot app:",
          "docker run \\",
          "  -p 8080:8080 \\",
          "  -e SPRING_PROFILES_ACTIVE=prod \\",
          "  -e DB_PASSWORD=secret \\",
          "  --name order-service \\",
          "  --restart unless-stopped \\",   
          "  myregistry/order-service:1.5.0",
          "",
          "# Build image from Dockerfile:",
          "docker build -t myregistry/order-service:1.5.0 .",
          "docker push myregistry/order-service:1.5.0",
          "",
          "# Inspect and debug:",
          "docker logs order-service -f            # Follow logs",
          "docker exec -it order-service /bin/sh   # Shell into running container",
          "docker stats                             # CPU/memory usage",
          "docker inspect order-service            # Full container details",
          "",
          "# Cleanup:",
          "docker stop order-service && docker rm order-service",
          "docker image prune -a                   # Remove unused images",
        ]},
        {t:"heading", v:"Docker Compose — Local Development Stack"},
        {t:"code", lang:"yaml", v:[
          "# docker-compose.yml — spin up entire local environment",
          "version: '3.8'",
          "",
          "services:",
          "  order-service:",
          "    build: .",
          "    ports: ['8080:8080']",
          "    environment:",
          "      SPRING_PROFILES_ACTIVE: dev",
          "      DB_URL: jdbc:postgresql://postgres:5432/orders",
          "      DB_USERNAME: postgres",
          "      DB_PASSWORD: postgres",
          "      REDIS_HOST: redis",
          "      KAFKA_BOOTSTRAP: kafka:9092",
          "    depends_on:",
          "      postgres: { condition: service_healthy }",
          "      redis:    { condition: service_started }",
          "    volumes:",
          "      - ./logs:/var/log/app   # Mount logs to host for easy viewing",
          "",
          "  postgres:",
          "    image: postgres:16-alpine",
          "    environment:",
          "      POSTGRES_DB: orders",
          "      POSTGRES_USER: postgres",
          "      POSTGRES_PASSWORD: postgres",
          "    ports: ['5432:5432']",
          "    volumes:",
          "      - postgres_data:/var/lib/postgresql/data",
          "      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d",
          "    healthcheck:",
          "      test: ['CMD-SHELL', 'pg_isready -U postgres']",
          "      interval: 5s",
          "",
          "  redis:",
          "    image: redis:7-alpine",
          "    ports: ['6379:6379']",
          "",
          "  kafka:",
          "    image: confluentinc/cp-kafka:7.5.0",
          "    environment:",
          "      KAFKA_BROKER_ID: 1",
          "      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181",
          "      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092",
          "    depends_on: [zookeeper]",
          "",
          "  zookeeper:",
          "    image: confluentinc/cp-zookeeper:7.5.0",
          "    environment:",
          "      ZOOKEEPER_CLIENT_PORT: 2181",
          "",
          "volumes:",
          "  postgres_data:",
          "",
          "# Commands:",
          "# docker-compose up -d        # Start all services in background",
          "# docker-compose logs -f      # Follow all logs",
          "# docker-compose down -v      # Stop and remove volumes",
        ]},
      ]
    },
    {
      title: "Kubernetes — Production Orchestration", level: "Advanced",
      blocks: [
        {t:"text", v:"Kubernetes (K8s) is the standard platform for running containerized microservices in production. It handles scheduling, scaling, self-healing, rolling updates, and service discovery automatically."},
        {t:"heading", v:"Core Kubernetes Objects"},
        {t:"code", lang:"yaml", v:[
          "# POD: smallest deployable unit — one or more containers",
          "# DEPLOYMENT: manages pod replicas + rolling updates",
          "# SERVICE: stable network endpoint for pods",
          "# CONFIGMAP: non-secret configuration",
          "# SECRET: sensitive configuration (passwords, tokens)",
          "# INGRESS: external HTTP routing into the cluster",
          "# HPA: Horizontal Pod Autoscaler",
          "",
          "# Complete Spring Boot deployment:",
          "---",
          "apiVersion: v1",
          "kind: ConfigMap",
          "metadata: { name: order-service-config }",
          "data:",
          "  SPRING_PROFILES_ACTIVE: prod",
          "  LOG_LEVEL: INFO",
          "",
          "---",
          "apiVersion: v1",
          "kind: Secret",
          "metadata: { name: order-service-secrets }",
          "type: Opaque",
          "data:",
          "  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded",
          "  JWT_SECRET: c2VjcmV0a2V5  # base64 encoded",
          "",
          "---",
          "apiVersion: apps/v1",
          "kind: Deployment",
          "metadata:",
          "  name: order-service",
          "  labels: { app: order-service }",
          "spec:",
          "  replicas: 3",
          "  selector:",
          "    matchLabels: { app: order-service }",
          "  strategy:",
          "    type: RollingUpdate",
          "    rollingUpdate: { maxUnavailable: 1, maxSurge: 1 }",
          "  template:",
          "    metadata:",
          "      labels: { app: order-service, version: '1.5.0' }",
          "    spec:",
          "      containers:",
          "      - name: order-service",
          "        image: myregistry/order-service:1.5.0",
          "        ports: [{ containerPort: 8080 }]",
          "        resources:",
          "          requests: { cpu: 250m, memory: 512Mi }",
          "          limits:   { cpu: 1000m, memory: 1Gi }",
          "        envFrom:",
          "        - configMapRef: { name: order-service-config }",
          "        - secretRef:    { name: order-service-secrets }",
          "        readinessProbe:",
          "          httpGet: { path: /actuator/health/readiness, port: 8080 }",
          "          initialDelaySeconds: 30",
          "        livenessProbe:",
          "          httpGet: { path: /actuator/health/liveness, port: 8080 }",
          "          initialDelaySeconds: 60",
          "          failureThreshold: 3",
          "",
          "---",
          "apiVersion: v1",
          "kind: Service",
          "metadata: { name: order-service }",
          "spec:",
          "  selector: { app: order-service }",
          "  ports: [{ port: 80, targetPort: 8080 }]",
          "",
          "---",
          "apiVersion: networking.k8s.io/v1",
          "kind: Ingress",
          "metadata:",
          "  name: order-service-ingress",
          "  annotations:",
          "    nginx.ingress.kubernetes.io/rewrite-target: /",
          "spec:",
          "  rules:",
          "  - host: api.mycompany.com",
          "    http:",
          "      paths:",
          "      - path: /api/v1/orders",
          "        pathType: Prefix",
          "        backend:",
          "          service: { name: order-service, port: { number: 80 } }",
        ]},
        {t:"heading", v:"Essential kubectl Commands"},
        {t:"code", lang:"bash", v:[
          "# Get resources",
          "kubectl get pods -n production              # List pods",
          "kubectl get pods -n production -w           # Watch pods (live)",
          "kubectl get deployments -A                  # All namespaces",
          "kubectl get svc,ingress -n production       # Services + ingress",
          "",
          "# Diagnose issues",
          "kubectl describe pod order-service-xyz -n production  # Full pod details",
          "kubectl logs order-service-xyz -n production -f       # Follow logs",
          "kubectl logs order-service-xyz --previous -n production # Crashed pod logs",
          "kubectl exec -it order-service-xyz -n production -- /bin/sh # Shell into pod",
          "",
          "# Deploy",
          "kubectl apply -f k8s/production/           # Apply all YAML in folder",
          "kubectl rollout status deployment/order-service -n production",
          "kubectl rollout history deployment/order-service -n production",
          "kubectl rollout undo deployment/order-service -n production  # Rollback!",
          "",
          "# Scale",
          "kubectl scale deployment/order-service --replicas=5 -n production",
          "",
          "# ConfigMap / Secret updates",
          "kubectl create secret generic order-secrets \\",
          "    --from-literal=DB_PASSWORD=newpassword \\",
          "    --dry-run=client -o yaml | kubectl apply -f -",
        ]},
      ]
    },
    {
      title: "IntelliJ IDEA — Professional IDE Setup", level: "Beginner",
      blocks: [
        {t:"text", v:"IntelliJ IDEA is the industry-standard IDE for Java development. Knowing your IDE deeply makes you dramatically more productive. This covers essential shortcuts, plugins, and configurations used by professional Java developers."},
        {t:"heading", v:"Essential Keyboard Shortcuts"},
        {t:"table", v:[
          ["Action","Windows/Linux","Mac","Why it matters"],
          ["Search everywhere","Double Shift","Double Shift","Find anything: files, classes, actions"],
          ["Find class","Ctrl+N","Cmd+O","Jump to any class instantly"],
          ["Find file","Ctrl+Shift+N","Cmd+Shift+O","Jump to any file"],
          ["Go to definition","Ctrl+B","Cmd+B","Navigate to method/class definition"],
          ["Find usages","Alt+F7","Option+F7","Where is this class/method used?"],
          ["Refactor rename","Shift+F6","Shift+F6","Rename everywhere safely"],
          ["Extract method","Ctrl+Alt+M","Cmd+Option+M","Refactor to method"],
          ["Auto-format","Ctrl+Alt+L","Cmd+Option+L","Format current file"],
          ["Organize imports","Ctrl+Alt+O","Cmd+Option+O","Remove unused imports"],
          ["Run tests","Ctrl+Shift+F10","Ctrl+Shift+R","Run test at cursor"],
          ["Debug","Shift+F9","Ctrl+D","Start debugger"],
          ["Git commit","Ctrl+K","Cmd+K","Open commit dialog"],
          ["Recent files","Ctrl+E","Cmd+E","Switch between recent files"],
          ["Generate code","Alt+Insert","Cmd+N","Generate getters/constructors/etc"],
        ]},
        {t:"heading", v:"Must-Have Plugins"},
        {t:"code", lang:"text", v:[
          "Lombok               — Reduces boilerplate (@Data, @Builder, @Slf4j)",
          "SonarLint            — Real-time code quality analysis (install SonarQube rules locally)",
          "CheckStyle-IDEA      — Enforce code style (Google/Sun style guides)",
          "Spring Assistant     — Spring Boot config file autocomplete",
          "Database Tools       — Built-in SQL editor, connect to PostgreSQL/Oracle/MySQL",
          "Docker               — Docker compose / Dockerfile support built-in",
          "Kubernetes           — YAML support + cluster integration",
          "GitToolBox           — Inline git blame, branch info in status bar",
          "HTTP Client          — Built-in API testing (alternative to Postman)",
          "Rainbow Brackets     — Color-code matching brackets (readability)",
          "Key Promoter X       — Learn shortcuts by suggesting them when you use mouse",
        ]},
        {t:"heading", v:"Run/Debug Configurations for Spring Boot"},
        {t:"code", lang:"text", v:[
          "1. Run/Debug Configurations → Add Application",
          "   Main class: com.mycompany.OrderServiceApplication",
          "   VM options: -Xmx512m -XX:+UseG1GC",
          "   Environment variables: SPRING_PROFILES_ACTIVE=dev",
          "                         DB_URL=jdbc:postgresql://localhost:5432/orders",
          "",
          "2. Remote JVM Debug (attach to running container):",
          "   Run/Debug → Add Remote JVM Debug",
          "   Host: localhost, Port: 5005",
          "",
          "   Start Spring Boot with debug port open:",
          "   java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -jar app.jar",
          "",
          "3. HTTP Client (.http files) — test your APIs without Postman:",
          "   Create OrderService.http in src/test/resources/",
          "",
          "### Get orders",
          "GET http://localhost:8080/api/v1/orders",
          "Authorization: Bearer {{auth_token}}",
          "",
          "### Create order",
          "POST http://localhost:8080/api/v1/orders",
          "Content-Type: application/json",
          "",
          "{",
          "  \"customerId\": \"cust-123\",",
          "  \"items\": [{\"productId\": \"p-1\", \"quantity\": 2}]",
          "}",
        ]},
      ]
    },
  ]
};
