export const coreJava = {
  id: "core-java", icon: "☕", title: "Core Java", color: "#f59e0b", accent: "#fbbf24",
  topics: [
    {
      title: "JVM, JDK & JRE — How Java Really Works", level: "Beginner",
      blocks: [
        {t:"text", v:"Before writing a single line of Java, you must understand the platform it runs on. This separates developers who guess from developers who know."},
        {t:"heading", v:"The Big Picture — Write Once, Run Anywhere"},
        {t:"code", lang:"text", v:[
          "Your .java file",
          "     |",
          "     v  javac (Java compiler)",
          "  .class file  (bytecode — NOT machine code)",
          "     |",
          "     v  JVM reads bytecode",
          "  Machine Code  (specific to your OS/CPU)",
          "     |",
          "     v",
          "  Program runs!",
          "",
          "Same .class file runs on Windows, Mac, Linux",
          "because each OS has its own JVM implementation.",
        ]},
        {t:"heading", v:"JDK — Java Development Kit (What You Install to Code)"},
        {t:"text", v:"The JDK is what you install on your machine to write and compile Java programs. It contains everything: the compiler (javac), debugger, jar tool, and the JRE."},
        {t:"bullet", v:"**javac**: Compiles .java source files into .class bytecode"},
        {t:"bullet", v:"**java**: Launches the JVM to run your compiled program"},
        {t:"bullet", v:"**jar**: Packages compiled classes into a .jar file for deployment"},
        {t:"bullet", v:"**jdb**: Command-line debugger for troubleshooting"},
        {t:"note", v:"Install JDK 21 (LTS) for all new projects. LTS = Long Term Support = production-stable for years."},
        {t:"heading", v:"JVM Internal Architecture"},
        {t:"code", lang:"text", v:[
          "┌──────────────────────────────────────────┐",
          "│            Class Loader                  │  Loads .class files into memory",
          "├──────────────────────────────────────────┤",
          "│          Runtime Data Areas              │",
          "│  ┌───────────┐  ┌──────────────────────┐│",
          "│  │   Heap    │  │  Stack (per thread)  ││",
          "│  │ (objects) │  │ (method calls, vars) ││",
          "│  └───────────┘  └──────────────────────┘│",
          "│  ┌─────────────────────────────────────┐ │",
          "│  │     Method Area / Metaspace          │ │  Class definitions",
          "│  └─────────────────────────────────────┘ │",
          "├──────────────────────────────────────────┤",
          "│          Execution Engine                │",
          "│   Interpreter + JIT Compiler + GC        │  Actually runs the code",
          "└──────────────────────────────────────────┘",
        ]},
        {t:"subheading", v:"Heap vs Stack — Critical to Understand"},
        {t:"bullet", v:"**Heap**: Where all OBJECTS live. Shared by all threads. Managed by Garbage Collector. Larger but slightly slower."},
        {t:"bullet", v:"**Stack**: Where METHOD CALLS and LOCAL VARIABLES live. Each thread gets its own stack. Auto-cleaned when method returns."},
        {t:"code", lang:"java", v:[
          "public class MemoryExample {",
          "    public static void main(String[] args) {",
          "        int x = 10;              // x lives on the STACK",
          "        String name = \"Alice\";   // 'name' reference on STACK",
          "                                 // actual String object on HEAP",
          "",
          "        Person p = new Person(); // 'p' reference on STACK",
          "                                 // Person object on HEAP",
          "    }",
          "    // When main() returns: stack frame is popped (x, p cleaned up)",
          "    // Person object on Heap becomes eligible for Garbage Collection",
          "    // GC runs periodically and frees heap memory automatically",
          "}",
        ]},
        {t:"heading", v:"Production JVM Tuning"},
        {t:"code", lang:"bash", v:[
          "java \\",
          "  -Xms512m \\                    # Initial heap (JVM starts here)",
          "  -Xmx2g \\                      # Max heap (don't exceed 70% of RAM)",
          "  -XX:+UseG1GC \\               # G1 Garbage Collector (best for most apps)",
          "  -XX:MaxGCPauseMillis=200 \\   # Target max 200ms GC pause",
          "  -XX:+HeapDumpOnOutOfMemoryError \\  # Save heap when app crashes with OOM",
          "  -XX:HeapDumpPath=/var/log/app/ \\",
          "  -XX:+UseContainerSupport \\         # Respect Docker memory limits",
          "  -XX:MaxRAMPercentage=75.0 \\        # Use 75% of container RAM",
          "  -jar payment-service.jar",
        ]},
        {t:"note", v:"Set -Xms equal to -Xmx in production. This prevents the JVM from wasting time resizing the heap and reduces GC pauses significantly."},
      ]
    },
    {
      title: "Data Types, Variables & Operators", level: "Beginner",
      blocks: [
        {t:"text", v:"Java is a strongly-typed language — every variable must have a declared type. This catches bugs at compile time rather than at runtime in front of your users."},
        {t:"heading", v:"The 8 Primitive Types"},
        {t:"table", v:[
          ["Type","Size","Range / Use","Example"],
          ["byte","1 byte","-128 to 127, network data","byte flags = 0b1010;"],
          ["short","2 bytes","-32,768 to 32,767","short port = 8080;"],
          ["int","4 bytes","-2.1B to 2.1B, most integers","int count = 100;"],
          ["long","8 bytes","Very large numbers, IDs","long userId = 9876543210L;"],
          ["float","4 bytes","Decimal, 7 digits precision","float ratio = 3.14f;"],
          ["double","8 bytes","Decimal, 15 digits precision","double pi = 3.14159265;"],
          ["boolean","1 bit","true / false only","boolean active = true;"],
          ["char","2 bytes","Single Unicode character","char grade = 'A';"],
        ]},
        {t:"note", v:"Never use float or double for money — they lose precision! Use **BigDecimal** for all financial calculations."},
        {t:"code", lang:"java", v:[
          "// WHY BigDecimal for money:",
          "double bad = 0.1 + 0.2;         // 0.30000000000000004 ← WRONG!",
          "BigDecimal good = new BigDecimal(\"0.1\").add(new BigDecimal(\"0.2\")); // 0.3 ← CORRECT",
          "",
          "// Integer overflow — silent and dangerous:",
          "int max = Integer.MAX_VALUE;  // 2,147,483,647",
          "int overflow = max + 1;       // -2,147,483,648 — wraps silently!",
          "long safe = (long) max + 1;   // 2,147,483,648 — correct",
          "",
          "// Readable number literals (Java 7+):",
          "int million  = 1_000_000;",
          "long billion = 1_000_000_000L;",
          "int hex      = 0xFF_EC_D1_12;",
        ]},
        {t:"heading", v:"Reference Types vs Primitives"},
        {t:"text", v:"Primitives store the value directly. Reference types (String, arrays, all objects) store a memory address pointing to the object on the heap. This is why == works for primitives but NOT for objects."},
        {t:"code", lang:"java", v:[
          "// Primitives: == compares VALUES",
          "int a = 5, b = 5;",
          "a == b;  // true — same value",
          "",
          "// Objects: == compares MEMORY ADDRESSES (references)",
          "String s1 = new String(\"hello\");",
          "String s2 = new String(\"hello\");",
          "s1 == s2;       // FALSE — different objects in memory",
          "s1.equals(s2);  // TRUE  — same content",
          "",
          "// String Pool exception:",
          "String s3 = \"hello\";  // Goes into String Pool",
          "String s4 = \"hello\";  // Reuses SAME Pool object",
          "s3 == s4;             // TRUE — same object from pool",
          "",
          "// RULE: Always use .equals() to compare Strings and objects",
        ]},
        {t:"heading", v:"Type Casting"},
        {t:"code", lang:"java", v:[
          "// Widening — automatic, safe (smaller type into larger):",
          "int i = 100;",
          "long l = i;      // int -> long: automatic",
          "double d = i;    // int -> double: automatic",
          "",
          "// Narrowing — manual, risky (larger into smaller, may lose data):",
          "double pi = 3.14159;",
          "int truncated = (int) pi;   // 3 — decimal part LOST silently",
          "",
          "// var — local type inference (Java 10+)",
          "var orderMap = new HashMap<String, List<Order>>();  // type inferred",
          "var items = List.of(\"apple\", \"banana\");",
          "",
          "// var is still STRONGLY typed — just inferred at compile time",
          "var name = \"Alice\";",
          "// name = 42;  // COMPILE ERROR — can't assign int to inferred String",
        ]},
      ]
    },
    {
      title: "OOP — Classes, Objects & the 4 Pillars", level: "Beginner",
      blocks: [
        {t:"text", v:"Object-Oriented Programming models your program as a collection of objects — entities with data (fields) and behaviour (methods). Instead of a list of instructions, you think in terms of real-world entities that interact."},
        {t:"heading", v:"Classes and Objects"},
        {t:"code", lang:"java", v:[
          "// CLASS — the blueprint (defines structure and behaviour)",
          "public class BankAccount {",
          "    // Fields: the data/state of each object",
          "    private String accountNumber;",
          "    private String ownerName;",
          "    private double balance;",
          "",
          "    // Constructor: called when creating a new object",
          "    public BankAccount(String accountNumber, String ownerName) {",
          "        this.accountNumber = accountNumber;",
          "        this.ownerName     = ownerName;",
          "        this.balance       = 0.0;",
          "    }",
          "",
          "    // Methods: the behaviour",
          "    public void deposit(double amount) {",
          "        if (amount <= 0) throw new IllegalArgumentException(\"Must be positive\");",
          "        this.balance += amount;",
          "    }",
          "",
          "    public void withdraw(double amount) {",
          "        if (amount > balance) throw new IllegalStateException(\"Insufficient funds\");",
          "        this.balance -= amount;",
          "    }",
          "",
          "    public double getBalance() { return balance; }",
          "}",
          "",
          "// OBJECTS: instances of the blueprint (each has its own state)",
          "BankAccount alice = new BankAccount(\"ACC001\", \"Alice\");",
          "BankAccount bob   = new BankAccount(\"ACC002\", \"Bob\");",
          "",
          "alice.deposit(1000);  // alice.balance = 1000",
          "bob.deposit(500);     // bob.balance   = 500   (independent!)",
        ]},
        {t:"heading", v:"Pillar 1 — Encapsulation (Protect Your Data)"},
        {t:"text", v:"Encapsulation hides internal data and only exposes it through controlled methods. The 'balance' field is private — nobody can set alice.balance = 999999. They must use deposit() which validates input. This protects data integrity."},
        {t:"heading", v:"Pillar 2 — Inheritance (Reuse and Extend)"},
        {t:"code", lang:"java", v:[
          "public class Animal {",
          "    protected String name;",
          "    public Animal(String name) { this.name = name; }",
          "    public void eat() { System.out.println(name + \" is eating\"); }",
          "}",
          "",
          "// Dog IS-A Animal — inherits eat(), name field",
          "public class Dog extends Animal {",
          "    private String breed;",
          "    public Dog(String name, String breed) {",
          "        super(name);      // Call parent constructor first!",
          "        this.breed = breed;",
          "    }",
          "    public void fetch() { System.out.println(name + \" fetches!\"); }",
          "    @Override",
          "    public String toString() { return name + \" (\" + breed + \")\"; }",
          "}",
          "",
          "Dog rex = new Dog(\"Rex\", \"Labrador\");",
          "rex.eat();    // Inherited from Animal",
          "rex.fetch();  // Dog-only method",
        ]},
        {t:"note", v:"Prefer **composition over inheritance**. Only use extends for true IS-A relationships. Use interfaces for shared behaviour contracts."},
        {t:"heading", v:"Pillar 3 — Polymorphism (One Interface, Many Forms)"},
        {t:"code", lang:"java", v:[
          "abstract class Shape {",
          "    abstract double area();",
          "    void printArea() { System.out.println(\"Area: \" + area()); }",
          "}",
          "",
          "class Circle    extends Shape { double r; Circle(double r){this.r=r;} double area(){return Math.PI*r*r;} }",
          "class Rectangle extends Shape { double w,h; Rectangle(double w,double h){this.w=w;this.h=h;} double area(){return w*h;} }",
          "",
          "// Polymorphism: same method call, different behaviour at runtime",
          "List<Shape> shapes = List.of(new Circle(5), new Rectangle(4, 6));",
          "shapes.forEach(Shape::printArea);",
          "// Area: 78.53...",
          "// Area: 24.0",
        ]},
        {t:"heading", v:"Pillar 4 — Abstraction (Hide Complexity)"},
        {t:"code", lang:"java", v:[
          "// Interface defines WHAT, not HOW",
          "public interface PaymentGateway {",
          "    PaymentResult charge(PaymentRequest req);",
          "    boolean refund(String transactionId);",
          "}",
          "",
          "// Stripe and Razorpay both implement the interface differently",
          "public class StripeGateway implements PaymentGateway {",
          "    public PaymentResult charge(PaymentRequest req) { /* Stripe API */ }",
          "    public boolean refund(String txnId)              { /* Stripe refund */ }",
          "}",
          "",
          "// OrderService uses the abstraction — doesn't care which gateway",
          "public class OrderService {",
          "    private final PaymentGateway gateway;  // Could be Stripe, Razorpay, PayPal",
          "    public void checkout(Order order) {",
          "        gateway.charge(order.toPaymentRequest()); // Same code for all gateways",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "SOLID Principles — Professional Code Design", level: "Intermediate",
      blocks: [
        {t:"text", v:"SOLID is a set of 5 principles for writing maintainable, testable, extensible code. Senior developers think in SOLID — it's the difference between code that lasts years vs code that becomes a nightmare in 3 months."},
        {t:"heading", v:"S — Single Responsibility Principle"},
        {t:"text", v:"A class should have ONE reason to change. If UserService handles registration, email, PDF reports, and audit logs — a change to the email template modifies user logic. That's fragile."},
        {t:"code", lang:"java", v:[
          "// BAD: UserService does too many unrelated things",
          "class UserService {",
          "    void register(UserDto dto) { ... }",
          "    void sendWelcomeEmail(User u) { ... }   // email concern",
          "    byte[] generateReport(User u) { ... }   // PDF concern",
          "    void auditLog(User u) { ... }            // audit concern",
          "}",
          "",
          "// GOOD: Each class has ONE responsibility",
          "class UserService        { void register(UserDto dto) { ... } }",
          "class EmailService       { void sendWelcome(User u)   { ... } }",
          "class UserReportService  { byte[] generate(User u)    { ... } }",
          "class AuditService       { void log(String event, Long id) { ... } }",
        ]},
        {t:"heading", v:"O — Open/Closed Principle"},
        {t:"text", v:"Open for extension, closed for modification. Add new behaviour by ADDING new classes, not changing existing tested ones."},
        {t:"code", lang:"java", v:[
          "// BAD: Adding a new discount type requires modifying this class",
          "class DiscountCalculator {",
          "    double calculate(Order o, String type) {",
          "        if (type.equals(\"STUDENT\")) return o.getTotal() * 0.10;",
          "        if (type.equals(\"SENIOR\"))  return o.getTotal() * 0.15;",
          "        // Need VETERAN discount? You must EDIT this file — risky!",
          "        return 0;",
          "    }",
          "}",
          "",
          "// GOOD: Add discounts by adding new classes",
          "interface DiscountStrategy {",
          "    double calculate(Order order);",
          "    boolean appliesTo(User user);",
          "}",
          "class StudentDiscount implements DiscountStrategy {",
          "    public double calculate(Order o) { return o.getTotal() * 0.10; }",
          "    public boolean appliesTo(User u) { return u.isStudent(); }",
          "}",
          "class VeteranDiscount implements DiscountStrategy {",
          "    public double calculate(Order o) { return o.getTotal() * 0.20; }",
          "    public boolean appliesTo(User u) { return u.isVeteran(); }",
          "}",
          "// Adding PayPal? Zero changes to existing code.",
        ]},
        {t:"heading", v:"I — Interface Segregation Principle"},
        {t:"code", lang:"java", v:[
          "// BAD: Fat interface forces implementors to stub methods they don't need",
          "interface NotificationService {",
          "    void sendEmail(String to, String msg);",
          "    void sendSMS(String phone, String msg);",
          "    void sendPush(String deviceId, String msg);",
          "}",
          "// EmailOnlyService is forced to throw UnsupportedOperationException for SMS and Push",
          "",
          "// GOOD: Segregated — implement only what you support",
          "interface EmailNotifier { void sendEmail(String to, String msg); }",
          "interface SMSNotifier   { void sendSMS(String phone, String msg); }",
          "interface PushNotifier  { void sendPush(String deviceId, String msg); }",
          "",
          "class GmailService  implements EmailNotifier { ... }",
          "class TwilioService implements SMSNotifier, EmailNotifier { ... }",
        ]},
        {t:"heading", v:"D — Dependency Inversion Principle"},
        {t:"code", lang:"java", v:[
          "// BAD: OrderService hard-wired to MySQL — can't test without a real DB",
          "class OrderService {",
          "    private MySQLOrderRepository repo = new MySQLOrderRepository();",
          "}",
          "",
          "// GOOD: Depend on the abstraction (interface), not the implementation",
          "interface OrderRepository {",
          "    Order save(Order order);",
          "    Optional<Order> findById(Long id);",
          "}",
          "",
          "class OrderService {",
          "    private final OrderRepository repo;  // Interface!",
          "    public OrderService(OrderRepository repo) { this.repo = repo; }",
          "}",
          "",
          "// Production: Spring injects real JPA implementation",
          "// Tests: inject a Mockito mock — no database needed!",
          "OrderRepository mock = Mockito.mock(OrderRepository.class);",
          "OrderService service = new OrderService(mock);",
        ]},
      ]
    },
    {
      title: "Collections Framework Deep Dive", level: "Intermediate",
      blocks: [
        {t:"text", v:"The Collections Framework is one of the most-used parts of Java. Picking the wrong collection causes bugs (thread safety), wrong results (ordering issues), or major performance problems. Master this and you'll avoid a whole class of production incidents."},
        {t:"heading", v:"Collection Hierarchy Overview"},
        {t:"code", lang:"text", v:[
          "Iterable",
          "  └── Collection",
          "        ├── List        (ordered, allows duplicates)",
          "        │     ├── ArrayList      (array-backed, fast random access)",
          "        │     └── LinkedList     (doubly-linked, fast insert/remove)",
          "        ├── Set         (no duplicates)",
          "        │     ├── HashSet        (no order, O(1) operations)",
          "        │     ├── LinkedHashSet  (insertion order maintained)",
          "        │     └── TreeSet        (sorted, O(log n) operations)",
          "        └── Queue / Deque",
          "              ├── PriorityQueue  (heap-based, smallest first)",
          "              └── ArrayDeque     (fast stack/queue, no nulls)",
          "",
          "Map (key-value pairs, NOT a Collection):",
          "  ├── HashMap            (no order, fastest, O(1))",
          "  ├── LinkedHashMap      (insertion order)",
          "  ├── TreeMap            (sorted by key, O(log n))",
          "  └── ConcurrentHashMap  (thread-safe, lock-free reads)",
        ]},
        {t:"heading", v:"Performance Complexity"},
        {t:"table", v:[
          ["Collection","get/contains","add","remove","Thread Safe?"],
          ["ArrayList","O(1) by index","O(1) amortized","O(n) shift","No"],
          ["LinkedList","O(n) search","O(1) head/tail","O(1) with iter","No"],
          ["HashSet","O(1) avg","O(1) avg","O(1) avg","No"],
          ["TreeSet","O(log n)","O(log n)","O(log n)","No"],
          ["HashMap","O(1) avg","O(1) avg","O(1) avg","No"],
          ["ConcurrentHashMap","O(1)","O(1)","O(1)","YES"],
          ["PriorityQueue","O(n) search","O(log n)","O(log n)","No"],
        ]},
        {t:"heading", v:"Choosing the Right Collection"},
        {t:"code", lang:"java", v:[
          "// Simple ordered list — ArrayList (default choice)",
          "List<Product> products = new ArrayList<>();",
          "",
          "// Fast membership check — HashSet NOT List!",
          "// BAD: O(n) per check = O(n^2) for 1 million items",
          "List<String> processedIds = new ArrayList<>();",
          "if (!processedIds.contains(id)) { ... }  // Slow!",
          "",
          "// GOOD: O(1) per check",
          "Set<String> processedIds = new HashSet<>();",
          "if (processedIds.add(id)) { /* add() returns false if already present */ }",
          "",
          "// Maintain insertion order in a Map (e.g. user cart):",
          "Map<String, CartItem> cart = new LinkedHashMap<>();",
          "",
          "// Thread-safe map for shared state across threads:",
          "Map<String, UserSession> sessions = new ConcurrentHashMap<>();",
          "",
          "// Priority queue — process orders by urgency:",
          "PriorityQueue<Order> queue = new PriorityQueue<>(",
          "    Comparator.comparingInt(Order::getPriority).reversed());",
          "",
          "// Immutable collections (Java 9+) for config data:",
          "List<String>       allowed = List.of(\"GET\", \"POST\", \"PUT\");",
          "Set<String>        roles   = Set.of(\"ADMIN\", \"USER\", \"GUEST\");",
          "Map<String,String> config  = Map.of(\"env\", \"prod\", \"region\", \"us-east\");",
        ]},
        {t:"heading", v:"HashMap Internals — Why equals() and hashCode() Matter"},
        {t:"code", lang:"java", v:[
          "// HashMap uses hashCode() to find the bucket, equals() to find the key",
          "// If you override equals() you MUST override hashCode() — rule!",
          "",
          "// DANGEROUS: Mutable object as HashMap key",
          "class User { String name; }",
          "Map<User, String> roles = new HashMap<>();",
          "User u = new User(); u.name = \"Alice\";",
          "roles.put(u, \"admin\");",
          "u.name = \"Bob\";           // Mutate the key",
          "roles.get(u);             // null! hashCode changed, can't find it",
          "",
          "// SAFE: Always use immutable keys (String, Integer, Long, record)",
          "Map<Long, String> userRoles = new HashMap<>();",
          "userRoles.put(userId, \"admin\"); // Long is immutable — always safe",
        ]},
      ]
    },
    {
      title: "Exception Handling — Production Patterns", level: "Intermediate",
      blocks: [
        {t:"text", v:"Exceptions are how Java signals that something went wrong. Poor exception handling is one of the leading causes of silent data corruption and production incidents. Learn this right — it separates junior from senior developers."},
        {t:"heading", v:"The Exception Hierarchy"},
        {t:"code", lang:"text", v:[
          "Throwable",
          "  ├── Error  (JVM problems — NEVER catch these)",
          "  │     ├── OutOfMemoryError",
          "  │     └── StackOverflowError",
          "  └── Exception",
          "        ├── Checked Exceptions  (must handle or declare)",
          "        │     ├── IOException, SQLException, FileNotFoundException",
          "        │     └── These signal recoverable situations",
          "        └── RuntimeException    (unchecked — optional to handle)",
          "              ├── NullPointerException  — accessed null reference",
          "              ├── IllegalArgumentException — bad method argument",
          "              ├── IllegalStateException    — object in wrong state",
          "              └── IndexOutOfBoundsException — bad array index",
        ]},
        {t:"note", v:"In modern Java (Spring Boot etc.), use unchecked exceptions everywhere for cleaner code. Only checked exceptions where the caller genuinely needs to recover from them (like file I/O)."},
        {t:"heading", v:"try-with-resources — Always Use for I/O"},
        {t:"code", lang:"java", v:[
          "// OLD: error-prone, easy to forget close()",
          "Connection conn = null;",
          "try {",
          "    conn = dataSource.getConnection();",
          "    // ... work",
          "} finally {",
          "    if (conn != null) try { conn.close(); } catch (Exception e) {}",
          "}",
          "",
          "// MODERN: resources auto-closed even if exception thrown",
          "try (Connection conn   = dataSource.getConnection();",
          "     PreparedStatement ps = conn.prepareStatement(SQL)) {",
          "    ps.setLong(1, orderId);",
          "    ResultSet rs = ps.executeQuery();",
          "    // ... process results",
          "} // conn and ps automatically closed here",
          "// Works for any class that implements AutoCloseable",
        ]},
        {t:"heading", v:"Custom Domain Exception Hierarchy"},
        {t:"code", lang:"java", v:[
          "// Base exception — all your app's exceptions extend this",
          "public abstract class AppException extends RuntimeException {",
          "    private final String errorCode;",
          "    private final int httpStatus;",
          "",
          "    protected AppException(String message, String code, int status) {",
          "        super(message);",
          "        this.errorCode  = code;",
          "        this.httpStatus = status;",
          "    }",
          "    // Overload: wraps an underlying cause (exception chaining)",
          "    protected AppException(String message, String code, int status, Throwable cause) {",
          "        super(message, cause);",
          "        this.errorCode  = code;",
          "        this.httpStatus = status;",
          "    }",
          "    public String getErrorCode()  { return errorCode; }",
          "    public int    getHttpStatus() { return httpStatus; }",
          "}",
          "",
          "// Domain-specific exceptions:",
          "public class OrderNotFoundException extends AppException {",
          "    public OrderNotFoundException(Long id) {",
          "        super(\"Order not found: \" + id, \"ORDER_NOT_FOUND\", 404);",
          "    }",
          "}",
          "public class DuplicateEmailException extends AppException {",
          "    public DuplicateEmailException(String email) {",
          "        super(\"Email already registered: \" + email, \"DUPLICATE_EMAIL\", 409);",
          "    }",
          "}",
          "public class InsufficientStockException extends AppException {",
          "    public InsufficientStockException(String sku, int need, int have) {",
          "        super(String.format(\"SKU %s: need %d, have %d\", sku, need, have),",
          "              \"INSUFFICIENT_STOCK\", 422);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Global Exception Handler (Spring Boot)"},
        {t:"code", lang:"java", v:[
          "@RestControllerAdvice",
          "public class GlobalExceptionHandler {",
          "",
          "    @ExceptionHandler(AppException.class)",
          "    public ResponseEntity<ErrorResponse> handleApp(AppException ex) {",
          "        log.warn(\"App exception [{}]: {}\", ex.getErrorCode(), ex.getMessage());",
          "        return ResponseEntity.status(ex.getHttpStatus())",
          "            .body(new ErrorResponse(ex.getErrorCode(), ex.getMessage(), Instant.now()));",
          "    }",
          "",
          "    @ExceptionHandler(MethodArgumentNotValidException.class)",
          "    public ResponseEntity<ErrorResponse> handleValidation(MethodArgumentNotValidException ex) {",
          "        String errors = ex.getBindingResult().getFieldErrors().stream()",
          "            .map(e -> e.getField() + \": \" + e.getDefaultMessage())",
          "            .collect(Collectors.joining(\", \"));",
          "        return ResponseEntity.badRequest()",
          "            .body(new ErrorResponse(\"VALIDATION_FAILED\", errors, Instant.now()));",
          "    }",
          "",
          "    @ExceptionHandler(Exception.class)",
          "    public ResponseEntity<ErrorResponse> handleUnexpected(Exception ex) {",
          "        log.error(\"Unexpected error — this needs investigation!\", ex);",
          "        return ResponseEntity.status(500)",
          "            .body(new ErrorResponse(\"INTERNAL_ERROR\", \"Unexpected error\", Instant.now()));",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Multithreading & Concurrency", level: "Advanced",
      blocks: [
        {t:"text", v:"Concurrency is what lets your application handle many users simultaneously. It's also the source of the hardest-to-find bugs: race conditions that only appear under load, deadlocks that freeze your app. Master this and you're ahead of 90% of developers."},
        {t:"heading", v:"Thread Lifecycle"},
        {t:"code", lang:"text", v:[
          "new Thread() ──> start() ──> RUNNABLE ──> CPU picks it ──> RUNNING",
          "                                                              |",
          "                                          ┌──────────────────┼──────────────┐",
          "                                          v                  v              v",
          "                                       BLOCKED           WAITING      TIMED_WAITING",
          "                                    (waiting for       (wait(),       (sleep(ms),",
          "                                     a lock)           join())         wait(ms))",
          "                                          |                  |              |",
          "                                          └──────────────────┴──────────────┘",
          "                                                             |",
          "                                                        TERMINATED",
        ]},
        {t:"heading", v:"Race Conditions — The Silent Bug"},
        {t:"code", lang:"java", v:[
          "// DANGEROUS: race condition — two threads can both read balance=1000",
          "// and both withdraw 500, leaving balance at 500 instead of 0",
          "public class BankAccount {",
          "    private int balance = 1000;",
          "",
          "    public void withdraw(int amount) {",
          "        if (balance >= amount) {   // Thread A: 1000>=500 TRUE",
          "                                   // --- context switch here ---",
          "                                   // Thread B: 1000>=800 TRUE (reads same 1000!)",
          "            balance -= amount;     // Thread A: balance = 500",
          "                                   // Thread B: balance = -300 !!",
          "        }",
          "    }",
          "}",
          "",
          "// FIX 1: synchronized — only one thread enters at a time",
          "public synchronized void withdraw(int amount) {",
          "    if (balance >= amount) balance -= amount;",
          "}",
          "",
          "// FIX 2: AtomicInteger for simple counters (faster than synchronized)",
          "private final AtomicInteger balance = new AtomicInteger(1000);",
          "public boolean withdraw(int amount) {",
          "    int current, next;",
          "    do {",
          "        current = balance.get();",
          "        if (current < amount) return false;",
          "        next = current - amount;",
          "    } while (!balance.compareAndSet(current, next)); // Retry if changed",
          "    return true;",
          "}",
        ]},
        {t:"heading", v:"ExecutorService — Never Use Raw Threads in Production"},
        {t:"code", lang:"java", v:[
          "// NEVER in production:",
          "new Thread(() -> processOrder(order)).start();",
          "// Creates unbounded threads, no lifecycle management",
          "",
          "// PRODUCTION: bounded thread pool",
          "ThreadPoolExecutor executor = new ThreadPoolExecutor(",
          "    5,                              // corePoolSize: always-alive threads",
          "    20,                             // maximumPoolSize: max under load",
          "    60, TimeUnit.SECONDS,           // idle threads die after 60s",
          "    new LinkedBlockingQueue<>(500), // bounded queue — backpressure!",
          "    new ThreadPoolExecutor.CallerRunsPolicy() // queue full? caller runs it",
          ");",
          "",
          "Future<Order> future = executor.submit(() -> processOrder(request));",
          "Order result = future.get(10, TimeUnit.SECONDS); // timeout after 10s",
        ]},
        {t:"heading", v:"CompletableFuture — Parallel Calls (Java 8+)"},
        {t:"code", lang:"java", v:[
          "// Sequential: 3 API calls × 1s each = 3 seconds total",
          "// Parallel:   3 API calls simultaneously = 1 second total",
          "",
          "CompletableFuture<UserProfile> profileF =",
          "    CompletableFuture.supplyAsync(() -> profileService.get(userId), executor);",
          "CompletableFuture<List<Order>> ordersF =",
          "    CompletableFuture.supplyAsync(() -> orderService.getRecent(userId), executor);",
          "CompletableFuture<Wallet> walletF =",
          "    CompletableFuture.supplyAsync(() -> walletService.get(userId), executor);",
          "",
          "// Wait for all, combine results:",
          "CompletableFuture.allOf(profileF, ordersF, walletF)",
          "    .thenApply(v -> new Dashboard(profileF.join(), ordersF.join(), walletF.join()))",
          "    .exceptionally(ex -> {",
          "        log.error(\"Dashboard load failed\", ex);",
          "        return Dashboard.empty(); // Graceful degradation",
          "    });",
        ]},
        {t:"heading", v:"Virtual Threads — Java 21 (Project Loom)"},
        {t:"code", lang:"java", v:[
          "// Before Loom: thread-per-request model limited to ~1000s of threads",
          "// Platform threads are expensive (1MB stack each)",
          "",
          "// Java 21: Virtual threads are cheap (a few KB each)",
          "// JVM can run MILLIONS of virtual threads on a handful of platform threads",
          "",
          "// Old Spring Boot (blocking I/O):",
          "// 1000 concurrent requests = 1000 threads = needs 1GB just for stacks",
          "",
          "// Spring Boot 3.2+ with virtual threads:",
          "// application.yml:",
          "// spring.threads.virtual.enabled: true",
          "// That's it! Now uses virtual threads for all request handling.",
          "",
          "// Manual virtual thread creation:",
          "try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {",
          "    IntStream.range(0, 100_000).forEach(i ->",
          "        executor.submit(() -> callExternalAPI(i))",
          "    );",
          "} // 100,000 concurrent I/O operations — no thread exhaustion!",
        ]},
      ]
    },
    {
      title: "Java 8–21 Modern Features", level: "Advanced",
      blocks: [
        {t:"text", v:"Java has evolved dramatically. Modern Java (8 through 21) introduced features that fundamentally change how you write code — less boilerplate, more expressive, fewer bugs."},
        {t:"heading", v:"Lambdas & Functional Interfaces (Java 8)"},
        {t:"code", lang:"java", v:[
          "// Before lambdas: verbose anonymous inner classes",
          "Collections.sort(names, new Comparator<String>() {",
          "    @Override public int compare(String a, String b) { return a.compareTo(b); }",
          "});",
          "",
          "// With lambdas: concise",
          "names.sort((a, b) -> a.compareTo(b));",
          "names.sort(String::compareTo); // Method reference — even shorter",
          "",
          "// Built-in functional interfaces:",
          "Predicate<String>      isLong  = s -> s.length() > 10;",
          "Function<String, Integer> len  = String::length;",
          "Consumer<String>       printer = System.out::println;",
          "Supplier<String>       greeting = () -> \"Hello!\";",
          "BiFunction<Integer,Integer,Integer> add = Integer::sum;",
        ]},
        {t:"heading", v:"Stream API (Java 8)"},
        {t:"code", lang:"java", v:[
          "// Declarative data processing — replaces for loops",
          "List<OrderSummary> top5 = orders.stream()",
          "    .filter(o -> o.getStatus() == Status.COMPLETED)",
          "    .filter(o -> o.getDate().isAfter(LocalDate.now().minusDays(30)))",
          "    .sorted(Comparator.comparingDouble(Order::getTotal).reversed())",
          "    .limit(5)",
          "    .map(o -> new OrderSummary(o.getId(), o.getTotal()))",
          "    .collect(Collectors.toList());",
          "",
          "// Aggregations:",
          "double total = orders.stream().mapToDouble(Order::getTotal).sum();",
          "OptionalDouble avg = orders.stream().mapToDouble(Order::getTotal).average();",
          "",
          "// Grouping — very powerful for reporting:",
          "Map<Status, List<Order>> byStatus =",
          "    orders.stream().collect(Collectors.groupingBy(Order::getStatus));",
          "",
          "Map<Status, Long> countByStatus =",
          "    orders.stream().collect(Collectors.groupingBy(Order::getStatus, Collectors.counting()));",
        ]},
        {t:"heading", v:"Optional (Java 8) — No More NullPointerException"},
        {t:"code", lang:"java", v:[
          "// Old way: NPE waiting to happen",
          "User user = repo.findByEmail(email);",
          "String city = user.getAddress().getCity(); // NPE if user or address is null!",
          "",
          "// Optional forces you to handle the empty case:",
          "Optional<User> userOpt = repo.findByEmail(email);",
          "",
          "// Get with default:",
          "String name = userOpt.map(User::getName).orElse(\"Guest\");",
          "",
          "// Throw meaningful exception:",
          "User user = userOpt.orElseThrow(() -> new UserNotFoundException(email));",
          "",
          "// Safe chaining:",
          "String city = userOpt",
          "    .map(User::getAddress)",
          "    .map(Address::getCity)",
          "    .orElse(\"Unknown\");",
          "// No NPE even if user, address, or city is null!",
        ]},
        {t:"heading", v:"Records (Java 16+) — Immutable Data Classes"},
        {t:"code", lang:"java", v:[
          "// Records auto-generate: constructor, getters, equals, hashCode, toString",
          "public record CreateOrderRequest(",
          "    String customerId,",
          "    List<OrderItem> items,",
          "    String deliveryAddress",
          ") {",
          "    // Optional compact constructor for validation:",
          "    public CreateOrderRequest {",
          "        Objects.requireNonNull(customerId, \"customerId required\");",
          "        if (items == null || items.isEmpty())",
          "            throw new IllegalArgumentException(\"Need at least one item\");",
          "        items = List.copyOf(items); // Defensive copy — truly immutable",
          "    }",
          "}",
          "",
          "// Usage — accessor methods use field names (not getXxx):",
          "var req = new CreateOrderRequest(\"cust-1\", items, \"123 Main St\");",
          "req.customerId();       // not getCustomerId()",
          "req.deliveryAddress();  // not getDeliveryAddress()",
        ]},
        {t:"heading", v:"Sealed Classes + Pattern Matching (Java 17/21)"},
        {t:"code", lang:"java", v:[
          "// Sealed: restricts which classes can implement/extend",
          "public sealed interface PaymentResult",
          "    permits PaymentSuccess, PaymentFailure, PaymentPending {}",
          "",
          "record PaymentSuccess(String txnId, BigDecimal amount)  implements PaymentResult {}",
          "record PaymentFailure(String code, boolean retryable)    implements PaymentResult {}",
          "record PaymentPending(String refId, Instant eta)         implements PaymentResult {}",
          "",
          "// Switch expression with pattern matching (Java 21):",
          "// Compiler REQUIRES you to handle ALL cases — no missing branch!",
          "String userMsg = switch (result) {",
          "    case PaymentSuccess s -> \"Paid \" + s.amount() + \". Ref: \" + s.txnId();",
          "    case PaymentFailure f when f.retryable() -> \"Failed, please retry: \" + f.code();",
          "    case PaymentFailure f                    -> \"Failed (permanent): \" + f.code();",
          "    case PaymentPending p -> \"Processing, ETA: \" + p.eta();",
          "};",
          "// Add a new PaymentResult type? Every switch BREAKS until you handle it.",
          "// The compiler is your safety net.",
        ]},
      ]
    },
  ]
};

// Extra topics appended
coreJava.topics.push(
  {
    title: "Generics — Type-Safe Collections & Methods", level: "Intermediate",
    blocks: [
      {t:"text", v:"Generics let you write code that works with any type while maintaining compile-time type safety. Without generics, you'd need to cast everywhere and could get ClassCastException at runtime. With generics, type errors are caught at compile time."},
      {t:"heading", v:"Why Generics?"},
      {t:"code", lang:"java", v:[
        "// Without generics (pre-Java 5) — unsafe:",
        "List list = new ArrayList();",
        "list.add(\"hello\");",
        "list.add(42);       // No error — but mixing types!",
        "String s = (String) list.get(1); // ClassCastException at runtime!",
        "",
        "// With generics — type-safe:",
        "List<String> list = new ArrayList<>();",
        "list.add(\"hello\");",
        "// list.add(42);     // COMPILE ERROR — caught immediately",
        "String s = list.get(0); // No cast needed",
      ]},
      {t:"heading", v:"Generic Classes & Methods"},
      {t:"code", lang:"java", v:[
        "// Generic class: T is a type parameter (placeholder)",
        "public class Box<T> {",
        "    private T value;",
        "    public Box(T value) { this.value = value; }",
        "    public T getValue() { return value; }",
        "    public <R> Box<R> map(Function<T, R> mapper) {",
        "        return new Box<>(mapper.apply(value));",
        "    }",
        "}",
        "",
        "Box<String>  nameBox  = new Box<>(\"Alice\");",
        "Box<Integer> lengthBox = nameBox.map(String::length);",
        "",
        "// Generic method:",
        "public static <T extends Comparable<T>> T max(T a, T b) {",
        "    return a.compareTo(b) >= 0 ? a : b;",
        "}",
        "int maxInt    = max(3, 7);         // T inferred as Integer",
        "String maxStr = max(\"apple\", \"mango\"); // T inferred as String",
        "",
        "// Generic with multiple type parameters:",
        "public class Pair<K, V> {",
        "    private final K key;",
        "    private final V value;",
        "    public Pair(K key, V value) { this.key = key; this.value = value; }",
        "    public K getKey()   { return key; }",
        "    public V getValue() { return value; }",
        "}",
        "Pair<String, Integer> pair = new Pair<>(\"age\", 30);",
      ]},
      {t:"heading", v:"Bounded Type Parameters & Wildcards"},
      {t:"code", lang:"java", v:[
        "// Upper bounded: T must be Number or its subclass",
        "public static <T extends Number> double sum(List<T> list) {",
        "    return list.stream().mapToDouble(Number::doubleValue).sum();",
        "}",
        "sum(List.of(1, 2, 3));         // Integer extends Number: OK",
        "sum(List.of(1.5, 2.5));        // Double extends Number: OK",
        "",
        "// Wildcards:",
        "// ? extends T (upper bounded): can READ, cannot write (covariant)",
        "public void printList(List<? extends Number> list) {",
        "    list.forEach(System.out::println);  // Reading is fine",
        "    // list.add(42);  // COMPILE ERROR",
        "}",
        "",
        "// ? super T (lower bounded): can WRITE, cannot read specific type (contravariant)",
        "public void addNumbers(List<? super Integer> list) {",
        "    list.add(1); list.add(2);  // Writing is fine",
        "}",
        "",
        "// Producer Extends, Consumer Super (PECS rule):",
        "// If a collection PRODUCES T for you to read: use extends",
        "// If a collection CONSUMES T that you write:  use super",
      ]},
      {t:"note", v:"Generics are erased at runtime (type erasure) — `List<String>` and `List<Integer>` are both just `List` at runtime. This is why you can't do `new T()` or `instanceof List<String>`. Use `Class<T>` token pattern when you need runtime type info."},
    ]
  },
  {
    title: "Functional Programming — Streams, Lambdas in Depth", level: "Advanced",
    blocks: [
      {t:"text", v:"Java 8 introduced functional programming features that fundamentally changed how Java code is written. Mastering these makes your code more concise, readable, and parallelizable."},
      {t:"heading", v:"Functional Interfaces — The Foundation"},
      {t:"code", lang:"java", v:[
        "// A functional interface has exactly ONE abstract method",
        "// Can be implemented as a lambda",
        "",
        "// Built-in functional interfaces:",
        "Predicate<String>      isLong   = s -> s.length() > 5;",
        "Function<String, Integer> len   = String::length;",
        "BiFunction<Integer,Integer,Integer> add = Integer::sum;",
        "Consumer<String>       printer  = System.out::println;",
        "Supplier<String>       greeting = () -> \"Hello World\";",
        "UnaryOperator<String>  upper    = String::toUpperCase;",
        "BinaryOperator<Integer> multiply = (a, b) -> a * b;",
        "",
        "// Composing functions:",
        "Function<String, String> transform =",
        "    Function.<String>identity()",
        "        .andThen(String::trim)",
        "        .andThen(String::toLowerCase);",
        "",
        "Predicate<Integer> isPositive = n -> n > 0;",
        "Predicate<Integer> isEven     = n -> n % 2 == 0;",
        "Predicate<Integer> isPositiveEven = isPositive.and(isEven);",
        "Predicate<Integer> eitherOr       = isPositive.or(isEven);",
        "Predicate<Integer> isNegative     = isPositive.negate();",
      ]},
      {t:"heading", v:"Advanced Stream Operations"},
      {t:"code", lang:"java", v:[
        "// flatMap: flatten nested collections",
        "List<List<Integer>> nested = List.of(List.of(1,2), List.of(3,4), List.of(5));",
        "List<Integer> flat = nested.stream()",
        "    .flatMap(Collection::stream)",
        "    .collect(Collectors.toList()); // [1, 2, 3, 4, 5]",
        "",
        "// Collectors.toMap:",
        "Map<Long, Product> productMap = products.stream()",
        "    .collect(Collectors.toMap(",
        "        Product::getId,",
        "        product -> product,",
        "        (existing, duplicate) -> existing  // Handle duplicates",
        "    ));",
        "",
        "// Collectors.teeing (Java 12+): two collectors at once",
        "record Stats(long count, double sum) {}",
        "Stats stats = orders.stream()",
        "    .collect(Collectors.teeing(",
        "        Collectors.counting(),",
        "        Collectors.summingDouble(Order::getTotal),",
        "        Stats::new",
        "    ));",
        "",
        "// Custom collector:",
        "Collector<String, StringBuilder, String> joiner =",
        "    Collector.of(",
        "        StringBuilder::new,",
        "        (sb, s) -> sb.append(s).append(\", \"),",
        "        StringBuilder::append,",
        "        sb -> sb.length() > 0 ? sb.substring(0, sb.length()-2) : \"\"",
        "    );",
        "",
        "// Parallel streams — only for CPU-bound, large collections:",
        "long count = veryLargeList.parallelStream()",
        "    .filter(ExpensiveCheck::test)  // Runs on ForkJoinPool",
        "    .count();",
        "// WARNING: parallel != always faster. Benchmark first.",
        "// Bad for: I/O, stateful operations, small collections",
      ]},
      {t:"heading", v:"Method References — Four Types"},
      {t:"code", lang:"java", v:[
        "// 1. Static method reference: ClassName::staticMethod",
        "Function<String, Integer> parse = Integer::parseInt;",
        "parse.apply(\"42\"); // same as Integer.parseInt(\"42\")",
        "",
        "// 2. Instance method on specific object: object::instanceMethod",
        "String prefix = \"Hello, \";",
        "Function<String, String> greet = prefix::concat;",
        "greet.apply(\"Alice\"); // \"Hello, Alice\"",
        "",
        "// 3. Instance method on arbitrary object of type: ClassName::instanceMethod",
        "Function<String, String> upper = String::toUpperCase;",
        "upper.apply(\"hello\"); // \"HELLO\"",
        "",
        "// 4. Constructor reference: ClassName::new",
        "Supplier<ArrayList<String>> listFactory = ArrayList::new;",
        "Function<String, User> userFactory = User::new;",
        "",
        "// Practical use in streams:",
        "List<String> names = users.stream()",
        "    .map(User::getName)          // Method ref to getter",
        "    .filter(Objects::nonNull)    // Static method ref",
        "    .sorted(String::compareTo)   // Method ref to comparator",
        "    .collect(Collectors.toList());",
      ]},
    ]
  },
  {
    title: "Design Patterns — Gang of Four", level: "Advanced",
    blocks: [
      {t:"text", v:"Design patterns are proven solutions to common software design problems. The Gang of Four (GoF) patterns are the most widely used — you'll see them throughout the Spring framework and every large Java codebase."},
      {t:"heading", v:"Creational: Singleton, Builder, Factory"},
      {t:"code", lang:"java", v:[
        "// SINGLETON: One instance globally",
        "// Thread-safe with double-checked locking:",
        "public class DatabaseConfig {",
        "    private static volatile DatabaseConfig instance;",
        "    private DatabaseConfig() {}",
        "",
        "    public static DatabaseConfig getInstance() {",
        "        if (instance == null) {                    // First check (no lock)",
        "            synchronized (DatabaseConfig.class) {",
        "                if (instance == null)              // Second check (with lock)",
        "                    instance = new DatabaseConfig();",
        "            }",
        "        }",
        "        return instance;",
        "    }",
        "}",
        "// In Spring: @Component is singleton by default — no manual Singleton needed!",
        "",
        "// BUILDER: Construct complex objects step by step",
        "Order order = Order.builder()",
        "    .customerId(\"cust-123\")",
        "    .deliveryAddress(address)",
        "    .addItem(laptop, 1)",
        "    .addItem(mouse, 2)",
        "    .priority(OrderPriority.EXPRESS)",
        "    .build();",
        "",
        "// FACTORY METHOD: Let subclasses decide which class to instantiate",
        "public interface NotificationFactory {",
        "    Notification create(String recipient, String message);",
        "}",
        "public class EmailNotificationFactory implements NotificationFactory {",
        "    public Notification create(String to, String msg) {",
        "        return new EmailNotification(to, msg);",
        "    }",
        "}",
      ]},
      {t:"heading", v:"Structural: Decorator, Proxy, Adapter"},
      {t:"code", lang:"java", v:[
        "// DECORATOR: Add behaviour without changing the original class",
        "interface OrderRepository {",
        "    Optional<Order> findById(Long id);",
        "}",
        "",
        "// Original repository",
        "class JpaOrderRepository implements OrderRepository { ... }",
        "",
        "// Decorator adds caching around existing repository:",
        "class CachingOrderRepository implements OrderRepository {",
        "    private final OrderRepository delegate;  // Wraps original",
        "    private final Map<Long, Order> cache = new HashMap<>();",
        "",
        "    public Optional<Order> findById(Long id) {",
        "        if (cache.containsKey(id)) return Optional.of(cache.get(id));",
        "        Optional<Order> order = delegate.findById(id);",
        "        order.ifPresent(o -> cache.put(id, o));",
        "        return order;",
        "    }",
        "}",
        "// Spring AOP is basically Decorator pattern implemented with proxies!",
        "",
        "// STRATEGY: Encapsulate interchangeable algorithms",
        "interface SortStrategy<T> { List<T> sort(List<T> items); }",
        "",
        "class QuickSort<T extends Comparable<T>> implements SortStrategy<T> {",
        "    public List<T> sort(List<T> items) { /* quicksort */ return items; }",
        "}",
        "class MergeSort<T extends Comparable<T>> implements SortStrategy<T> {",
        "    public List<T> sort(List<T> items) { /* mergesort */ return items; }",
        "}",
        "",
        "class DataProcessor<T extends Comparable<T>> {",
        "    private SortStrategy<T> sortStrategy;",
        "    // Swap strategies at runtime without changing DataProcessor",
        "    public void setSortStrategy(SortStrategy<T> strategy) {",
        "        this.sortStrategy = strategy;",
        "    }",
        "}",
      ]},
      {t:"heading", v:"Behavioural: Observer, Chain of Responsibility"},
      {t:"code", lang:"java", v:[
        "// OBSERVER: Notify subscribers of state changes",
        "// Spring's ApplicationEvent is Observer pattern:",
        "",
        "// 1. Define event:",
        "public class OrderPlacedEvent extends ApplicationEvent {",
        "    private final Order order;",
        "    public OrderPlacedEvent(Object source, Order order) {",
        "        super(source); this.order = order;",
        "    }",
        "    public Order getOrder() { return order; }",
        "}",
        "",
        "// 2. Publish event:",
        "@Service",
        "public class OrderService {",
        "    private final ApplicationEventPublisher events;",
        "    public Order placeOrder(CreateOrderRequest req) {",
        "        Order order = orderRepo.save(Order.from(req));",
        "        events.publishEvent(new OrderPlacedEvent(this, order));",
        "        return order;",
        "    }",
        "}",
        "",
        "// 3. Multiple listeners (observers):",
        "@EventListener",
        "public void sendConfirmationEmail(OrderPlacedEvent e) { ... }",
        "",
        "@EventListener @Async",
        "public void updateInventory(OrderPlacedEvent e) { ... }",
        "",
        "@EventListener @Async",
        "public void notifyWarehouse(OrderPlacedEvent e) { ... }",
        "// OrderService doesn't know about email/inventory/warehouse",
        "// — fully decoupled via Observer pattern",
      ]},
    ]
  }
);
