export const hibernateData = {
  id: "hibernate", icon: "🔄", title: "Hibernate & JPA", color: "#059669", accent: "#34d399",
  topics: [
    {
      title: "Hibernate Architecture & JPA Fundamentals", level: "Beginner",
      blocks: [
        {t:"text", v:"Hibernate is the most popular ORM (Object-Relational Mapping) framework for Java. JPA (Java Persistence API) is the standard specification, and Hibernate is the most widely used implementation. Together they let you work with database tables as Java objects — no SQL required for most operations."},
        {t:"heading", v:"ORM Concept — Why Hibernate?"},
        {t:"code", lang:"text", v:[
          "WITHOUT ORM (raw JDBC):",
          "  Connection conn = dataSource.getConnection();",
          "  PreparedStatement ps = conn.prepareStatement(",
          "      'INSERT INTO orders (customer_id, status, total) VALUES (?,?,?)');",
          "  ps.setLong(1, order.getCustomerId());",
          "  ps.setString(2, order.getStatus().name());",
          "  ps.setBigDecimal(3, order.getTotal());",
          "  ps.executeUpdate();",
          "  // Then get generated ID... handle exceptions... close resources...",
          "  // Multiply this by every table in your app: hundreds of lines",
          "",
          "WITH HIBERNATE/JPA:",
          "  entityManager.persist(order);  // That's it!",
          "  // Hibernate generates SQL, maps columns to fields, handles keys",
          "",
          "ORM does:",
          "  ✓ Maps Java classes to database tables",
          "  ✓ Maps Java fields to database columns",
          "  ✓ Generates CRUD SQL automatically",
          "  ✓ Manages database connections",
          "  ✓ Tracks which objects changed (dirty checking)",
          "  ✓ Caches data for performance",
          "  ✓ Handles relationships (OneToMany, ManyToOne)",
        ]},
        {t:"heading", v:"JPA Entity Mapping in Depth"},
        {t:"code", lang:"java", v:[
          "@Entity",
          "@Table(name = \"orders\",",
          "       schema = \"public\",",
          "       uniqueConstraints = @UniqueConstraint(columnNames = {\"reference_number\"}),",
          "       indexes = {",
          "           @Index(name = \"idx_customer\", columnList = \"customer_id\"),",
          "           @Index(name = \"idx_status_date\", columnList = \"status, created_at DESC\")",
          "       })",
          "@EntityListeners(AuditingEntityListener.class)",
          "public class Order {",
          "",
          "    // Primary key strategies:",
          "    @Id",
          "    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = \"order_seq\")",
          "    @SequenceGenerator(name=\"order_seq\", sequenceName=\"order_id_seq\",",
          "                       allocationSize=50) // Pre-allocate 50 IDs per batch",
          "    private Long id;",
          "",
          "    // Basic column mappings:",
          "    @Column(name = \"reference_number\", nullable = false, length = 20)",
          "    private String referenceNumber;",
          "",
          "    @Column(precision = 12, scale = 2)",
          "    private BigDecimal total;",
          "",
          "    // Enum stored as string (NEVER use ORDINAL):",
          "    @Enumerated(EnumType.STRING)",
          "    @Column(nullable = false, length = 20)",
          "    private OrderStatus status;",
          "",
          "    // Embedded value object:",
          "    @Embedded",
          "    private DeliveryAddress deliveryAddress;",
          "",
          "    // Audit fields:",
          "    @CreatedDate",
          "    @Column(updatable = false)",
          "    private Instant createdAt;",
          "",
          "    @LastModifiedDate",
          "    private Instant updatedAt;",
          "",
          "    @CreatedBy",
          "    @Column(updatable = false)",
          "    private String createdBy;",
          "",
          "    // Optimistic locking:",
          "    @Version",
          "    private Long version; // Hibernate auto-manages",
          "}",
          "",
          "@Embeddable",
          "public class DeliveryAddress {",
          "    private String street;",
          "    private String city;",
          "    private String state;",
          "    @Column(name = \"postal_code\") private String postalCode;",
          "    @Column(name = \"country_code\") private String countryCode;",
          "}",
        ]},
        {t:"heading", v:"Hibernate Session & EntityManager Lifecycle"},
        {t:"code", lang:"java", v:[
          "// Entity states in Hibernate:",
          "// TRANSIENT: new object, not associated with session, no DB row",
          "Order order = new Order(customerId, items);  // TRANSIENT",
          "",
          "// PERSISTENT: associated with session, changes auto-tracked (dirty checking)",
          "entityManager.persist(order);  // TRANSIENT → PERSISTENT",
          "// Now: INSERT SQL queued (may be delayed until flush)",
          "",
          "// Load = PERSISTENT immediately:",
          "Order loaded = entityManager.find(Order.class, 42L);  // PERSISTENT",
          "loaded.setStatus(OrderStatus.SHIPPED);",
          "// No update() call needed! Hibernate dirty-checks on flush",
          "",
          "// DETACHED: disconnected from session (after close/clear/evict)",
          "entityManager.detach(loaded);  // PERSISTENT → DETACHED",
          "// Changes no longer tracked",
          "",
          "// REMOVED: marked for deletion",
          "entityManager.remove(loaded);  // PERSISTENT → REMOVED",
          "// DELETE SQL queued",
          "",
          "// First-Level Cache (Session Cache):",
          "Order o1 = entityManager.find(Order.class, 42L);  // DB query",
          "Order o2 = entityManager.find(Order.class, 42L);  // CACHE HIT — no query!",
          "o1 == o2;  // true — same Java object!",
          "",
          "// Second-Level Cache (across sessions — optional, needs setup):",
          "@Entity @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)",
          "public class Product { ... }",
          "// Product loaded in any transaction hits L2 cache first",
        ]},
      ]
    },
    {
      title: "Hibernate Relationships & Fetch Strategies", level: "Intermediate",
      blocks: [
        {t:"text", v:"Relationships are the most complex and most bug-prone part of Hibernate. Getting fetch strategies wrong causes N+1 queries or OutOfMemoryErrors. This is one of the most important topics for any Java developer using databases."},
        {t:"heading", v:"All Relationship Types"},
        {t:"code", lang:"java", v:[
          "// @OneToMany — Customer has many Orders",
          "@Entity",
          "public class Customer {",
          "    @OneToMany(",
          "        mappedBy = \"customer\",       // 'customer' field on Order side",
          "        cascade = CascadeType.ALL,    // operations cascade to orders",
          "        orphanRemoval = true,          // delete order if removed from list",
          "        fetch = FetchType.LAZY         // ALWAYS lazy for collections",
          "    )",
          "    private List<Order> orders = new ArrayList<>();",
          "",
          "    // Helper methods (always add these for bidirectional):",
          "    public void addOrder(Order order) {",
          "        orders.add(order);",
          "        order.setCustomer(this);",
          "    }",
          "    public void removeOrder(Order order) {",
          "        orders.remove(order);",
          "        order.setCustomer(null);",
          "    }",
          "}",
          "",
          "// @ManyToOne — Order belongs to Customer",
          "@Entity",
          "public class Order {",
          "    @ManyToOne(fetch = FetchType.LAZY)  // ALWAYS lazy",
          "    @JoinColumn(name = \"customer_id\", nullable = false)",
          "    private Customer customer;",
          "}",
          "",
          "// @ManyToMany — Order has many Products, Product in many Orders",
          "@Entity",
          "public class Order {",
          "    @ManyToMany",
          "    @JoinTable(",
          "        name = \"order_products\",",
          "        joinColumns = @JoinColumn(name = \"order_id\"),",
          "        inverseJoinColumns = @JoinColumn(name = \"product_id\")",
          "    )",
          "    private Set<Product> products = new HashSet<>();",
          "    // Use Set not List for ManyToMany — avoids duplicate join results",
          "}",
          "",
          "// @OneToOne — Order has one Invoice",
          "@Entity",
          "public class Order {",
          "    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY,",
          "              optional = false)",
          "    @JoinColumn(name = \"invoice_id\", unique = true)",
          "    private Invoice invoice;",
          "}",
        ]},
        {t:"heading", v:"FetchType LAZY vs EAGER — Critical Understanding"},
        {t:"code", lang:"java", v:[
          "// EAGER: load related data immediately in same query",
          "// LAZY:  load related data only when accessed (proxy)",
          "",
          "// DEFAULT fetch types (remember these!):",
          "// @ManyToOne  → EAGER by default ← Change to LAZY always!",
          "// @OneToOne   → EAGER by default ← Change to LAZY always!",
          "// @OneToMany  → LAZY by default",
          "// @ManyToMany → LAZY by default",
          "",
          "// WHY always LAZY?",
          "// EAGER on @ManyToOne Customer in Order:",
          "// orderRepo.findAll()  →  SELECT * FROM orders",
          "//                     +   SELECT * FROM customers WHERE id=1  (N times!)",
          "// Loading 1000 orders = 1001 SQL queries",
          "",
          "// LAZY → load only when needed:",
          "@ManyToOne(fetch = FetchType.LAZY)  // Always override to LAZY",
          "private Customer customer;",
          "",
          "// When you DO need customer data, use JOIN FETCH:",
          "@Query(\"SELECT o FROM Order o JOIN FETCH o.customer WHERE o.id = :id\")",
          "Optional<Order> findByIdWithCustomer(@Param(\"id\") Long id);",
          "// Result: 1 SQL query with JOIN — efficient",
          "",
          "// LazyInitializationException — the most common Hibernate error:",
          "// Occurs when accessing lazy relation outside of transaction",
          "Order order = orderRepo.findById(42L).get(); // Transaction ends here",
          "order.getCustomer().getName(); // EXCEPTION! Session closed",
          "",
          "// Fix 1: Keep transaction open (@Transactional on service method)",
          "// Fix 2: Use JOIN FETCH",
          "// Fix 3: Initialize in query (JPQL fetch join)",
          "// Fix 4: DTO projection (best for read-only views)",
        ]},
        {t:"heading", v:"Cascade Types Explained"},
        {t:"code", lang:"java", v:[
          "// Cascade: propagate operations from parent to children",
          "",
          "// CascadeType.PERSIST — save parent also saves children",
          "Order order = new Order(customer);",
          "order.addItem(new OrderItem(product, 2));",
          "orderRepo.save(order);  // Also saves OrderItem automatically",
          "",
          "// CascadeType.MERGE — update parent also updates children",
          "",
          "// CascadeType.REMOVE — delete parent also deletes children",
          "orderRepo.delete(order);  // Also deletes all OrderItems",
          "",
          "// CascadeType.ALL = PERSIST + MERGE + REMOVE + REFRESH + DETACH",
          "// Safe for owned entities (Order owns OrderItems)",
          "// NEVER cascade to shared entities (Order shouldn't cascade to Product!)",
          "",
          "// orphanRemoval: delete child if removed from parent's collection",
          "@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)",
          "private List<OrderItem> items = new ArrayList<>();",
          "",
          "order.getItems().remove(item);  // Triggers DELETE for this item",
          "// Without orphanRemoval: item stays in DB but orphaned",
          "",
          "// RULE: CascadeType.ALL + orphanRemoval = true",
          "// for entities that are 'owned' by parent",
          "// (OrderItem owned by Order, Address owned by Customer)",
        ]},
      ]
    },
    {
      title: "Spring Batch — Bulk Data Processing", level: "Advanced",
      blocks: [
        {t:"text", v:"Spring Batch is the standard framework for batch processing in Java — processing large volumes of data in chunks. Use cases: nightly data migrations, monthly invoice generation, bulk imports/exports, ETL pipelines, payment reconciliation."},
        {t:"heading", v:"Spring Batch Architecture"},
        {t:"code", lang:"text", v:[
          "Job → one complete batch process",
          "  Step → one phase of the job (can have multiple steps)",
          "    ItemReader  → read data (DB, file, API)",
          "    ItemProcessor → transform/validate data",
          "    ItemWriter   → write results (DB, file, email)",
          "",
          "Chunk-Oriented Processing (the standard pattern):",
          "  1. Read N items one at a time",
          "  2. Accumulate into a chunk (e.g., chunk size = 100)",
          "  3. Process all items in the chunk",
          "  4. Write the entire chunk in one transaction",
          "  5. Repeat until all items processed",
          "",
          "Spring Batch tracks job state in its own DB tables:",
          "  BATCH_JOB_INSTANCE    — distinct job runs",
          "  BATCH_JOB_EXECUTION   — each execution attempt",
          "  BATCH_STEP_EXECUTION  — each step execution",
          "  On restart: resumes from last successful chunk!",
        ]},
        {t:"heading", v:"Complete Batch Job — Invoice Generation"},
        {t:"code", lang:"java", v:[
          "@Configuration",
          "@EnableBatchProcessing",
          "public class InvoiceGenerationJobConfig {",
          "",
          "    @Bean",
          "    public Job invoiceGenerationJob(JobRepository jobRepo, Step generateStep) {",
          "        return new JobBuilder(\"invoiceGenerationJob\", jobRepo)",
          "            .incrementer(new RunIdIncrementer())  // New run each time",
          "            .start(generateStep)",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    public Step generateInvoicesStep(JobRepository jobRepo,",
          "                                      PlatformTransactionManager txMgr) {",
          "        return new StepBuilder(\"generateInvoicesStep\", jobRepo)",
          "            .<Order, Invoice>chunk(100, txMgr)  // Process 100 at a time",
          "            .reader(completedOrdersReader())",
          "            .processor(invoiceProcessor())",
          "            .writer(invoiceWriter())",
          "            .faultTolerant()",
          "            .skipLimit(10)                      // Skip up to 10 bad records",
          "            .skip(DataIntegrityViolationException.class)",
          "            .retryLimit(3)                      // Retry transient errors",
          "            .retry(TransientDataAccessException.class)",
          "            .listener(new InvoiceStepListener())  // Log progress",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    @StepScope",
          "    public JpaPagingItemReader<Order> completedOrdersReader(",
          "            @Value(\"#{jobParameters['month']}\") String month) {",
          "        return new JpaPagingItemReaderBuilder<Order>()",
          "            .name(\"completedOrdersReader\")",
          "            .entityManagerFactory(emf)",
          "            .queryString(\"SELECT o FROM Order o WHERE o.status = 'COMPLETED'\" +",
          "                         \" AND FUNCTION('date_trunc','month',o.completedAt) =\" +",
          "                         \" FUNCTION('to_date',:month,'YYYY-MM')\")",
          "            .parameterValues(Map.of(\"month\", month))",
          "            .pageSize(100)",
          "            .build();",
          "    }",
          "",
          "    @Bean",
          "    public ItemProcessor<Order, Invoice> invoiceProcessor() {",
          "        return order -> {",
          "            if (order.getTotal().compareTo(BigDecimal.ZERO) <= 0) {",
          "                return null;  // null = skip this item",
          "            }",
          "            return invoiceService.generateFor(order);",
          "        };",
          "    }",
          "",
          "    @Bean",
          "    public JpaItemWriter<Invoice> invoiceWriter() {",
          "        return new JpaItemWriterBuilder<Invoice>()",
          "            .entityManagerFactory(emf)",
          "            .build();",
          "        // Writes 100 invoices per DB transaction",
          "    }",
          "}",
          "",
          "// Launch job (from scheduler or REST endpoint):",
          "@Service",
          "public class BatchJobLauncher {",
          "    public void runMonthlyInvoices(String month) {",
          "        JobParameters params = new JobParametersBuilder()",
          "            .addString(\"month\", month)",
          "            .addLong(\"timestamp\", System.currentTimeMillis())",
          "            .toJobParameters();",
          "        jobLauncher.run(invoiceGenerationJob, params);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Parallel Processing & Partitioning"},
        {t:"code", lang:"java", v:[
          "// Process multiple customer segments in PARALLEL:",
          "@Bean",
          "public Step partitionedStep(JobRepository jobRepo) {",
          "    return new StepBuilder(\"partitionedStep\", jobRepo)",
          "        .partitioner(\"workerStep\", rangePartitioner())",
          "        .step(workerStep())                  // Each partition runs this step",
          "        .gridSize(8)                          // 8 parallel partitions",
          "        .taskExecutor(new SimpleAsyncTaskExecutor())",
          "        .build();",
          "}",
          "",
          "@Bean",
          "public Partitioner rangePartitioner() {",
          "    return gridSize -> {",
          "        Map<String, ExecutionContext> partitions = new HashMap<>();",
          "        long totalOrders = orderRepo.count();",
          "        long chunkSize   = totalOrders / gridSize;",
          "        for (int i = 0; i < gridSize; i++) {",
          "            ExecutionContext ctx = new ExecutionContext();",
          "            ctx.putLong(\"minId\", i * chunkSize);",
          "            ctx.putLong(\"maxId\", (i + 1) * chunkSize - 1);",
          "            partitions.put(\"partition\" + i, ctx);",
          "        }",
          "        return partitions;",
          "    };",
          "}",
          "// Result: 8 threads each process 1/8 of the data simultaneously",
          "// 10M records / 8 threads = 8x faster than sequential",
        ]},
      ]
    },
    {
      title: "Testing — JUnit5, Mockito & Spring Test", level: "Intermediate",
      blocks: [
        {t:"text", v:"Testing is not optional — it is what separates professional code from amateur code. A comprehensive test suite lets you refactor fearlessly, deploy confidently, and sleep at night. This covers the full testing pyramid for Spring Boot applications."},
        {t:"heading", v:"Testing Pyramid"},
        {t:"code", lang:"text", v:[
          "        ╔═══════════════╗",
          "        ║  E2E Tests    ║  Few, slow, test full system",
          "        ╠═══════════════╣  (Selenium, TestContainers full stack)",
          "        ║  Integration  ║  Some, test layers together",
          "        ║  Tests        ║  (@SpringBootTest, @DataJpaTest)",
          "        ╠═══════════════╣",
          "        ║  Unit Tests   ║  Many, fast, test one class",
          "        ║               ║  (JUnit5 + Mockito, no Spring context)",
          "        ╚═══════════════╝",
          "",
          "Rule of thumb: 70% unit, 20% integration, 10% E2E",
        ]},
        {t:"heading", v:"Unit Testing with JUnit5 & Mockito"},
        {t:"code", lang:"java", v:[
          "@ExtendWith(MockitoExtension.class)",
          "class OrderServiceTest {",
          "",
          "    @Mock private OrderRepository orderRepo;",
          "    @Mock private PaymentService   paymentService;",
          "    @Mock private EmailService     emailService;",
          "    @InjectMocks private OrderService orderService;",
          "",
          "    @Test",
          "    @DisplayName(\"Should create order and send confirmation when payment succeeds\")",
          "    void createOrder_whenPaymentSucceeds_shouldSaveOrderAndSendEmail() {",
          "        // ARRANGE (Given)",
          "        CreateOrderRequest req = new CreateOrderRequest(\"cust-1\",",
          "            List.of(new OrderItem(\"prod-1\", 2, BigDecimal.valueOf(99.99))));",
          "        Order savedOrder = new Order(1L, \"cust-1\", BigDecimal.valueOf(199.98));",
          "",
          "        when(orderRepo.save(any(Order.class))).thenReturn(savedOrder);",
          "        when(paymentService.charge(any())).thenReturn(PaymentResult.success(\"txn-1\"));",
          "",
          "        // ACT (When)",
          "        Order result = orderService.createOrder(req);",
          "",
          "        // ASSERT (Then)",
          "        assertThat(result.getId()).isEqualTo(1L);",
          "        assertThat(result.getTotal()).isEqualByComparingTo(\"199.98\");",
          "",
          "        verify(orderRepo, times(1)).save(any(Order.class));",
          "        verify(emailService, times(1)).sendOrderConfirmation(savedOrder);",
          "        verify(paymentService).charge(argThat(p ->",
          "            p.getAmount().compareTo(BigDecimal.valueOf(199.98)) == 0));",
          "    }",
          "",
          "    @Test",
          "    void createOrder_whenPaymentFails_shouldNotSaveOrder() {",
          "        when(paymentService.charge(any()))",
          "            .thenThrow(new PaymentFailedException(\"Card declined\"));",
          "",
          "        assertThatThrownBy(() -> orderService.createOrder(mockRequest()))",
          "            .isInstanceOf(PaymentFailedException.class)",
          "            .hasMessageContaining(\"Card declined\");",
          "",
          "        verify(orderRepo, never()).save(any());",
          "        verify(emailService, never()).sendOrderConfirmation(any());",
          "    }",
          "",
          "    @ParameterizedTest",
          "    @ValueSource(strings = { \"\", \"   \", \"invalid-email\" })",
          "    void createOrder_withInvalidCustomerId_shouldThrowValidationException(String id) {",
          "        assertThatThrownBy(() ->",
          "            orderService.createOrder(new CreateOrderRequest(id, List.of())))",
          "            .isInstanceOf(IllegalArgumentException.class);",
          "    }",
          "}",
        ]},
        {t:"heading", v:"Integration Testing with @SpringBootTest"},
        {t:"code", lang:"java", v:[
          "// Full Spring context — tests everything wired together",
          "@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)",
          "@AutoConfigureMockMvc",
          "@ActiveProfiles(\"test\")",
          "@Transactional  // Rollback after each test — keeps DB clean",
          "class OrderControllerIntegrationTest {",
          "",
          "    @Autowired private MockMvc mockMvc;",
          "    @Autowired private ObjectMapper objectMapper;",
          "    @Autowired private OrderRepository orderRepository;",
          "",
          "    @Test",
          "    void createOrder_withValidRequest_returns201WithOrderDetails() throws Exception {",
          "        CreateOrderRequest req = new CreateOrderRequest(",
          "            \"cust-123\",",
          "            List.of(new OrderItem(\"prod-1\", 2, BigDecimal.valueOf(50)))",
          "        );",
          "",
          "        mockMvc.perform(post(\"/api/v1/orders\")",
          "                .contentType(MediaType.APPLICATION_JSON)",
          "                .content(objectMapper.writeValueAsString(req))",
          "                .header(\"Authorization\", \"Bearer \" + getTestJwt()))",
          "            .andExpect(status().isCreated())",
          "            .andExpect(jsonPath(\"$.status\").value(\"PENDING\"))",
          "            .andExpect(jsonPath(\"$.total\").value(100.0))",
          "            .andExpect(jsonPath(\"$.customerId\").value(\"cust-123\"))",
          "            .andExpect(header().exists(\"Location\"));",
          "",
          "        assertThat(orderRepository.findAll()).hasSize(1);",
          "    }",
          "",
          "    @Test",
          "    void getOrder_withInvalidId_returns404() throws Exception {",
          "        mockMvc.perform(get(\"/api/v1/orders/99999\")",
          "                .header(\"Authorization\", \"Bearer \" + getTestJwt()))",
          "            .andExpect(status().isNotFound())",
          "            .andExpect(jsonPath(\"$.errorCode\").value(\"ORDER_NOT_FOUND\"));",
          "    }",
          "}",
          "",
          "// @DataJpaTest — test only JPA layer (faster)",
          "@DataJpaTest",
          "@AutoConfigureTestDatabase(replace = NONE)  // Use real DB",
          "class OrderRepositoryTest {",
          "    @Autowired private OrderRepository orderRepo;",
          "",
          "    @Test",
          "    void findByStatus_returnsPendingOrders() {",
          "        orderRepo.save(Order.pending(\"cust-1\"));",
          "        orderRepo.save(Order.pending(\"cust-2\"));",
          "        orderRepo.save(Order.shipped(\"cust-3\"));",
          "",
          "        List<Order> pending = orderRepo.findByStatus(OrderStatus.PENDING);",
          "        assertThat(pending).hasSize(2);",
          "    }",
          "}",
        ]},
      ]
    },
  ]
};

// ─── EXPANDED HIBERNATE TOPICS ───────────────────────────────────────
hibernateData.topics.push(

  {
    title: "Hibernate Caching — L1, L2 & Query Cache", level: "Advanced",
    blocks: [
      {t:"text", v:"Hibernate has a sophisticated multi-level caching system that can dramatically reduce database load. Understanding when and how to use each level separates junior developers from seniors. Incorrect caching is one of the most common sources of stale data bugs in production."},
      {t:"heading", v:"First Level Cache (Session Cache) — Always On"},
      {t:"code", lang:"java", v:[
        "// L1 Cache is automatic — scoped to one Session/EntityManager",
        "// Cannot be disabled",
        "",
        "@Service @Transactional",
        "public class OrderService {",
        "    public void demonstrateL1Cache() {",
        "        Order o1 = orderRepo.findById(42L).get();  // SELECT * FROM orders WHERE id=42",
        "        Order o2 = orderRepo.findById(42L).get();  // NO SQL — returned from L1 cache",
        "        Order o3 = entityManager.find(Order.class, 42L); // NO SQL",
        "",
        "        System.out.println(o1 == o2); // true — same object!",
        "        System.out.println(o1 == o3); // true — same object!",
        "    }",
        "    // L1 cache is CLEARED when:",
        "    // 1. Session/EntityManager closes (end of @Transactional method)",
        "    // 2. entityManager.clear() called",
        "    // 3. entityManager.evict(entity) called for specific entity",
        "    // 4. entityManager.flush() then entityManager.clear()",
        "}",
        "",
        "// L1 cache across sessions — does NOT work:",
        "public Order getInSession1(Long id) {",
        "    return entityManager.find(Order.class, id); // Query 1",
        "}",
        "public Order getInSession2(Long id) {",
        "    return entityManager.find(Order.class, id); // Query 2 — different session!",
        "}",
      ]},
      {t:"heading", v:"Second Level Cache (L2) — Cross-Session Shared Cache"},
      {t:"code", lang:"java", v:[
        "// L2 Cache: shared across all sessions in same JVM",
        "// Must be explicitly configured and enabled per entity",
        "",
        "// Step 1: Add Ehcache or Caffeine dependency",
        "// <dependency>",
        "//   <groupId>org.hibernate.orm</groupId>",
        "//   <artifactId>hibernate-jcache</artifactId>",
        "// </dependency>",
        "",
        "// Step 2: Enable in application.yml",
        "// spring.jpa.properties.hibernate.cache.use_second_level_cache: true",
        "// spring.jpa.properties.hibernate.cache.region.factory_class:",
        "//   org.hibernate.cache.jcache.JCacheRegionFactory",
        "",
        "// Step 3: Annotate entities to cache",
        "@Entity",
        "@Cache(usage = CacheConcurrencyStrategy.READ_WRITE) // Cache strategy",
        "public class Product {",
        "    @Id private Long id;",
        "    private String name;",
        "    private BigDecimal price;",
        "}",
        "",
        "// Cache Concurrency Strategies:",
        "// READ_ONLY:         Immutable data (reference data, categories)",
        "//                    Fastest, no locking overhead",
        "// READ_WRITE:        Mutable data with concurrent access",
        "//                    Uses soft locks to prevent stale reads",
        "// NONSTRICT_READ_WRITE: Mutable, rare updates, stale reads acceptable",
        "//                       No locking, slight risk of stale data",
        "// TRANSACTIONAL:     Full transaction isolation (JTA only)",
        "",
        "// Usage — L2 cache transparent to code:",
        "// Session 1:",
        "Product p1 = productRepo.findById(1L).get();  // DB query → stored in L2",
        "// Session 2 (different request, different user):",
        "Product p2 = productRepo.findById(1L).get();  // L2 cache hit — NO DB query!",
        "",
        "// Cache entity collections too:",
        "@OneToMany(mappedBy = \"product\")",
        "@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)",
        "private List<ProductImage> images;",
      ]},
      {t:"heading", v:"Query Cache — Cache JPQL Results"},
      {t:"code", lang:"java", v:[
        "// Query cache stores result sets (list of IDs), not entities",
        "// Works with L2 cache — IDs in query cache, entities in L2",
        "",
        "// Enable:",
        "// spring.jpa.properties.hibernate.cache.use_query_cache: true",
        "",
        "// Use in repository:",
        "public interface ProductRepository extends JpaRepository<Product, Long> {",
        "",
        "    @QueryHints(@QueryHint(name = HINT_CACHEABLE, value = \"true\"))",
        "    List<Product> findByCategory(String category);",
        "",
        "    @Query(\"SELECT p FROM Product p WHERE p.active = true\")",
        "    @QueryHints({",
        "        @QueryHint(name = HINT_CACHEABLE, value = \"true\"),",
        "        @QueryHint(name = HINT_CACHE_REGION, value = \"active-products\")",
        "    })",
        "    List<Product> findAllActive();",
        "}",
        "",
        "// Query cache invalidation:",
        "// When ANY product is updated/inserted/deleted,",
        "// ALL cached queries on Product are INVALIDATED automatically",
        "// This is why query cache is only useful for rarely-changing data",
        "",
        "// Statistics to monitor cache effectiveness:",
        "// spring.jpa.properties.hibernate.generate_statistics: true",
        "// Logs: SecondLevelCacheHitCount, QueryCacheHitCount, QueryCacheMissCount",
      ]},
      {t:"note", v:"L2 cache is a double-edged sword. Cache stale data = users see wrong information. Cache too aggressively = memory issues. Best candidates for L2 caching: reference/lookup data (countries, categories, product types), data that changes infrequently, data read much more than written. Never cache: financial transactions, inventory levels, user sessions."},
    ]
  },

  {
    title: "JPQL, Criteria API & Native Queries", level: "Intermediate",
    blocks: [
      {t:"text", v:"Hibernate provides three ways to query data: JPQL (object-oriented query language), Criteria API (type-safe programmatic queries), and Native SQL (raw database queries). Knowing when to use each is essential for production Java development."},
      {t:"heading", v:"JPQL — Java Persistence Query Language"},
      {t:"code", lang:"java", v:[
        "// JPQL operates on ENTITIES and FIELDS, not tables and columns",
        "// Hibernate translates to SQL based on your entity mappings",
        "",
        "// Basic JPQL in Spring Data repository:",
        "@Repository",
        "public interface OrderRepository extends JpaRepository<Order, Long> {",
        "",
        "    // Derived query (Spring generates JPQL automatically):",
        "    List<Order> findByStatusAndCustomerIdOrderByCreatedAtDesc(",
        "        OrderStatus status, Long customerId);",
        "",
        "    // Custom JPQL:",
        "    @Query(\"SELECT o FROM Order o WHERE o.total > :minAmount \" +",
        "           \"AND o.createdAt > :since ORDER BY o.total DESC\")",
        "    List<Order> findHighValueRecentOrders(",
        "        @Param(\"minAmount\") BigDecimal minAmount,",
        "        @Param(\"since\") Instant since);",
        "",
        "    // JOIN with fetch (solve N+1):",
        "    @Query(\"SELECT DISTINCT o FROM Order o \" +",
        "           \"JOIN FETCH o.customer c \" +",
        "           \"JOIN FETCH o.items i \" +",
        "           \"WHERE o.status = :status\")",
        "    List<Order> findWithCustomerAndItems(@Param(\"status\") OrderStatus status);",
        "",
        "    // Aggregation in JPQL:",
        "    @Query(\"SELECT o.status, COUNT(o), SUM(o.total) \" +",
        "           \"FROM Order o GROUP BY o.status\")",
        "    List<Object[]> getOrderStatsByStatus();",
        "",
        "    // Constructor expression — map to DTO directly:",
        "    @Query(\"SELECT new com.myapp.dto.OrderSummary(o.id, o.status, \" +",
        "           \"o.total, c.name) FROM Order o JOIN o.customer c \" +",
        "           \"WHERE o.customerId = :customerId\")",
        "    List<OrderSummary> findSummariesByCustomer(@Param(\"customerId\") Long id);",
        "",
        "    // Bulk UPDATE (does NOT trigger entity lifecycle events):",
        "    @Modifying @Transactional",
        "    @Query(\"UPDATE Order o SET o.status = :newStatus \" +",
        "           \"WHERE o.status = :oldStatus AND o.createdAt < :before\")",
        "    int bulkUpdateStatus(@Param(\"newStatus\") OrderStatus newStatus,",
        "                         @Param(\"oldStatus\") OrderStatus oldStatus,",
        "                         @Param(\"before\") Instant before);",
        "}",
      ]},
      {t:"heading", v:"Criteria API — Type-Safe Dynamic Queries"},
      {t:"code", lang:"java", v:[
        "// Criteria API: programmatic, compile-time type-safe queries",
        "// Best for: complex dynamic queries where conditions vary at runtime",
        "",
        "@Service",
        "public class OrderSearchService {",
        "    private final EntityManager em;",
        "",
        "    public List<Order> search(OrderSearchRequest req) {",
        "        CriteriaBuilder cb  = em.getCriteriaBuilder();",
        "        CriteriaQuery<Order> cq = cb.createQuery(Order.class);",
        "        Root<Order> order   = cq.from(Order.class);",
        "",
        "        // Fetch join to avoid N+1:",
        "        order.fetch(\"customer\", JoinType.LEFT);",
        "        order.fetch(\"items\",    JoinType.LEFT);",
        "",
        "        // Build predicates dynamically:",
        "        List<Predicate> predicates = new ArrayList<>();",
        "",
        "        if (req.getStatus() != null) {",
        "            predicates.add(cb.equal(order.get(\"status\"), req.getStatus()));",
        "        }",
        "        if (req.getCustomerId() != null) {",
        "            predicates.add(cb.equal(",
        "                order.get(\"customer\").get(\"id\"), req.getCustomerId()));",
        "        }",
        "        if (req.getMinTotal() != null) {",
        "            predicates.add(cb.greaterThanOrEqualTo(",
        "                order.get(\"total\"), req.getMinTotal()));",
        "        }",
        "        if (req.getFromDate() != null) {",
        "            predicates.add(cb.greaterThan(",
        "                order.get(\"createdAt\"), req.getFromDate()));",
        "        }",
        "        if (req.getSearchText() != null) {",
        "            predicates.add(cb.or(",
        "                cb.like(cb.lower(order.get(\"customer\").get(\"name\")),",
        "                        \"%\" + req.getSearchText().toLowerCase() + \"%\"),",
        "                cb.like(cb.lower(order.get(\"referenceNumber\")),",
        "                        \"%\" + req.getSearchText().toLowerCase() + \"%\")",
        "            ));",
        "        }",
        "",
        "        cq.select(order).distinct(true)",
        "          .where(predicates.toArray(new Predicate[0]))",
        "          .orderBy(cb.desc(order.get(\"createdAt\")));",
        "",
        "        return em.createQuery(cq)",
        "                 .setFirstResult(req.getPage() * req.getSize())",
        "                 .setMaxResults(req.getSize())",
        "                 .getResultList();",
        "    }",
        "}",
        "",
        "// Spring Data Specifications (cleaner alternative to raw Criteria API):",
        "public class OrderSpecifications {",
        "    public static Specification<Order> hasStatus(OrderStatus status) {",
        "        return (root, q, cb) -> status == null ? null",
        "            : cb.equal(root.get(\"status\"), status);",
        "    }",
        "    public static Specification<Order> byCustomer(Long customerId) {",
        "        return (root, q, cb) -> customerId == null ? null",
        "            : cb.equal(root.get(\"customerId\"), customerId);",
        "    }",
        "    public static Specification<Order> totalBetween(BigDecimal min, BigDecimal max) {",
        "        return (root, q, cb) -> cb.between(root.get(\"total\"), min, max);",
        "    }",
        "}",
        "",
        "// Usage:",
        "Page<Order> results = orderRepo.findAll(",
        "    Specification.where(hasStatus(PENDING))",
        "                 .and(byCustomer(customerId))",
        "                 .and(totalBetween(new BigDecimal(\"100\"), new BigDecimal(\"1000\"))),",
        "    PageRequest.of(0, 20));",
      ]},
      {t:"heading", v:"Native SQL Queries — When JPQL Is Not Enough"},
      {t:"code", lang:"java", v:[
        "// Use native SQL for:",
        "// - Database-specific features (PostgreSQL window functions, Oracle CONNECT BY)",
        "// - Complex queries JPQL can't express",
        "// - Performance-critical queries needing specific SQL",
        "// - Stored procedure calls",
        "",
        "// Native query in Spring Data:",
        "@Query(value = \"SELECT o.*, c.name as customer_name \" +",
        "               \"FROM orders o \" +",
        "               \"JOIN customers c ON o.customer_id = c.id \" +",
        "               \"WHERE o.total > :minAmount \" +",
        "               \"ORDER BY o.total DESC \" +",
        "               \"LIMIT :limit OFFSET :offset\",",
        "       nativeQuery = true)",
        "List<Object[]> findTopOrders(@Param(\"minAmount\") BigDecimal min,",
        "                              @Param(\"limit\") int limit,",
        "                              @Param(\"offset\") int offset);",
        "",
        "// Map native query to DTO via interface projection:",
        "public interface OrderNativeSummary {",
        "    Long getId();",
        "    String getStatus();",
        "    BigDecimal getTotal();",
        "    String getCustomerName();  // From JOIN",
        "}",
        "",
        "@Query(value = \"SELECT o.id, o.status, o.total, c.name as customer_name \" +",
        "               \"FROM orders o JOIN customers c ON o.customer_id = c.id \" +",
        "               \"WHERE o.created_at > :since\",",
        "       nativeQuery = true)",
        "List<OrderNativeSummary> findRecentOrderSummaries(@Param(\"since\") Instant since);",
        "",
        "// Stored procedure call:",
        "@Procedure(procedureName = \"calculate_customer_score\")",
        "Integer calculateScore(@Param(\"customer_id\") Long customerId);",
        "",
        "// Or via EntityManager:",
        "StoredProcedureQuery spq = em.createStoredProcedureQuery(\"sp_process_batch\");",
        "spq.registerStoredProcedureParameter(\"batch_date\", Date.class, ParameterMode.IN);",
        "spq.registerStoredProcedureParameter(\"processed_count\", Integer.class, ParameterMode.OUT);",
        "spq.setParameter(\"batch_date\", Date.valueOf(LocalDate.now()));",
        "spq.execute();",
        "Integer count = (Integer) spq.getOutputParameterValue(\"processed_count\");",
      ]},
    ]
  },

  {
    title: "Hibernate Performance Tuning & Common Pitfalls", level: "Advanced",
    blocks: [
      {t:"text", v:"Hibernate performance issues are the most common source of slow Java applications. These are the patterns that senior developers recognise immediately and junior developers spend weeks debugging."},
      {t:"heading", v:"Detecting Performance Problems"},
      {t:"code", lang:"yaml", v:[
        "# application.yml — enable SQL logging in development",
        "spring:",
        "  jpa:",
        "    show-sql: true",
        "    properties:",
        "      hibernate:",
        "        format_sql: true",
        "        generate_statistics: true",
        "        # Log slow queries (>500ms):",
        "        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 500",
        "",
        "logging:",
        "  level:",
        "    org.hibernate.SQL: DEBUG",
        "    org.hibernate.type.descriptor.sql: TRACE  # Log parameter values",
        "    org.hibernate.stat: DEBUG                 # Session statistics",
        "",
        "# Count SQL queries in tests using datasource-proxy:",
        "# <dependency>",
        "#   <groupId>net.ttddyy</groupId>",
        "#   <artifactId>datasource-proxy</artifactId>",
        "# </dependency>",
      ]},
      {t:"heading", v:"Pitfall 1 — The N+1 Problem (Deep Dive)"},
      {t:"code", lang:"java", v:[
        "// N+1 in 5 different forms — recognize all of them!",
        "",
        "// Form 1: Classic LAZY collection access in loop",
        "List<Customer> customers = customerRepo.findAll();  // 1 query",
        "customers.forEach(c -> c.getOrders().size());      // N queries",
        "// FIX: JOIN FETCH or @EntityGraph",
        "",
        "// Form 2: EAGER fetch causing unnecessary JOINs",
        "@ManyToOne(fetch = FetchType.EAGER)  // WRONG default!",
        "private Customer customer;",
        "// Every Order query now ALWAYS JOINs customers even when not needed",
        "// FIX: Change to LAZY (always!), JOIN FETCH only when needed",
        "",
        "// Form 3: ManyToMany causing duplicate rows",
        "@ManyToMany",
        "private List<Tag> tags;  // Use List with JOIN FETCH → Cartesian product!",
        "// Order with 3 items × 4 tags = 12 rows in result set",
        "// FIX: Use Set<Tag> instead of List<Tag> for @ManyToMany",
        "",
        "// Form 4: Open Session in View anti-pattern",
        "// spring.jpa.open-in-view: true (DEFAULT — change this!)",
        "// Keeps session open during view rendering → lazy loads in templates",
        "// Triggers N+1 in Thymeleaf/JSP templates silently!",
        "// FIX: spring.jpa.open-in-view: false + use DTOs in controllers",
        "",
        "// Form 5: @OneToOne bidirectional — always EAGER on inverse side",
        "@Entity public class Order {",
        "    @OneToOne(mappedBy = \"order\", fetch = FetchType.LAZY) // Still EAGER!",
        "    private Invoice invoice; // Hibernate can't make inverse OneToOne lazy",
        "}",
        "// FIX: Use @LazyToOne(LazyToOneOption.NO_PROXY) with bytecode enhancement",
        "// Or: Use @MapsId instead of bidirectional @OneToOne",
      ]},
      {t:"heading", v:"Pitfall 2 — Dirty Checking Performance"},
      {t:"code", lang:"java", v:[
        "// Dirty checking: Hibernate compares ALL persistent entities on flush",
        "// Problem: Loading 10,000 entities in one session is very expensive",
        "",
        "// BAD: Load everything, Hibernate tracks all 10k entities:",
        "@Transactional",
        "public void processAll() {",
        "    List<Product> products = productRepo.findAll(); // 10,000 products tracked!",
        "    products.forEach(p -> {",
        "        if (needsUpdate(p)) p.setPrice(calculateNewPrice(p));",
        "    });",
        "} // On commit: compare all 10,000 for changes → slow!",
        "",
        "// GOOD Option 1: Bulk UPDATE — no entity loading",
        "@Modifying @Transactional",
        "@Query(\"UPDATE Product p SET p.price = p.price * 1.1 WHERE p.category = :cat\")",
        "int bulkPriceIncrease(@Param(\"cat\") String category);",
        "",
        "// GOOD Option 2: Process in batches, clear session between batches",
        "@Transactional",
        "public void processBatched() {",
        "    int page = 0, batchSize = 100;",
        "    List<Product> batch;",
        "    do {",
        "        batch = productRepo.findAll(PageRequest.of(page++, batchSize)).getContent();",
        "        batch.forEach(p -> { if (needsUpdate(p)) p.setPrice(newPrice(p)); });",
        "        entityManager.flush();   // Write changes",
        "        entityManager.clear();  // Clear session — free memory, stop tracking",
        "    } while (batch.size() == batchSize);",
        "}",
        "",
        "// GOOD Option 3: Read-only queries (no dirty checking at all)",
        "@Transactional(readOnly = true)",
        "public List<ProductDto> getProductDtos() {",
        "    return productRepo.findAll().stream()",
        "        .map(productMapper::toDto)",
        "        .collect(Collectors.toList());",
        "    // readOnly=true: Hibernate skips dirty checking on flush",
        "}",
      ]},
      {t:"heading", v:"Hibernate Batch Insert/Update Configuration"},
      {t:"code", lang:"yaml", v:[
        "spring:",
        "  jpa:",
        "    properties:",
        "      hibernate:",
        "        # Enable JDBC batch operations:",
        "        jdbc.batch_size: 50          # Send 50 statements per DB round-trip",
        "        order_inserts: true          # Reorder inserts for same entity type",
        "        order_updates: true          # Reorder updates for same entity type",
        "        jdbc.batch_versioned_data: true  # Allow batching of versioned entities",
        "",
        "# Without batching: 1000 inserts = 1000 round-trips to DB",
        "# With batching (size=50): 1000 inserts = 20 round-trips",
        "# Up to 50x faster for bulk operations!",
        "",
        "# IMPORTANT: Use SEQUENCE for IDs (not IDENTITY/AUTO_INCREMENT)",
        "# IDENTITY strategy disables batching (DB must return ID after each insert)",
        "# SEQUENCE pre-allocates IDs → batching works",
        "# @SequenceGenerator(allocationSize=50) — matches batch_size",
      ]},
      {t:"code", lang:"java", v:[
        "// Verify batching is working — check Hibernate statistics:",
        "@Component",
        "public class HibernateStats implements ApplicationListener<ContextRefreshedEvent> {",
        "    @Autowired private EntityManagerFactory emf;",
        "",
        "    public void printStats() {",
        "        Statistics stats = emf.unwrap(SessionFactory.class).getStatistics();",
        "        log.info(\"Entity loads:         {}\", stats.getEntityLoadCount());",
        "        log.info(\"Collection loads:     {}\", stats.getCollectionLoadCount());",
        "        log.info(\"Query executions:     {}\", stats.getQueryExecutionCount());",
        "        log.info(\"L2 cache hit ratio:   {}\", stats.getSecondLevelCacheHitCount());",
        "        log.info(\"Transactions:         {}\", stats.getTransactionCount());",
        "    }",
        "}",
      ]},
    ]
  },

  {
    title: "Hibernate Interview Questions — Complete Guide", level: "Advanced",
    blocks: [
      {t:"text", v:"These are the exact Hibernate/JPA questions asked at companies like TCS, Infosys, Wipro, Cognizant, Goldman Sachs, and product companies. Master every one of these with the cross-questions."},
      {t:"heading", v:"Q1: What is the difference between get() and load() in Hibernate?"},
      {t:"code", lang:"java", v:[
        "// get() → Immediate database hit, returns null if not found",
        "Order order1 = session.get(Order.class, 999L);",
        "// SQL: SELECT * FROM orders WHERE id = 999",
        "// If not found: returns null immediately",
        "// Use when: you need to check if entity exists",
        "",
        "// load() → Returns a PROXY (lazy placeholder), throws exception if not found",
        "Order order2 = session.load(Order.class, 999L);",
        "// NO SQL yet! Just creates a proxy object",
        "// SQL fires only when you ACCESS a property:",
        "System.out.println(order2.getStatus()); // SQL fires HERE",
        "// If not found: throws ObjectNotFoundException (not null!)",
        "// Use when: you only need a reference (e.g., to set as FK)",
        "",
        "// Modern Spring Data equivalents:",
        "orderRepo.findById(999L);       // Like get() — returns Optional",
        "orderRepo.getReferenceById(999L); // Like load() — returns proxy",
        "",
        "// Real use case for getReferenceById (no SELECT needed):",
        "Order order = new Order();",
        "order.setCustomer(customerRepo.getReferenceById(customerId));",
        "// No SELECT on customers table — just sets FK value",
        "orderRepo.save(order); // Only INSERT needed",
      ]},
      {t:"note", v:"Cross Question: 'What is a Hibernate proxy?' → A proxy is a subclass of your entity created dynamically by Hibernate (using ByteBuddy or Javassist). It overrides all methods to check if data is loaded. If not loaded, it triggers a SELECT. The proxy shares the same ID as the real entity. Cross Question: 'Why would getReferenceById() throw LazyInitializationException?' → If you call it outside a transaction and then access a field, the session is closed. Always access proxy properties within an active transaction."},

      {t:"heading", v:"Q2: What is the difference between save(), persist(), saveOrUpdate(), merge()?"},
      {t:"code", lang:"java", v:[
        "// save() — Hibernate-specific, returns generated Serializable ID",
        "Long id = (Long) session.save(order); // Always INSERT",
        "",
        "// persist() — JPA standard, void return, deferred INSERT",
        "entityManager.persist(order); // May not INSERT immediately — waits for flush",
        "// Difference: persist() must be in transaction; save() doesn't require it",
        "",
        "// saveOrUpdate() — Hibernate specific, INSERT or UPDATE based on ID",
        "session.saveOrUpdate(order);",
        "// order.id == null  → INSERT",
        "// order.id != null  → UPDATE (or SELECT + UPDATE)",
        "",
        "// merge() — JPA standard, handles DETACHED entities",
        "Order detachedOrder = loadFromCacheOrSession();",
        "detachedOrder.setStatus(OrderStatus.SHIPPED); // Modified while detached",
        "Order managedOrder = entityManager.merge(detachedOrder);",
        "// merge() copies state from detached → managed entity",
        "// Returns a NEW managed instance (the original stays detached!)",
        "// DON'T use the original object after merge — use the returned one",
        "",
        "// Spring Data save() — combines all of the above:",
        "// entity.id == null  → calls persist() (INSERT)",
        "// entity.id != null  → calls merge()   (UPDATE)",
        "orderRepo.save(order); // Use this in Spring Boot always",
      ]},
      {t:"note", v:"Cross Question: 'When does Hibernate flush to the database?' → FlushMode.AUTO (default): before query execution (to ensure query sees latest changes) and at transaction commit. FlushMode.COMMIT: only at transaction commit. FlushMode.MANUAL: only when flush() explicitly called. Cross Question: 'What is the difference between flush() and commit()?' → flush() writes changes to DB but does NOT commit the transaction (other transactions still can't see it). commit() both flushes AND commits (makes changes permanent and visible)."},

      {t:"heading", v:"Q3: Explain @OneToMany with mappedBy — what is the owning side?"},
      {t:"code", lang:"java", v:[
        "// In a bidirectional relationship, ONE side owns the FK in the database.",
        "// The NON-owning side uses mappedBy pointing to the OWNING side's field.",
        "",
        "// OWNING SIDE: the side with @JoinColumn (has the FK in DB)",
        "@Entity",
        "public class OrderItem {",
        "    @ManyToOne(fetch = FetchType.LAZY)",
        "    @JoinColumn(name = \"order_id\") // This side OWNS the FK column",
        "    private Order order;",
        "}",
        "",
        "// NON-OWNING SIDE: uses mappedBy (NO FK column in this table)",
        "@Entity",
        "public class Order {",
        "    @OneToMany(mappedBy = \"order\") // 'order' = field name in OrderItem",
        "    private List<OrderItem> items = new ArrayList<>();",
        "}",
        "",
        "// CRITICAL: Hibernate only looks at the OWNING SIDE to persist the relationship!",
        "",
        "// WRONG — only setting the non-owning side:",
        "Order order = new Order();",
        "OrderItem item = new OrderItem();",
        "order.getItems().add(item); // Non-owning side — Hibernate IGNORES this!",
        "// Result: item.order_id = NULL in database!",
        "",
        "// CORRECT — must set the owning side:",
        "item.setOrder(order);    // Owning side — Hibernate uses this",
        "order.getItems().add(item); // Optional but needed for in-memory consistency",
        "",
        "// Best practice: use helper methods on the parent:",
        "public void addItem(OrderItem item) {",
        "    items.add(item);",
        "    item.setOrder(this); // Always set BOTH sides",
        "}",
      ]},
      {t:"note", v:"Cross Question: 'What is the difference between cascade REMOVE and orphanRemoval?' → CascadeType.REMOVE: deleting parent also deletes children. orphanRemoval=true: removing a child from the parent's collection triggers DELETE for that child (even without deleting the parent). orphanRemoval=true implies CascadeType.REMOVE, but is more powerful. Cross Question: 'Can you have cascade ALL on @ManyToMany?' → Technically yes but highly dangerous. CascadeType.REMOVE on @ManyToMany would delete the shared entity when you remove it from one side, potentially breaking all other associations."},

      {t:"heading", v:"Q4: What is Hibernate's dirty checking and how does it work internally?"},
      {t:"code", lang:"java", v:[
        "// Dirty checking: Hibernate automatically detects changed entities",
        "// and generates UPDATE SQL — no explicit save() needed for managed entities",
        "",
        "@Transactional",
        "public void updateOrderStatus(Long orderId, OrderStatus newStatus) {",
        "    Order order = orderRepo.findById(orderId).orElseThrow();",
        "    // order is now MANAGED by Hibernate",
        "",
        "    order.setStatus(newStatus); // Just set — no save() call!",
        "",
        "} // On transaction commit: Hibernate detects change, generates:",
        "  // UPDATE orders SET status='SHIPPED' WHERE id=42 AND version=3",
        "",
        "// How dirty checking works internally:",
        "// 1. On load: Hibernate takes a SNAPSHOT of entity state",
        "// 2. On flush: Compares CURRENT state with SNAPSHOT",
        "// 3. If different: generates UPDATE SQL for changed columns",
        "",
        "// Performance concern: large sessions with many entities",
        "@Transactional",
        "public void processMany() {",
        "    List<Order> all = orderRepo.findAll(); // 10k orders tracked!",
        "    // On flush: compare all 10k orders field by field = slow",
        "}",
        "",
        "// Disable dirty checking for read-only operations:",
        "@Transactional(readOnly = true) // Hibernate skips dirty check",
        "public List<OrderDto> getDashboard() { ... }",
        "",
        "// Or selectively:",
        "session.setReadOnly(order, true); // This entity won't be dirty-checked",
        "",
        "// @DynamicUpdate — only update changed columns (not all):",
        "@Entity @DynamicUpdate",
        "public class Order { ... }",
        "// Without @DynamicUpdate: UPDATE orders SET status=?, total=?, created_at=? WHERE id=?",
        "// With @DynamicUpdate:    UPDATE orders SET status=? WHERE id=?",
        "// Useful for wide tables with many columns",
      ]},
      {t:"note", v:"Cross Question: 'What is the difference between @DynamicInsert and @DynamicUpdate?' → @DynamicInsert: only includes non-null columns in INSERT statement (useful when columns have DB-level defaults). @DynamicUpdate: only includes modified columns in UPDATE (reduces data sent to DB, avoids lock contention on unmodified columns). Both have overhead of building dynamic SQL each time vs reusing cached SQL."},

      {t:"heading", v:"Q5: What are the different inheritance mapping strategies in JPA?"},
      {t:"code", lang:"java", v:[
        "// 3 strategies to map class hierarchies to database tables:",
        "",
        "// STRATEGY 1: SINGLE_TABLE (default, fastest)",
        "// All classes in hierarchy → ONE table with a discriminator column",
        "@Entity",
        "@Inheritance(strategy = InheritanceType.SINGLE_TABLE)",
        "@DiscriminatorColumn(name = \"payment_type\", discriminatorType = DiscriminatorType.STRING)",
        "public abstract class Payment {",
        "    @Id @GeneratedValue private Long id;",
        "    private BigDecimal amount;",
        "}",
        "",
        "@Entity @DiscriminatorValue(\"CREDIT_CARD\")",
        "public class CreditCardPayment extends Payment {",
        "    private String cardLastFour;",
        "    private String cardBrand;",
        "    // These columns are NULL for other payment types",
        "}",
        "",
        "@Entity @DiscriminatorValue(\"UPI\")",
        "public class UPIPayment extends Payment {",
        "    private String upiId;",
        "}",
        "// PRO: No JOINs, simple queries, fast",
        "// CON: Many nullable columns, can't add NOT NULL constraints on subtype fields",
        "",
        "// STRATEGY 2: TABLE_PER_CLASS",
        "// Each concrete class → separate table with ALL columns",
        "@Entity",
        "@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)",
        "public abstract class Payment { ... }",
        "// Tables: credit_card_payment (id, amount, card_last_four, card_brand)",
        "//          upi_payment        (id, amount, upi_id)",
        "// PRO: No nullable columns, no JOINs for single type query",
        "// CON: Polymorphic queries use UNION ALL (slow), IDs must be globally unique",
        "",
        "// STRATEGY 3: JOINED (most normalized)",
        "// Each class → separate table, parent columns in parent table",
        "@Entity",
        "@Inheritance(strategy = InheritanceType.JOINED)",
        "public abstract class Payment { ... }",
        "// Tables: payment (id, amount)",
        "//          credit_card_payment (id FK, card_last_four, card_brand)",
        "//          upi_payment         (id FK, upi_id)",
        "// PRO: Fully normalized, proper NOT NULL constraints",
        "// CON: Every query requires JOINs, complex schema",
      ]},
      {t:"note", v:"Cross Question: 'Which strategy do you recommend in production?' → SINGLE_TABLE for simple hierarchies (2-3 subtypes, few extra fields) — best performance. JOINED for complex hierarchies where normalization matters (many subtypes, many unique fields, need DB constraints). TABLE_PER_CLASS — rarely recommended in practice due to UNION ALL performance and ID management complexity."},

      {t:"heading", v:"Q6: What is optimistic vs pessimistic locking? When to use each?"},
      {t:"code", lang:"java", v:[
        "// OPTIMISTIC LOCKING: 'I assume no conflict, check at commit time'",
        "@Entity",
        "public class Product {",
        "    @Version  // Magic column — Hibernate auto-increments on each UPDATE",
        "    private Long version;",
        "    private int stockQuantity;",
        "}",
        "",
        "// Thread A and Thread B both load Product with version=5:",
        "// Thread A: product.stockQuantity-- → tries to UPDATE WHERE version=5",
        "// Thread B: product.stockQuantity-- → tries to UPDATE WHERE version=5",
        "// Thread A commits first: version becomes 6",
        "// Thread B tries: UPDATE WHERE version=5 → 0 rows updated!",
        "// Hibernate throws OptimisticLockException",
        "",
        "// Handle in service:",
        "public void decrementStock(Long productId) {",
        "    for (int attempt = 0; attempt < 3; attempt++) {",
        "        try {",
        "            Product p = productRepo.findById(productId).orElseThrow();",
        "            if (p.getStockQuantity() <= 0) throw new OutOfStockException();",
        "            p.setStockQuantity(p.getStockQuantity() - 1);",
        "            productRepo.save(p);",
        "            return; // Success",
        "        } catch (OptimisticLockException e) {",
        "            if (attempt == 2) throw new ConcurrentModificationException();",
        "            // Retry",
        "        }",
        "    }",
        "}",
        "",
        "// PESSIMISTIC LOCKING: 'Lock the row immediately — others must wait'",
        "@Lock(LockModeType.PESSIMISTIC_WRITE)",
        "Optional<Product> findByIdForUpdate(Long id);",
        "// Generates: SELECT * FROM products WHERE id=? FOR UPDATE",
        "// Database-level row lock — other transactions block until this commits",
        "",
        "// When to use which?",
        "// Optimistic:  Read-heavy, conflicts rare, user can retry (e-commerce cart)",
        "// Pessimistic: Write-heavy, conflicts frequent, can't retry (bank transfer)",
        "// Optimistic is usually preferred — scales better, no deadlock risk",
      ]},
      {t:"note", v:"Cross Question: 'What is a deadlock and how do you prevent it with Hibernate?' → Deadlock: Transaction A locks row 1 and waits for row 2; Transaction B locks row 2 and waits for row 1 — both wait forever. Prevention: always acquire locks in same ORDER (e.g., always lock by ascending ID), use @Lock(PESSIMISTIC_WRITE) with findById (not findAll then lock), set lock timeout: @QueryHint(name='javax.persistence.lock.timeout', value='3000')."},

      {t:"heading", v:"Q7: What is the Open Session in View pattern and why is it controversial?"},
      {t:"code", lang:"java", v:[
        "// Open Session in View (OSIV):",
        "// Keeps Hibernate Session open for the ENTIRE HTTP request lifecycle",
        "// (including view rendering in templates)",
        "",
        "// spring.jpa.open-in-view: true (DEFAULT in Spring Boot!)",
        "",
        "// What it allows:",
        "@Controller",
        "public class OrderController {",
        "    @GetMapping(\"/orders/{id}\")",
        "    public String getOrder(@PathVariable Long id, Model model) {",
        "        Order order = orderService.findById(id);",
        "        model.addAttribute(\"order\", order);",
        "        return \"order-detail\"; // Template rendered AFTER service method returns",
        "    }",
        "}",
        "// order-detail.html: {{ order.customer.name }}",
        "// OSIV=true: session still open during template rendering",
        "// → LAZY customer loads silently in the template layer ← This is bad!",
        "",
        "// WHY it's controversial:",
        "// PRO: Convenient — no LazyInitializationException in views",
        "// CON 1: Hides N+1 problems (lazy loads in templates are invisible)",
        "// CON 2: Session held open for entire request → DB connection held longer",
        "// CON 3: Business logic bleeds into view layer",
        "// CON 4: Under load: connection pool exhausted (each request holds a connection)",
        "",
        "// Best practice: DISABLE OSIV in production",
        "// spring.jpa.open-in-view: false",
        "",
        "// Fix controllers to return DTOs (not entities) to views:",
        "public String getOrder(@PathVariable Long id, Model model) {",
        "    OrderDetailDto dto = orderService.findByIdAsDto(id); // DTO with all data loaded",
        "    model.addAttribute(\"order\", dto);  // No lazy loading needed in template",
        "    return \"order-detail\";",
        "}",
      ]},
      {t:"note", v:"Cross Question: 'How do you fix LazyInitializationException without OSIV?' → Three approaches: 1) Use DTOs — map entity to DTO inside @Transactional service method (load all needed data while session is open). 2) Use JOIN FETCH or @EntityGraph to eagerly load only what you need for this specific use case. 3) Use projections (interface-based) that directly map needed columns. The DTO approach is the cleanest for most REST APIs."},
    ]
  }
);
