export const systemDesignData = {
  id: "system-design", icon: "🏗️", title: "System Design", color: "#10b981", accent: "#34d399",
  topics: [
    {
      title: "System Design Fundamentals", level: "Intermediate",
      blocks: [
        {t:"text", v:"System design is about making architectural decisions that allow your application to be reliable, scalable, and maintainable. These skills are tested in senior engineer interviews and applied every day in production engineering."},
        {t:"heading", v:"The RESHADED Framework for Design Interviews"},
        {t:"code", lang:"text", v:[
          "R — Requirements clarification (functional + non-functional)",
          "E — Estimation (scale, storage, bandwidth, QPS)",
          "S — Storage schema (database choice + data model)",
          "H — High-level design (components + interactions)",
          "A — API design (endpoints, contracts)",
          "D — Deep dive (bottlenecks, scaling, edge cases)",
          "E — Evaluation (trade-offs, what you'd do differently)",
          "D — Done? Ask interviewer what to explore further",
          "",
          "Always start with requirements — never jump to solutions.",
          "A solution without requirements is just guessing.",
        ]},
        {t:"heading", v:"Scalability Fundamentals"},
        {t:"code", lang:"text", v:[
          "VERTICAL SCALING (Scale Up):",
          "  Add more CPU/RAM/storage to existing machine",
          "  Simple — no code changes needed",
          "  Limited — single machine has a ceiling",
          "  Single point of failure",
          "  Best for: databases (easier than sharding)",
          "",
          "HORIZONTAL SCALING (Scale Out):",
          "  Add more machines, distribute load",
          "  Virtually unlimited scale",
          "  Requires stateless services (no local session state)",
          "  Needs load balancer in front",
          "  Best for: stateless API servers",
          "",
          "STATELESS SERVICES (critical for horizontal scaling):",
          "  Store NO state on the server itself",
          "  Session data → Redis",
          "  File uploads → S3 / object storage",
          "  User authentication → JWT (self-contained)",
          "  Any server can handle any request → easy horizontal scale",
        ]},
        {t:"heading", v:"CAP Theorem — The Fundamental Trade-off"},
        {t:"code", lang:"text", v:[
          "In a distributed system, you can guarantee only 2 of 3:",
          "",
          "C — Consistency: All nodes see the same data at the same time",
          "A — Availability: Every request gets a response (may not be latest)",
          "P — Partition Tolerance: System works even when network splits",
          "",
          "Since network partitions are inevitable in distributed systems,",
          "you must choose between C and A:",
          "",
          "CP (Consistency + Partition Tolerance):",
          "  Return error rather than stale data",
          "  Examples: HBase, MongoDB (with strong consistency), ZooKeeper",
          "  Use when: financial transactions, inventory, anything with money",
          "",
          "AP (Availability + Partition Tolerance):",
          "  Return possibly stale data rather than error",
          "  Eventually consistent",
          "  Examples: Cassandra, DynamoDB, CouchDB",
          "  Use when: social media feeds, product catalog, analytics",
          "",
          "PRACTICAL RULE: Most web apps tolerate some staleness.",
          "Use eventual consistency (AP) for reads, strong consistency for writes.",
        ]},
        {t:"heading", v:"Latency Numbers Every Engineer Must Know"},
        {t:"table", v:[
          ["Operation","Latency","Notes"],
          ["L1 cache reference","0.5 ns","CPU cache — nearly instant"],
          ["L2 cache reference","7 ns","Still very fast"],
          ["RAM access","100 ns","100x slower than L1"],
          ["SSD random read","150 μs","150,000 ns"],
          ["HDD seek","10 ms","10,000,000 ns — avoid for hot data"],
          ["Same datacenter round trip","500 μs","Your microservice calls"],
          ["Cross-continent round trip","150 ms","US to India"],
          ["MySQL query (indexed)","1-10 ms","With proper indexing"],
          ["Redis GET","< 1 ms","In-memory = fast"],
          ["Kafka publish","1-5 ms","With replication"],
        ]},
        {t:"note", v:"These numbers guide architecture decisions. An API calling 10 microservices sequentially adds 10 × 500μs = 5ms just in network overhead. This is why you batch calls, use caching, and parallelize when possible."},
      ]
    },
    {
      title: "Database Design & Selection", level: "Intermediate",
      blocks: [
        {t:"text", v:"Choosing the right database is one of the most important architectural decisions. The wrong choice can't easily be changed later. Understand the trade-offs deeply."},
        {t:"heading", v:"SQL vs NoSQL — Decision Framework"},
        {t:"table", v:[
          ["Factor","SQL (PostgreSQL, MySQL)","NoSQL (MongoDB, Cassandra)"],
          ["Data structure","Structured, schema enforced","Flexible, schema-less"],
          ["Relationships","Strong (JOINs)","Weak (denormalize data)"],
          ["ACID","Full ACID","Varies (eventual consistency)"],
          ["Scale","Vertical + limited horizontal","Horizontal (built-in sharding)"],
          ["Query flexibility","Very flexible (SQL)","Limited (query by partition key)"],
          ["Consistency","Strong by default","Eventual (configurable)"],
          ["Best for","Financial, ERP, relational data","Catalogs, logs, social, IoT"],
        ]},
        {t:"heading", v:"Database Indexing — The #1 Performance Tool"},
        {t:"code", lang:"sql", v:[
          "-- Without index: full table scan — O(n)",
          "SELECT * FROM orders WHERE customer_id = 12345;",
          "-- Scans ALL 10 million rows every time. Kills production.",
          "",
          "-- With B-Tree index: O(log n)",
          "CREATE INDEX idx_orders_customer_id ON orders(customer_id);",
          "-- Now finds rows in microseconds.",
          "",
          "-- Composite index: column order matters!",
          "CREATE INDEX idx_orders_status_date",
          "  ON orders(status, created_at DESC);",
          "-- Efficient for: WHERE status = 'PENDING' ORDER BY created_at DESC",
          "-- NOT efficient for: WHERE created_at > '2024-01-01' (missing status)",
          "",
          "-- Covering index: includes all queried columns — avoids table lookup",
          "CREATE INDEX idx_orders_covering",
          "  ON orders(customer_id) INCLUDE (status, total_amount);",
          "-- Query: SELECT status, total_amount FROM orders WHERE customer_id = ?",
          "-- Entire answer is in the index — never touches the main table row",
          "",
          "-- When NOT to index:",
          "-- Low cardinality columns (status with 3 values)",
          "-- Columns updated very frequently (index maintenance overhead)",
          "-- Small tables (full scan is faster than index lookup)",
        ]},
        {t:"heading", v:"Database Sharding — Horizontal Partitioning"},
        {t:"code", lang:"text", v:[
          "SHARDING: Split data across multiple databases",
          "Each database (shard) holds a subset of rows",
          "",
          "HASH SHARDING:",
          "  shard = hash(user_id) % number_of_shards",
          "  user_id 1001 → hash → shard 2",
          "  user_id 1002 → hash → shard 0",
          "  PRO: Even distribution",
          "  CON: Resharding is painful (consistent hashing helps)",
          "",
          "RANGE SHARDING:",
          "  Shard 0: user_id 1 - 1,000,000",
          "  Shard 1: user_id 1,000,001 - 2,000,000",
          "  PRO: Range queries stay on one shard",
          "  CON: Hot shards (new users all go to last shard)",
          "",
          "GEOGRAPHIC SHARDING:",
          "  Shard US: US users",
          "  Shard EU: European users (also satisfies GDPR data residency)",
          "  PRO: Low latency, compliance",
          "  CON: Cross-shard queries impossible",
          "",
          "AVOID SHARDING until you need it:",
          "  PostgreSQL handles 100M+ rows well with proper indexing.",
          "  Try: read replicas, caching, query optimization first.",
        ]},
        {t:"heading", v:"Caching Strategy — Redis in Production"},
        {t:"code", lang:"java", v:[
          "// Cache-Aside (Lazy Loading) — most common pattern",
          "public Product getProduct(String productId) {",
          "    // 1. Check cache first",
          "    String cached = redis.get(\"product:\" + productId);",
          "    if (cached != null) return JsonUtils.parse(cached, Product.class);",
          "",
          "    // 2. Cache miss: fetch from DB",
          "    Product product = productRepo.findById(productId)",
          "        .orElseThrow(() -> new ProductNotFoundException(productId));",
          "",
          "    // 3. Store in cache with TTL",
          "    redis.setex(\"product:\" + productId,",
          "                3600,  // 1 hour TTL",
          "                JsonUtils.toJson(product));",
          "",
          "    return product;",
          "}",
          "",
          "// Write-Through: update cache AND DB together",
          "public Product updateProduct(String id, UpdateProductRequest req) {",
          "    Product product = productRepo.save(/* update */);",
          "    redis.setex(\"product:\" + id, 3600, JsonUtils.toJson(product));",
          "    return product;",
          "}",
          "",
          "// Cache Invalidation on delete:",
          "public void deleteProduct(String id) {",
          "    productRepo.deleteById(id);",
          "    redis.del(\"product:\" + id);  // Evict from cache",
          "}",
          "",
          "// Cache Stampede prevention (many simultaneous cache misses):",
          "// Use probabilistic early expiration or Redis locks",
          "// Spring Cache with @Cacheable handles this elegantly:",
          "@Cacheable(value = \"products\", key = \"#id\", unless = \"#result == null\")",
          "public Product getProduct(String id) { return productRepo.findById(id).orElse(null); }",
          "",
          "@CacheEvict(value = \"products\", key = \"#id\")",
          "public void deleteProduct(String id) { productRepo.deleteById(id); }",
        ]},
      ]
    },
    {
      title: "Design: URL Shortener (Like bit.ly)", level: "Intermediate",
      blocks: [
        {t:"text", v:"The URL shortener is a classic system design question. It's simple enough to complete in 45 minutes but has enough depth to reveal whether you understand scalability, hashing, and database design."},
        {t:"heading", v:"Requirements"},
        {t:"code", lang:"text", v:[
          "FUNCTIONAL:",
          "  - Given a long URL, return a short URL (7 characters)",
          "  - Given a short URL, redirect to original long URL",
          "  - Short URLs expire after 1 year (configurable)",
          "  - Custom aliases: users can choose their short code",
          "",
          "NON-FUNCTIONAL (scale):",
          "  - 100M URLs created per day",
          "  - Read:Write ratio = 100:1 (reads dominate)",
          "  - 10 BILLION redirects per day = ~115,000 reads/second",
          "  - 99.9% availability",
          "  - Redirect latency < 50ms",
          "",
          "CAPACITY ESTIMATION:",
          "  Writes: 100M/day = 1,157/second",
          "  Reads:  10B/day  = 115,740/second",
          "  Storage per URL: 500 bytes avg",
          "  Storage/year: 100M × 365 × 500B = ~18 TB",
        ]},
        {t:"heading", v:"API Design"},
        {t:"code", lang:"text", v:[
          "POST /api/v1/urls",
          "  Body:   { longUrl, customAlias?, expiryDays? }",
          "  Returns: { shortUrl, shortCode, expiresAt }",
          "",
          "GET /{shortCode}",
          "  Returns: 301 Redirect to longUrl",
          "  (Use 301 Permanent for caching, 302 Temporary for analytics)",
          "",
          "DELETE /api/v1/urls/{shortCode}",
          "  Auth required, owner only",
          "",
          "GET /api/v1/urls/{shortCode}/stats",
          "  Returns: { clicks, countries, devices, timeline }",
        ]},
        {t:"heading", v:"Short Code Generation — The Core Problem"},
        {t:"code", lang:"java", v:[
          "// Option 1: MD5 Hash (first 7 chars)",
          "// Problem: collisions! Different URLs can produce same 7 chars",
          "String hash = DigestUtils.md5Hex(longUrl).substring(0, 7);",
          "",
          "// Option 2: Base62 Encoding of Auto-increment ID (BEST for simplicity)",
          "// 62^7 = 3.5 trillion unique codes — enough for decades",
          "private static final String CHARS =",
          "    \"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\";",
          "",
          "public String encode(long id) {",
          "    StringBuilder sb = new StringBuilder();",
          "    while (id > 0) {",
          "        sb.append(CHARS.charAt((int)(id % 62)));",
          "        id /= 62;",
          "    }",
          "    // Pad to 7 chars and reverse",
          "    while (sb.length() < 7) sb.append('0');",
          "    return sb.reverse().toString();",
          "}",
          "// id=1       → '0000001'",
          "// id=1000000 → '4c92'",
          "",
          "// Option 3: Pre-generate codes in batch",
          "// Generate 1M random codes offline, store in 'available_codes' table",
          "// On create: pop one from the pool — no collision possible",
          "// Eliminates hot-spot problem of sequential IDs",
        ]},
        {t:"heading", v:"High-Level Architecture"},
        {t:"code", lang:"text", v:[
          "                    ┌─────────────────┐",
          "  User Request ───> │   CDN / Cache   │ ──> Cache hit: instant redirect",
          "                    └────────┬────────┘",
          "                             │ Cache miss",
          "                    ┌────────▼────────┐",
          "                    │  Load Balancer  │",
          "                    └──┬──────────┬───┘",
          "                  ┌────▼───┐  ┌───▼────┐",
          "                  │ URL    │  │ URL    │  Stateless API servers",
          "                  │ Svc 1  │  │ Svc 2  │  (horizontally scaled)",
          "                  └────┬───┘  └───┬────┘",
          "              ┌────────▼──────────▼────────┐",
          "              │         Redis Cache         │  shortCode → longUrl",
          "              │    (read-through, 24h TTL)  │  115k reads/sec",
          "              └────────────────┬────────────┘",
          "                               │ Cache miss only",
          "              ┌────────────────▼────────────┐",
          "              │       PostgreSQL             │",
          "              │  Primary (writes)            │",
          "              │  Read Replicas (reads)       │",
          "              └─────────────────────────────┘",
          "",
          "Analytics Flow (async, non-blocking):",
          "  Click event → Kafka → Analytics Service → ClickHouse/DynamoDB",
        ]},
        {t:"heading", v:"Database Schema"},
        {t:"code", lang:"sql", v:[
          "CREATE TABLE short_urls (",
          "  id           BIGSERIAL PRIMARY KEY,",
          "  short_code   VARCHAR(10) UNIQUE NOT NULL,",
          "  long_url     TEXT NOT NULL,",
          "  user_id      BIGINT REFERENCES users(id),",
          "  created_at   TIMESTAMPTZ DEFAULT NOW(),",
          "  expires_at   TIMESTAMPTZ,",
          "  click_count  BIGINT DEFAULT 0",
          ");",
          "",
          "CREATE INDEX idx_short_urls_code ON short_urls(short_code);",
          "CREATE INDEX idx_short_urls_user ON short_urls(user_id);",
          "CREATE INDEX idx_short_urls_expiry ON short_urls(expires_at)",
          "  WHERE expires_at IS NOT NULL;  -- Partial index",
          "",
          "-- Expiry cleanup job (runs nightly):",
          "DELETE FROM short_urls WHERE expires_at < NOW();",
        ]},
      ]
    },
    {
      title: "Design: E-Commerce Order System", level: "Advanced",
      blocks: [
        {t:"text", v:"Designing an order management system is the most common system design interview for Java backend engineers. It covers databases, message queues, distributed transactions, and microservices."},
        {t:"heading", v:"Requirements & Scale"},
        {t:"code", lang:"text", v:[
          "FUNCTIONAL:",
          "  - Browse products (catalog)",
          "  - Add to cart, place order",
          "  - Payment processing",
          "  - Inventory management (no overselling!)",
          "  - Order tracking (real-time status)",
          "  - Email/SMS notifications",
          "",
          "NON-FUNCTIONAL:",
          "  - 1M daily active users",
          "  - Peak: 10,000 orders/minute (flash sale)",
          "  - Inventory must be accurate — no overselling",
          "  - Order confirmation < 2 seconds",
          "  - 99.99% availability for checkout",
        ]},
        {t:"heading", v:"Microservices Architecture"},
        {t:"code", lang:"text", v:[
          "  ┌──────────────────────────────────────────────────┐",
          "  │              API Gateway (Spring Cloud)          │",
          "  │  Auth │ Rate Limiting │ Routing │ Circuit Break  │",
          "  └───┬───────┬──────┬──────────┬──────────┬────────┘",
          "      │       │      │          │          │",
          "  [User]  [Catalog] [Cart]  [Order]  [Payment] [Notify]",
          "   Svc     Svc      Svc     Svc       Svc       Svc",
          "    |        |       |        |          |         |",
          "  UserDB  CatalogDB RedisDB OrderDB  PaymentDB  ---",
          "                    (cart)               Kafka ───┘",
          "",
          "KEY DESIGN DECISIONS:",
          "",
          "Cart Service → Redis (TTL 30 days)",
          "  Cart is temporary, needs fast reads/writes",
          "  Redis sorted sets for ordering, hashes for items",
          "",
          "Inventory → PostgreSQL with SELECT FOR UPDATE",
          "  Strong consistency required — no overselling",
          "  Pessimistic locking during checkout",
          "",
          "Orders → PostgreSQL with event sourcing",
          "  Immutable audit log of all state changes",
          "  Replay events to rebuild state",
          "",
          "Notifications → Kafka + dedicated service",
          "  Async — doesn't block order confirmation",
          "  Email/SMS/Push handled by separate workers",
        ]},
        {t:"heading", v:"Preventing Overselling — The Critical Design"},
        {t:"code", lang:"java", v:[
          "// PROBLEM: Two users checkout simultaneously for last item",
          "// Both check stock, both see 1, both succeed → stock goes to -1",
          "",
          "// SOLUTION 1: Pessimistic Locking (SELECT FOR UPDATE)",
          "@Transactional",
          "public Order checkout(CheckoutRequest req) {",
          "    // Lock the inventory row — other transactions wait",
          "    Inventory inv = inventoryRepo.findByProductIdForUpdate(req.getProductId());",
          "    if (inv.getStock() < req.getQuantity()) {",
          "        throw new InsufficientStockException(req.getProductId());",
          "    }",
          "    inv.setStock(inv.getStock() - req.getQuantity());",
          "    inventoryRepo.save(inv);",
          "    return orderRepo.save(Order.from(req));",
          "    // Lock released when transaction commits",
          "}",
          "// Good for low concurrency. Slow under high load (waiting).",
          "",
          "// SOLUTION 2: Optimistic Locking (better for high concurrency)",
          "@Entity",
          "public class Inventory {",
          "    private int stock;",
          "    @Version private Long version; // Increments on each update",
          "}",
          "",
          "@Transactional",
          "public Order checkout(CheckoutRequest req) {",
          "    Inventory inv = inventoryRepo.findById(req.getProductId());",
          "    if (inv.getStock() < req.getQuantity())",
          "        throw new InsufficientStockException(req.getProductId());",
          "    inv.setStock(inv.getStock() - req.getQuantity());",
          "    inventoryRepo.save(inv); // Throws OptimisticLockException if version changed",
          "    return orderRepo.save(Order.from(req));",
          "}",
          "// On OptimisticLockException: retry 3 times, then fail",
          "",
          "// SOLUTION 3: Redis atomic DECR (best for flash sales)",
          "Long remaining = redis.decrement(\"stock:\" + productId);",
          "if (remaining < 0) {",
          "    redis.increment(\"stock:\" + productId); // Rollback",
          "    throw new InsufficientStockException(productId);",
          "}",
          "// DECR is atomic — no race condition possible",
          "// Sync Redis → DB asynchronously via Kafka",
        ]},
        {t:"heading", v:"Order Flow with Saga Pattern"},
        {t:"code", lang:"text", v:[
          "Happy Path:",
          "  1. Cart → Checkout API",
          "  2. Order Service: Create order (PENDING)",
          "  3. Inventory Service: Reserve stock",
          "  4. Payment Service: Charge card",
          "  5. Order Service: Confirm order (CONFIRMED)",
          "  6. Kafka: order.confirmed event",
          "  7. Notification Service: Send confirmation email",
          "  8. Fulfillment Service: Schedule shipping",
          "",
          "Failure: Payment Declined",
          "  4. Payment Service: DECLINED",
          "  → Inventory Service: Release reservation (compensate step 3)",
          "  → Order Service: Cancel order (compensate step 2)",
          "  → Return error to user",
          "",
          "Failure: Inventory unavailable after payment succeeded",
          "  → Payment Service: Refund (compensate step 4)",
          "  → Order Service: Cancel with 'Out of Stock' (compensate step 2)",
          "  → Notification: 'Sorry, item sold out. Refund in 3-5 days'",
        ]},
      ]
    },
    {
      title: "Design: Chat Application (Like WhatsApp)", level: "Advanced",
      blocks: [
        {t:"text", v:"Real-time chat is one of the most technically interesting design problems — it touches WebSockets, message ordering, offline delivery, and massive scale. Asked frequently at companies like Meta, Slack, and Uber."},
        {t:"heading", v:"Requirements & Scale"},
        {t:"code", lang:"text", v:[
          "FUNCTIONAL:",
          "  - 1-1 and group messaging (up to 256 members)",
          "  - Message delivery status: Sent / Delivered / Read",
          "  - Media: images, videos, documents",
          "  - Message history with search",
          "  - Online/offline presence",
          "",
          "NON-FUNCTIONAL:",
          "  - 100M daily active users",
          "  - 50B messages per day = ~580,000 messages/second",
          "  - Message delivery < 100ms (same region)",
          "  - No message loss",
          "  - Messages delivered in order",
        ]},
        {t:"heading", v:"Core Architecture"},
        {t:"code", lang:"text", v:[
          "CLIENT CONNECTION LAYER:",
          "  WebSocket servers (chat-server instances)",
          "  Each server maintains ~50,000 persistent connections",
          "  For 100M users: 2,000 chat-server instances",
          "",
          "  User connects → routed to nearest chat-server",
          "  Connection maintained with heartbeat ping every 30s",
          "",
          "MESSAGE ROUTING:",
          "  Sender → their chat-server",
          "  Chat-server → looks up recipient's current chat-server",
          "  → routes message via internal network",
          "",
          "  How to find recipient's server?",
          "  Redis: SET user:presence:{userId} {serverId}",
          "  Set when user connects, TTL 60s (refreshed by heartbeat)",
          "",
          "OFFLINE DELIVERY:",
          "  If recipient offline: store message in DB",
          "  When recipient reconnects: fetch undelivered messages",
          "  Push notification via APNs/FCM to wake up their device",
          "",
          "MESSAGE STORAGE:",
          "  Cassandra (ideal for chat):",
          "    Partition key: conversation_id",
          "    Clustering key: message_id (time-ordered UUID)",
          "    Automatically ordered within partition",
          "    Scales horizontally to petabytes",
        ]},
        {t:"heading", v:"Message Ordering & IDs"},
        {t:"code", lang:"java", v:[
          "// Problem: How to assign message IDs that are:",
          "// 1. Globally unique (across all servers)",
          "// 2. Time-ordered (newer = higher ID)",
          "// 3. Efficient to generate (no central coordination)",
          "",
          "// SOLUTION: Snowflake ID (Twitter's approach)",
          "// 64-bit ID = timestamp (41 bits) + datacenter (5 bits)",
          "//            + machine (5 bits) + sequence (12 bits)",
          "",
          "public class SnowflakeIdGenerator {",
          "    private static final long EPOCH = 1700000000000L; // Custom epoch",
          "    private final long datacenterId;",
          "    private final long machineId;",
          "    private long sequence = 0;",
          "    private long lastTimestamp = -1;",
          "",
          "    public synchronized long nextId() {",
          "        long timestamp = System.currentTimeMillis() - EPOCH;",
          "        if (timestamp == lastTimestamp) {",
          "            sequence = (sequence + 1) & 0xFFF; // 12-bit mask = 4096/ms",
          "            if (sequence == 0) timestamp = waitNextMs(lastTimestamp);",
          "        } else { sequence = 0; }",
          "        lastTimestamp = timestamp;",
          "        return (timestamp << 22) | (datacenterId << 17) | (machineId << 12) | sequence;",
          "    }",
          "}",
          "// 4096 IDs/ms per machine, globally unique, time-sortable, no DB needed",
        ]},
        {t:"heading", v:"Read Receipts & Presence"},
        {t:"code", lang:"text", v:[
          "MESSAGE STATUS FLOW:",
          "",
          "  Sender sends message",
          "    → Server receives: update status to SENT (✓)",
          "    → Recipient's device receives: update to DELIVERED (✓✓)",
          "    → Recipient opens chat: update to READ (✓✓ blue)",
          "",
          "IMPLEMENTATION:",
          "  DB column: message_status ENUM('SENT','DELIVERED','READ')",
          "  WebSocket event: { type: 'READ_RECEIPT', messageId, userId, timestamp }",
          "  Batch read receipts for group messages",
          "",
          "PRESENCE (Online/Offline):",
          "  User connects → Redis SET user:online:{id} = serverID, EX 60",
          "  Heartbeat every 30s → refresh TTL",
          "  User disconnects or TTL expires → user appears offline",
          "  Friend list: subscribe to presence changes via Pub/Sub",
          "",
          "LAST SEEN:",
          "  When user disconnects: UPDATE users SET last_seen = NOW()",
          "  Display: 'last seen today at 2:34 PM'",
        ]},
      ]
    },
    {
      title: "Design: Notification System", level: "Intermediate",
      blocks: [
        {t:"text", v:"Every large application needs a notification system. This design covers the architecture for reliably sending millions of push, email, and SMS notifications per day with prioritization and retry logic."},
        {t:"heading", v:"Requirements"},
        {t:"code", lang:"text", v:[
          "FUNCTIONAL:",
          "  - Push notifications (iOS, Android)",
          "  - Email notifications",
          "  - SMS notifications",
          "  - User preferences (opt-out per channel/category)",
          "  - Priority levels: CRITICAL, HIGH, NORMAL, LOW",
          "  - Scheduled notifications",
          "  - Notification history",
          "",
          "NON-FUNCTIONAL:",
          "  - 10M notifications per day",
          "  - Critical (OTP, alerts): < 5 second delivery",
          "  - Normal (marketing): within 5 minutes",
          "  - At-least-once delivery",
          "  - Respect user quiet hours (no 3am marketing emails)",
        ]},
        {t:"heading", v:"Architecture"},
        {t:"code", lang:"text", v:[
          "PRODUCER SERVICES (Order, Payment, etc.)",
          "  Send notification events to Kafka",
          "  Event: { userId, type, priority, template, params, channel }",
          "",
          "NOTIFICATION SERVICE (Orchestrator)",
          "  1. Consume from Kafka topic 'notifications.raw'",
          "  2. Check user preferences (opt-out? quiet hours?)",
          "  3. Resolve template (fill in {name}, {amount} etc.)",
          "  4. Route to correct channel queue:",
          "     - notifications.push   (high throughput)",
          "     - notifications.email  (medium throughput)",
          "     - notifications.sms    (rate-limited, expensive)",
          "",
          "CHANNEL WORKERS (separate scalable services):",
          "  Push Worker  → FCM (Android) / APNs (iOS)",
          "  Email Worker → SendGrid / AWS SES",
          "  SMS Worker   → Twilio / AWS SNS",
          "",
          "RETRY MECHANISM:",
          "  Kafka retry topics: notifications.push.retry.1",
          "                      notifications.push.retry.2",
          "                      notifications.push.retry.3",
          "  DLT: notifications.push.dead-letter",
          "",
          "STORAGE:",
          "  User preferences → PostgreSQL (with Redis cache)",
          "  Notification history → Cassandra (time-series)",
          "  Templates → PostgreSQL + in-memory cache",
        ]},
        {t:"heading", v:"Rate Limiting & Throttling"},
        {t:"code", lang:"java", v:[
          "// Protect external APIs (Twilio charges per SMS!)",
          "// Token Bucket Algorithm using Redis:",
          "",
          "public class RateLimiter {",
          "    private final RedisTemplate<String, String> redis;",
          "",
          "    // Sliding window rate limiter",
          "    public boolean isAllowed(String userId, String channel) {",
          "        String key = \"ratelimit:\" + channel + \":\" + userId;",
          "        long now = System.currentTimeMillis();",
          "        long windowMs = 60_000; // 1 minute window",
          "",
          "        // Redis ZREMRANGEBYSCORE: remove old entries",
          "        redis.opsForZSet().removeRangeByScore(key, 0, now - windowMs);",
          "",
          "        // Count requests in current window",
          "        Long count = redis.opsForZSet().zCard(key);",
          "",
          "        int limit = switch (channel) {",
          "            case \"SMS\"   -> 5;    // Max 5 SMS per minute per user",
          "            case \"EMAIL\" -> 10;   // Max 10 emails per minute",
          "            case \"PUSH\"  -> 50;   // Max 50 pushes per minute",
          "            default      -> 20;",
          "        };",
          "",
          "        if (count >= limit) return false;",
          "",
          "        // Add this request to window",
          "        redis.opsForZSet().add(key, String.valueOf(now), now);",
          "        redis.expire(key, Duration.ofMinutes(2));",
          "        return true;",
          "    }",
          "}",
        ]},
      ]
    },
    {
      title: "Load Balancing, CDN & Caching Layers", level: "Advanced",
      blocks: [
        {t:"text", v:"Understanding how traffic flows from user to server — through CDNs, load balancers, and caches — is essential for designing systems that handle millions of users. This is asked in almost every senior system design interview."},
        {t:"heading", v:"Load Balancing Algorithms"},
        {t:"table", v:[
          ["Algorithm","How it works","Best for"],
          ["Round Robin","Rotate through servers in order","Equal capacity servers, stateless"],
          ["Weighted Round Robin","More requests to higher-capacity servers","Mixed server capacities"],
          ["Least Connections","Route to server with fewest active connections","Variable request duration"],
          ["IP Hash","Hash user IP to pick server","Session affinity (sticky sessions)"],
          ["Least Response Time","Route to fastest responding server","Heterogeneous workloads"],
          ["Random","Pick random server","Simple, works well at scale"],
        ]},
        {t:"heading", v:"CDN — Content Delivery Network"},
        {t:"code", lang:"text", v:[
          "WITHOUT CDN:",
          "  User in India → Server in US-East → 200ms round trip",
          "  Static files (JS, CSS, images) served from one location",
          "  Every user downloads same file from same server = bottleneck",
          "",
          "WITH CDN (CloudFront, Fastly, Cloudflare):",
          "  CDN has edge nodes in 200+ cities worldwide",
          "  User in India → Mumbai edge node → 5ms",
          "  File cached at edge after first request",
          "",
          "WHAT TO PUT ON CDN:",
          "  Static assets: JS bundles, CSS, images, fonts",
          "  Public API responses with Cache-Control headers",
          "  Video/audio files",
          "  PDF documents, downloads",
          "",
          "WHAT NOT TO PUT ON CDN:",
          "  User-specific data (dashboards, account pages)",
          "  Frequently changing data (stock prices, live scores)",
          "  POST/PUT/DELETE requests (CDN is for GETs only)",
          "",
          "CACHE INVALIDATION:",
          "  Strategy 1: Version in filename (main.a3f2d1.js) — never expires",
          "  Strategy 2: Cache-Control: max-age=86400 + CDN purge on deploy",
          "  Strategy 3: Short TTL (5min) for semi-dynamic content",
        ]},
        {t:"heading", v:"Caching Layers in a Full Stack System"},
        {t:"code", lang:"text", v:[
          "Layer 1: Browser Cache",
          "  Cache-Control: max-age=3600 (1 hour)",
          "  ETag for conditional requests",
          "  Eliminates network request entirely for cached resources",
          "",
          "Layer 2: CDN Cache",
          "  Serves static assets from edge nodes",
          "  Reduces origin server load by 90%+",
          "",
          "Layer 3: API Gateway Cache",
          "  Cache responses for identical requests",
          "  Useful for public, non-personalized data",
          "",
          "Layer 4: Application Cache (Redis)",
          "  Cache DB query results, computed data",
          "  Session storage",
          "  Rate limiting counters",
          "  TTL-based expiry",
          "",
          "Layer 5: Database Buffer Pool",
          "  DB keeps hot data in memory automatically",
          "  PostgreSQL: shared_buffers = 25% of RAM",
          "  MySQL: innodb_buffer_pool_size = 70-80% of RAM",
          "",
          "Layer 6: Database Read Replicas",
          "  Separate servers for read queries",
          "  Replication lag typically < 100ms",
          "  Route read-heavy queries to replicas",
        ]},
        {t:"heading", v:"Message Queues vs Databases for Async Work"},
        {t:"code", lang:"text", v:[
          "WHEN TO USE A MESSAGE QUEUE (Kafka, RabbitMQ, SQS):",
          "  - Decoupling producers from consumers",
          "  - Handling traffic spikes (queue absorbs burst)",
          "  - Guaranteed delivery with retry",
          "  - Fan-out (one event → many consumers)",
          "  - Order processing, notifications, analytics",
          "",
          "KAFKA vs RABBITMQ vs SQS:",
          "",
          "Kafka:",
          "  Log-based: messages retained for days/weeks",
          "  Consumers can replay from any offset",
          "  Extremely high throughput (millions/sec)",
          "  Best for: event streaming, audit logs, analytics",
          "",
          "RabbitMQ:",
          "  Traditional message broker",
          "  Message acknowledged and deleted on consumption",
          "  Flexible routing (exchanges, topics, fanout)",
          "  Best for: task queues, work distribution, RPC",
          "",
          "AWS SQS:",
          "  Managed, serverless, auto-scales",
          "  At-least-once delivery",
          "  FIFO queues for ordering guarantee",
          "  Best for: cloud-native AWS architectures",
        ]},
      ]
    },
  ]
};
